----------Covert Ops----------
st_menu_ghost_stealth = "",--Covert Ops
menu_jail_workout_beta = "",--Sixth Sense
menu_jail_workout_beta_desc = "BASIC:##$basic;##$NL;เพิ่มเวลาก่อนที่จะถูกสงสัย ##$multibasic3;##$NL;คุณสามารถชี้เป้าศัตรูตอนที่ยังไม่ใส่หน้ากากได้ $NL;$NL;ACE:##$pro;##$NL;คุณสามารถหยิบของตอนที่ยังไม่ใส่หน้ากากได้$NL;และเพิ่มมูลค่าของเงินและไอเท็มที่คุณหยิบ ##$multipro;##",--BASIC:##$basic;##$NL;Increases the time before you start getting detected by ##$multibasic3;## while in casing mode. You can also mark enemies while in casing mode.$NL;$NL;ACE:##$pro;##$NL;You can pick up items while in casing mode. You also gain ##$multipro;## more value to items and cash that you pick up.
menu_cleaner_beta = "",--Cleaner
menu_cleaner_beta_desc = "BASIC: ##$basic;##$NL;เพิ่มถุงเก็บศพติดตัวอีก ##$multibasic3;## อันและเพิ่มช่องถุงเก็บศพ$NL;เป็น ##$multibasic2;## จาก ##$multibasic5;## ช่อง.$NL;$NL;ACE: ##$pro;##$NL;สามารถพกและวางกระเป๋าถุงเก็บศพได้ ##$multipro2;## กล่อง.",--BASIC: ##$basic;##$NL;You gain ##$multibasic3;## additional body bag in your inventory. Also increases the body bag inventory space to ##$multibasic2;## from ##$multibasic5;##.$NL;$NL;ACE: ##$pro;##$NL;You gain the ability to place ##$multipro2;## body bag cases.
menu_chameleon_beta = "",--Chameleon
menu_chameleon_beta_desc = "BASIC: ##$basic;##$NL;คุณสามารถเห็นศัตรูในระยะ ##$multibasic2;## เมตรขณะยืนนิ่ง$NL;เป็นเวลา ##$multibasic3;##  วินาทีในโหมดย่องเงียบ.$NL;$NL;ACE: ##$pro;##$NL;ปลดล็อคการซื้อตัวช่วยภารกิจ$NL;เงินที่จะหายไปจากการฆ่าประชาชนจะลดลง ##$multipro2;##.",--BASIC: ##$basic;##$NL;You gain the ability to automatically mark enemies within a ##$multibasic2;## meter radius around you after standing still for ##$multibasic3;## seconds while in stealth.$NL;$NL;ACE: ##$pro;##$NL;You gain access to all insider assets. Cleaning costs after killing a civilian is reduced by ##$multipro2;##.
menu_second_chances_beta = "",--Undertaker
menu_second_chances_beta_desc = "BASIC: ##$basic;##$NL;คุณสามารถปิดใช้งานกล้องชั่วคราวได้ ##$multibasic;## เครื่อง$NL;และกล้องจะกลับมาทำงานปกติภายในเวลา ##$multibasic2;## วินาที.$NL;$NL;ACE: ##$pro;##$NL;คุณจะสะเดาะล็อคไวขึ้น ##$multipro2;## และคุณสามารถ$NL;สะเดาะล็อคตู้เซฟแบบปกติได้แล้ว.",--BASIC: ##$basic;##$NL;You gain the ability to disable ##$multibasic;## camera from detecting you and your crew. Effect lasts for ##$multibasic2;## seconds.$NL;$NL;ACE: ##$pro;##$NL;You lockpick ##$multipro2;## faster. You also gain the ability to lockpick safes.
menu_ecm_booster_beta = "",--ECM Overdrive
menu_ecm_booster_beta_desc = "BASIC: ##$basic;##$NL;สัญญานรบกวนจาก Ecm Jammer และ Ecm Feedback $NL;ของคุณจะนานขึ้น ##$multibasic;##$NL;$NL;ACE: ##$pro;##$NL;คุณสามารถใช้่ Ecm Jammer เปิดประตูไฟฟ้าได้แล้ว.",--BASIC: ##$basic;##$NL;Your Ecm Jammer and feedback duration is increased by ##$multibasic;##.$NL;$NL;ACE: ##$pro;##$NL;Your Ecm Jammer can now also be used to open certain electronic doors.
menu_ecm_2x_beta = "",--ECM Specialist
menu_ecm_2x_beta_desc = "BASIC: ##$basic;##$NL;ได้รับ ECM Jammer สำหรับใช้ระหว่างภารกิจเป็น ##$multibasic;## อัน.$NL;$NL;ACE: ##$pro;##$NL;Ecm Jammer ของคุณทำงานนานขึ้น ##$multipro;##$NL;และ Ecm Feedback ของคุณทำงานนานขึ้น ##$multipro2;##$NL;วอตำรวจจะถูกพักชั่วคราวจนกว่า Ecm Jammer หยุดทำงาน.",--BASIC: ##$basic;##$NL;You can now place ##$multibasic;## Ecm Jammers instead of just one.$NL;$NL;ACE: ##$pro;##$NL;The Ecm Jammer duration is increased by an additional ##$multipro;## and the Ecm Feedback duration lasts ##$multipro2;## longer. Pagers are delayed by the Ecm Jammer.
----------Commando----------
st_menu_ghost_concealed = "",--Commando
menu_sprinter_beta = "",--Duck and Cover
menu_sprinter_beta_desc = "BASIC: ##$basic;##$NL;คุณจะแข็งแรงและวิ่งได้นานขึ้น ##$multibasic;## และร่างกายของคุณ$NL;จะฟื้นฟูจากอาการเหนื่อยไวขึ้น ##$multibasic2;## $NL;และคุณจะวิ่งเร็วขึ้น ##$multibasic2;##.$NL;$NL;ACE: ##$pro;##$NL;เพิ่มโอกาสหลบกระสุนขณะวิ่ง ##$multipro;## และเพิ่มโอกาสหลบกระสุน ##$multipro3;## ขณะนั่งหรือโหนสลิง.",--BASIC: ##$basic;##$NL;Your stamina starts regenerating ##$multibasic;## earlier and ##$multibasic2;## faster. You also sprint ##$multibasic2;## faster.$NL;$NL;ACE: ##$pro;##$NL;You have a ##$multipro;## increased chance to dodge while sprinting. You gain ##$multipro3;## chance to dodge while crouching or ziplining.
menu_awareness_beta = "",--Evasion
menu_awareness_beta_desc = "BASIC: ##$basic;##$NL;เคลื่อนที่เร็วขึ้นอีก ##$multibasic;## และปืนบันไดเร็วขึ้นอีก ##$multibasic2;##.$NL;$NL;ACE: ##$pro;##$NL;ทำให้สามารถวิ่งไปทิศทางไหนก็ได้$NL;คุณจะได้รับบาดเจ็บน้อยลงเมื่อตกลงจากที่สูง ##$multipro;##$NL;และเลือดของคุณจะไม่ลดถ้าหากคุณตกจากที่สูง$NL;พอประมาณแต่จะทำให้ค่าเกราะของคุณหมดทันที.",--BASIC: ##$basic;##$NL;You gain ##$multibasic;## additional movement speed and ##$multibasic2;## ladder climbing speed.$NL;$NL;ACE: ##$pro;##$NL;You gain the ability to sprint in any direction. Your fall damage is also reduced by ##$multipro;## and you only take armor damage from falling from non fatal heights.
menu_thick_skin_beta = "",--Thick Skin
menu_thick_skin_beta_desc = "BASIC:##$basic;##$NL;เพิ่มค่าปกปิดของอาวุธระยะประชิด ##$multibasic2;## แต้ม.$NL;$NL;ACE: ##$pro;##$NL;เพิ่มค่าปกปิดเกราะประเภท Ballistic Vest ##$multipro2;##.",--BASIC:##$basic;##$NL;Increases the concealment of melee weapons by ##$multibasic2;##.$NL;$NL;ACE: ##$pro;##$NL;Increases the concealment of all ballistic vests by ##$multipro2;##.
menu_dire_need_beta = "",--Dire Need
menu_dire_need_beta_desc = "BASIC: ##$basic;##$NL;เมื่อเกราะของคุณแตกกระสุนนัดแรกของศัตรูที่ยิงใส่คุณ$NL;จะทำให้ศัตรูเดินเซไปมาผลของสกิลจะสิ้นสุด$NL;เมื่อเกราะของคุณถูกฟื้นฟู.$NL;$NL;ACE: ##$pro;##$NL;ความสามารถนี้ยังคงสามารถใช้งานได้อยู่ ##$multipro;## วินาที$NL;หลังจากเกราะของคุณถูกฟื้นฟูแล้ว.",--BASIC: ##$basic;##$NL;When your armor is depleted, the first shot on any enemies will cause those enemies to stagger. This effect ends when your armor regenerates.$NL;$NL;ACE: ##$pro;##$NL;This effect persists for ##$multipro;## seconds after your armor has regenerated.
menu_insulation_beta = "",--Shockproof
menu_insulation_beta_desc = "BASIC: ##$basic;##$NL;เมื่อถูกศัตรูช็อตไฟฟ้าใส่มีโอกาส ##$multibasic;## สะท้อนไฟฟ้ากลับใส่ศัตรู.$NL;$NL;ACE: ##$pro;##$NL;เมื่อถูกเทเซอร์ช็อตไฟฟ้าใส่หากกดปุ่ม $BTN_INTERACT; ใส่ศัตรูทันทีภายใน ##$multipro2;## วินาทีจะหลุดจากการถูกไฟฟ้าช็อต$NL;ทันที.$NL;$NL;ปุ่มพื้นฐานคือปุ่ม [ F ]",--BASIC: ##$basic;##$NL;The taser's shock attack has a ##$multibasic;## chance to backfire when targeted at you, causing the taser to be knocked back.$NL;$NL;ACE: ##$pro;##$NL;When tased, you are able to free yourself from the taser by interacting with it within ##$multipro2;## seconds of getting tased.
menu_jail_diet_beta = "",--Sneaky Bastard
menu_jail_diet_beta_desc = "BASIC: ##$basic;##$NL;คุณจะได้รับ ##$multibasic;## โอกาสการหลบหลีก$NL;สำหรับทุกๆ ##$multibasic2;## ของค่าปกปิดทั้งหมดที่คุณมี$NL;และจำนวนค่าปกปิดที่มีและมีค่าต่ำกว่า ##$multibasic3;## จะได้รับโอกาสสูงสุดอยู่ที่ ##$multibasic4;##.$NL;$NL;ACE: ##$pro;##$NL;คุณจะได้รับ ##$multipro;## โอกาสการหลบหลีก$NL;สำหรับทุกๆ ##$multipro2;## ของค่าปกปิดทั้งหมดที่คุณมี$NL;และจำนวนค่าปกปิดที่มีและมีค่าต่ำกว่า ##$multipro3;## จะได้รับโอกาสสูงสุดอยู่ที่ ##$multipro4;##.",--BASIC: ##$basic;##$NL;You gain a ##$multibasic;## dodge chance for every ##$multibasic2;## points of concealment under ##$multibasic3;## up to ##$multibasic4;##.$NL;$NL;ACE: ##$pro;##$NL;You gain a ##$multipro;## dodge chance for every ##$multipro2;## point of concealment under ##$multipro3;## up to ##$multipro4;##.
----------Silent Killer----------
st_menu_ghost_silencer = "",--Silent Killer
menu_scavenger_beta = "",--Second Wind
menu_scavenger_beta_desc = "BASIC: ##$basic;##$NL;เมื่อเกราะของคุณแตกคุณจะวิ่งเร็วขึ้น ##$multibasic;## $NL;เป็นเวลา  ##$multibasic2;## วินาที.$NL;$NL;ACE:##$pro;##$NL;ทักษะนี้จะมีผลกับเพื่อนร่วมทีมด้วย$NL;เมื่อคุณเกราะแตก.",--BASIC: ##$basic;##$NL;When your armor breaks your movement speed is increased by ##$multibasic;## for ##$multibasic2;## seconds.$NL;$NL;ACE:##$pro;##$NL;This effect also applies to your crew when triggered.
menu_optic_illusions = "" ,--Optical Illusions
menu_optic_illusions_desc = "BASIC: ##$basic;##$NL;คุณจะถูกตกเป็นเป้าหมายน้อยลง ##$multibasic;##.$NL;$NL;ACE: ##$pro;##$NL;คุณจะได้รับค่าปกปิด ##$multipro;## แต้มหากพกปืนที่ใส่ที่เก็บเสียง$NL;และเพิ่มค่าปกปิดของปืนที่ใส่ที่เก็บเสียง ##$multipro2;## แต้ม.",--BASIC: ##$basic;##$NL;You are ##$multibasic;## less likely to be targeted by enemies.$NL;$NL;ACE: ##$pro;##$NL;You gain ##$multipro;## concealment for each silenced weapon you equip and reduces the concealment penalty of silencers by ##$multipro2;##.
menu_silence_expert_beta = "",--The Professional
menu_silence_expert_beta_desc = "BASIC: ##$basic;##$NL;ปืนที่ใส่ที่เก็บเสียงจะได้รับความนิ่งขึ้นไปอีก ##$multibasic;## แต้ม$NL;และเล็งปืนได้เร็วขึ้นไปอีก ##$multibasic2;##.$NL;$NL;ACE: ##$pro;##$NL;ปืนที่ใส่ที่เก็บเสียงจะได้รับความแม่นขึ้นไปอีก ##$multipro3;##.",--BASIC: ##$basic;##$NL;You gain ##$multibasic;## weapon stability and ##$multibasic2;## snap to zoom speed increase with silenced weapons.$NL;$NL;ACE: ##$pro;##$NL;You gain ##$multipro3;## weapon accuracy with silenced weapons.
menu_backstab_beta = "",--Low Blow
menu_backstab_beta_desc = "BASIC: ##$basic;##$NL;คุณจะได้รับ ##$multibasic;## โอกาสการทำความเสียหายคริติคอล$NL;สำหรับทุกๆ ##$multibasic2;## ของค่าปกปิดทั้งหมดที่คุณมี$NL;และจำนวนค่าปกปิดที่มีและมีค่าต่ำกว่า ##$multibasic3;## จะได้รับโอกาสสูงสุดอยู่ที่ ##$multibasic4;##.$NL;$NL;ACE: ##$pro;##$NL;คุณจะได้รับ ##$multipro;## โอกาสการทำความเสียหายคริติคอล$NL;สำหรับทุกๆ ##$multibasic2;## ของค่าปกปิดทั้งหมดที่คุณมี$NL;และจำนวนค่าปกปิดที่มีและมีค่าต่ำกว่า ##$multipro3;## จะได้รับโอกาสสูงสุดอยู่ที่ ##$multipro4;##.$NL;$NL;คำเตือน:$NL;ความสามารถนี้ไม่มีผลกับปืนยิงระเบิด.",--BASIC: ##$basic;##$NL;You gain a ##$multibasic;## critical hit chance for every ##$multibasic2;## points of concealment under ##$multibasic3;## up to ##$multibasic4;##.$NL;$NL;ACE: ##$pro;##$NL;You gain ##$multipro;## critical hit chance for every ##$multipro2;## point of concealment under ##$multipro3;## up to ##$multipro4;##.$NL;$NL;Note: Does not apply to grenade launchers.

menu_spotter_teamwork_beta = "",--Spotter Teamwork
menu_spotter_teamwork_beta_desc = "BASIC: ##$basic;##$NL;ศัตรูที่ถูกคุณชี้จะได้รับค่าเสียหายมากขึ้น ##$multibasic;##.$NL;$NL;ACED: ##$pro;##$NL;ศัตรูที่ถูกคุณชี้จะได้รับค่าเสียหายมากขึ้น ##$multipro;##$NL;เมื่อศัตรูอยู่ในระยะที่ไกลกว่า ##$multipro2;## เมตร$NL;เพิ่มระยะเวลาที่ศัตรูถูกชี้เป้านานขึ้น ##$multipro3;##$NL;และคุณสามารถที่จะมาร์กศัตรูพิเศษด้วยการ$NL;เล็งไปที่ศัตรูด้วยอาวุธอะไรก็ได้.",--BASIC: ##$basic;##$NL;Enemies you mark take ##$multibasic;## more damage.$NL;$NL;ACE: ##$pro;##$NL;Enemies you mark take an additional ##$multipro;## damage when further away than ##$multipro2;## meters.$NL;Increase the duration of marked enemies by ##$multipro3;## and you can now mark specials by aiming at them with any weapon.

menu_unseen_strike_beta = "",--Unseen Strike
menu_unseen_strike_beta_desc = "BASIC: ##$basic;##$NL;ถ้าคุณไม่เสียเกราะหรือเลือดเลยเป็นเวลา ##$multibasic;## วินาที$NL;คุณจะทำความเสียหายคริติคอล ##$multibasic2;## $NL;เป็นระยะเวลา ##$multibasic3;## วินาที.$NL;$NL;ACE: ##$pro;##$NL;เพิ่มระยะเวลาทำความเสียหายคริติคอลเป็นเวลา ##$multipro;## วินาที.$NL;$NL;คำเตือน: เมื่อคุณโดนดาเมจใดๆ ก็ตามทักษะนี้$NL;จะถูกยกเลิกทันที.",--BASIC: ##$basic;##$NL;If you do not lose any armor or health for ##$multibasic;## seconds, you gain ##$multibasic2;## critical hit chance for ##$multibasic3;## seconds.$NL;$NL;ACE: ##$pro;##$NL;The critical hit chance duration is increased to ##$multipro;## seconds.


--RemovedSkills--
menu_hitman_beta = "",--Subsonic Rounds
menu_hitman_beta_desc = "BASIC: ##$basic;##$NL;ปืนที่ใส่ที่เก็บเสียงดาเมจเพิ่มขึ้น ##$multibasic2;##.$NL;$NL;ACE: ##$pro;##$NL;ปืนที่ใส่ที่เก็บเสียงดาเมจเพิ่มขึ้นอีก ##$multipro3;##.",--BASIC: ##$basic;##$NL;You deal ##$multibasic2;## more damage with all silenced weapons.$NL;$NL;ACE: ##$pro;##$NL;You deal an additional ##$multipro3;## more damage with all silenced weapons.