heist_mex = "",--Border Crossing
heist_mex_transition = "แห่งหนึ่งในเม็กซิโก",--SOMEWHERE IN MEXICO...
hud_heist_mex17 = "รอจนกว่าจะเติมน้ำมันให้กับเครื่องบินเสร็จ",--Wait for the pump to refuel the plane.
hud_heist_mex21_hl = "ระเบิดประตูรันเวย์ทิ้งซะ",--Blow up the runway gates
hud_heist_mex7 = "พยายามอย่าให้พวก Murkywater หยุดการทำงานของเครื่องระเบิด",--Keep the Murkywater soldiers from disabling the detonator.
hud_heist_mex18 = "พยายามอย่าให้พวก Murkywater ถอดสายยางออกจากถังน้ำมันหรือเครื่องปั้ม",--Keep the Murkywater soldiers from detaching the hose from the tank or the pump.
hud_heist_mex1 = "หาอุโมงค์ใต้ดินเพื่อไปยังเม็กซิโก",--Find an underground tunnel leading to Mexico somewhere outside.
hud_heist_mex8 = "ใช้อุโมงค์เพื่อข้ามฝั่งชายแดน",--Use the tunnel to reach the other side of the border.
hud_heist_mex11_hl = "การหลบหนีพร้อมแล้ว",--Escape available
hud_heist_mex3_hl = "หารหัสและใช้งาน",--Find and enter the code
hud_heist_mex11 = "หลบหนีโดยขโมยเครื่องบิน",--Escape by stealing the plane.
hud_heist_mex10_hl = "เชื่อมต่อท่อเข้ากับเครื่องบิน",--Connect the fuel hose to the plane
hud_heist_mex16_hl = "หากุญแจเครื่องบิน",--Find the keys to the plane
hud_heist_mex1_hl = "ค้นหาอุโมงค์",--Locate the tunnel
hud_heist_mex2_hl = "ค้นหาและเข้าไปยังห้องทำงาน",--Locate and enter the briefing room
hud_heist_mex7_hl = "ป้องกันเครื่องระเบิด",--Defend the detonator
hud_heist_mex13 = "หาและขโมยเงินบริเวณนั้น",--Find and steal money from around the compound.
hud_heist_mex6 = "เริ่มนับเครื่องระเบิดเพื่อทำการทำลาย",--Start the countdown to detonate the breaching charges.
hud_heist_mex20 = "ถอดสายยางออกจากเครื่องบิน",--Detach the hose from the plane.
hud_heist_mex15_hl = "เติมน้ำมันเครื่องปั้ม",--Refuel the generator
hud_heist_mex9_hl = "ขโมยอาวุธ",--Steal weapons
hud_heist_mex19 = "หาสวิตช์เพื่อเปิดประตูรันเวย์",--Find the switch to open the gates to the runway.
hud_heist_mex15 = "หาน้ำมันถังสีแดงและเติมเข้าเครื่องปั้ม",--Find red gasoline cans and refuel the pump's generator.
hud_heist_mex17_hl = "รอเติมน้ำมัน",--Wait for the refueling process
hud_heist_mex8_hl = "เข้าอุโมงค์ไปยังเม็กชิโก",--Take the tunnel to Mexico
hud_heist_mex14 = "หาเครื่องบินในโรงเก็บเครื่องบิน",--Find the plane in one of the hangers.
hud_heist_mex4_hl = "หาเครื่องระเบิด",--Find the breaching charges
hud_heist_mex18_hl = "ป้องกันสายยาง",--Defend the hose
hud_heist_mex13_hl = "ขโมยเงิน",--Steal money
hud_heist_mex2 = "หาห้องทำงานของแก๊งมอเตอร์ไซต์และเข้าไปข้างใน",--Search the bikers clubhouse for the briefing room and gain access to it.
hud_heist_mex5 = "วางเครื่องระเบิดหน้าอุโมงค์",--Place the breaching charges on the tunnel entrance.
hud_heist_mex12_hl = "ขโมยโคเคน",--Steal cocaine
hud_heist_mex4 = "",--Find where the bikers are storing breaching charges.
hud_heist_mex19_hl = "",--Open the runway gates
hud_heist_mex10 = "",--Find a tank of airplane fuel and a pump. Connect them both to the plane.
hud_heist_mex12 = "",--Find and steal cocaine from around the compound.
hud_heist_mex14_hl = "",--Locate the getaway plane
hud_heist_mex16 = "",--Locate the plane keys somewhere in the compound.
hud_heist_mex20_hl = "",--Detach the hose
hud_heist_mex21 = "",--Use C4 to blow open the runway gates.
hud_heist_mex3 = "",--Use the hint to locate the correct code and enter it into the keypad.
hud_heist_mex5_hl = "",--Set up the breaching charges
hud_heist_mex6_hl = "",--Rig the detonator
hud_heist_mex9 = "",--Find and steal weapons from around the compound.


loc_mex_23_01 = "",--Time to start looking for that stash of Murky loot. It's drugs we're after. 
loc_mex_03_02 = "",--Nicely done, friends. That's what we're looking for.
loc_mex_70_03 = "",--This is not a good day for Murkywater or the Dentist, yeah?! For sure!
loc_mex_64_02 = "",--Your first priority is finding your ride out of there. Maybe check the hangars, yeah?
loc_mex_68_01 = "",--Time to start looking for that stash of Murky loot. It's drugs we're after. 
loc_mex_61_02 = "",--Now get your sombreros on and into that tunnel.
loc_mex_40_03 = "",--Time to fly, friends. 
loc_mex_45_03 = "",--Murky dwankies coming your way!
loc_mex_46_01 = "",--I've got an idea about what we can use those for later!
loc_mex_21_03 = "",--OK, that's it. When you've got the loot aboard, you need to juice it up as well.
loc_mex_66_01 = "",--There's your ride out. Once you've got all the loot secured, you gotta get it refueled. 
loc_mex_53_01 = "",--No telling where they might be though, you'll have to look around.
loc_mex_32_02 = "",--Just gotta give it some time to fill.
loc_mex_44_02 = "",--Wrong code, the alarm has gone off!
loc_mex_59_01 = "",--Wait for it... 
loc_mex_76_03 = "",--How's the refueling going?
loc_mex_53_02 = "",--Make sure you look around everywhere.
loc_mex_13_03 = "",--That was it. Niiice.
loc_mex_23_03 = "",--Start searching for that Murkywater nest egg, shaped like a lot of cocaine.
loc_mex_69_03 = "",--The Murky's nest egg is cash money, so start looking. It could be anywhere around there.
loc_mex_49_02 = "",--They would probably want easy access to the tunnel, so check around outside.
loc_mex_44_01 = "",--Ag man, that was the wrong code!
loc_mex_54_03 = "",--Good, now get them onto the door!
loc_mex_01_03 = "",--Find that tunnel, friends. They've probably got it hidden, but it shouldn't be too hard to locate.
loc_mex_55_01 = "",--Set up the detonator.
loc_mex_07_01 = "",--Watch for anything odd.
loc_mex_71_02 = "",--Blerrie, that's the vault from the blueprints. 
loc_mex_10_01 = "",--Oh, you're going to give old Locke a heart attack. That was a close one.
loc_mex_28_01 = "",--You're going to need two key cards to get in there. 
loc_mex_64_01 = "",--First thing to do is find that plane. Start by looking in the hangars. 
loc_mex_11_03 = "",--Get to searching for the code, yeah?
loc_mex_65_01 = "",--You gotta find that plane. 
loc_mex_83_04 = "",--Fly you fools!
loc_mex_02_03 = "",--You'll probably find the tunnel if you look around outside.
loc_mex_04_01 = "",--Ah, blerrie. Of course it had to have a keylock. Maybe you can find some way to figure out the code in the clubhouse briefing room. Go have a look, yeah?
loc_mex_84_03 = "",--Rust said something about this... see if you can find anything useful.
loc_mex_81_03 = "",--Blow up the gate, friends!
loc_mex_74_02 = "",--You gotta get some fuel in that dinges. Get to work. 
loc_mex_05_01 = "",--Come on you chops, keep looking.
loc_mex_15_03 = "",--Nice going, taking out the cameras.
loc_mex_65_02 = "",--No standing around. Find the plane, quickly.
loc_mex_31_01 = "",--Can't get out of there on an empty tank. Fuel the plane!
loc_mex_16_02 = "",--Now put your sombreros on and get into that tunnel.
loc_mex_04_02 = "",--Ach, I should've known they would have it locked. Maybe have a look in the clubhouse and see if you can find any clues to the code in the briefing room.
loc_mex_59_03 = "",--Hold your ears, you chops! It's going to be loud!
loc_mex_43_02 = "",--Everyone knows you're there now!
loc_mex_38_01 = "",--Now you gotta clear the runway by opening the gates. The Murkys and Cartel dwankies will go bossies, when they realise what we're doing!
loc_mex_06_02 = "",--Looks like a good place to check for clues.
loc_mex_29_01 = "",--There's gotta be something special about that thing if they keep it locked up in here. Maybe take it with you, yeah?
loc_mex_25_03 = "",--This is not a good day for Murkywater or the Dentist, yeah?
loc_mex_33_03 = "",--You gotta get some more gas in that donnerse pump.
loc_mex_07_02 = "",--Tread carefully, friends.
loc_mex_84_02 = "",--What's this? Might be worth a look, yeah?
loc_mex_39_01 = "",--You have to clear the runway, friends!
loc_mex_51_01 = "",--The keypad has been disabled! You're going to have to blow your way in.
loc_mex_57_01 = "",--Now keep it clear of dwankies.
loc_mex_41_01 = "",--No time to sit around, you gotta go!
loc_mex_78_02 = "",--Just gotta give it some time to fill.
loc_mex_79_03 = "",--Time to disconnect the hose, the plane is all full.
loc_mex_66_03 = "",--OK, that's it. When you've got the loot inside, you need to juice it up as well.
loc_mex_73_01 = "",--There's gotta be something special about that thing if they keep it locked up in here. Maybe take it with you, yeah?
loc_mex_32_03 = "",--Looks like it's working. Will take some time before it's full.
loc_mex_60_03 = "",--Blueprints to a vault. Interesting.
loc_mex_30_03 = "",--OK, friends. Time to put some fuel in that plane.
loc_mex_18_02 = "",--Welcome to Mexico amigos. Try not to make a ruckus.
loc_mex_21_02 = "",--That's the plane. Get the loot inside, then give it some fuel.
loc_mex_15_02 = "",--You took care of the cameras, friends.
loc_mex_45_01 = "",--You've got Murkys coming!
loc_mex_02_01 = "",--The tunnel entrance should be outside somewhere.
loc_mex_02_02 = "",--They would probably want easy access to the tunnel, so check around outside.
loc_mex_39_03 = "",--Almost time to leave. You just need to open up the runway.
loc_mex_29_03 = "",--You wouldn't think that the cartels would bother with such a thing, yeah? Might as well take it with you.
loc_mex_20_02 = "",--No standing around. Find the plane, quickly.
loc_mex_75_01 = "",--Ach! Someone stopped the pump. Get it going again!
loc_mex_55_02 = "",--Now hook up the detonator, friends.
loc_mex_59_02 = "",--Here we go... here... we... goooooo!
loc_mex_65_03 = "",--The plane, friends, the plane!
loc_mex_67_02 = "",--The Murky resources we're after will be weapons. They could be anywhere around here, so you're just going to have to start looking.
loc_mex_48_01 = "",--More leather dwankies! Take care of them.
loc_mex_13_01 = "",--Nicely done, friends. 
loc_mex_67_01 = "",--Time to start looking for that stash of Murky loot. It's weapons we're after. 
loc_mex_43_01 = "",--The entire compound heard that blast. 
loc_mex_62_01 = "",--You gotta get into that tunnel, friends. 
loc_mex_50_03 = "",--Ah, that's a tunnel entrance if I've ever seen one.
loc_mex_77_01 = "",--Good, now keep those dwankies away from the pump!
loc_mex_19_02 = "",--Your first priority is finding your ride out of there. Maybe check the hangars, yeah?
loc_mex_14_02 = "",--Looks like there might be an underground vault somewhere.
loc_mex_71_03 = "",--Good thing you found that blueprint. 
loc_mex_58_01 = "",--It stopped! You gotta start it up again!
loc_mex_37_03 = "",--Time to disconnect the hose, the plane is all full.
loc_mex_05_02 = "",--Did you find it yet? Have you checked the upper floor?
loc_mex_33_02 = "",--The pump needs to be filled with gasoline.
loc_mex_86_01 = "",--Can't get in there with a key now, you gotta use a dril instead.
loc_mex_77_03 = "",--You gotta keep the pump running. Protect it!
loc_mex_24_02 = "",--The Murky contraband we're after will be money. Could be kept anywhere nearby, so you're just going to have to search for it.
loc_mex_40_01 = "",--Good, now it's time to leave. Get onboard that dinges, quickly!
loc_mex_82_01 = "",--Blerrie, what a noise! Time to leave!
loc_mex_31_02 = "",--The plane needs juice to fly.
loc_mex_76_01 = "",--Can't get out of there on an empty tank. Fuel the plane!
loc_mex_39_02 = "",--Open the gate so you have a clear path to take off.
loc_mex_34_02 = "",--The pump stopped again.
loc_mex_47_01 = "",--No need to sneak about now. Locke has a plan B!
loc_mex_50_01 = "",--There you go, that's it.
loc_mex_69_01 = "",--Time to start looking for that stash of Murky loot. We're looking for cash, and lots of it. 
loc_mex_10_03 = "",--Nicely done. Leave it to those Overkill dwankies to go over the top with security.
loc_mex_64_03 = "",--The getaway plane is probably in one of the hangars. Go have a look!
loc_mex_29_02 = "",--That will look great in the safehouse if we can ever make room for it. Take it with you. 
loc_mex_16_01 = "",--OK, get into that tunnel. Time for a visit to Mexico.
loc_mex_17_02 = "",--Hurry up you chops, get into that tunnel.
loc_mex_27_02 = "",--Blerrie, that's the vault from the blueprints. 
loc_mex_70_02 = "",--Good, we got what we need. Murkywater and the Dentist will be in big trouble once this hits home.
loc_mex_51_02 = "",--Ach, the keypad doesn't work. You gotta blow the door.
loc_mex_79_02 = "",--The plane is full, you can take off the hose.
loc_mex_15_01 = "",--Cameras are now disabled.
loc_mex_63_02 = "",--Welcome to Mexico, dear amigos. No time to waste!
loc_mex_22_01 = "",--Time to start looking for that stash of Murkywater contraband. It's weapons we're after. 
loc_mex_10_02 = "",--Fast work, friends. 
loc_mex_83_01 = "",--No time to sit around, you gotta go!
loc_mex_50_02 = "",--Nicely done, friends. That's what we're looking for.
loc_mex_56_03 = "",--Hurry, friends. The detonator! 
loc_mex_03_03 = "",--That's a tunnel entrance if ever I've seen one.
loc_mex_18_01 = "",--Nice night for a jol in the desert. Try to stay quiet.
loc_mex_52_02 = "",--According to Rust, these biker keks keep lots of breaching charges around. 
loc_mex_58_03 = "",--You need to restart the detonator.
loc_mex_30_01 = "",--Time to juice up that plane. Get the fuel hose connected. 
loc_mex_58_02 = "",--The detonator has been stopped!
loc_mex_26_02 = "",--You would think the feds would've found this place and cleared it out.
loc_mex_40_04 = "",--Fly you fools!
loc_mex_54_01 = "",--There you go! Take them and set them on the door!
loc_mex_63_03 = "",--Thought that tunnel would never end! No time to waste, friends. Everyone knows you're there.
loc_mex_14_01 = "",--What's that? A blueprint?
loc_mex_48_02 = "",--Get rid of those biker keks!
loc_mex_81_02 = "",--You need to get some explosives onto the gate.
loc_mex_42_03 = "",--What happened? Do you read me friends?
loc_mex_18_03 = "",--That was a long bekakin' tunnel. Stay quiet and get to it, friends.
loc_mex_01_02 = "",--Now, get to finding that tunnel. The entrance should be fairly accessible. 
loc_mex_42_01 = "",--Blerrie! You guys OK?
loc_mex_65_04 = "",--"Ze plane, friends, ze plane!"
loc_mex_70_01 = "",--That should be enough to kick the Murkys in the teeth.
loc_mex_72_01 = "",--You're going to need two key cards to get in there. How many have you found?
loc_mex_35_01 = "",--You can probably find fuel in one of the warehouses. 
loc_mex_08_03 = "",--Look for a way to get the code.
loc_mex_85_01 = "",--Friends, you got to tell me what all the fuss is with those fish tacos. Sounds pretty awful if you ask me. Maybe if it were shark fins...
loc_mex_47_02 = "",--Go ahead. Make some noise, friends.
loc_mex_57_03 = "",--Keep it clear until it's done.
loc_mex_22_03 = "",--Start searching for that Murkywater nest egg. It's in the form of weapons.
loc_mex_69_02 = "",--The Murky resources we're after will be money. Could be kept anywhere nearby, so you're just going to have to search for it.
loc_mex_74_03 = "",--OK, friends. Time to put some fuel in that plane.
loc_mex_56_02 = "",--You gotta blow that door. 
loc_mex_42_02 = "",--Ach! Did you make it, friends?
loc_mex_05_03 = "",--You gotta find that code, friends. Check the rooms.
loc_mex_47_03 = "",--Let's go with the other plan. No need to keep quiet!
loc_mex_31_03 = "",--How's the refueling going?
loc_mex_48_03 = "",--You gotta take out those bikers!
loc_mex_80_03 = "",--Time to blow the gates so you can take off!
loc_mex_37_02 = "",--The plane is full, you can take off the hose.
loc_mex_75_03 = "",--You need to restart the pump!
loc_mex_07_03 = "",--Stay alert. 
loc_mex_20_01 = "",--You gotta find that plane. 
loc_mex_83_02 = "",--Gotta go, friends. Hurry!
loc_mex_23_02 = "",--The Murky resources we've gotta find will be in the form of drugs. They could be anywhere around here.
loc_mex_19_01 = "",--First thing to do is find that plane.
loc_mex_61_03 = "",--Time to go to Mexico, yeah?
loc_mex_01_01 = "",--OK, you chops. Time to find that tunnel entrance. 
loc_mex_82_02 = "",--Hurry, friends! Get to the plane.
loc_mex_38_03 = "",--One last thing. You got to open the gates so you can take off. Move fast, cause the Murkys will jump on us if they realize what's going on!
loc_mex_41_02 = "",--More dwankies coming soon. You gotta get out of there!
loc_mex_49_01 = "",--The tunnel entrance should be outside somewhere.
loc_mex_44_03 = "",--The code was wrong, they know you're there now!
loc_mex_09_03 = "",--Look out, the room is booby-trapped! Disarm or get out!
loc_mex_78_03 = "",--Looks like it's working. Will take some time before it's full.
loc_mex_36_01 = "",--That'll keep it going for now.
loc_mex_46_03 = "",--Old Locke knows what to do with those suits.
loc_mex_85_03 = "",--I've always wondered why I seem to have such bad luck near wildlife. There's always something trying to bite old Locke... And I do nothing but nice things for the little bastards.
loc_mex_11_01 = "",--When you find the code, get back to the keypad and give it a go.
loc_mex_67_03 = "",--Start searching for the Murkywater nest egg we're after. It's in the form of weapons.
loc_mex_52_01 = "",--Luckily, we were ready for this. Rust told me these Overkill dwankies keep loads of explosives around, so all you gotta do is find some.
loc_mex_46_02 = "",--Those suits will come in handy, later. 
loc_mex_17_03 = "",--You gotta get to Mexico. Hurry.
loc_mex_32_01 = "",--Right, now just let it fill up.
loc_mex_60_02 = "",--Looks like there might be an underground vault somewhere.
loc_mex_13_02 = "",--Groot job with the code.
loc_mex_33_01 = "",--Ag man, the pump stopped. Maybe it needs more juice?
loc_mex_60_01 = "",--What's that? A blueprint?
loc_mex_52_03 = "",--You'll probably find explosives around there to use.
loc_mex_86_03 = "",--The key is not going to work any longer, you gotta use a drill, friends.
loc_mex_85_02 = "",--One time, I was in the jungle with a kak piece of laptop, trying to hack into this ancient security system being run by a bunch of dwankie terrorists. In a very unfortunate event, a snake bites my leg, and I mistakenly activate the alarm, alerting everyone, and making them blow up the entire place. Lots of terrorists died, and no one got paid that day. Blerrie snake...
loc_mex_40_02 = "",--Hurry, friends! Get into that plane.
loc_mex_24_03 = "",--The Murky's nest egg is cash money, so start looking. It could be anywhere around there.
loc_mex_68_03 = "",--Start searching for the Murkywater nest egg we're after. It's in the form of cocaine.
loc_mex_75_02 = "",--You let someone stop the pump. Get over there and start it up!
loc_mex_49_03 = "",--You'll probably find the tunnel if you look around outside.
loc_mex_76_02 = "",--The plane needs juice to fly.
loc_mex_57_02 = "",--You gotta protect it for a bit. Shouldn't take too long.
loc_mex_09_01 = "",--Bliksem, the place is rigged! Get out of there if you can't disarm it!
loc_mex_06_01 = "",--Maybe in there?
loc_mex_43_03 = "",--No need to sneak about any longer!
loc_mex_03_01 = "",--There you go, that's it.
loc_mex_12_03 = "",--Check the tables, walls, chairs... wherever.
loc_mex_11_02 = "",--Ok, get to searching for the answer to that code. 
loc_mex_73_03 = "",--Whoever locked that in there doesn't want it to fall into hands like ours, so why not bring it along?
loc_mex_73_02 = "",--That would look lekker in Duke's corner, for sure! Maybe you should take it!
loc_mex_08_02 = "",--Go inside and see if there's a clue to the code anywhere.
loc_mex_06_03 = "",--Might be a good place to look.
loc_mex_35_02 = "",--Look around the warehouses for a can of fuel.
loc_mex_35_03 = "",--There's gotta be juice around there somewhere.
loc_mex_83_03 = "",--More dwankies incoming. You gotta get out of there!
loc_mex_79_01 = "",--Refueling is done, so take that hose off. 
loc_mex_68_02 = "",--The Murky resources we're after will be in the form of drugs. They could be anywhere around there, so you're just going to have to start looking.
loc_mex_08_01 = "",--Now, get in there and see what you can find.
loc_mex_21_01 = "",--There's your ride. Once you've got all the loot secured, you gotta get it refueled. 
loc_mex_16_03 = "",--Time to go to Mexico, yeah?
loc_mex_55_03 = "",--The detonator needs to be rigged.
loc_mex_14_03 = "",--Blueprints... to a vault?
loc_mex_27_01 = "",--Looks like the vault in the blueprint you found.
loc_mex_25_02 = "",--That should be enough to kick the Murkys in the teeth.
loc_mex_27_03 = "",--Good thing you found that blueprint. That's the vault.
loc_mex_38_02 = "",--You need to open the runway gates. It's gonna be jol, and the Murkys will go crazy when we take off!
loc_mex_66_02 = "",--That's the plane we're looking for. Get the loot inside, then give it some fuel.
loc_mex_24_01 = "",--Time to start looking for that stash of Murky loot. We're looking for cash, and lots of it. 
loc_mex_22_02 = "",--The Murky resources we're after will be weapons. They could be anywhere so you'll just have to start looking.
loc_mex_04_03 = "",--That's typical. You should have a look in the clubhouse in case these dwankies have left a way to access the code somewhere. Start with the briefing room.
loc_mex_20_03 = "",--The plane, friends, the plane!
loc_mex_12_01 = "",--Find the code. Did you check the whole room?
loc_mex_26_03 = "",--Gotta wonder who has the resources to back the Dentist in all this. Is he the top of the food chain, or is there more to this braai?
loc_mex_45_02 = "",--Heads-up, friends. Murky agents on the way.
loc_mex_25_01 = "",--Groot, that's all we need. Murkywater and the Dentist will be in big trouble once this hits home.
loc_mex_82_03 = "",--Time to fly, friends. Get onboard that dinges, quickly!
loc_mex_84_01 = "",--I think Rust mentioned this room. Maybe there's something useful in there.
loc_mex_62_03 = "",--You gotta get to Mexico. Hurry.
loc_mex_77_02 = "",--Make sure you protect the pump while it's running!
loc_mex_34_03 = "",--See to the pump again, friends.
loc_mex_12_02 = "",--Did you search everywhere?
loc_mex_36_02 = "",--Ok, that's enough for now.
loc_mex_63_01 = "",--Nice night for a barbacao. Shame the Cartel dwankies know we're crashing it!
loc_mex_74_01 = "",--Time to juice up that plane. Get the fuel hose connected. 
loc_mex_30_02 = "",--You gotta get some fuel in that dinges. Get to work. 
loc_mex_09_02 = "",--Ach, it's rigged with C4! Look out, friends!
loc_mex_17_01 = "",--You gotta get into that tunnel, friends. 
loc_mex_19_03 = "",--The getaway plane is probably still in one of the hangars.
loc_mex_34_01 = "",--Ach, the pump again. Donnerse thing needs more gas.
loc_mex_36_03 = "",--Should stay running for a bit, now.
loc_mex_37_01 = "",--Refueling is done, so take that hose off. 
loc_mex_51_03 = "",--You can't use the keypad. Time to blow the door open!
loc_mex_53_03 = "",--Might be a good idea to look outside.
loc_mex_54_02 = "",--That looks right. Grab them and put them on the door.
loc_mex_56_01 = "",--What are you waiting for? Set that detonator!
loc_mex_61_01 = "",--OK, get into that tunnel. Time for a visit to Mexico.
loc_mex_62_02 = "",--Hurry up you chops, get into that tunnel.
loc_mex_71_01 = "",--Looks like the vault in the blueprint you found.
loc_mex_78_01 = "",--Right, now just let it fill up.
loc_mex_80_01 = "",--Now you gotta clear the runway by blowing the gates!
loc_mex_80_02 = "",--You need to blow the runway gates. It's gonna be jol!
loc_mex_81_01 = "",--Stick some explosives on the gate and we're good to go.
loc_mex_86_02 = "",--Ach, now you've got to drill through the door instead.
