heist_mex = "",--Border Crossing
heist_mex_transition = "แห่งหนึ่งในเม็กซิโก",--SOMEWHERE IN MEXICO...
hud_heist_mex17 = "รอจนกว่าจะเติมน้ำมันให้กับเครื่องบินเสร็จ",--Wait for the pump to refuel the plane.
hud_heist_mex21_hl = "ระเบิดประตูรันเวย์ทิ้งซะ",--Blow up the runway gates
hud_heist_mex7 = "พยายามอย่าให้พวก Murkywater หยุดการทำงานของเครื่องระเบิด",--Keep the Murkywater soldiers from disabling the detonator.
hud_heist_mex18 = "พยายามอย่าให้พวก Murkywater ถอดสายยางออกจากถังน้ำมันหรือเครื่องปั้ม",--Keep the Murkywater soldiers from detaching the hose from the tank or the pump.
hud_heist_mex1 = "ค้นหาอุโมงค์ใต้ดินเพื่อไปยังเม็กซิโก",--Find an underground tunnel leading to Mexico somewhere outside.
hud_heist_mex8 = "ใช้อุโมงค์เพื่อข้ามฝั่งชายแดน",--Use the tunnel to reach the other side of the border.
hud_heist_mex11_hl = "การหลบหนีพร้อมแล้ว",--Escape available
hud_heist_mex3_hl = "ค้นหารหัสและใช้งาน",--Find and enter the code
hud_heist_mex11 = "หลบหนีโดยขโมยเครื่องบิน",--Escape by stealing the plane.
hud_heist_mex10_hl = "เชื่อมต่อท่อเข้ากับเครื่องบิน",--Connect the fuel hose to the plane
hud_heist_mex16_hl = "ค้นหากุญแจเครื่องบิน",--Find the keys to the plane
hud_heist_mex1_hl = "ค้นหาอุโมงค์",--Locate the tunnel
hud_heist_mex2_hl = "ค้นหาและเข้าไปยังห้องทำงาน",--Locate and enter the briefing room
hud_heist_mex7_hl = "ป้องกันเครื่องระเบิด",--Defend the detonator
hud_heist_mex13 = "ค้นหาและขโมยเงินบริเวณโดยรอบ",--Find and steal money from around the compound.
hud_heist_mex6 = "เริ่มนับเครื่องระเบิดเพื่อทำการทำลาย",--Start the countdown to detonate the breaching charges.
hud_heist_mex20 = "ถอดสายยางออกจากเครื่องบิน",--Detach the hose from the plane.
hud_heist_mex15_hl = "เติมน้ำมันเครื่องปั้ม",--Refuel the generator
hud_heist_mex9_hl = "ขโมยอาวุธ",--Steal weapons
hud_heist_mex19 = "ค้าหาสวิตช์เพื่อเปิดประตูรันเวย์",--Find the switch to open the gates to the runway.
hud_heist_mex15 = "ค้นหาน้ำมันถังสีแดงและเติมเข้าเครื่องปั้ม",--Find red gasoline cans and refuel the pump's generator.
hud_heist_mex17_hl = "รอเติมน้ำมัน",--Wait for the refueling process
hud_heist_mex8_hl = "เข้าอุโมงค์ไปยังเม็กชิโก",--Take the tunnel to Mexico
hud_heist_mex14 = "ค้าหาเครื่องบินในโรงเก็บเครื่องบิน",--Find the plane in one of the hangers.
hud_heist_mex4_hl = "ค้าหาเครื่องระเบิด",--Find the breaching charges
hud_heist_mex18_hl = "ป้องกันสายยาง",--Defend the hose
hud_heist_mex13_hl = "ขโมยเงิน",--Steal money
hud_heist_mex2 = "ค้าหาห้องทำงานของแก๊งมอเตอร์ไซต์และเข้าไปข้างใน",--Search the bikers clubhouse for the briefing room and gain access to it.
hud_heist_mex5 = "วางเครื่องระเบิดหน้าอุโมงค์",--Place the breaching charges on the tunnel entrance.
hud_heist_mex12_hl = "ขโมยโคเคน",--Steal cocaine
hud_heist_mex4 = "ค้าหาระเบิดที่กลุ่มมอเตอร์ไซต์เก็บไว้",--Find where the bikers are storing breaching charges.
hud_heist_mex19_hl = "เปิดรันเวย์",--Open the runway gates
hud_heist_mex10 = "ค้นหาถังน้ำมันของเครื่องบิน เครื่องปั้ม และเชื่อมสายยางทั้งคู่เข้าเครื่องบิน",--Find a tank of airplane fuel and a pump. Connect them both to the plane.
hud_heist_mex12 = "ค้นหาและขโมยโคเคนจากบริเวณโดยรอบ",--Find and steal cocaine from around the compound.
hud_heist_mex14_hl = "ค้นหาเครื่องบินหลบหนี",--Locate the getaway plane
hud_heist_mex16 = "ค้นหากุญแจเครื่องบินบริเวณโดยรอบ",--Locate the plane keys somewhere in the compound.
hud_heist_mex20_hl = "ถอดสายยาง",--Detach the hose
hud_heist_mex21 = "ใช้ระเบิด C4 เพื่อเปิดรันเวย์",--Use C4 to blow open the runway gates.
hud_heist_mex3 = "ดูการใบ้เพื่อค้นหารหัสผ่านที่แท้จริงและนำไปใส่ที่ปุ่มกดรหัส",--Use the hint to locate the correct code and enter it into the keypad.
hud_heist_mex5_hl = "วางระเบิด",--Set up the breaching charges
hud_heist_mex6_hl = "ตั้งค่าระเบิด",--Rig the detonator
hud_heist_mex9 = "หาและขโมยอาวุธจากบริเวณโดยรอบ",--Find and steal weapons from around the compound.
loc_mex_23_01 = "ได้เวลาหาของที่ Murky มีแล้วหละ และสิ่งที่เรากำลังตามหาคือ สารเสพติด",--Time to start looking for that stash of Murky loot. It's drugs we're after. 
loc_mex_03_02 = "เยี่ยมมาก เพื่อน นั่นแหละสิ่งที่เรากำลังมองหาอยู่",--Nicely done, friends. That's what we're looking for.
loc_mex_70_03 = "นี่ไม่ใช่วันที่ดีของ Murky แน่นอนหรือ the Dentist ใช่ไหมละ? แน่นอน!",--This is not a good day for Murkywater or the Dentist, yeah?! For sure!
loc_mex_64_02 = "สิ่งสำคัญแรกที่ต้องทำก็คือ หายานพาหนะเพื่อจะออกไปจากที่นั่น บางที่ก็โรงเก็บเครื่องบินใช่ไหมละ?",--Your first priority is finding your ride out of there. Maybe check the hangars, yeah?
loc_mex_68_01 = "ได้เวลาหาของที่ Murky มีแล้วหละ และสิ่งที่เรากำลังตามหาคือ สารเสพติด",--Time to start looking for that stash of Murky loot. It's drugs we're after. 
loc_mex_61_02 = "ทีนี้ก็หยิบหมวก sombreros ของตัวเองแล้วเข้าไปในอุโมงค์กันเถอะ",--Now get your sombreros on and into that tunnel.
loc_mex_40_03 = "ได้เวลาบินแล้วเพื่อน",--Time to fly, friends. 
loc_mex_45_03 = "Murky กำลังไปหาแล้ว",--Murky dwankies coming your way!
loc_mex_46_01 = "ได้ไอเดียแล้วเกี่ยวกับสิ่งที่เราสามารถใช้มันทีหลัง",--I've got an idea about what we can use those for later!
loc_mex_21_03 = "โอเค นั่นแหละ ถ้าเอาของขึ้นเครื่องหมดแล้ว จำเป็นที่จะต้องเลี้ยงน้ำให้กับมันสักหน่อย",--OK, that's it. When you've got the loot aboard, you need to juice it up as well.
loc_mex_66_01 = "นั่นแหละ ที่เราจะใช้มันหนีไปจากที่นี่ ถ้าเก็บของบริเวณรอบๆครบแล้วละก็ต้องเติมน้ำมันให้มันด้วย",--There's your ride out. Once you've got all the loot secured, you gotta get it refueled. 
loc_mex_53_01 = "ไม่บอกนะว่ามันอยู่ที่ไหน ต้องลองมองหาบริเวณรอบๆดู",--No telling where they might be though, you'll have to look around.
loc_mex_32_02 = "ให้เวลามันเติมนิดหนึ่ง",--Just gotta give it some time to fill.
loc_mex_44_02 = "รหัสผิด สัญญานเตือนดังแล้ว!!!",--Wrong code, the alarm has gone off!
loc_mex_59_01 = "อีกเดี๋ยวหนึ่ง...",--Wait for it... 
loc_mex_76_03 = "การเติมน้ำมันเป็นยังไงบ้าง?",--How's the refueling going?
loc_mex_53_02 = "ทำให้แน่ใจด้วยนะว่ามองดูทุกทีแล้ว",--Make sure you look around everywhere.
loc_mex_13_03 = "นั่นแหละ เยี่ยมมมมม",--That was it. Niiice.
loc_mex_23_03 = "เริ่มการค้นหารังของ Murkywater ได้และมันดูเหมือนโคเคนมากเลยหละ",--Start searching for that Murkywater nest egg, shaped like a lot of cocaine.
loc_mex_69_03 = "รังของ Murkywater คือเงินนี่เอง ถ้างั้นก็มองดูรอบๆ มันจะอยู่ได้ทุกที่แหละ",--The Murky's nest egg is cash money, so start looking. It could be anywhere around there.
loc_mex_49_02 = "พวกมันต้องการจะใช้งานองค์อย่างง่ายดายแหละ ลองมองหาข้างนอกดู",--They would probably want easy access to the tunnel, so check around outside.
loc_mex_44_01 = "อ๊าว ดูเหมือนว่ารหัสจะผิด!",--Ag man, that was the wrong code!
loc_mex_54_03 = "ดี ทีนี้ก็เอาไปไว้ที่ประตู",--Good, now get them onto the door!
loc_mex_01_03 = "เพื่อน หาอุโมงค์นั่น พวกมันน่าจะซ่อนมันไว้ แต่ไม่น่าจะยากพอที่จะหามันหรอก",--Find that tunnel, friends. They've probably got it hidden, but it shouldn't be too hard to locate.
loc_mex_55_01 = "ติดตั้งเครื่องระเบิด",--Set up the detonator.
loc_mex_07_01 = "ดูสิ่งที่ผิดปกติด้วย",--Watch for anything odd.
loc_mex_71_02 = "อ๊า นั่นห้องเซฟจากพิมพ์เขียว",--Blerrie, that's the vault from the blueprints. 
loc_mex_10_01 = "โอ้ เกือบหัวใจวายซะแล้วเชียว เกือบแล้วไหมละ",--Oh, you're going to give old Locke a heart attack. That was a close one.
loc_mex_28_01 = "ต้องการคีย์การ์ดอย่างน้อย 2 ใบเพื่อเข้าไปข้างในนั้น",--You're going to need two key cards to get in there. 
loc_mex_64_01 = "อันดับแรกที่ต้องทำคือ หาเครื่องบิน โดยเริ่มต้นหาที่โรงเก็บเครื่องบินละกัน",--First thing to do is find that plane. Start by looking in the hangars. 
loc_mex_11_03 = "ต้องหารหัสผ่านใช่ไหมหล่ะ?",--Get to searching for the code, yeah?
loc_mex_65_01 = "ต้องหาเครื่องบินนั้นมให้ได้",--You gotta find that plane. 
loc_mex_83_04 = "บินกันไอ้โง่!",--Fly you fools!
loc_mex_02_03 = "ดูเหมือนว่าจะต้องหาอุโมค์ที่อยู่บริเวณด้านนอก",--You'll probably find the tunnel if you look around outside.
loc_mex_04_01 = "อ๊า แน่นอนสิพวกมันมีรหัสผ่านไว้ บางทีก็ลองหา รหัสลับที่คลับในห้องทำงานดู ลองไปดูสักหน่อยไหมละ?",--Ah, blerrie. Of course it had to have a keylock. Maybe you can find some way to figure out the code in the clubhouse briefing room. Go have a look, yeah?
loc_mex_84_03 = "Rust พูดไว้เกี่ยวกับเรื่องนี้ ลองหาดูว่าอาจจะมีอะไรมีประโยชน์",--Rust said something about this... see if you can find anything useful.
loc_mex_81_03 = "ระเบิดกำแพงซะ เพื่อน",--Blow up the gate, friends!
loc_mex_74_02 = "ต้องหาเชื้อเพลิงหน่อย ไปทำงาน",--You gotta get some fuel in that dinges. Get to work. 
loc_mex_05_01 = "เอาหน่อยน่า ลองหาดู",--Come on you chops, keep looking.
loc_mex_15_03 = "ไปได้สวย กล้องไปเรียบร้อยแล้ว",--Nice going, taking out the cameras.
loc_mex_65_02 = "อย่ายืนอยู่เฉยๆ หาเครื่องบิน ด่วน!",--No standing around. Find the plane, quickly.
loc_mex_31_01 = "จะหนียังไงถ้าถังยังว่างเปล่าแบบนั้น เติมน้ำมันสิ!",--Can't get out of there on an empty tank. Fuel the plane!
loc_mex_16_02 = "ทีนี้ก็ใส่ sombreros ของตัวเองแล้วเข้าไปในอุโมงค์นั่นกัน",--Now put your sombreros on and get into that tunnel.
loc_mex_04_02 = "อ๊า น่าจะรู้ไว้ก่อนว่าพวกมันล็อคไว้ บางทีลองหาเบาะแสไปหารหัสผ่านในห้องทำงานของพวกมันละกัน",--Ach, I should've known they would have it locked. Maybe have a look in the clubhouse and see if you can find any clues to the code in the briefing room.
loc_mex_59_03 = "ปิดหูไว้ พวก เสียงมันดังมาก",--Hold your ears, you chops! It's going to be loud!
loc_mex_43_02 = "พวกมันรู้แล้วว่าพวกเราอยู่นี่",--Everyone knows you're there now!
loc_mex_38_01 = "ทีนี้นายต้องจัดการกับประตูรันเวย์โดยการเปิดมัน พวก Murkys และ Cartel dwankies จะต้องโกรธแน่นอน เมื่อพวกมันรู้ว่าพวกเราทำอะไรลงไป",--Now you gotta clear the runway by opening the gates. The Murkys and Cartel dwankies will go bossies, when they realise what we're doing!
loc_mex_06_02 = "ดูเหมือนจะเป็นที่หาเบาะแสที่ดีนะเนี่ย",--Looks like a good place to check for clues.
loc_mex_29_01 = "มันน่าจะมีอะไรพิเศษบางอย่างอยู่ข้างในนั้นแน่นอนถึงได้ล็อคมันไว้แบบนี้ บางทีน่าจะเอามันมาด้วยสักหน่อยไหม?",--There's gotta be something special about that thing if they keep it locked up in here. Maybe take it with you, yeah?
loc_mex_25_03 = "มันไม่ใช่วันที่ดีของ Murkywater หรือ Dentist แน่ ใช่ไหมหละ?",--This is not a good day for Murkywater or the Dentist, yeah?
loc_mex_33_03 = "ต้องใช้เชื้อเพลิงเพิ่มที่ปั้ม donnerse",--You gotta get some more gas in that donnerse pump.
loc_mex_07_02 = "ระมัดระวังนะเพื่อน",--Tread carefully, friends.
loc_mex_84_02 = "อะไรเนี่ย? ดูแล้วน่าจะคุ้มแค่อยู่ใช่ไหมหละ ?",--What's this? Might be worth a look, yeah?
loc_mex_39_01 = "ต้องจัดการกับรันเวย์หนะ เพื่อน",--You have to clear the runway, friends!
loc_mex_51_01 = "ปุ่มกดรหัสหยุดทำงานแล้ว ดูเหมือนว่าจะต้องระเบิดมันเข้าไปนะ",--The keypad has been disabled! You're going to have to blow your way in.
loc_mex_57_01 = "ที่อย่าพวก dwankies เข้าใกล้มันหละ",--Now keep it clear of dwankies.
loc_mex_41_01 = "ไม่มีเวลานั่งเล่นแล้ว ต้องไปกันแล้ว!",--No time to sit around, you gotta go!
loc_mex_78_02 = "ทีนี้ก็ให้เวลามันเติมก่อนสักนิดหนึ่ง",--Just gotta give it some time to fill.
loc_mex_79_03 = "ได้เวลาถอดสายยางออกแล้ว เครื่องบินเชื้อเพลิงเต็มแล้ว!",--Time to disconnect the hose, the plane is all full.
loc_mex_66_03 = "โอเคนั่นแหละ ถ้าได้ของข้างในแล้วก็ต้องเลี้ยงน้ำให้มันสักหน่อย",--OK, that's it. When you've got the loot inside, you need to juice it up as well.
loc_mex_73_01 = "ถ้ามันล็อคไว้แบบนี้มันน่าจะมีอะไรพิเศษเกี่ยวกับมันอยู่นะเนี่ย ลองเอาไปด้วยไหมหละ?",--There's gotta be something special about that thing if they keep it locked up in here. Maybe take it with you, yeah?
loc_mex_32_03 = "ดูเหมือนจะใช้ได้อยู่ ทีนี้ก็รอจบกว่ามันจะเติม",--Looks like it's working. Will take some time before it's full.
loc_mex_60_03 = "พิมพ์เขียวไปหาตู้เซฟงั้นหรอ น่าสนใจ",--Blueprints to a vault. Interesting.
loc_mex_30_03 = "โอเคเพื่อน ได้เวลาเติมน้ำมันเครื่องบินแล้ว",--OK, friends. Time to put some fuel in that plane.
loc_mex_18_02 = "ยินดีต้อนรับสู่ เม๊กซิโก เพื่อน พยายามอย่าให้มันวุ่นวายหละ!",--Welcome to Mexico amigos. Try not to make a ruckus.
loc_mex_21_02 = "เครื่องบินนั่นแหละ เอาของขึ้นเครื่อง และเติมเชื้อเพลิงให้มันหน่อย",--That's the plane. Get the loot inside, then give it some fuel.
loc_mex_15_02 = "ดูเหมือนว่าจะจัดการกับกล้องเรียบร้อยเพื่อน",--You took care of the cameras, friends.
loc_mex_45_01 = "พวก Murkys กำลังมาแล้ว",--You've got Murkys coming!
loc_mex_02_01 = "อุโมงค์ทางเข้าน่าจะอยู่ข้างนอกสักที่หนึ่ง",--The tunnel entrance should be outside somewhere.
loc_mex_02_02 = "พวกมันต้องการจะใช้งานองค์อย่างง่ายดายแหละ ลองมองหาข้างนอกดู",--They would probably want easy access to the tunnel, so check around outside.
loc_mex_39_03 = "เกือบได้เวลาเผ่นแล้ว เหลือแค่เปิดรันเวย์เท่านั้น",--Almost time to leave. You just need to open up the runway.
loc_mex_29_03 = "คงไม่ได้คิดว่าแก๊งค้ายาจะมายุ่งกับของพวกนี้ใช่ไหมหละ? บางทีเอามันติดตัวมาด้วยก็ดี",--You wouldn't think that the cartels would bother with such a thing, yeah? Might as well take it with you.
loc_mex_20_02 = "อย่ามัวแต่ยืนเล่น หาเครื่องบินไห้ไวเลย",--No standing around. Find the plane, quickly.
loc_mex_75_01 = "อ๊า! มีคนหยุดเครื่องปั้ม ไปจัดการกับมันหน่อย!",--Ach! Someone stopped the pump. Get it going again!
loc_mex_55_02 = "ทีนี้ก็เชื่อมกับตัวจุดซะ เพื่อน",--Now hook up the detonator, friends.
loc_mex_59_02 = "เรามาแล้ววววว พวก.... เรา.... มา.... แล้ววววววววว!",--Here we go... here... we... goooooo!
loc_mex_65_03 = "เครื่องบิน เพื่อน เครื่องบิน!",--The plane, friends, the plane!
loc_mex_67_02 = "ทรัพยากรของ Murky ที่เรากำลังตามหาคือ อาวุธปืน มันจะอยู่ที่ไหนก็ได้แถวๆนี้แหละ ก็แค่ต้องลองหามันดู",--The Murky resources we're after will be weapons. They could be anywhere around here, so you're just going to have to start looking.
loc_mex_48_01 = "พวก dwankies มาเพิ่มอีกแล้ว จัดการกับพวกมันซะ",--More leather dwankies! Take care of them.
loc_mex_13_01 = "ทำได้ดีมากเพื่อน",--Nicely done, friends. 
loc_mex_67_01 = "ได้เวลาหาของที่ Murky มีแล้วหละ และสิ่งที่เรากำลังตามหาคือ อาวุธปืน",--Time to start looking for that stash of Murky loot. It's weapons we're after. 
loc_mex_43_01 = "แถวๆนั้นได้ยินเสียงระเบิดนั่นหมดเลย",--The entire compound heard that blast. 
loc_mex_62_01 = "ต้องเข้าไปในอุโมงค์แล้วเพื่อน",--You gotta get into that tunnel, friends. 
loc_mex_50_03 = "อ๊า นั่นคือทางเข้าอุโมงค์ ถ้ามันเหมือนกันกับที่เคยเห็นอะนะ",--Ah, that's a tunnel entrance if I've ever seen one.
loc_mex_77_01 = "ดี ที่นี้ก็อย่าให้พวก dwankies เข้าใกล้เครื่องปั้มหละ",--Good, now keep those dwankies away from the pump!
loc_mex_19_02 = "สิ่งสำคัญแรกที่ต้องทำก็คือ หายานพาหนะเพื่อจะออกไปจากที่นั่น บางที่ก็โรงเก็บเครื่องบินใช่ไหมละ?",--Your first priority is finding your ride out of there. Maybe check the hangars, yeah?
loc_mex_14_02 = "ดูเหมือนว่ามันจะมีทางเข้าใต้ดินอยู่ที่ไหนสักทีหนึ่ง",--Looks like there might be an underground vault somewhere.
loc_mex_71_03 = "เจอพิมพ์เขียวหนิ เยี่ยมไปเลย",--Good thing you found that blueprint. 
loc_mex_58_01 = "มันหยุดทำงานแล้ว! ต้องทำให้มันทำงานอีกครั้ง!",--It stopped! You gotta start it up again!
loc_mex_37_03 = "ได้เวลาถอดสายยางออกแล้ว เครื่องบินเชื้อเพลิงเต็มแล้ว!",--Time to disconnect the hose, the plane is all full.
loc_mex_05_02 = "หามันเจอรึยัง? ได้ลองดูชั้นต่อไปรึยัง?",--Did you find it yet? Have you checked the upper floor?
loc_mex_33_02 = "ปั้มต้องการให้เติมเชื้อเพลิง",--The pump needs to be filled with gasoline.
loc_mex_86_01 = "ไม่มีกุญแจเข้าไปดูเหมือนว่าจะต้องเจาะเข้าไปแทนแล้วหละ",--Can't get in there with a key now, you gotta use a dril instead.
loc_mex_77_03 = "ปั้มต้องทำงานตลอดนะนั้น ดูแลมันด้วย!",--You gotta keep the pump running. Protect it!
loc_mex_24_02 = "ของ Murky ที่เรากำลังตามหาอยู่นั้นคือ เงิน มันอยู่ได้ทุกที่บริเวณรอบๆแถวนั้นแหละ แต่ก็ต้องหามันสักหน่อย",--The Murky contraband we're after will be money. Could be kept anywhere nearby, so you're just going to have to search for it.
loc_mex_40_01 = "ดี ทีนี้ก็ได้เวลาเผ่น ขั้นเครื่องให้ไว้เลย",--Good, now it's time to leave. Get onboard that dinges, quickly!
loc_mex_82_01 = "",--Blerrie, what a noise! Time to leave!
loc_mex_31_02 = "เครื่องบินต้องมีน้ำมันเพื่อบิน!",--The plane needs juice to fly.
loc_mex_76_01 = "จะหนียังไงถ้าถังยังว่างเปล่าแบบนั้น เติมน้ำมันสิ!",--Can't get out of there on an empty tank. Fuel the plane!
loc_mex_39_02 = "เปิดประตูและจัดการเส้นทางให้เรียบร้อยก่อนที่จะออกตัวได้",--Open the gate so you have a clear path to take off.
loc_mex_34_02 = "ปั้มหยุดทำงานอีกแล้ว",--The pump stopped again.
loc_mex_47_01 = "ไม่ต้องย่องอีกต่อไปแล้ว Locke มีแผน B!",--No need to sneak about now. Locke has a plan B!
loc_mex_50_01 = "นั่นแหละพวก นั่นแหละ",--There you go, that's it.
loc_mex_69_01 = "ได้เวลาหาของที่ Murky มีแล้วหละ และสิ่งที่เรากำลังตามหาคือ เงิน และมีเยอะมากด้วยหละ",--Time to start looking for that stash of Murky loot. We're looking for cash, and lots of it. 
loc_mex_10_03 = "เยี่ยมมาก ปล่อยให้พวก Overkill dwankies ก้าวผ่านกับผู้รักษาความปลอดชั้นสูงเถอะ",--Nicely done. Leave it to those Overkill dwankies to go over the top with security.
loc_mex_64_03 = "เครื่องบินหนีน่าจะอยู่ที่โรงจอดเครื่องบินอันใดอันหนึ่ง ลองไปดูกัน",--The getaway plane is probably in one of the hangars. Go have a look!
loc_mex_29_02 = "นั่นมันดูดีมากเลยถ้ามันอยู่ในเซฟเฮาส์เรา จะสร้างห้องให้มันใหม่ด้วยหละ เอามันมาด้วยละกัน",--That will look great in the safehouse if we can ever make room for it. Take it with you. 
loc_mex_16_01 = "โอเค เข้าไปยังอุโมงค์ ได้เวลาไปเยี่ยมเม๊กชิโกแล้ว",--OK, get into that tunnel. Time for a visit to Mexico.
loc_mex_17_02 = "รีบๆหน่อยพวก ไปเข้าอุโมงค์",--Hurry up you chops, get into that tunnel.
loc_mex_27_02 = "อ๊า! นั่นมันตู้เซฟจากพิพม์เขียวหนิ",--Blerrie, that's the vault from the blueprints. 
loc_mex_70_02 = "ดี เอาของที่เราต้องการมา Murkywater กับ the Dentist จะมีปัญหาแน่นอนถ้าเราถึงบ้านแล้ว",--Good, we got what we need. Murkywater and the Dentist will be in big trouble once this hits home.
loc_mex_51_02 = "อ๊า! ปุ่มกดรหัสผ่านใช้ไม่ได้แล้ว ต้องระเบิดประตูทิ้ง",--Ach, the keypad doesn't work. You gotta blow the door.
loc_mex_79_02 = "เครื่องบินเต็มแล้ว! ทีนี้ก็ถอดสายยางออกได้แล้ว",--The plane is full, you can take off the hose.
loc_mex_15_01 = "กล้องไม่ทำงานอีกต่อไปแล้ว",--Cameras are now disabled.
loc_mex_63_02 = "ยินดีต้อนรับสู่ เม๊กซิโก เพื่อน อย่าเสียเวลาเปล่าเลย!",--Welcome to Mexico, dear amigos. No time to waste!
loc_mex_22_01 = "ได้เวลาหาของที่ Murky มีแล้วหละ และสิ่งที่เรากำลังตามหาคือ อาวุธปืน",--Time to start looking for that stash of Murkywater contraband. It's weapons we're after. 
loc_mex_10_02 = "ให้ไวเลยเพื่อน",--Fast work, friends. 
loc_mex_83_01 = "ไม่มีเวลานั่งเล่นแล้ว ต้องออกจากที่นั่นแล้ว",--No time to sit around, you gotta go!
loc_mex_50_02 = "เยี่ยมมากเพื่อน นั่นแหละสิ่งที่เรากำลังตามหาอยู่",--Nicely done, friends. That's what we're looking for.
loc_mex_56_03 = "รีบๆหน่อยเพื่อน ที่จุดชนวนหนะ!",--Hurry, friends. The detonator! 
loc_mex_03_03 = "นั่นเป็นอุโมงค์ที่เคยเห็นมาก่อนนี่หนา",--That's a tunnel entrance if ever I've seen one.
loc_mex_18_01 = "ถือว่าเป็นคืนที่ดีกลางทะเลทรายเลยหละ ลองย่องเงียบดูละกัน",--Nice night for a jol in the desert. Try to stay quiet.
loc_mex_52_02 = "ตามที่ Rust เคยบอกไว้ว่าพวกแก๊งมอเตอร์ไซต์มีระเบิดทำลายเยอะมากอยู่แถวๆนี้",--According to Rust, these biker keks keep lots of breaching charges around. 
loc_mex_58_03 = "ดูเหมือนว่าต้องเริ่มต้นชนวนใหม่อีกครั้ง",--You need to restart the detonator.
loc_mex_30_01 = "ได้เวลาเลี้ยงน้ำเครื่องบินแล้ว ต่อสายเชื้อเพลิงเลย",--Time to juice up that plane. Get the fuel hose connected. 
loc_mex_58_02 = "ที่จุดชนวนหยุดทำงาน",--The detonator has been stopped!
loc_mex_26_02 = "คิดไหมถ้าหากพวก feds มาเจอพวกนี้เข้าแล้วก็น่าจะจัดการมันให้หมด",--You would think the feds would've found this place and cleared it out.
loc_mex_40_04 = "บินกันไอ้โง่",--Fly you fools!
loc_mex_54_01 = "นั่นแหละ! เอาไว้วางไว้ที่ประตู",--There you go! Take them and set them on the door!
loc_mex_63_03 = "นึกว่าอุโมงค์นั่นจะไม่สิ้นสุดแล้วหละสิ ไม่มีเวลาให้เสียแล้ว เพื่อน พวกมันรู้แล้วว่าเราอยู่นี่",--Thought that tunnel would never end! No time to waste, friends. Everyone knows you're there.
loc_mex_14_01 = "อะไรหนะนั่น? พิมพ์เขียวงั้นหรอ?",--What's that? A blueprint?
loc_mex_48_02 = "จัดการกับพวกไบเกอร์ให้หมด!",--Get rid of those biker keks!
loc_mex_81_02 = "ต้องการระเบิดไว้หน้าประตู",--You need to get some explosives onto the gate.
loc_mex_42_03 = "เกิดอะไรขึ้น? ติดต่อได้ไหมเพื่อน?",--What happened? Do you read me friends?
loc_mex_18_03 = "นั่นมันเป็นอุโมงค์ที่ยาวมาก อยู่ให้เงียบไว้และจัดการเสร็จนะเพื่อน",--That was a long bekakin' tunnel. Stay quiet and get to it, friends.
loc_mex_01_02 = "ทีนี้ต้องหาอุโมงค์นั่นให้ได้ ทางเข้าน่าจะเข้าถึงได้ไม่ยากนัก",--Now, get to finding that tunnel. The entrance should be fairly accessible. 
loc_mex_42_01 = "เห้ย! โอเคกันรึปล่าว",--Blerrie! You guys OK?
loc_mex_65_04 = "เครื่องบินเพื่อน เครื่องบิน",--"Ze plane, friends, ze plane!"
loc_mex_70_01 = "นั่นน่าจะมากพอที่จะเตะฟันของ Murkys ให้หลุดแล้วหละ",--That should be enough to kick the Murkys in the teeth.
loc_mex_72_01 = "ดูเหมือนว่าต้องการคีย์การ์ดสองอันเพื่อเข้าไปข้างใน เจอกี่อันแล้วหละ ?",--You're going to need two key cards to get in there. How many have you found?
loc_mex_35_01 = "ดูเหมือนว่าเชื้อเพลิงจะหาได้ง่ายๆรอบๆโกดังนะ",--You can probably find fuel in one of the warehouses. 
loc_mex_08_03 = "ลองหาวิธีหารหัสผ่านดู",--Look for a way to get the code.
loc_mex_85_01 = "เพื่อน ดูเหมือนว่าต้องบอกกันหน่อยเกี่ยวกับปลาทาโก้นั่น มันฟังดูน่าขยะแขยงมากถ้าถามกลับมาอะน่ะ ถ้ามันเป็นครีบของปลาฉลาม",--Friends, you got to tell me what all the fuss is with those fish tacos. Sounds pretty awful if you ask me. Maybe if it were shark fins...
loc_mex_47_02 = "เอาเลยพวก เสียงดังกันสักหน่อย",--Go ahead. Make some noise, friends.
loc_mex_57_03 = "จัดการกับมันให้ได้จนกว่าจะเสร็จหละ",--Keep it clear until it's done.
loc_mex_22_03 = "เริ่มหารังของพวก Murkywater และมันก็ดูเหมือนจะทำมาจากอาวุธปืนอะนะ",--Start searching for that Murkywater nest egg. It's in the form of weapons.
loc_mex_69_02 = "ทรัพยากรของ Murky ที่เราตามหาคือเงิน มันอยู่ได้ทุกที่บริเวณรอบๆแถวนั้นแหละ แต่ก็ต้องหามันหน่อย",--The Murky resources we're after will be money. Could be kept anywhere nearby, so you're just going to have to search for it.
loc_mex_74_03 = "โอเคเพื่อน ได้เวลาเติมเชื้อเพลิงเข้าเครื่องบินแล้ว",--OK, friends. Time to put some fuel in that plane.
loc_mex_56_02 = "ดูเหมือนว่าต้องระเบิดประตูนั้นนะ",--You gotta blow that door. 
loc_mex_42_02 = "อ๊า! ทำสำเร็จไหมพวก ?",--Ach! Did you make it, friends?
loc_mex_05_03 = "ดูเหมือนต้องหารหัสผ่านนะพวก ลองหาที่ห้องดู",--You gotta find that code, friends. Check the rooms.
loc_mex_47_03 = "ไปกันกับแผนอื่น ไม่ต้องเงียบอีกต่อไปแล้ว",--Let's go with the other plan. No need to keep quiet!
loc_mex_31_03 = "การเติมเชื้อเพลิงเป็นยังไงบ้าง",--How's the refueling going?
loc_mex_48_03 = "จัดการกับพวกไบเกอร์ให้หมดไปซะ!",--You gotta take out those bikers!
loc_mex_80_03 = "ได้เวลาระเบิดประตูแล้ว และจะได้ไปสักที",--Time to blow the gates so you can take off!
loc_mex_37_02 = "เครื่องบินเต็มแล้ว! ทีนี้ก็ถอดสายยางออกได้แล้ว",--The plane is full, you can take off the hose.
loc_mex_75_03 = "ต้องเริ่มการทำงานเครื่องปั้มใหม่",--You need to restart the pump!
loc_mex_07_03 = "ระวังตัวไว้",--Stay alert. 
loc_mex_20_01 = "ต้องหาเครื่องบินนั้นให้ได้",--You gotta find that plane. 
loc_mex_83_02 = "ต้องไปแล้วพวก รีบๆหน่อย",--Gotta go, friends. Hurry!
loc_mex_23_02 = "ทรัพยากรของ Murky ที่เรากำลังตามหาคือ สารเสพติด มันจะอยู่ที่ไหนก็ได้แถวๆนี้แหละ ก็แค่ต้องลองหามันดู",--The Murky resources we've gotta find will be in the form of drugs. They could be anywhere around here.
loc_mex_19_01 = "อย่างแรกที่ต้องทำเลยคือหาเครื่องบินนั่น",--First thing to do is find that plane.
loc_mex_61_03 = "ได้เวลาไปเม๊กชิโกแล้วใช่ไหมพวก?",--Time to go to Mexico, yeah?
loc_mex_01_01 = "โอเค ได้เวลาหาอุโมงค์นั่น",--OK, you chops. Time to find that tunnel entrance. 
loc_mex_82_02 = "รีบๆหน่อยเพื่อน ขึ้นเครื่องบิน",--Hurry, friends! Get to the plane.
loc_mex_38_03 = "อย่างสุดท้ายคือ ต้องเปิดประตูก่อนถึงจะสามารถออกตัวได้ จัดการให้ไว เพราะพวก Murkys จะโถมมาแน่ถ้าพวกมันรู้ว่าเกิดอะไรขึ้น",--One last thing. You got to open the gates so you can take off. Move fast, cause the Murkys will jump on us if they realize what's going on!
loc_mex_41_02 = "ไอ้พวก dwankies จะมาแล้ว ต้องออกมาจากที่นั่นให้ไวที่สุด",--More dwankies coming soon. You gotta get out of there!
loc_mex_49_01 = "ทางเข้าอุโมงค์น่าจะอยู่ข้างนอกสักที่",--The tunnel entrance should be outside somewhere.
loc_mex_44_03 = "รหัสผ่านผิด พวกมันรู้แล้วว่าเราอยู่ที่นี่",--The code was wrong, they know you're there now!
loc_mex_09_03 = "ระวังด้วย ห้องถูกวางกับดักไว้ จัดการกับมันก่อน",--Look out, the room is booby-trapped! Disarm or get out!
loc_mex_78_03 = "ดูเหมือนว่ามันกำลังทำงานอยู่ น่าจะใช้เวลาสักครู่ก่อนที่มันจะเต็ม",--Looks like it's working. Will take some time before it's full.
loc_mex_36_01 = "มันน่าจะไปต่อได้อยู่ตอนนี้",--That'll keep it going for now.
loc_mex_46_03 = "Locke คนเก่ารู้วิธีจัดการพวกนี้อยู่แล้ว",--Old Locke knows what to do with those suits.
loc_mex_85_03 = "สงสัยมาตลอดเลยว่า ทำไมตัวเองถึงต้องโชคร้ายเหมือนกับสิ่งมีชีวิตในป่าในเขาเลย มีบางอย่างต้องการที่จะลอบกัด Locke",--I've always wondered why I seem to have such bad luck near wildlife. There's always something trying to bite old Locke... And I do nothing but nice things for the little bastards.
loc_mex_11_01 = "",--When you find the code, get back to the keypad and give it a go.
loc_mex_67_03 = "",--Start searching for the Murkywater nest egg we're after. It's in the form of weapons.
loc_mex_52_01 = "",--Luckily, we were ready for this. Rust told me these Overkill dwankies keep loads of explosives around, so all you gotta do is find some.
loc_mex_46_02 = "",--Those suits will come in handy, later. 
loc_mex_17_03 = "",--You gotta get to Mexico. Hurry.
loc_mex_32_01 = "",--Right, now just let it fill up.
loc_mex_60_02 = "ดูเหมือนว่ามันจะมีทางเข้าใต้ดินอยู่ที่ไหนสักทีหนึ่ง",--Looks like there might be an underground vault somewhere.
loc_mex_13_02 = "",--Groot job with the code.
loc_mex_33_01 = "",--Ag man, the pump stopped. Maybe it needs more juice?
loc_mex_60_01 = "",--What's that? A blueprint?
loc_mex_52_03 = "",--You'll probably find explosives around there to use.
loc_mex_86_03 = "",--The key is not going to work any longer, you gotta use a drill, friends.
loc_mex_85_02 = "",--One time, I was in the jungle with a kak piece of laptop, trying to hack into this ancient security system being run by a bunch of dwankie terrorists. In a very unfortunate event, a snake bites my leg, and I mistakenly activate the alarm, alerting everyone, and making them blow up the entire place. Lots of terrorists died, and no one got paid that day. Blerrie snake...
loc_mex_40_02 = "",--Hurry, friends! Get into that plane.
loc_mex_24_03 = "",--The Murky's nest egg is cash money, so start looking. It could be anywhere around there.
loc_mex_68_03 = "",--Start searching for the Murkywater nest egg we're after. It's in the form of cocaine.
loc_mex_75_02 = "",--You let someone stop the pump. Get over there and start it up!
loc_mex_49_03 = "",--You'll probably find the tunnel if you look around outside.
loc_mex_76_02 = "",--The plane needs juice to fly.
loc_mex_57_02 = "",--You gotta protect it for a bit. Shouldn't take too long.
loc_mex_09_01 = "",--Bliksem, the place is rigged! Get out of there if you can't disarm it!
loc_mex_06_01 = "",--Maybe in there?
loc_mex_43_03 = "",--No need to sneak about any longer!
loc_mex_03_01 = "",--There you go, that's it.
loc_mex_12_03 = "",--Check the tables, walls, chairs... wherever.
loc_mex_11_02 = "",--Ok, get to searching for the answer to that code. 
loc_mex_73_03 = "",--Whoever locked that in there doesn't want it to fall into hands like ours, so why not bring it along?
loc_mex_73_02 = "",--That would look lekker in Duke's corner, for sure! Maybe you should take it!
loc_mex_08_02 = "",--Go inside and see if there's a clue to the code anywhere.
loc_mex_06_03 = "",--Might be a good place to look.
loc_mex_35_02 = "",--Look around the warehouses for a can of fuel.
loc_mex_35_03 = "",--There's gotta be juice around there somewhere.
loc_mex_83_03 = "",--More dwankies incoming. You gotta get out of there!
loc_mex_79_01 = "",--Refueling is done, so take that hose off. 
loc_mex_68_02 = "",--The Murky resources we're after will be in the form of drugs. They could be anywhere around there, so you're just going to have to start looking.
loc_mex_08_01 = "",--Now, get in there and see what you can find.
loc_mex_21_01 = "",--There's your ride. Once you've got all the loot secured, you gotta get it refueled. 
loc_mex_16_03 = "",--Time to go to Mexico, yeah?
loc_mex_55_03 = "",--The detonator needs to be rigged.
loc_mex_14_03 = "",--Blueprints... to a vault?
loc_mex_27_01 = "",--Looks like the vault in the blueprint you found.
loc_mex_25_02 = "",--That should be enough to kick the Murkys in the teeth.
loc_mex_27_03 = "",--Good thing you found that blueprint. That's the vault.
loc_mex_38_02 = "",--You need to open the runway gates. It's gonna be jol, and the Murkys will go crazy when we take off!
loc_mex_66_02 = "",--That's the plane we're looking for. Get the loot inside, then give it some fuel.
loc_mex_24_01 = "ได้เวลาหาของที่ Murky มีแล้วหละ และสิ่งที่เรากำลังตามหาคือ เงิน และมีเยอะมากด้วยหละ",--Time to start looking for that stash of Murky loot. We're looking for cash, and lots of it. 
loc_mex_22_02 = "",--The Murky resources we're after will be weapons. They could be anywhere so you'll just have to start looking.
loc_mex_04_03 = "",--That's typical. You should have a look in the clubhouse in case these dwankies have left a way to access the code somewhere. Start with the briefing room.
loc_mex_20_03 = "",--The plane, friends, the plane!
loc_mex_12_01 = "",--Find the code. Did you check the whole room?
loc_mex_26_03 = "",--Gotta wonder who has the resources to back the Dentist in all this. Is he the top of the food chain, or is there more to this braai?
loc_mex_45_02 = "",--Heads-up, friends. Murky agents on the way.
loc_mex_25_01 = "",--Groot, that's all we need. Murkywater and the Dentist will be in big trouble once this hits home.
loc_mex_82_03 = "",--Time to fly, friends. Get onboard that dinges, quickly!
loc_mex_84_01 = "",--I think Rust mentioned this room. Maybe there's something useful in there.
loc_mex_62_03 = "",--You gotta get to Mexico. Hurry.
loc_mex_77_02 = "",--Make sure you protect the pump while it's running!
loc_mex_34_03 = "",--See to the pump again, friends.
loc_mex_12_02 = "",--Did you search everywhere?
loc_mex_36_02 = "",--Ok, that's enough for now.
loc_mex_63_01 = "",--Nice night for a barbacao. Shame the Cartel dwankies know we're crashing it!
loc_mex_74_01 = "",--Time to juice up that plane. Get the fuel hose connected. 
loc_mex_30_02 = "",--You gotta get some fuel in that dinges. Get to work. 
loc_mex_09_02 = "",--Ach, it's rigged with C4! Look out, friends!
loc_mex_17_01 = "",--You gotta get into that tunnel, friends. 
loc_mex_19_03 = "",--The getaway plane is probably still in one of the hangars.
loc_mex_34_01 = "",--Ach, the pump again. Donnerse thing needs more gas.
loc_mex_36_03 = "",--Should stay running for a bit, now.
loc_mex_37_01 = "",--Refueling is done, so take that hose off. 
loc_mex_51_03 = "",--You can't use the keypad. Time to blow the door open!
loc_mex_53_03 = "",--Might be a good idea to look outside.
loc_mex_54_02 = "",--That looks right. Grab them and put them on the door.
loc_mex_56_01 = "",--What are you waiting for? Set that detonator!
loc_mex_61_01 = "",--OK, get into that tunnel. Time for a visit to Mexico.
loc_mex_62_02 = "",--Hurry up you chops, get into that tunnel.
loc_mex_71_01 = "",--Looks like the vault in the blueprint you found.
loc_mex_78_01 = "",--Right, now just let it fill up.
loc_mex_80_01 = "",--Now you gotta clear the runway by blowing the gates!
loc_mex_80_02 = "",--You need to blow the runway gates. It's gonna be jol!
loc_mex_81_01 = "",--Stick some explosives on the gate and we're good to go.
loc_mex_86_02 = "",--Ach, now you've got to drill through the door instead.
