loc_mex_cook_11_25 = "",--...I'm 72% sure.
loc_mex_cook_07_04 = "",--Ach no, that's not it!
loc_mex_cook_09_02 = "",--It should be caustic soda!
loc_mex_cook_05_01 = "",--Hydrogen... chloride. Ach, nasty!
loc_mex_cook_23_02 = "",--Power was cut. Please restore it, yeah?
loc_mex_cook_12_06 = "",--Oh dear, that wasn't the right ingredient after all.
loc_mex_cook_08_07 = "",--It should be acid.
loc_mex_cook_11_06 = "",--...I'm blerrie sure. Probably.
loc_mex_cook_10_05 = "",--No, it's chloride, hydrogen chloride.
loc_mex_cook_07_03 = "",--No, wait!
loc_mex_cook_11_03 = "",--...IF old Locke's calculations are correct.
loc_mex_cook_03_07 = "",--Acid. Muriatic acid.
loc_mex_cook_06_01 = "",--See any of that lying around?
loc_mex_cook_16_03 = "",--You can stay and make more or leave, but we have all we need!
loc_mex_cook_12_02 = "",--I should read up on these things, yeah?
loc_mex_cook_06_04 = "",--That should get things cooking.
loc_mex_cook_10_07 = "",--Hydrogen chloride is what you want!
loc_mex_cook_15_03 = "",--There might be more chemicals in the trucks.
loc_mex_cook_04_07 = "",--Probably caustic soda.
loc_mex_cook_17_03 = "",--That's another one.
loc_mex_cook_11_19 = "",--...it's a toss-up, really.
loc_mex_cook_05_07 = "",--Chloride. Hydrogen chloride.
loc_mex_cook_11_12 = "",--...this isn't what old Locke does best, really.
loc_mex_cook_05_06 = "",--How about hydrogen chloride.
loc_mex_cook_10_06 = "",--It should be hydrogen chloride instead.
loc_mex_cook_14_06 = "",--Move that out of the way to a good place, then get back to it, friends.
loc_mex_cook_12_12 = "",--Pretty loud, yeah?
loc_mex_cook_10_03 = "",--Use hydrogen chloride!
loc_mex_cook_01_01 = "",--OK, friends. Let's get some cooking started. Old Locke isn't the best cook in the world, so maybe, don't sample the goods, yeah?
loc_mex_cook_02_07 = "",--Okay, now comes...
loc_mex_cook_13_01 = "",--Thats one batch done.
loc_mex_cook_04_10 = "",--Soda. Caustic soda. I don't think you're supposed to drink it.
loc_mex_cook_11_22 = "",--...I'm 86% sure.
loc_mex_cook_06_07 = "",--Go for it, you chops.
loc_mex_cook_08_06 = "",--It's muriatic acid.
loc_mex_cook_02_05 = "",--Now you're going to need...
loc_mex_cook_12_20 = "",--This stuff makes great bombs...
loc_mex_cook_09_06 = "",--It's caustic soda.
loc_mex_cook_07_05 = "",--Wait a second...
loc_mex_cook_11_20 = "",--...I'm 93% sure.
loc_mex_cook_11_05 = "",--...unless I've missed something...
loc_mex_cook_04_01 = "",--Caustic soda. Yes, that's it.
loc_mex_cook_01_02 = "",--You chops ready for a cookout? Used to throw a good braai in my Cape Town days, but this is a bit different!
loc_mex_cook_11_27 = "",--...I'm 65.5% sure.
loc_mex_cook_12_01 = "",--Sorry, friends.
loc_mex_cook_23_03 = "",--The power is down. You need to restore it.
loc_mex_cook_11_24 = "",--...I'm 79% sure.
loc_mex_cook_15_01 = "",--Check the trucks for ingredients we can use.
loc_mex_cook_11_21 = "",--...I'm 91% sure.
loc_mex_cook_05_03 = "",--...hydrogen chloride?
loc_mex_cook_14_01 = "",--Hide the meth nearby and then let's cook another round.
loc_mex_cook_12_09 = "",--OK, that one is on me.
loc_mex_cook_04_09 = "",--Soda. Caustic soda.
loc_mex_cook_10_01 = "",--It's supposed to be hydrogen chloride!
loc_mex_cook_17_04 = "",--More corruption for the dwankies!
loc_mex_cook_02_10 = "",--Hope old Locke gets this right...
loc_mex_cook_09_03 = "",--We should have used caustic soda!
loc_mex_cook_08_02 = "",--A katspoegie of muriatic acid!
loc_mex_cook_09_07 = "",--Should have been soda.
loc_mex_cook_06_08 = "",--Add it, chop chop.
loc_mex_cook_10_02 = "",--It should be hydrogen chloride!
loc_mex_cook_12_10 = "",--You should always trust Locke, except when you shouldn't.
loc_mex_cook_12_05 = "",--Kakspul of trouble!
loc_mex_cook_04_08 = "",--Let's go with caustic soda. What could go wrong?
loc_mex_cook_12_19 = "",--I had a feeling that was the wrong ingredient...
loc_mex_cook_11_28 = "",--...I'm 57% sure.
loc_mex_cook_08_01 = "",--It's supposed to be muriatic acid!
loc_mex_cook_22_01 = "",--Now let's see what happens!
loc_mex_cook_03_01 = "",--Muriatic acid.
loc_mex_cook_11_08 = "",--...that's my best guess.
loc_mex_cook_22_02 = "",--If you did it right, it will now cook!
loc_mex_cook_14_05 = "",--That batch needs to go somewhere safe, chop chop. Then you can have another go.
loc_mex_cook_12_18 = "",--My gut feeling told me that wasn't the right ingredient... should have listened!
loc_mex_cook_19_01 = "",--OK, let's have a look...
loc_mex_cook_11_10 = "",--...it has gotta be.
loc_mex_cook_14_04 = "",--Once you get that stowed, you can get another one going.
loc_mex_cook_12_04 = "",--Ach! No, that wasn't right...
loc_mex_cook_04_11 = "",--Soda. Caustic soda.I wouldn't mix a gin and tonic with it, though.
loc_mex_cook_06_10 = "",--Pour it in, come on.
loc_mex_cook_12_14 = "",--Death... by meth... sorry, friends. Not funny.
loc_mex_cook_17_05 = "",--And another...
loc_mex_cook_06_02 = "",--Find some, and pour it in, yeah?
loc_mex_cook_10_04 = "",--We need hydrogen chloride!
loc_mex_cook_02_08 = "",--Now you should go with...
loc_mex_cook_08_05 = "",--Yes... it's acid, muriatic acid.
loc_mex_cook_08_08 = "",--It has got to be muriatic acid.
loc_mex_cook_09_01 = "",--It's supposed to be caustic soda, friends!
loc_mex_cook_11_01 = "",--...I reckon.
loc_mex_cook_11_17 = "",--...and cross your fingers.
loc_mex_cook_11_26 = "",--...I'm 68% sure.
loc_mex_cook_12_13 = "",--Did you hear that loud noise? Friends?
loc_mex_cook_11_02 = "",--...I... think.
loc_mex_cook_12_21 = "",--Maybe I'm confusing these things... 
loc_mex_cook_03_05 = "",--I'm going to assume muriatic acid.
loc_mex_cook_04_05 = "",--It's caustic soda, yeah?
loc_mex_cook_18_03 = "",--Have a proper look around, don't miss out on any ingredients.
loc_mex_cook_05_02 = "",--...hydrogen chloride?
loc_mex_cook_01_03 = "",--Time for a nice, old fashioned cookout, for sure!
loc_mex_cook_10_08 = "",--Hydrogen chloride has to be right.
loc_mex_cook_14_02 = "",--Put that batch away so we can make some more.
loc_mex_cook_07_08 = "",--Wait!
loc_mex_cook_06_06 = "",--That should get it on.
loc_mex_cook_03_02 = "",--Perhaps... muriatic acid?
loc_mex_cook_06_05 = "",--That should get the process going.
loc_mex_cook_12_07 = "",--That's what you get for trusting the internet, I suppose.
loc_mex_cook_02_04 = "",--So, next step is...
loc_mex_cook_07_10 = "",--Blerrie!
loc_mex_cook_11_23 = "",--...I'm 84% sure.
loc_mex_cook_12_17 = "",--Ag man, that wasn't very nice!
loc_mex_cook_06_09 = "",--Fok voort, add some!
loc_mex_cook_08_03 = "",--That should have been muriatic acid!
loc_mex_cook_08_04 = "",--We need muriatic acid!
loc_mex_cook_17_01 = "",--Another batch done!
loc_mex_cook_11_04 = "",--...I think so, at least.
loc_mex_cook_02_09 = "",--Blerrie, if I read this correctly... eh...
loc_mex_cook_02_02 = "",--Hold on...
loc_mex_cook_12_03 = "",--I suppose that wasn't it.
loc_mex_cook_11_07 = "",--...for sure. Or, most likely.
loc_mex_cook_07_07 = "",--Sorry friends, that wasn't right.
loc_mex_cook_15_02 = "",--Have a look in the trucks for materials.
loc_mex_cook_12_11 = "",--No... that wasn't right, was it?
loc_mex_cook_11_09 = "",--...that's my very best guess.
loc_mex_cook_17_06 = "",--How many are you gonna cook?
loc_mex_cook_07_02 = "",--Hold up!
loc_mex_cook_11_18 = "",--...and hope it works.
loc_mex_cook_11_16 = "",--...OK... OK.
loc_mex_cook_04_06 = "",--I'm betting on caustic soda.
loc_mex_cook_05_04 = "",--It's hydrogen chloride.
loc_mex_cook_11_15 = "",--...bekaken internet descriptions are not too clear.
loc_mex_cook_09_08 = "",--My superior intellect tells me it has to be caustic soda.
loc_mex_cook_02_06 = "",--Alright, the next ingredient is...
loc_mex_cook_03_06 = "",--We'll go with muriatic acid.
loc_mex_cook_16_01 = "",--OK, that's enough. You can keep cooking or get out of there.
loc_mex_cook_16_02 = "",--Groot, friends. We got what we need. Make more if you want or leave!
loc_mex_cook_22_03 = "",--There you go, it will start now!
loc_mex_cook_06_03 = "",--You got some of that somewhere?
loc_mex_cook_11_13 = "",--...hope this website is accurate.
loc_mex_cook_12_15 = "",--Heh. I suppose you learn something new every day.
loc_mex_cook_09_04 = "",--You need caustic soda, yeah?
loc_mex_cook_02_03 = "",--Okay, what's next...
loc_mex_cook_07_06 = "",--Wait a blerrie minute!
loc_mex_cook_09_05 = "",--It's soda, caustic soda.
loc_mex_cook_14_03 = "",--Get that to a safe place and we can start up another braai.
loc_mex_cook_07_09 = "",--Stop! You didn't put it in yet, did you?
loc_mex_cook_07_01 = "",--Wait, cancel that...
loc_mex_cook_04_02 = "",--...caustic soda?
loc_mex_cook_22_04 = "",--Good, now watch it cook!
loc_mex_cook_04_03 = "",--...caustic soda, friends?
loc_mex_cook_04_04 = "",--...caustic soda?
loc_mex_cook_11_11 = "",--...this is not my area of expertise.
loc_mex_cook_03_04 = "",--It's muriatic acid.
loc_mex_cook_18_01 = "",--There should be some more ingredients locked up somewhere.
loc_mex_cook_03_03 = "",--...muriatic acid?
loc_mex_cook_05_05 = "",--Let's try a katspoegie of hydrogen chloride.
loc_mex_cook_11_14 = "",--...what's the worst that could happen, eh?
loc_mex_cook_12_08 = "",--Blerrie! What are the odds?
loc_mex_cook_12_16 = "",--Ach, what a kraaines we made!
loc_mex_cook_13_02 = "",--The batch is done, friends.
loc_mex_cook_13_03 = "",--First serving is ready!
loc_mex_cook_17_02 = "",--Nice friends. More crystal gold!
loc_mex_cook_18_02 = "",--Check every cranny, there is supposed to be a lot of ingredients there.
loc_mex_cook_23_01 = "",--Lost power friends, you need to get it back on.
