menu_st_spec_9 = "",--Sociopath
menu_st_spec_9_desc = "Sociopath[社会病質者]は犯罪にとても向いていることが知られているが、同時にとても扱いにくい存在でもある。大きな組織が嫌うのはそのためだ。$NL;$NL;大胆で強靭かつ頑固な意志を持つSociopathは、暴力的な仕事に優れている。罪の意識を決して感じない彼はとても危険な敵である。",--The Sociopath is known to be one of the most effective type of criminals. Where he is effective, he is also difficult to deal with, which is why larger organizations avoid him.$NL;$NL;Bold, disinhibitted and mean, the Sociopath excels in the most violent of jobs. Unable to feel guilt for the crimes he commits, he is a dangerous enemy.
menu_deck9_1 = "",--No Talk
menu_deck9_1_desc = "敵が近くにいると被ダメージが ##$multiperk;## 減少する。",--When you are close to an enemy, you receive ##$multiperk;## less damage from enemies.
menu_deck9_2 = "",--Helmet Popping
menu_deck9_2_desc = "ヘッドショットダメージが ##$multiperk;## 増加する。",--Increases your headshot damage by ##$multiperk;##.
menu_deck9_3 = "",--Tension
menu_deck9_3_desc = "敵を倒すとアーマーが ##$multiperk;## 回復する。$NL;$NL;クールダウンは ##$multiperk2;## 秒。",--Killing an enemy regenerates ##$multiperk;## armor.$NL;$NL;This cannot occur more than once every ##$multiperk2;## seconds.
menu_deck9_4 = "",--Blending In
menu_deck9_4_desc = "隠密性が ##$multiperk;## 増加する。$NL;$NL;アーマーの移動速度低下が ##$multiperk2;## 減少する。$NL;$NL;取得経験値が ##$multiperk3;## 増加する。",--You gain ##$multiperk;## increased concealment.$NL;$NL;When wearing armor, your movement speed is ##$multiperk2;## less affected.$NL;$NL;You gain ##$multiperk3;## more experience when you complete days and jobs.
menu_deck9_5 = "",--Clean Hit
menu_deck9_5_desc = "敵を倒すと体力が ##$multiperk;## 回復する。$NL;$NL;クールダウンは ##$multiperk2;## 秒。",--Killing an enemy with a melee weapon regenerates ##$multiperk;## health.$NL;$NL;This cannot occur more than once every ##$multiperk2;## seconds.
menu_deck9_6 = "",--Walk-in Closet
menu_deck9_6_desc = "Heist中にアーマーを着用できるArmor Bagが使用できるようになる。$NL;$NL;拾える弾薬が ##$multiperk;## 増加する。",--Unlocks an armor bag equipment for you to use. The armor bag can be used to change your armor during a heist.$NL;$NL;Increases your ammo pickup to ##$multiperk;## of the normal rate.
menu_deck9_7 = "",--Overdose
menu_deck9_7_desc = "中距離以内の敵を倒すとアーマーが ##$multiperk;## 回復する。$NL;$NL;クールダウンは ##$multiperk2;## 秒。",--Killing an enemy at medium range regenerates ##$multiperk;## armor.$NL;$NL;This cannot occur more than once every ##$multiperk2;## seconds.
menu_deck9_8 = "",--Fast and Furious
menu_deck9_8_desc = "ダメージが ##$multiperk;## 増加する。ただし、近接ダメージには適用されない。$NL;$NL;Doctor Bagの使用が ##$multiperk2;## 速くなる。",--You do ##$multiperk;## more damage. Does not apply to melee damage.$NL;$NL;Increases your doctor bag interaction speed by ##$multiperk2;##.
menu_deck9_9 = "",--Showdown
menu_deck9_9_desc = "近くで敵を倒すと ##$multiperk;## の確率で周囲の敵が短時間パニックを起こし立ち止まる。$NL;$NL;クールダウンは ##$multiperk2;## 秒。",--Killing an enemy at close range has a ##$multiperk;## chance to spread panic among your enemies.$NL;$NL;Panic will make enemies go into short bursts of uncontrollable fear.$NL;$NL;This cannot occur more than once every ##$multiperk2;## seconds.
menu_st_spec_10 = "",--Gambler
menu_st_spec_10_desc = "銃弾の飛び交う戦場に向かうために必要なのは、スキルとタフさに、なにより運だ。 持っている人というのはいるものだ。$NL;$NL;運というのは定義しにくい特性で、古代ギリシャ人はそれを神々の定めるものとした。それは間違いだ。運は確かに存在し、そして勝ち取るものだ。そのためには、入念な計画と準備をして状況を操り、利益の期待値を最大化しなければならない。 フォルトゥナの祝福を祈る暇があったら、カウンティングをすることだ。$NL;$NL;Gamblerは支援のためのパークデッキだ。チームを勝たせるだけなら誰でもできるが、大勝ちしたいならGamblerが必要になる。",--Heading into the furnace of battle requires skill, hardness and more than a little luck. Some people just have it.$NL;$NL;Luck is an elusive quality. The ancient Greeks believed it was the design of the Gods. It isn't. It certainly exists, but it's something you can earn. It requires preparation and forethought to get your pieces in place, and maximize your chances of a return. It's counting cards, rather than the blessing of Fortuna.$NL;$NL;The Gambler perk deck is a support deck. Anyone can help the team win, but it takes the Gambler to help the team win big.
menu_deck10_1 = "",--Medical Supplies
menu_deck10_1_desc = "弾薬箱を拾うと体力が ##$multiperk;## ～ ##$multiperk2;## 回復する。$NL;$NL;クールダウンは ##$multiperk3;## 秒。",--Ammo packs you pick up also yield medical supplies and heals you for ##$multiperk;## to ##$multiperk2;## health.$NL;$NL;Cannot occur more than once every ##$multiperk3;## seconds.
menu_deck10_2 = "",--Helmet Popping
menu_deck10_2_desc = "ヘッドショットダメージが ##$multiperk;## 増加する。",--Increases your headshot damage by ##$multiperk;##.
menu_deck10_3 = "",--Ammo Give Out
menu_deck10_3_desc = "弾薬箱を拾うと、仲間にも通常回収率の ##$multiperk;## の弾薬が補給される。$NL;$NL;クールダウンは ##$multiperk2;## 秒。",--When you pick up ammo, you trigger an ammo pickup for ##$multiperk;## of normal pickup to other players in your team.$NL;$NL;Cannot occur more than once every ##$multiperk2;## seconds.
menu_deck10_4 = "",--Blending In
menu_deck10_4_desc = "隠密性が ##$multiperk;## 増加する。$NL;$NL;アーマーの移動速度低下が ##$multiperk2;## 減少する。$NL;$NL;取得経験値が ##$multiperk3;## 増加する。",--You gain ##$multiperk;## increased concealment.$NL;$NL;When wearing armor, your movement speed is ##$multiperk2;## less affected.$NL;$NL;You gain ##$multiperk3;## more experience when you complete days and jobs.
menu_deck10_5 = "",--Sharing Is Caring
menu_deck10_5_desc = "弾薬箱を拾って体力が回復した場合、回復量の ##$multiperk;## 分だけ仲間の体力が回復する。",--When you get healed from picking up ammo packs, your teammates also get healed for ##$multiperk;## of the amount.
menu_deck10_6 = "",--Walk-in Closet
menu_deck10_6_desc = "Heist中にアーマーを着用できるArmor Bagが使用できるようになる。$NL;$NL;拾える弾薬が ##$multiperk;## 増加する。",--Unlocks an armor bag equipment for you to use. The armor bag can be used to change your armor during a heist.$NL;$NL;Increases your ammo pickup to ##$multiperk;## of the normal rate.
menu_deck10_7 = "",--More Healing 1
menu_deck10_7_desc = "弾薬箱で回復できる体力がさらに ##$multiperk;## 増加する。",--Increase health gained from ammo packs by additional ##$multiperk;##.
menu_deck10_8 = "",--Fast and Furious
menu_deck10_8_desc = "ダメージが ##$multiperk;## 増加する。ただし、近接ダメージには適用されない。$NL;$NL;Doctor Bagの使用が ##$multiperk2;## 速くなる。",--You do ##$multiperk;## more damage. Does not apply to melee damage.$NL;$NL;Increases your doctor bag interaction speed by ##$multiperk2;##.
menu_deck10_9 = "",--More Healing 2
menu_deck10_9_desc = "弾薬箱で回復できる体力がさらに ##$multiperk;## 増加する。$NL;$NL;コンプリートデッキ ボーナス: Infamousアイテムの出現率が ##$multiperk2;## 増加する。",--Increase health gained from ammo packs by additional ##$multiperk;##.$NL;$NL;Deck Completion Bonus: Your chance of getting a higher quality item during a PAYDAY is increased by ##$multiperk2;##.
menu_st_spec_11 = "",--Grinder
menu_st_spec_11_desc = "典型的なGrinderは個人で困難な状況をコントロールし、場を好転させる働き者だ。Grinderは何時でも前線で生存し、相手をたっぷりと痛めつけます。また、ダメージに屈せず、敵を倒しあたりまえのように生還します。",--A typical grinder is a hard working individual, able take control of difficult situations and turn them around. The grinder relies heavily on always being in the front and dishing out punishment, being able to survive due to the fact that he does damage to enemies regardless of how much damage he has sustained.
menu_deck11_1 = "",--Histamine
menu_deck11_1_desc = "敵へのダメージで体力を##$multiperk;## ポイント回復し、これは ##$multiperk2;##秒ごとに発動され 、 ##$multiperk3;## 秒間持続する。.$NL;$NL;この効果は重複するが、##$multiperk4;## 秒ごとに一度しか発動出来ない。このパークはTwo-piece SuitもしくはLightweight Ballistic Vest装備中しか発動されない。",--Damaging an enemy heals ##$multiperk;## life points every ##$multiperk2;## seconds for ##$multiperk3;## seconds.$NL;$NL;This effect stacks but cannot occur more than once every ##$multiperk4;## seconds and only while wearing the Two-piece Suit or Lightweight Ballistic Vest.
menu_deck11_2 = "",--Helmet Popping
menu_deck11_2_desc = "ヘッドショットダメージが ##$multiperk;## 増加する。",--Increases your headshot damage by ##$multiperk;##.
menu_deck11_3 = "",--Adrenaline
menu_deck11_3_desc = "敵へのダメージで ##$multiperk;## ポイント回復するようになり、 ##$multiperk2;## 秒ごとに発動され、 ##$multiperk3;## 秒間持続する.$NL;$NL;また、体力が ##$multiperk4;## 上昇する。.",--Damaging an enemy now heals ##$multiperk;## life points every ##$multiperk2;## seconds for ##$multiperk3;## seconds.$NL;$NL;You gain ##$multiperk4;## more health.
menu_deck11_4 = "",--Blending In
menu_deck11_4_desc = "Concealmentが ##$multiperk;## 上昇する。$NL;$NL;アーマーの移動速度低下が ##$multiperk2;## 減少する。$NL;$NL;取得経験値が ##$multiperk3;## 増加する。",--You gain ##$multiperk;## increased concealment.$NL;$NL;When wearing armor, your movement speed is ##$multiperk2;## less affected.$NL;$NL;You gain ##$multiperk3;## more experience when you complete days and jobs.
menu_deck11_5 = "",--Endorphins
menu_deck11_5_desc = "敵へのダメージで ##$multiperk;## ポイント回復するようになり、 ##$multiperk2;## 秒ごとに発動され、 ##$multiperk3;## 秒間持続する.$NL;$NL;また、弾が敵のアーマーを貫通する確率を ##$multiperk4;## 上昇させる。.",--Damaging an enemy now heals ##$multiperk;## life points every ##$multiperk2;## seconds for ##$multiperk3;## seconds.$NL;$NL;Increases you chance to pierce enemy armor by ##$multiperk4;##.
menu_deck11_6 = "",--Walk-in Closet
menu_deck11_6_desc = "Heist中にアーマーを着用できるArmor Bagが使用できるようになる。$NL;$NL;拾える弾薬が ##$multiperk;## 増加する。",--Unlocks an armor bag equipment for you to use. The armor bag can be used to change your armor during a heist.$NL;$NL;Increases your ammo pickup to ##$multiperk;## of the normal rate.
menu_deck11_7 = "",--Dopamine
menu_deck11_7_desc = "敵へのダメージで ##$multiperk;## ポイント回復するようになり、 ##$multiperk2;## 秒ごとに発動され、 ##$multiperk3;## 秒間持続する.$NL;$NL;また、体力が ##$multiperk4;## 上昇する。.",--Damaging an enemy now heals ##$multiperk;## life points every ##$multiperk2;## seconds for ##$multiperk3;## seconds.$NL;$NL;You gain ##$multiperk4;## more health.
menu_deck11_8 = "",--Fast and Furious
menu_deck11_8_desc = "ダメージが ##$multiperk;## 増加する。ただし、近接ダメージには適用されない。$NL;$NL;Doctor Bagの使用が ##$multiperk2;## 速くなる。",--You do ##$multiperk;## more damage. Does not apply to melee damage.$NL;$NL;Increases your doctor bag interaction speed by ##$multiperk2;##.
menu_deck11_9 = "",--Euphoria
menu_deck11_9_desc = "敵へのダメージで ##$multiperk;## ポイント回復するようになり、 ##$multiperk2;## 秒ごとに発動され、 ##$multiperk3;## 秒間持続する.$NL;$NL;また、弾が敵のアーマーを貫通する確率を ##$multiperk4;## 上昇させる。$NL;$NL;コンプリートデッキ ボーナス: Infamousアイテムの出現率が ##$multiperk5;## 増加する。",--Damaging an enemy now heals ##$multiperk;## life points every ##$multiperk2;## seconds for ##$multiperk3;## seconds.$NL;$NL;Increase you chance to pierce enemy armor by ##$multiperk4;##.$NL;$NL;Deck Completion Bonus: Your chance of getting a higher quality item during a PAYDAY is increased by ##$multiperk5;##.
menu_st_spec_12 = "",--Yakuza
menu_st_spec_12_desc = "Yakuzaは世界で最も恐れられてる犯罪組織の1つだ。任侠と親分に従う、厳しい行動規範で知られており、彼らの体全体は組織的性質とタトゥーで覆われている。$NL;$NL;社会から追放され、落伍したYakuzaは自活する方法を知っている。$NL;情けを見せたとしても、軽々しく見られるべきではない。",--The Yakuza are one of the most feared crime syndicates in the world. Ruled by the ninkyo and lead by the Oyabun, the Yakuza are known for their strict code of conduct, organized nature and the tattoos that cover their entire bodies.$NL;$NL;An outcast and a dropout from society, the Yakuza knows how it is to fend for himself. While he appears gentle, he is not to be taken lightly.
menu_deck12_1 = "",--Koi Irezumi
menu_deck12_1_desc = "体力が低いほど、アーマーの回復開始までの時間がより早くなる。体力が ##$multiperk;## 以下の時、最大で ##$multiperk2;## まで早くなる。$NL;$NL;注釈: この効果が発動すると、体力の自動回復効果は無効化される。",--The lower your health, the more armor recovery rate you have. When your health is below ##$multiperk;##, you will gain up to ##$multiperk2;## armor recovery rate.$NL;$NL;NOTE: Entering this state negates regeneration effects.
menu_deck12_3 = "",--Hebi Irezumi
menu_deck12_3_desc = "体力が低いほど、移動速度が上昇する。体力が体力が ##$multiperk;## 以下の時、最大で ##$multiperk2;## まで上昇する。",--The lower your health, the more movement speed you gain. When your health is below ##$multiperk;##, you will gain up to ##$multiperk2;## movement speed.
menu_deck12_5 = "",--Tora Irezumi
menu_deck12_5_desc = "体力が低いほど、アーマーの回復開始までの時間がより早くなる。体力が ##$multiperk;## 以下の時、最大で ##$multiperk2;## さらに早くなる。",--The lower your health, the more armor recovery rate you have. When your health is below ##$multiperk;##, you will gain up to an additional ##$multiperk2;## armor recovery rate.
menu_deck12_7 = "",--Ryu Irezumi
menu_deck12_7_desc = "体力が低いほど、アーマーの回復開始までの時間がより早くなる。体力が ##$multiperk;## 以下の時、最大で ##$multiperk2;## さらに早くなる。",--The lower your health, the more armor recovery rate you have. When your health is below ##$multiperk;##, you will gain up to an additional ##$multiperk2;## armor recovery rate.
menu_deck12_9 = "",--Oni Irezumi
menu_deck12_9_desc = "このデッキ内全ての体力減少に伴う効果が ##$multiperk2;## の代わりに ##$multiperk;## から発動するようになる。$NL;$NL;コンプリートデッキ ボーナス: Infamousアイテムの出現率が ##$multiperk3;## 増加する。",--All berserker state effects in this perk deck will start at ##$multiperk;## health instead of ##$multiperk2;##.$NL;$NL;Deck Completion Bonus: Your chance of getting a higher quality item during a PAYDAY is increased by ##$multiperk3;##.
