menu_st_spec_6 = "",--Crook
menu_st_spec_6_desc = "The Crook is a versatile criminal. The term is as old as crime itself.$NL;$NL;Truly, the crook is a jack of all trades and a master of none. He steals, lies, cheats and does any and every dishonest or illegal work necessary to get by.",--The Crook is a versatile criminal. The term is as old as crime itself.$NL;$NL;Truly, the crook is a jack of all trades and a master of none. He steals, lies, cheats and does any and every dishonest or illegal work necessary to get by.
menu_deck6_1 = "",--Subtle
menu_deck6_1_desc = "เพิ่มโอกาสในการหลบหลีกขึ้นอีก  ##$multiperk;##",--Your chance to dodge is increased by ##$multiperk;##.
menu_deck6_3 = "",--Basic Composure
menu_deck6_3_desc = "เพิ่มโอกาสในการหลบหลีกขึ้นอีก ##$multiperk;## เมื่อสวมใส่เกราะ Ballistic vest$NL;$NL;เพิ่มเกราะอีก  ##$multiperk2;## เมื่อสวมใส่เกราะ Ballistic vest",--Your chance to dodge is increased by ##$multiperk;## for ballistic vests.$NL;$NL;Your armor is increased by ##$multiperk2;## for ballistic vests.
menu_deck6_5 = "",--Advanced Composure
menu_deck6_5_desc = "เพิ่มโอกาสในการหลบหลีกขึ้นอีก ##$multiperk;## เมื่อสวมใส่เกราะ Ballistic vest",--Your chance to dodge is increased by ##$multiperk;## for ballistic vests.
menu_deck6_7 = "",--Expert Composure
menu_deck6_7_desc = "เพิ่มโอกาสในการหลบหลีกขึ้นอีก  ##$multiperk;## เมื่อสวมใส่เกราะ Ballistic vest$NL;$NL;เพิ่มเกราะอีก  ##$multiperk2;## เมื่อสวมใส่เกราะ Ballistic vest",--Your chance to dodge is increased by ##$multiperk;## for ballistic vests.$NL;$NL;Your armor is increased by ##$multiperk2;## for ballistic vests.
menu_deck6_9 = "",--Master Recovery
menu_deck6_9_desc = "อัตราการฟื้นฟูเกราะเพิ่มขึ้นอีก ##$multiperk;##.$NL;$NL;โบนัสเมื่ออัพความสามารถพิเศษนี้ตัน: โอกาสที่จะได้รับไอเท็มระดับสูงในการเปิดการ์ด PAYDAY เพิ่มขึ้นอีก ##$multiperk2;##.",--Your armor recovery rate is increased by ##$multiperk;##.$NL;$NL;Deck Completion Bonus: Your chance of getting a higher quality item during a PAYDAY is increased by ##$multiperk2;##.