menu_specialization = "",--Perk Decks
menu_st_active_spec = "ใช้งาน: $specialization;",--Equipped: $specialization;
menu_st_available_spec_points = "$points; พอยท์ที่เหลืออยู่ทั้งหมด",--$points; Perk points available
menu_st_activate_spec = "ใช้งานความสามารถ",--Equip Deck
menu_st_add_spec_points = "เพิ่มแต้ม",--Add points
menu_st_remove_spec_points = "ลบแต้ม",--Remove points
menu_st_progress = "ความคืบหน้า: $progress;",--Progress: $progress;
menu_st_spec_xp_conversion = "อัตราการแปลง: $rate;",--Conversion Rate: $rate;
menu_st_spec_xp_gained = "ค่าประสบการณ์ที่ได้รับ:",--XP gained since last conversion:
menu_st_spec_xp_perk_gained = "ค่าพอยท์ที่ได้รับ:",--Converted perk points gained:
menu_st_spec_xp_perk_total = "ค่าพอยท์ทั้งหมด:",--Total available perk points:
menu_st_spec_xp_progress = "ความคืบหน้า",--Progress
