--Framing Frame / Art Gallery
--Heist Info
heist_gallery_crimenet = "เบนต้องการให้เรากลับไปยังหอศิลป์.$NL;$NL;» ตรวจสอบสถานที่อย่างระมัดระวัง.$NL;» ตรวจสอบยามและกล้องวงจรปิด.$NL;» ขโมยรูปภาพที่ถูกประกาศขายและหลบหนี",--Bain wants you to head back to the Art Gallery.$NL;$NL;» Case the place carefully.$NL;» Check for guards and cameras$NL;» Bag the marked out paintings and get to the escape van

--Objective
hud_e_framing_frame_stage1_mission1_hl = "เข้าไปในหอศิลป์",--Enter the gallery
hud_e_framing_frame_stage1_mission1 = "หาทางเข้าไปในหอศิลป์",--Find a way to get inside the gallery
hud_e_framing_frame_stage1_mission2_hl = "ขโมยรูปที่มีสัญลักษณ์",--Steal the marked paintings
hud_e_framing_frame_stage1_mission2 = "มองหาภาพวาดที่มีสติกเกอร์สีแดงติดอยู่",--Look for paintings that have the red "sold" sticker on them
hud_e_framing_frame_stage1_mission3_hl = "เอาภาพวาดใส่รถตู้",--Take the paintings to the van
hud_e_framing_frame_stage1_mission3 = "เอาภาพวาดโยนใส่ใส่รถตู้",--Carry the paintings and throw them into the van
hud_e_framing_frame_stage1_mission4_hl = "ปิดระบบป้องกัน",--Disable the barriers
hud_e_framing_frame_stage1_mission4 = "เข้าไปในห้องรักษาความปลอดภัยและแฮกระบบรักษาความปลอดภัย",--To reach the paintings, access the security room and hack the security system
hud_e_framing_frame_stage1_mission5_hl = "หนี!",--Escape is available!
hud_e_framing_frame_stage1_mission5 = "ขึ้นยานพาหนะเพื่อหลบหนี",--Get to the escape vehicle
hud_e_framing_frame_stage2_mission1_hl = "รับสายโทรศัพท์",--Answer the phone
hud_e_framing_frame_stage2_mission1 = "รับสายโทรศัพท์เพื่อทำการแลกเปลี่ยน",--Answer the phone to make the trade
hud_e_framing_frame_stage2_mission2_hl = "วางภาพวาด",--Place the paintings
hud_e_framing_frame_stage2_mission2 = "วางภาพวาดไว้บนโต๊ะ",--Place the paintings on the table
hud_e_framing_frame_stage2_mission3_hl = "เข้าไปในโบกี้รถไฟ",--Get into the train cart
hud_e_framing_frame_stage2_mission3 = "เพื่อดำเนินต่อการแลกเปลี่ยนให้แน่ใจว่าทุกคนที่อยู่ในรถเข็นโบกี้รถไฟ",--To continue the trade, make sure everyone is in the train cart
hud_e_framing_frame_stage2_mission4_hl = "แลกเปลี่ยน",--Do the trade
hud_e_framing_frame_stage2_mission4 = "โยนกระเป๋าเพื่อแลกเปลี่ยน",--Throw the bags to do the trade
hud_e_framing_frame_stage2_mission5_hl = "ซุ่มโจมตี!",--Ambushed
hud_e_framing_frame_stage2_mission5 = "เกิดการซุ่มโจมตี หาหลบหนี",--It's an ambush! Make for the escape
hud_e_framing_frame_stage2_mission6_hl = "หลบหนี",--Escape is available
hud_e_framing_frame_stage2_mission6 = "ขึ้นยานพาหนะเพื่อหลบหนี",--Get to the escape vehicle
hud_e_framing_frame_stage3_mission1_hl = "เข้าไปในอพาร์ทเม้นท์",--Get into the apartment
hud_e_framing_frame_stage3_mission1 = "เข้าไปในอพาร์ทเม้นท์",--Get into the Democrat's apartment
hud_e_framing_frame_stage3_mission2_hl = "ขโมยอุปกรณ์",--Steal the items
hud_e_framing_frame_stage3_mission2 = "หา แลปท็อป, แท็บแลต, ฮาร์ดไดรฟ์, โทรศัพท์",--Find the laptop, harddrive, USB stick, tablet and the phone
hud_e_framing_frame_stage3_mission3_hl = "ติดตั้งอุปกรณ์ทุกอย่างบนดาดฟ้า",--Set-up everything at the roof
hud_e_framing_frame_stage3_mission3 = "ติดตั้งอุปกรณ์ทุกอย่างบนดาดฟ้า",--Set-up all the devices at your station on the roof
hud_e_framing_frame_stage3_mission4_hl = "แฮกคอมพิวเตอร์",--Access the computer
hud_e_framing_frame_stage3_mission4 = "เข้าไปในออฟฟิศ และแฮกคอมพิวเตอร์ของเขา",--Get into the democrat's office and access his stationary computer
hud_e_framing_frame_stage3_mission5_hl = "หาตู้นิรภัยที่ซ่อนอยู่",--Find the hidden vault
hud_e_framing_frame_stage3_mission5 = "หาตู้นิรภัยและเข้าไป",--Locate and get into the hidden vault
hud_e_framing_frame_stage3_mission6_hl = "วางโคเคนข้างหน้าตู้นิรภัย",--Plant the coke infront of the vault door
hud_e_framing_frame_stage3_mission6 = "เอากระเป๋าพร้อมโคเคนจากดาดฟ้าไปวางหน้าตู้นิรภัย",--Carry the bags with coke from the roof and place it infront of the vault door
hud_e_framing_frame_stage3_mission7_hl = "เปิดตู้นิรภัย",--Open the vault door
hud_e_framing_frame_stage3_mission7 = "แฮกคอมพิวเตอร์เพื่อเปิดตู้นิรภัย",--Use the stationary computer and open the vault door
hud_e_framing_frame_stage3_mission8_hl = "ขโมยทอง",--Get the gold
hud_e_framing_frame_stage3_mission8 = "ระวังเลเซอร์และขโมยทองมายังจุดส่งของ",--Take care of the lasers and carry the gold to the insertion point
hud_e_framing_frame_stage3_mission9_hl = "หลบหนี",--Escape
hud_e_framing_frame_stage3_mission9 = "หลบหนีด้วยซิปไลน์บนดาดฟ้า",--Escape via the zip line on the roof next to the insertion point
hud_e_framing_frame_stage3_mission10_hl = "หาห้องเซิฟเวอร์",--Locate the server room
hud_e_framing_frame_stage3_mission10 = "หาห้องเซิฟเวอร์ในอพาร์ทเม้นท์",--Find the server room somewhere in the democrats' apartment
hud_e_framing_frame_stage3_mission11_hl = "อัพโหลดไฟล์",--Upload the files
hud_e_framing_frame_stage3_mission11 = "แฮกคอมพิวเตอร์เพื่ออัพโหลดไฟล์ไปยังเอฟบีไอ",--Use the computer in the server room to start uploading the files to the FBI
hud_e_framing_frame_stage3_mission12_hl = "เปิดระบบจ่ายไฟ",--Turn the power back on
hud_e_framing_frame_stage3_mission12 = "เปิดระบบจ่ายไฟ เพื่ออัพโหลดไฟล์ต่อ",--Find the circuitbreaker to turn the power back on and continue the upload
hud_e_framing_frame_stage3_mission13_hl = "หลบหนี",--Escape is available
hud_e_framing_frame_stage3_mission13 = "ขึ้นยานพาหนะเพื่อหลบหนี",--Get to the escape vehicle
hud_e_framing_frame_stage3_mission14_hl = "แฮกคอมพิวเตอร์ต่อ",--Reactivate the computer
hud_e_framing_frame_stage3_mission14 = "แฮกคอมพิวเตอร์ต่อ",--Use the keyboard to reactivate the computer and continue the hacking
pln_framing_stage1_intro_a_01 = "ใกล้ถึงหอศิลป์แล้ว แทรกแซงเข้าไป ระวังกล้องและยาม เครื่องตรวจจับการเคลื่อนไหว",--You're almost at the gallery. Slip in, avoid cameras, guards, and motion detectors. Security's high because of a bomb threat.
pln_framing_stage1_intro_a_01b = "ยังไงก็เหอะหารูปที่มีสัญลักษณ์ติดอยู่ เราต้องการอย่างน้อยสักสี่เพื่อกันไว้ก่อน",--Anyway, find the paintings marked as sold and take them. We need at least four to be safe.
pln_framing_stage1_intro_a_02 = "ที่นี่แหละ รูปที่กำลังตามหาอยู่จะมีสัญลักษณ์สีแดงติดอยู่ เราต้องมีอย่างน้อยสี่อันนะเพื่อความแน่ใจ ที่นี่มันถูกปิดและกักกันไว้ หาทางเข้าไปให้ได้ละกัน",--This is the gallery.  You're looking for the paintings marked by a red sold sticker. We need at least four to make this work. The place is closed and locked down. Find a way in. Go.
pln_framing_stage1_intro_a_03 = "โอเค อยู่ข้างหน้าแล้วหละ ระวัง ระวังกล้องและยาม เครื่องตรวจจับการเคลื่อนไหว เข้าไปข้างในและเอามาให้ได้สี่อันที่มีสัญลักษณ์สีแดงติดอยู่ เวลากำลังเดินอยู่นะพวก",--OK, gallery's just ahead. Watch out for motion detectors, cameras and guards. Get in there and bring me four of the paintings marked with a red sold sticker. Time is ticking guys.
pln_framing_stage1_intro_a_04 = "มันน่าจะเป็นงานง่ายถ้าจัดการกับกล้องและการ์ดก่อน บางทีก็ไม่ เอาละหารูปที่มีสัญลักษญ์สีแดงติดอยู่ เราต้องการอย่างน้อยสี่อัน",--This is gonna be easy as long as you steer clear of the security systems and guards. Well maybe not so easy. Take the paintings with red sold stickers and clear out. We need four at least.
pln_framing_stage1_01_any_01 = "เอาหล่ะพวก เข้าไปข้างในหารูป เราต้องการอันที่มีสัญาลักษญ์สีแดงติดอยู่ ระวังการ์ดกับกล้องด้วยหล่ะ",--OK guys, get inside and locate the art. We want the paintings with the red stickers on. Look out for guards and cameras.
pln_framing_stage1_01_any_02 = "โอเค นี่คือแผนเรากำลังมองหารูปที่มีสัญลักษญ์สีแดงติดอยู่ น่าจะมีการดูแลแน่นหนาด้านใน ระวังไว้ละกัน",--OK, here's the setup: we're looking for the paintings with red stickers on them. Security is going to be on the heavy side, cameras and guards. 
pln_framing_stage1_01_any_03 = "พร้อมที่จะยิงรึยัง ? เอาหล่ะฟังก่อน เรากำลังมองหารูปที่มีสัญลักษญ์สีแดงติดอยู่ ข้างในมันคุบไว้อย่างแน่นหนา กล้องก็เยอะเช่นกัน และห้องรักษาความปลอดภัยด้วยแหละ ที่นี้ก็ทำการบ้านซะละกัน",--Ready for the shot? OK listen: you are looking for the paintings marked with red stickers. They've got unusually tight security here. A lot of cameras, even a security room, so do your homework.
pln_framing_stage1_02_any_01 = "โอเค เข้ามาข้างในแล้ว หารูปที่มีสัญลักษญ์สีแดงติดอยู่ เราต้องการอย่างน้อยสี่อัน",--OK, you're inside. Find the paintings with the red stickers on them, we want at least four.
pln_framing_stage1_02_any_02 = "เอาหล่ะ โอเค เราต้องการอย่างน้อยสี่อัน พวกที่มีสัญลักษญ์สีแดงติดอยู่ด้วยหนะ",--Alright... OK, we need at least four paintings, remember, the ones with red stickers.
pln_framing_stage1_02_any_03 = "โอเคเข้ามาข้างในแล้ว เยี่ยม ที่นี้เราต้องการอย่างน้อยสี่รูป อันที่ใช้ได้ก็จะมีสัญลักษญ์สีแดงติดอยู่ ",--OK you're in, good. Now you need at least four paintings, the good ones have red stickers - those are the ones our art lover intends to buy.
pln_framing_stage1_02_any_04 = "",--Nice work, folks. Now what you're looking for are paintings with red stickers. Those are the ones the democrat wants. Get at least four. 
pln_framing_stage1_03_any_01 = "ชิบหายละ! สัญญาณแจ้งเตือน!",--Damn it! That's the alarm!
pln_framing_stage1_04_any_01 = "",--Listen up, if you can get me access to the computer in the surveillance room I'll get it open.
pln_framing_stage1_04_any_02 = "",--OK we can't screw around anymore. Just get me access to the computer in the surveillance room, I'll deal with it remotely.
pln_framing_stage1_04_any_03 = "",--We don't have enough paintings yet! Can someone get me access to the computer in the surveillance room, fast? I'll get it open, don't you worry about your pretty little heads.
pln_framing_stage1_05_any_01 = "",--Alright, that's enough to go now if you want, but if we want more - get me access to the surveillance room so I can see what's on their network.
pln_framing_stage1_05_any_02 = "",--OK crew, you have enough to get the hell out now. If you want more then I need access to the surveillance room. I'll do the rest once you get in.
pln_framing_stage1_06_any_01 = "",--Dammit! If you want everything open again, you're going to need to get into the surveillance room.
pln_framing_stage1_06_any_02 = "",--Everything's locked down - if you want me to fix it then I need to get into the surveillance room.
pln_framing_stage1_06_any_03 = "",--We're locked down... if you want me to open it up you need to get the surveilance room open fast.
pln_framing_stage1_07_any_01 = "",--Can't wait around out here - get into that building as fast as you can. Try the roof.
pln_framing_stage1_07_any_02 = "",--We don't have the time to wait around - can't you find a way in? What about the roof?
pln_framing_stage1_08_any_01 = "",--Have a look around - there has to be a way in, we're losing precious time.
pln_framing_stage1_08_any_02 = "",--Have you checked any of the vertical options? There's got to be access to the interior up there.
pln_framing_stage1_08_any_03 = "",--Check the roof - find your route inside. Get creative, we don't have time.
pln_framing_stage1_09_any_01 = "",--Great, we need at least 3 more, get it to the van. It's in the parking lot next to the gallery.
pln_framing_stage1_09_any_02 = "",--Good, now we need at least 3 more just like this and you need to get them to the van. It's in the parking lot next to the gallery.
pln_framing_stage1_09_any_03 = "",--OK, that's a start, we need three more just like it. Get 'em! Take them to the van in the parking lot next to the gallery and we're in business.
pln_framing_stage1_10_any_01 = "ครึ่งทางละ พวกเราต้องการอีกสอง",--That's half, we need 2 more.
pln_framing_stage1_10_any_02 = "",--That's half the required paintings, you need to get the rest before we can roll out.
pln_framing_stage1_10_any_03 = "",--Halfway there with the painting collection. Now just get the rest and we're home free.
pln_framing_stage1_11_any_01 = "",--Thats four, we're good to go now. If you want to get the rest of the paintings thats up to you.
pln_framing_stage1_11_any_02 = "",--We have four now and four's what we need - now if you want to get more, your move.
pln_framing_stage1_12_any_01 = "",--Bam, that's the doors, I'm still working on the paintings.
pln_framing_stage1_12_any_02 = "",--There we go, off like a prom dress, I'm still working on the paintings.
pln_framing_stage1_13_any_01 = "",--Yes! Hack's done, everything should be unlocked now.
pln_framing_stage1_13_any_02 = "",--OK, OK, I'm done with the security hack, everything's unlocked.
pln_framing_stage1_14_any_01 = "",--Good, with that guy out of the picture, no more cameras.
pln_framing_stage1_14_any_02 = "",--Great, so much for the camera alarm.
pln_framing_stage1_15_any_01 = "",--SWAT responders, coming in hard. Dig in.
pln_framing_stage1_15_any_02 = "",--SWAT units are moving into the building, get ready!
pln_framing_stage1_15_any_03 = "",--SWATs on the scene... Here we go.
pln_framing_stage1_16_any_01 = "",--They just blew a hole in the wall! Hold them back!
pln_framing_stage1_16_any_02 = "",--SWATs just breached the wall! 
pln_framing_stage1_16_any_03 = "พวกมันกำลังเจาะกำแพง!!!",--They're breaching the wall!
pln_framing_stage1_16_any_04 = "พวกมันกำลังระเบิดกำแพง!!!",--They're blowing the wall!
pln_framing_stage1_17_any_01 = "กำลังเชื่อมต่อกลับ น่าจะใช้เวลาหน่อยหนึ่ง",--Connecting... This might take a minute.
pln_framing_stage2_intro_a_01 = "",--Right, this is the place. Get to the traincar and look for your contact. They said they'd meet you there. So far it all looks good. Just trade the paintings and get out fast. Keep it rolling.
pln_framing_stage2_01_any_01 = "",--OK people, get the phone. Let's get this trade out of the way.
pln_framing_stage2_01_any_02 = "",--Head over to the phone, the phone's ringing. Make the contact there.
pln_framing_stage2_01_any_03 = "",--Phone's ringing, time to pick it up and start this trade off.
pln_framing_stage2_02_any_01 = "",--Someone pick up the phone...
pln_framing_stage2_02_any_02 = "",--Is someone going to get that? Can't start the trade until you do..
pln_framing_stage2_03_any_01 = "",--They're pretty antsy - just get the paintings on the table and keep both eyes open for anything weird.
pln_framing_stage2_03_any_02 = "",--I don't like it... Let's get this over with as soon as we can, get the paintings on the table. 
pln_framing_stage2_03_any_03 = "",--This seems fishy but I don't know - get the paintings on the table and keep your spider sense tingling.
pln_framing_stage2_05_any_01 = "",--That's everything, wait for their call.
pln_framing_stage2_05_any_02 = "",--OK, now let's just hope they call you fast.
pln_framing_stage2_05_any_03 = "",--Alright, they just need to call you back. Faster the better.
pln_framing_stage2_06_any_01 = "นั่นแหละ หยิบโทรศัพท์",--There it is, get the phone.
pln_framing_stage2_06_any_02 = "บิงโก หยิบมาซะ",--Bingo. Pick it up.
pln_framing_stage2_06_any_03 = "โอเค พวกแม่งกำลังโทรหา",--OK, that's them calling.
pln_framing_stage2_07_any_01 = "โอเคพวก เข้าไปในรถไฟทุกคน",--OK folks, everyone into the train.
pln_framing_stage2_07_any_02 = "พาทุกคนขึ้นรถไฟ",--Get everyone into the train.
pln_framing_stage2_09_any_01 = "โอเค จำนะ เงินหนึ่งถุงสำหรับภาพวาดทุกครั้ง",--OK now remember, one bag of cash for every painting. 
pln_framing_stage2_09_any_02 = "",--Now we wait. Remember we get a bag of cash for every painting we throw into the chopper. All we need to do is be patient and lucky. 
pln_framing_stage2_10_any_01 = "",--OK good, now there is a van waiting for you on the other side of that building. Go through, load up the car, and we're done for the day.
pln_framing_stage2_10_any_02 = "",--We're done here, there's a van waiting on the other side of the building. Go on through, load the car up, and we're done.
pln_framing_stage2_12_any_01 = "",--Good, good. This'll make our lives easier when we hit the Democrat...
pln_framing_stage2_12_any_02 = "",--This is definitely going to make our lives easier when we go in to hit the Democrat's place.
pln_framing_stage2_13_any_01 = "",--SWAT! I knew it was too easy!
pln_framing_stage2_13_any_02 = "",--Dammit! SWAT ambush. I didn't see it!
pln_framing_stage2_13_any_03 = "",--Get the money and clear out ASAP!
pln_framing_stage2_16_any_01 = "",--That's the doors, they blocked off the doors! There's gotta be another way out!
pln_framing_stage2_17_any_01 = "",--Only an ECM jammer's going to get that door open...Otherwise you need another way around.
pln_framing_stage2_17_any_02 = "",--Dammit does anyone have an ECM jammer - that's about the only thing that'll crack that door. Othewise you need another route.
pln_framing_stage2_18_any_01 = "",--Those tunnels will lead you into the warehouse.
pln_framing_stage2_18_any_02 = "",--I think those tunnels will get you into the warehouse folks.
pln_framing_stage2_18_any_03 = "",--Good move.. that's bound to lead to the warehouse.
pln_framing_stage2_19_any_01 = "",--You clever bastards, you'll get around them using those tunnels.
pln_framing_stage2_19_any_02 = "",--Very smart to use the tunnels like that - very professional.
pln_framing_stage2_19_any_03 = "",--Hell of a good move to use the tunnels - they'll be off-balance.
pln_framing_stage2_20_any_01 = "",--Don't let the workers see you or they might blow the whole deal.
pln_framing_stage2_20_any_02 = "",--Keep a low profile near the workers to be safe.
pln_framing_stage2_20_any_03 = "",--Unless you still want the cops to show up you better be careful around those workers
pln_framing_stage2_20_any_04 = "",--Hey they might be workers but they're not dumb and blind - keep your profile low.
pln_framing_stage3_intro_01  = "ที่แห่งนี้ยามแม่งยั้วเยี้ยเต็มไปหมด คุณต้องหยิบทุกอย่างที่เป็นสิ่งของอิเล็กทรอนิกส์ โทรศัพท์มือถือ, แล็ปท็อป, ฮาร์ดไดร์ฟ เข้าไปข้างในแล้วหาวาล์วซะ",--This place is crawling with guards. You need to grab anything technological of his that isn't nailed down - mobile phones, laptops, hard drives. Slip in and find the vault.
pln_framing_stage3_intro_01b = "",--Get to the roof with the gadgets and bang, we're gold - literally. 
pln_framing_stage3_01_any_01 = "",--So the plan is, go in, get me the following objects. When you have them we'll connect them to our station on the roof.
pln_framing_stage3_02_any_01 = "",--We need his phone, his tablet, his laptop and two external hard drives.
pln_framing_stage3_03_any_01 = "",--You can access the hidden cameras in the paintings with the laptop on the roof.
pln_framing_stage3_04_any_01 = "",--I hope you got a lot of cameras. It'll make it easier for us to find all the devices.
pln_framing_stage3_05_any_01 = "เยี่ยม คุณเจอแล็ปท็อปแล้ว",--Great, you found the laptop.
pln_framing_stage3_06_any_01 = "นี่แหละมือถือของเขา ดีมาก",--That's his phone. Good.
pln_framing_stage3_07_any_01 = "นี่แหละ แท็ปเล็ตพีซี สวยงาม",--That's the tablet PC. Perfect.
pln_framing_stage3_08_any_01 = "นี่แหละ ฮาร์ดไดรฟ์ เยี่ยม",--That's the external hard drive. Nice.
pln_framing_stage3_09_any_01 = "นั่นคือฮาร์ดไดรฟ์อันที่หนึ่ง",--That's one of the external hard drives.
pln_framing_stage3_10_any_01 = "นั่นคือฮาร์ดไดร์ฟอันที่สอง",--That's the second external hard drive.
pln_framing_stage3_11_any_01 = "อีกหนึ่ง หาดูดี ๆ",--One more, keep looking.
pln_framing_stage3_12_any_01 = "อีกสอง ค้นหาต่อไป",--Two more, keep on searching.
pln_framing_stage3_13_any_01 = "น่าจะหมดแล้วล่ะ",--Thats all of them.
pln_framing_stage3_14_any_01 = "เยี่ยม! ตอนนี้ เอาทั้งหมดมารวมกันที่สเตชั่นบนหลังคาและเชื่อมต่อมันซะ",--Great! Now get them up to the station on the roof and connect them.
pln_framing_stage3_15_any_01 = "เชื่อมต่ออุปกรณ์ที่สเตชั่นบนหลังคา",--Connect the devices to the station on the roof.
pln_framing_stage3_16_any_01 = "เอาล่ะ ฉันเข้าถึงได้ละ รอซักครู่...",--Alright now, I have access, hold on a sec...
pln_framing_stage3_17_any_01 = "โอเค! ทอง ฉันคิดว่าเราได้ทุกอย่างที่เราต้องการละ คุณควรจะสามารถเข้าถึงคอมพิวเตอร์ของเขาได้นะ",--OK! We're gold. I think I got everything we need. You should be able to access his desktop computer now.
pln_framing_stage3_18_any_01 = "มันตั้งอยู่ในสำนักงานของเขา",--It's located in his office.
pln_framing_stage3_19_any_01 = "",--Good, OK, you can open the vault now. I have turned on the vault's camera feed as well.
pln_framing_stage3_20_any_01 = "",--There's just a little problem... I don't actually know where the vault is, physically.
pln_framing_stage3_21_any_01 = "",--So this means you have to find it. References seem to indicate it's... Connected to a bookshelf. I know, leave it to a politician to be cliche.
pln_framing_stage3_22_any_01 = "",--Look for bookshelves, see if you can move them and find something.
pln_framing_stage3_23_any_01 = "",--There you go.  Now let's frame this guy, get up to the roof, and our guy will throw you the coke.
pln_framing_stage3_24_any_01 = "",--Carry the coke down to the vault and plant it outside in the pre vault room.
pln_framing_stage3_25_any_01 = "",--That's it, fine work. The escape is ready for you. Unless you want to stick around and clean out the vault. Either way the vehicle's waiting.
pln_framing_stage3_26_any_01 = "",--Good job, we are gone.
pln_framing_stage3_27_any_01 = "",--If you want to go for more, use his desktop PC, it should open the vault up for you.
pln_framing_stage3_28_any_01 = "",--Alright, vault is popped, but watch out for those lasers, they connect directly to the alarm
pln_framing_stage3_29_any_01 = "",--We have to shut them off.
pln_framing_stage3_30_any_01 = "",--Use his computer again, be careful, they only go down for a small amount of time.
pln_framing_stage3_31_any_01 = "",--Use the camera to see when they turn on, and then turn them off again.
pln_framing_stage3_32_any_01 = "",--That's the damn alarm! Time to shift to plan B, folks. 
pln_framing_stage3_33_any_01 = "",--Find his server room and get in there.
pln_framing_stage3_34_any_01 = "",--See if you can find the keycards to  get in there, otherwise we have to drill the doors.
pln_framing_stage3_35_any_01 = "",--Great, that's the server room, start the computer in there, we need to upload all the files.
pln_framing_stage3_36_any_01 = "",--It'll take some time, lots of data to up and a small pipe.
pln_framing_stage3_37_any_01 = "",--Now hopefully they won't notice anything. Because we're just that lucky.
pln_framing_stage3_39_any_01 = "",--Make sure you keep the power up.
pln_framing_stage3_40_any_01 = "",--They cut the power! Get it back up!
pln_framing_stage3_41_any_01 = "",--Get the power back up!
pln_framing_stage3_42_any_01 = "",--Look for a circuit breaker to get the power back up.
pln_framing_stage3_43_any_01 = " ",--Alright, the files are all uploaded, it should do the trick.
pln_framing_stage3_44_any_01 = "",--Our chopper is coming in, he'll blend in with all the news choppers.
pln_framing_stage3_45_any_01 = "",--Get to the chopper to escape!
pln_framing_stage3_46_any_01 = "",--They're gonna try to kill the power! Don't let them!
pln_framing_stage3_46_any_02 = "",--Keep the cops off the circuit breakers if you want to make it!
pln_framing_stage3_46_any_03 = "",--You can't let them kill the power, it'll slow everything down!
pln_framing_stage3_47_any_01 = "",--Whatever you do don't let the sons of bitches cut the power!
pln_framing_stage3_47_any_02 = "",--Keep them the hell away from the circuit breaker, you hear me?
pln_framing_stage3_48_any_01 = "",--So I'm going to send this feed live to all the media outlets as you're uploading. They're gonna eat this up.
pln_framing_stage3_48_any_02 = "",--OK, to make things a little more interesting I'm sending this feed live to all the big media outlets while we upload. Lots of coverage.
pln_framing_stage3_50_any_01 = "",--Pretty soon we're going to be swamped with news choppers. Our escape chopper? Blend right in.
pln_framing_stage3_50_any_02 = "",--When all that media shows up in their choppers, no one's gonna look sideways at our escape bird. 
pln_framing_stage3_50_any_03 = "",--Bain's got a little plan - I think all those media choppers are a convenient smokescreen for our escape chopper, don't you?
pln_framing_stage3_51_any_01 = "โอเค พวกเราใกล้แล้ว!",--OK, we're almost done!
pln_framing_stage3_51_any_02 = "",--It's getting there!
pln_framing_stage3_51_any_03 = "ใกล้แล้ว! ใกล้แล้ว ใกล้แล้ววววว...",--Almost! Almost, almost...
pln_framing_stage3_51_any_04 = "อัพโหลดแม่งไม่เร็วพอ แม่งเอ้ย!",--This upload isn't going fast enough, dammit!
pln_framing_stage3_51_any_05 = "",--We're going to be done soon - I hope.
pln_framing_stage3_51_any_06 = "กำลังอัพโหลด ใกล้แล้ว ๆ",--It's uploading... It's almost there.
pln_framing_stage3_51_any_07 = "",--Christ... Is it buffering? Go faster! Why don't they have Google fiber... Goddam American broadband.
pln_framing_stage3_52_any_01 = "",--Get that gold up to the roof, put it in the bag on the zip line, we are bringing it home!
pln_framing_stage3_52_any_02 = "",--Hustle that gold onto the roof, get it into the bag on the zipline, we're taking it. 
pln_framing_stage3_53_any_01 = "",--Whenever you're ready, I want you on the roof, then we'll get you outta there with the zipline.
pln_framing_stage3_53_any_02 = "",--When you're ready, get to the roof and we'll get you clear with the zipline.
