menu_cn_casino = "ลงพนัน",--Offshore PAYDAY
menu_cn_casino_desc = "จำนวนเงินลงพนัน",--Bet offshore money
menu_cn_casino_pay_accept = "",--Pay fee
menu_cn_casino_pay_fee = "A fee will be deducted from your offshore account when you enter the casino.$NL;$NL;Offshore cost: $contract_fee;$NL;Offshore account: $offshore;",--A fee will be deducted from your offshore account when you enter the casino.$NL;$NL;Offshore cost: $contract_fee;$NL;Offshore account: $offshore;
menu_casino_title_main = "ลงพนัน",--Offshore PAYDAY
menu_casino_title_betting = "ลงพนัน",--Betting
menu_casino_title_stats = "โอกาสดรอป",--Drop Probabilities
menu_casino_stat_base = "ปกติ",--Base
menu_casino_stat_bets = "พนัน",--Bets
menu_casino_stat_skill = "ทักษะ",--Skill
menu_casino_stat_total = "รวม",--Total
menu_casino_stat_weapon_mods = "ของแต่งปืน",--Weapon Mod
menu_casino_stat_masks = "หน้ากาก",--Mask
menu_casino_stat_materials = "วัสดุหน้ากาก",--Material
menu_casino_stat_textures = "พื้นผิวหน้ากาก",--Pattern
menu_casino_stat_colors = "สี",--Color
menu_casino_title_breakdown = "ข้อมูลการลงพนัน",--Betting Breakdown
menu_casino_total_bet = "ต้องจ่ายเป็นจำนวนเงินทั้งหมด: $casino_bet;",--Total Bet: $casino_bet;
menu_casino_cost_fee = "จำนวนเงิน",--Initial fee
menu_casino_option_prefer_title = "ประเภทที่ต้องการ",--Preferred card type
menu_casino_option_prefer_none = "ไม่มีต้องการ",--None
menu_casino_option_infamous_title = "ไอเทม Infamous",--Infamous quality
menu_casino_option_safecard_title = "ประเภท",--Safe cards
menu_casino_option_safecard1 = "1 ใบ",--1 card safed
menu_casino_option_safecard2 = "2 ใบ",--2 cards safed
menu_casino_option_safecard3 = "3 ใบ",--3 cards safed
menu_casino_option_safecard_lock = "レベル制限 $level;",--Locked to level $level;
menu_offshore_account = "จำนวนเงินนอกระบบ",--Offshore account
menu_casino_choice_exit = "กด $BTN_X; เพื่อออก",--$BTN_X; Exit
menu_casino_choice_bet = "กด $BTN_X; เพื่อลงพนัน",--$BTN_X; Place bet
