dialog_accept = "ยอมรับ",--Accept
dialog_ok = "โอเค",--Ok
dialog_yes = "ใช่",--Yes
dialog_yes = "ใช่",--Yes
dialog_reset_filters = "รีเซ็ตการตั้งค่า",--
dialog_no = "ไม่",--No
dialog_continue = "ต่อไป",--Continue
dialog_cancel = "ยกเลิก",--Cancel
dialog_wait = "กรุณารอ",--Please wait
dialog_the_host_has_left_the_game = "โฮสต์ออกจากเกม",--The host has left the game
dialog_connection_to_host_lost = "ขาดการเชื่อมตัวจากโฮสต์",--Connection to the host has been lost
dialog_creating_lobby_title = "กำลังสร้างห้อง",--Creating game
dialog_err_failed_creating_lobby = "เกิดการผิดพลาดขณะสร้างห้องกรุณาลองใหม่อีกครั้ง",--Failed to create game.
dialog_connect_controller_title = "ไม่มีการควบคุม",--No controller
dialog_connect_controller_text = "กรุณาใส่อุปกรณ์ควบคุม",--Please insert controller.
dialog_warning_title = "คำเตือน",--Warning
dialog_are_you_sure_you_want_to_quit = "กรุณายืนยันอีกครั้งที่จะออกเกม?",--Are you sure you want to quit?
dialog_are_you_sure_you_want_leave = "กรุณายืนยันอีกครั้งเพื่อออกจากล็อบบี้นี้",--Are you sure you want to leave this lobby?
dialog_mp_kick_player_title = "ขับไล่ผู้เล่น",--Kick player
dialog_mp_kick_player_message = "ขับไล่ $PLAYER;ใช่หรือไม่",--Player $PLAYER; will be banned from this game. Do you wish to continue?
dialog_mp_restart_level_title = "เริ่มเกมใหม่",--Restart
dialog_mp_restart_level_host_message = "กรุณายืนยันอีกครั้งที่จะเริ่มเกมใหม่?",--Are you sure you want to restart?
dialog_remove_dead_peer = "ไม่สามารถเข้าร่วมเกมของโอสต์ได้",--Connection to one or more players could not be established.
dialog_are_you_sure_you_want_to_reset_statistics = "กรุณายืนยันอีกครั้งเพื่อรีค่าสถิติของคุณ",--Are you sure you want to reset your statistics?
dialog_are_you_sure_you_want_to_leave_game = "กรุณายืนยันอีกครั้งเพื่อออกจากเกมปัจจุบันของคุณ",--Are you sure you want to leave current game?
dialog_are_you_sure_you_want_to_clear_progress = "กรุณายืนยันอีกครั้งเพื่อลบเซฟเกมของคุณ",--Are you sure you want to clear your progress? This will reset your cash, reputation level and your inventory.
dialog_retrieving_servers_title = "กำลังเชื่อมต่อกลับ",--Retrieving games
dialog_logging_in = "กำลังเข้าสู่ระบ",--Logging in
dialog_error_title = "เกิดข้อผิดพลาด",--Error
dialog_game_permission_changed = "เปลี่ยนการตั้งของเกมคุณไม่ได้รับอนุญาติให้เข้าร่วมเกม",--The game settings has changed, you no longer have permission to join
dialog_too_low_level = "เลเวทของคุณน้อยเกินไปไม่ได้รับอนุญาติให้เข้าร่วมเกม",--Your reputation is too low to join this server.
dialog_too_low_level_ovk145 = "สำหรับทีมพัฒนาเท่านั้นไม่สามารถเข้าร่วมเกมได้",--OVERKILL 145+ cannot be played with people below reputation level 145.
dialog_does_not_own_heist = "คุณไม่ได้เป็นเจ้าของภารกิจนี้และไม่สามารถเข้าร่วมเซิฟเวอร์ได้",--You do not own this heist and are unable to join this server.
dialog_does_not_own_heist_info = "'$HEIST;' ไม่สามารถเล่นร่วมกับ $PLAYER; ได้",--Heist "$HEIST;" cannot be played with player $PLAYER;.
dialog_err_failed_joining_lobby = "เกิดความผิดพลาดขณะเข้าร่วมเกม",--Failed joining game.
dialog_err_cant_join_from_game = "คุณต้องออกจากเกมปัจจุบันก่อนเพื่อเข้าร่วมเกมใหม่",--You must leave your current game before joining a new one.
dialog_game_started = "ไม่สามารถเข้าร่วมเกมในปัจจุบันได้",--The game is currently not joinable
dialog_joining_lobby_title = "กำลังเข้าร่วม",--Joining game
dialog_no_connection_to_game_servers = "ไม่สามารถเชื่อมต่อกับเซิฟเวอร์ได้",--Connection to game servers could not be established.
dialog_dropin_title = "$USER; กำลังเข้าร่วมเกม",--$USER; is joining the game
dialog_fail_load_dlc_corrupt = "เนื้อหาที่ดาวน์โหลดได้รับความเสียหายกรุณาลบเนื้อหาและดาวน์โหลดใหม่อีกครั้ง",--Corrupted downloadable content detected. Please go to the Memory section of the Dashboard, delete the corrupted content and download it again.
dialog_information_title = "ขู้อมูล",--Information
dialog_mp_kicked_out_title = "ขับไล่ผู้เล่น",--Kicked out
dialog_mp_kicked_out_message = "คุณถูกบับไล่ออกจากเกม",--You've been kicked from the game.
dialog_default_options_title = "เรียกคืนการตั้งค่าแบบพื้นฐาน",--Reset options
dialog_default_options_message = "กรุณายืนยันอีกครั้งที่จะเรียกคืนการตั้งค่าทั้งหมด",--Do you wish to reset all options to their default state?
dialog_default_controls_options_message = "กรุณายืนยันอีกครั้งที่จะเรียกคืนการควบคุมทั้งหมด",--Do you wish to reset all control options to their default state?
dialog_default_video_options_message = "กรุณายืนยันอีกครั้งที่จะเรียกคืนการตั้งค่าวิดีโอทั้งหมด",--Do you wish to reset all video options to their default state?
dialog_default_sound_options_message = "กรุณายืนยันอีกครั้งที่จะเรียกคืนการตั้งค่าเสียงทั้งหมด?",--Do you wish to reset all sound options to their default state?
dialog_default_network_options_message = "กรุณายืนยันอีกครั้งที่จะเรียกคืนการตั้งค่าเครือข่ายทั้งหมด?",--Do you wish to reset all network options to their default state?
dialog_err_not_signed_in = "คุณต้องเชื่อมต่อเครือข่ายเพื่อเข้าสู่ระบบ",--YOU MUST BE ONLINE TO MAKE USE OF NETWORK MODES.
dialog_mp_disconnected_internet = "คุณได้ยกเลิกการเชื่อมต่อ",--YOU HAVE BEEN DISCONNECTED
dialog_information_title = "ข้อมูล",--Information
dialog_no_chat_parental_control = "ระบบพูดคัยถูกปิดใช้งาน บน Sony Entertainment บัญชี เครือข่าย เนื่องจากข้อ จำกัด การควบคุม ผู้ปกครอง",--CHAT IS DISABLED ON YOUR Sony Entertainment Network Account DUE TO PARENTAL CONTROL RESTRICTIONS.
dialog_age_restriction = "บริการออนไลน์ ถูกปิดใช้งาน ในบัญชี เครือข่าย ความบันเทิง ของ Sonyเนื่องจากข้อ จำกัด ควบคุมโดยผู้ปกครอง",--Online service is disabled on your Sony Entertainment Network account due to parental control restrictions.
dialog_waiting_for_server_response_title = "กรุณารอการตอบสนองจากเซิฟเวอร์",--Waiting for game to respond
dialog_request_timed_out_title = "หมดระยะเวลาการเชื่อมต่อ",--Timed out
dialog_request_timed_out_message = "หมดระยะเวลาคำขอการเข้าร่วมเกม",--Request to join game timed out
dialog_show_restart_game_message = "คุณแน่ใจหรือว่าต้องการเริ่มเกมใหม่เกมในปัจจุบัน??",--Are you sure you want to restart current game?
dialog_mp_no_invites_message = "คุณไม่ได้รับคำเชิญเข้าร่วมเกม",--You have no game invites.
dialog_mp_invite_wrong_version_message = "คำขอที่คุณถูกเชิญใช้เวอร์ชั่นที่ต่างกันคุณไม่สามารถเข้าร่วมเกมได้",--The game you have been invited to is running another version of PAYDAY 2. You are unable to join.
dialog_mp_invite_join_message = "กรุณาเข้าร่วมกับเกมนี้ใช้ในเมนู Crime.net",--Please join this game using the 'View Invites' option in the Crime.net menu.
dialog_mp_pending_invite_short_message = "คุณมีเกมที่รอการเชิญ",--YOU HAVE A PENDING GAME INVITE.
dialog_npcommerce_fail_open = "ไม่สามารถเชื่อมต่อกับPlayStationStoreได้",--FAILED INITIALIZING PlayStationStore
dialog_npcommerce_checkout_fail = "การตรวจสอบผิดพลาด",--Checkout failed
dialog_npcommerce_opening = "กำลังเชื่อมต่อกับPlayStationStore",--INITIALIZING PlayStationStore
dialog_npcommerce_browse_fail = "ไม่สามารถเปิดPlayStationStoreได้",--COULD NOT OPEN PlayStationStore
dialog_transaction_successful = "การติดต่อสำเร็จ",--TRANSACTION SUCCESSFUL
dialog_npcommerce_need_install = "ในการเล่นเวอร์ชั่นเต็มคุณต้องเริ่มเกมใหม่หลังจากการติดตั้งเสร็จสมบูรณ์",--To play the full version, you will need to restart the game after the installation is completed.
dialog_dlc_require_restart = "หมายเหตุ",--Attention
dialog_dlc_require_restart_desc = "คุณจำเป็นต้องเริ่มเกมใหม่ในการเข้าถึงไอเทมใหม่ของคุณ",--You need to restart PAYDAY 2 to access your new items.
dialog_fail_load_setting_wrong_version = "การตั้งค่าไม่ถูกต้องข้อมูลนี้จะถูกลบออก",--Settings file wrong version. Data will now be deleted.
dialog_fail_load_setting_wrong_version_retry = "การตั้งค่าแฟ้มรุ่นที่ไม่ถูกต้องหรือสูงกว่าเวอร์ชั่น $VERSION; ลองโหลดอีกครั้งหรือไม่",--Settings file wrong version. Version $VERSION; or higher is required. Try loading again?
dialog_fail_load_setting_corrupt = "การตั้งค่าไฟล์ที่เสียหายข้อมูลนี้จะถูกลบออก",--Settings file corrupt. Data will now be deleted.
dialog_fail_load_setting_corrupt_retry = "ไฟล์การตั้งค่าความเสียหาย ลองโหลดอีกครั้งหรือไม่",--Settings file corrupt. Try loading again?
dialog_fail_load_progress_wrong_version = "ไฟล์รุ่นที่ไม่ถูกต้องข้อมูลนี้จะถูกลบออก",--Progress file wrong version. Data will now be deleted.
dialog_fail_load_progress_wrong_version_retry = "ไฟล์รุ่นที่ไม่ถูกต้อง $VERSION; หรือสูงกว่าลองโหลดอีกครั้งหรือไม่",--Progress file wrong version. Version $VERSION; or higher is required. Try loading again?
dialog_fail_load_progress_corrupt = "ความคืบหน้าเสียหายข้อมูลนี้จะถูกลบออก",--Progress corrupt. Data will now be deleted.
dialog_fail_load_progress_corrupt_retry = "ไม่สามารถโหลด ลองโหลดอีกครั้งหรือไม่",--Progress could not be loaded. Try loading again?
dialog_fail_load_game_corrupt = "บันทึกไฟล์เสียหาย ไม่สามารถโหลดเกม",--Save file corrupt. Unable to load game.
dialog_ask_load_progress_backup_low_lvl = "กดใช่หากคุณต้องการที่จะโหลดข้อมูลสำรองจากเซิฟเวอร์",--Your local backup save is more recent than the last Steam save.$NL;$NL;Press YES if you want to load your local backup save.
dialog_ask_load_progress_backup_corrupt = "คุณต้องการที่จะโหลดข้อมูลสำรองหรือไม่",--Progress profile corrupt. Load from Backup? Chosing NO will delete your progress.
dialog_ask_load_progress_backup_wrong_version = "โหลดข้อมูลผิดเวอร์ชั่น คุณต้องการที่จะโหลดข้อมูลสำรองหรือไม่",--Progress profile wrong version. Load from Backup? Chosing NO will delete your progress.
menu_feature_heat_title = "คุณได้รับข้อความใหม่",--YOU HAVE A NEW MESSAGE
menu_feature_heat_desc = "From: Bain [bain@///REDACTED///]$NL;To: $player;$NL;Date: 2014-02-27 17:45 (GMT)$NL;Subject: Patch notes$NL;$NL;Greetings, $player;. ฉันกำลังติดตามงานของคุณ",--From: Bain [bain@///REDACTED///]$NL;To: $player;$NL;Date: 2014-02-27 17:45 (GMT)$NL;Subject: Patch notes$NL;$NL;Greetings, $player;. ฉันกำลังติดตามงานของคุณ
dialog_accept_changes_title = "ยืนยันการเปลี่ยนแปลง",--CONFIRM CHANGE?
dialog_accept_changes = "คุณต้องการที่จะให้ตั้งค่าการแสดงเหล่านี้หรือไม่ จะถูกเปลี่ยนกลับภายในใน  $TIME; ",--Do you wish to keep these display settings? They will be reverted in $TIME;.
dialog_key_binding_collision = "1337",--Key "$KEY;" is already mapped to "$MAPPED;", please remap it first.
dialog_key_binding_forbidden = "\"$KEY;\" ได้ถูกตั้งค่าไว้แล้วกรุณาลองอันอื่น",--Key "$KEY;" is reserved by the game, please try something else.
dialog_preplanning_help = "",--Preplanning allows to you learn more about the target and gives you the tools to plan out your perfect heist.$NL;$NL;If you are planning to do a stealth job, focus on surveillance, easier access, and bypassing security. If you plan on going loud, plant supplies at strategic points, and choose fast approaches and exits.$NL;$NL;Preplanning is paid for with cash and favors; however, you can only call so many favors before you raise suspicions and the feds start looking for you. Choose wisely: some plans call for a lot of favors, while others only take a single phone call.$NL;$NL;Expensive, complex operations like safe cracking and escape plans require a vote. In a tie, the host has a casting vote. The host can also override all decisions on placements (but he can't force you to pay for anything you don't agree with).
dialog_preplanning_help_controller = "$NL;$NL;การควบคุมทั่วไป:$NL;$NL;เลื่อนเมาส์หาจุดยุทธศาสตร์เพื่อหาข้อมูลเพิ่มเติม.$NL;$NL;คลิกซ้ายในเเผนที่เพื่อเปิดในเมนู.$NL;$NL;เมื่อดูรายการ.",--$NL;$NL;GENERAL CONTROLS:$NL;$NL;Roll over a map point to find out more.$NL;$NL;Left click on a map point to open it in the menu.$NL;$NL;When viewing an item in the menu, left click on the item point list or on the map to place the item.$NL;$NL; Click [RIGHT MOUSE] on a menu item to find it on the map. $NL;$NL;Hold [CTRL] + [LEFT MOUSE] to draw.
dialog_new_unlock_title = "ขอแสดงความยินดี",--Congratulations!
dialog_skills_place_title = "คุณแน่ใจหรือไม่?",--Are you sure?
dialog_unlock_skilltree = "คุณกำลังจะเริ่มต้น $skill; ทักษะ $NL;$NL; เสียค่าใช้จ่าย $cost; และ $remaining_points; เสีย $points; พ้อยท์",--You are about to start $skill; skill tree.$NL;$NL;It will cost $cost; and $points; out of $remaining_points; points.
dialog_allocate_skillpoint = "จะปลดล็อคทักษะ $skill; ทักษะ $NL;$NL; จะเสียค่าใช้จ่าย $cost; จาก $remaining_points; และ  $points; พ้อยท์",--This will unlock the $skill; skill.$NL;$NL;It will cost $cost; and $points; out of $remaining_points; points.
dialog_skills_respec_title = "คุณแน่ใจหรือไม่?",--Are you sure?
dialog_respec_skilltree = "คุณกำลังจะรีเซ็ตทักษะ $NL; $NL;ทักษะ $tree; จะคืนพ้อยท์ทั้งหมด  $NL;จะได้รับเงิน $cost; ของการรีเซ็ตทักษะ",--You are about to respec this skill tree.$NL;$NL;Doing a respec resets all skill points in the $tree; skill tree.$NL;You will also be refunded $cost; of your investments in this tree.
dialog_skills_reseted_title = "โปรดทราบ",--Please note
dialog_skilltree_reseted = "มีการเปลี่ยนแปลงที่เกิดขึ้นกับ ทักษะ $NL;$NL; ทักษะทั้งหมดของคุณได้รับการรีเซ็ตและความสามารถของคุณจะคืนเป็นเงินสด",--Changes have been made to the skill tree.$NL;$NL;All your skills have been reset and your skill points as well as your cash has been refunded.
dialog_unlock_skill_switch = "คุณกำลังจะปลดล็อคเซ็ตทักษะ $NL;$NL;$cost_text;",--You are about to unlock a new skill set.$NL;$NL;$cost_text;
dialog_unlock_skill_switch_free = "ไม่คิดค่าใช้จ่าย",--This one is free of charge.
dialog_unlock_skill_switch_offshore = "จะเสียค่าใช้จ่ายจากเงินนอกระบบเป็นจำนวนทั้งหมด $offshore;",--It will cost you $offshore; offshore cash.
dialog_unlock_skill_switch_spending = "จะเสียค่าใช้จ่าย $spending;",--It will cost you $spending; spending cash.
dialog_unlock_skill_switch_spending_offshore = "มันจะเสียค่าใช้จ่าย $spending; และเงินนอกระบบทั้งหมด $offshore;",--It will cost you $spending; spending cash and $offshore; offshore cash.
dialog_unlock_skill_switch_title = "คุณแน่ใจหรือไม่?",--Are you sure?
dialog_xp_to_specialization = "ค่าสำหรับใช้งานทักษะเพิ่มเติมหรือPerk",--XP to Perk Conversion
dialog_infamy_reseted_title = "โปรดทราบ",--Please note
dialog_infamytree_reseted = "มีการเปลี่ยนแปลงที่เกิดขึ้นกับ Infamy $NL;$NL; รายการทั้งหมดของคุณได้รับการรีเซ็ตและคะแนนของคุณได้รับการคืนเงิน",--Changes have been made to the infamy tree.$NL;$NL;All your infamy items have been reset and your infamy points have been refunded.
dialog_bm_mask_sell_title = "คุณแน่ใจหรือไม่?",--Are you sure?
dialog_blackmarket_item = "$item;",--$item;
dialog_blackmarket_slot_item_sell = "หากคุณขายสิ่งนี้จะได้รับเงิน $money;",--If you sell this, you will be paid $money;.
dialog_bm_crafted_sell_title = "คุณแน่ใจหรือไม่?",--Are you sure?
dialog_blackmarket_slot_item = "[ปืนนี้อยู่ในช่องที่ $slot;] $item;",--[SLOT $slot;] $item;
dialog_blackmarket_slot_mask_remove = "นำหน้ากากนี้กลับไปยังที่เก็บของคุณ  $suffix;",--Return this mask back to your stash? $suffix;
dialog_blackmarket_slot_mask_remove_suffix = "การปรับแต่งนี้จะขายเป็นเงิน $money;",--Customizations will be sold for $money;.
dialog_blackmarket_mask_sell_mod_readded = "$mod;กลับไปยังที่เก็บของคุณ",--$mod; will return to your inventory.
dialog_bm_weapon_buy_title = "คุณแน่ใจหรือไม่?",--Are you sure?
dialog_repair_weapon_title = "ซ่อมแซม",--Repair
dialog_repair_weapon_message = "คุณต้องการที่จะซ่อมแชม \"$WEAPON;\" $COST; ใช่หรือไม่",--Do you want to repair weapon "$WEAPON;" for $COST;?
dialog_buy_weapon_title = "ซื้อ",--Buy
dialog_buy_weapon_message = "คุณต้องการที่จะซื้อ \"$WEAPON;\" ในราคา  $COST; ใช่หรือไม่",--Do you want to buy weapon "$WEAPON;" for $COST;?
dialog_blackmarket_buy_weapon_slot = "ซื้อพื้นที่สำหรับเก็บของจะปลดล็อกหนึ่งช่องใช้งาน slot.$NL;$NL; ในราคา $NL;$NL;$money; ",--Buying this will unlock one more weapon slot.$NL;$NL;This will cost you $money;.
dialog_blackmarket_mod_add = "คุณกำลังจะปรับแต่งปืนโดยใส่ $mod; ในอาวุธของคุณ",--You are about to add modification $mod; to your weapon.
dialog_blackmarket_mod_remove = "คุณกำลังจะลบ $mod; ในอาวุธของคุณ",--You are about to remove modification $mod; from your weapon.
dialog_blackmarket_mod_replace = "และจะแทนที่ $mod; ของคุณ",--This will replace your current modification $mod;.
dialog_blackmarket_num_in_inventory = "คุณมี $item; อยู่จำนวน $amount; ในคลังของคุณ",--You own $amount; $item; already.
dialog_blackmarket_buy_item = "คุณแน่ใจที่จะซื้อ $item; ในราคา $NL;$NL;$money; ใช่หรือไม่ $NL;$NL;$num_in_inventory;",--
dialog_bm_weapon_modify_title = "คุณแน่ใจหรือไม่?",--Are you sure?
dialog_bm_mask_assemble_title = "คุณแน่ใจหรือไม่?",--Are you sure?
dialog_blackmarket_assemble_item = "คุณต้องการที่จะเพิ่ม $item; ลงในคลังของคุณหรือใช่หรีอไม่ $NL;$NL;$num_in_inventory;",--Do you really want to put together $item; mask and place it into your inventory?$NL;$NL;$num_in_inventory;
dialog_bm_mask_custom_abort = "คุณแน่ใจหรือไม่?",--Are you sure?
dialog_blackmarket_abort_mask_warning = "หน้ากากของคุณยังไม่ได้รับการปรับแต่งต้องการที่จะออกใช่หรือไม่",--Your mask has not been finalized. Aborting will leave the mask unchanged.
dialog_bm_mask_custom_final_title = "คุณแน่ใจหรือไม่?",--Are you sure?
dialog_blackmarket_finalize_item = "$ITEM;$NL; คุณกำลังจะจบการปรับแต่งของคุณและไม่เสียค่าใช้จ่าย $money;",--$ITEM;$NL; You are about to finalize your customizations, this process is irreversible and will cost you $money;.
dialog_assets_buy_title = "คุณแน่ใจหรือไม่?",--Are you sure?
dialog_mission_asset_buy = "$asset_desc;$NL;$NL;Cost: $cost;.",--$asset_desc;$NL;$NL;Cost: $cost;.
dialog_premium_buy_title = "คุณแน่ใจหรือไม่?",--Are you sure?
dialog_casino_pay_title = "คุณแน่ใจหรือไม่?",--Are you sure?
dialog_storage_removed_warning_X360 = "อุปกรณ์จัดเก็บข้อมูลที่เลือกได้ถูกลบออกไฟล์เซิฟของคุณจะไม่ถูกบัน ทีกไว้",--Selected storage device has been removed. Your progress will no longer be saved
dialog_err_room_is_full = "ห้องนี้เต็มแล้วกรุณาลองอีกครั้ง",--This room has been filled, please try another one.
dialog_err_room_no_longer_exists = "ห้องนี้ไม่มีอยู่แล้วโปรดลองอีกคนหนึ่ง",--This room no longer exists, please try another one.
dialog_err_wrong_version_message = "เกมที่คุณกำลังพยายามที่จะเข้าร่วมทำงานเวอร์ชั่นอื่นคุณไม่สามารถที่จะเข้าร่วมเกมได้",--The game you are trying to join is running another version of PAYDAY 2. You are unable to join.
dialog_inactive_user_accepted_invite = "เชิญได้รับการยอมรับจากผู้ใช้ที่ไม่ได้ใช้งาน",--An invitation has been accepted by an inactive user. The invitation is successfully completed after pressing START.
dialog_safehouse_title = "เซฟเฮ้าส์",--Safe house
dialog_safehouse_text = "คุณยังไม่เคยไปที่เซฟเฮ้าส์เลยจะลองไปที่นั้นไหมล่ะ",--You haven't visited the safe house yet. Would you like to go there now?
dialog_save_settings_failed = "การดำเนินการล้มเหลวในการบันทึก",--Saving operation failed
dialog_safehouse_goto_text = "คุณต้องการที่จะไปยังเซฟเฮ้าส์หรือไม่",--Do you want to go to your safe house?
dialog_load_wrong_user = "ข้อมูลนี้เป็นของผู้ใช้รายอื่น จะไม่ทำการนำข้อมูลมาใช้งาน",--Save data belongs to a different user. No progress will be loaded.
dialog_abort_mission_text = "กรุณายืนยันอีกครั้งเพื่อยกเลิกงานจ้างของคุณในปัจุบัน",--Are you sure you would like to terminate the current contract?$NL;$NL;You and your crew will be returned to the planning phase where a new contract can be selected.
dialog_become_infamous = "คำเตือน!",--WARNING!
dialog_new_tradable_item_open_container = "เปิดตู้เซฟ",--Open Safe
dialog_new_tradable_item_accept_all = "ยอมรับทั้งหมด",--Accept All
dialog_new_tradable_item_accept = "ยอมรับ",--Accept
dialog_new_tradable_item_title = "คุณได้รับไอเทมใหม่",--You have received a new item!
dialog_new_tradable_item_bonus = "คุณได้รับ $bonus;",--$bonus; modifier
dialog_new_tradable_item = "$quality; ##$name;##",--$quality; ##$name;##
dialog_tradable_item_store_title = "ร้านค้าของเพลเดย์",--Payday Store
dialog_challenge_reward_plural = "ขอแสดงความยินดีคุณได้รับ $NL;$amount;x $item; ถูกเพิ่มลงในคลังของคุณแล้ว$NL;",--Congratulations!$NL;$amount;x $item; has been added to your inventory.$NL;
dialog_weapon_cosmetics_replace = "ลายจะเข้ามาแทนที่อาวุธปัจจุบันของคุณ $cosmetic;",--This will replace your current weapon skin $cosmetic;.
dialog_weapon_cosmetics_remove = "แบบคุณกำลังจะเอาลาย $cosmetic; ออกจากปืนของคุณ",--You are about to remove weapon skin $cosmetic; from your weapon.
dialog_no_safe_for_this_drill_title = "คำเตือน",--Warning
dialog_tradable_item_failed = "การซื้อขายผิดพลาด",--Transaction failed.
dialog_challenge_reward_cash = "ขอแสดงความยินดีจำนวนเงิน $NL;$cash; ได้เพิ่มลงในคลังของคุณแล้ว$NL;",--Congratulations!$NL;$cash; has been added to your spending cash.$NL;
dialog_weapon_cosmetics_locked = "นี่คือลายอาวุธพิเศษ ในขณะที่ใช้งานอยู่ไม่สามารถเปลี่ยนชื่อได้",--This is a special weapon skin, while it is applied you will not be able to change the configuration nor custom name for this weapon.
dialog_preplanning_help = "การวางแผนล่วงหน้าจะช่วยให้คุณเรียนรู้เกี่ยวกับเป้าหมายและช่วยให้คุณมีการวางแผนออกปล้นสมบูรณ์แบบของคุณ $NL;$NL;If หากคุณกำลังวางแผนที่จะย่องเงียบ",--Preplanning allows to you learn more about the target and gives you the tools to plan out your perfect heist.$NL;$NL;If you are planning to do a stealth job, focus on surveilla
dialog_weapon_cosmetics_add = "คุณกำลังจะใช้งานลาย $cosmetic; กับอาวุธของคุณ",--You are about to apply weapon skin $cosmetic; to your weapon.
dialog_checking_out = "การตรวจสอบ",--Checking out...
menu_dialog_warning_infamy_replace_primary = "คุณไม่มีปืนหลักที่สามารถใช้งานได้อาวุธของคุณในช่องที่ 1 ($primary;) จะถูกขายและแทนที่ด้วย ($amcar;)",--You currently do not have any primary weapon that will be useable if you accept. Your primary weapon in slot 1 ($primary;) will be sold and replaced with a basic weapon ($amcar;).
dialog_and_more_tradable_item_title = "คุณได้รับไอเทมใหม่",--You have received new items!
dialog_failed_open_safe = "ไม่สามารถเปิดเซฟได้",--Failed to open safe
dialog_weapon_cosmetics_remove_blueprint = "อาวุธของคุณจะกลับไปยังค่าเริ่มต้น",--This will return your weapon to its default configuration.
dialog_tradable_item_canceled = "การซื้อขายถูกยกเลิกคุณยังไม่ได้รับการชำระเงิน",--Transaction canceled. You have not been charged.
dialog_feature_thq_title = "คุณได้รับข้อความใหม่",--You have a new message
dialog_premium_buy_title = "คุณแน่ใจหรือไม่",--Are you sure?
dialog_feature_thq = "การตั้งค่าใหม่สามารถเข้าไปดูได้ที่  Options->Video->Advanced. มันชื่อว่า ใช้โมเดลของอาวุธคุณภาพสูง และลองดูผู้เล่นคนอื่นๆอาวุธ. จะใช้ทรัพยากรเพิ่มขึ้น.$NL;$NL;ต้องการที่จะเปิดมันตอนนี้เลยใช่หรือไม่",--A new option can be found in "Options->Video->Advanced". It is called "Use HQ weapons" and lets you see other players' weapons in high quality. The option greatly increases graphic memory usage.$NL;$NL;Do you wish to turn it on now?
dialog_requires_steam_overlay_tradable_item = "การซื้อต้องใช้งานSteam Community Overlay กรุณาเช็คให้แน่ใจว่า Steam overlay ของคุณได้เปิดใช้งานอยู่หากไม่มีให้รีสตาร์ทเกมของคุณเพื่อใช้งาน",--Making a purchase requires the Steam Community Overlay. Please ensure that the in-game Steam Community is enabled and restart the game to use the store.
dialog_weapon_cosmetics_set_blueprint = "งานของปืนนั้นที่ถูกใช้งานอยู่จะถูกแทนที่กับลายปัจจุบัน",--This weapon skin contains its own set of weapon modifications and will replace your current configuration.
menu_dialog_become_infamous_free = "หากคุณจะดำเนินการต่อเลเวลของคุณจะเหลือ 0 และทักษะพ้อยท์ทั้งหมดจะถูกลบออก .$NL;$NL; คุณจะเริ่มใหม่โดยที่ไม่มีทักษะคุณไม่สามารถกลับคืนได้ $NL;$NL; แต่จะเก็บปืน ที่แต่งปืน หน้ากาก ลวดลายหน้ากากไว้",--If you proceed, your reputation level will be reset to level 0. All your skills and unspent skill points will be removed.$NL;$NL;You will start over with no skills. This is not reversible, and you CAN NOT get back what you sacrifice.$NL;$NL;You get to keep all your guns, mods, masks, patterns and materials. You will also gain one level of Infamy and one Infamy point to spend in the Infamy tree.
dialog_no_safe_for_this_drill = "คุณไม่มีเซฟสำหรับเปิดกับเครื่องเจาะได้",--You do not own any safes that this drill can open
dialog_inventory_load_fail_text = "ไม่สามารถโหลดข้อมูลได้กรุณาลองเริ่มเกมใหม่",--Could not retrieve your inventory. Restart Payday 2.
dialog_challenge_reward_title = "ได้รับรางวัลแล้ว",--Reward Collected!
menu_dialog_warning_infamy_replace_pri_sec = "คุณไม่มีปืนหลักและปืนรองที่สามารถใช้งานได้อาวุธของคุณในช่องที่ 1 ($primary; and $secondary;) จะถูกขายและแทนที่ด้วย ($amcar; and $glock_17;)",--You currently do not have any primary nor secondary weapon that will be useable if you accept. Your primary and secondary weapons in slot 1 ($primary; and $secondary;) will be sold and replaced with basic weapons ($amcar; and $glock_17;).
dialog_tradable_item_error = "ข้อผิดพลาดที่ไม่รู้จักกรุณาลองใหม่ในภายหลัง",--Unknown error. Please try later.
dialog_inventory_item_fail_title = "คลังเก็บของ",--Inventory
dialog_inventory_item_fail_text = "$items;ไม่สามารถใช้ได้ในคลังของคุณและได้ถูกลบออก",--$items; aren't available in your Inventory and have been removed.
dialog_tradable_item_success = "การซื้อขายเสร็จสิ้น",--Transaction success.
dialog_challenge_reward_xp = "ขอแสดงความยินดีคุณได้รับXP$NL;$xp; XP ได้รับการแล้ว .$NL;",--Congratulations!$NL;$xp; experience has been gained.$NL;
menu_dialog_become_infamous_no_cash = "คุณต้องมีเงินนอกระบบ $cash; เพื่อได้รับการจุติ",--You need $cash; from your offshore account to become infamous.
menu_dialog_warning_infamy_replace_secondary = "คุณไม่มีรองหลักที่สามารถใช้งานได้อาวุธของคุณในช่องที่ 1 ($secondary;) จะถูกขายและแทนที่ด้วย ($glock_17;).",--You currently do not have any secondary weapon that will be useable if you accept. Your secondary weapon in slot 1 ($secondary;) will be sold and replaced with a basic weapon ($glock_17;).
menu_dialog_become_infamous = "การจุติจะเสียค่าใช้จ่าย 200,000,000 ซึ่งจะหักเงินจากเงินนอกระบบของคุณและคุณจะได้รับการรีเซ็ตเลเวลไปที่เลเวล 0 ทักษะทั้งหมดของคุณและทักษะพ้อยท์ต์ จะถูกลบออกและเงินสดของคุณจะหายไปแต่เงินนอกระบบของคุณจะยังคงอยู่ $NL;$NL;คุณจะเริ่มต้นใหม่โดยไม่มีเงินสดเหลืออยู่หากยอมรับไม่สามารถย้อนกลับการกระทำนี้ได้ $NL;$NL;คุณจะไม่สูญเสียของแต่งปืน, หน้ากาก,ลวดลายเเละวัสดุ นอกจากนี้คุณยังจะได้รับระดับจุติ 1 ระดับทุกๆครั้งที่จุติ",--Becoming Infamous will cost $200,000,000 which will be deducted from your offshore account. If you proceed, your reputation level will be reset to level 0. All your skills and unspent skill points will be removed, and all your spending cash will be burned. The cash on your offshore account however will remain.$NL;$NL;You will start over with no skills and your spending cash will be reset. This is not reversible, and you CAN NOT get back what you sacrifice.$NL;$NL;You get to keep all your guns, mods, masks, patterns and materials. You will also gain one level of Infamy and one Infamy point to spend in the Infamy tree.
dialog_infamous_info_title = "ระบบเลื่อนขั้น",--Infamy
dialog_infamous_info_desc = "คุณยังไม่มีคุณสมบัติในการเลื่อนขั้น.การที่คุณจะเลื่อนขั้นได้จำเป็นต้องมี Level 100 และมีเงินOffshore Accountจำนวน $200,000,000 โดยคุณจะถูกหักเงิน cash และ skill point ทั้งหมดไป",--You don't have what it takes yet. To become infamous, you will need to get to reputation level $level; and pay a fee of $cash; from your offshore account along with your skill points and the rest of your spending cash.
dialog_blackmarket_mod_cost = "ค่าใช้จ่ายทั้งหมด $money;",--This will cost you $money;.
dialog_blackmarket_lost_mods_warning = "(อะไหล่ปืนอันเก่าของคุณจะถูกถอดออกและส่งไปยังช่องเก็บของของคุณ)",--(Your removed modifications will be placed in the inventory)
dialog_are_you_sure_you_want_leave_cs = "คุณต้องการออกจากโหมด Crime Spree ใช่หรือไม่",
dialog_cs_claim_rewards_text = "คุณต้องการรับรางวัลของโหมด Crime Spree ใช่หรือไม่$NL;การกระทำนี้จะจบ Crime Spree ปัจจุบันของคุณ$NL;คุณต้องเริ่มโหมด Crime Spree ใหม่เพื่อรับรางวัลครั้งต่อไป",
dialog_cs_claim_rewards = "รับรางวัล Crime Spree",--
dialog_are_you_sure_you_want_stop_cs_refund = "คุณแน่ใจที่จะหยุด Crime spree ของคุณ ?$NL;$NL;นี่จะหยุดสถานะ Crime spree ปัจจุบันของคุณและจะคืนเหรียญแลกเปลี่ยนที่ใช้ไป $coins; เหรียญให้กับคุญ",--Are you sure you want to stop your Crime Spree?$NL;$NL;This will end your current spree, and no rewards will be given to you. Your initial investment of $coins; Continental Coins will be returned to you.
