menu_lobby_filters = "เซิฟเวอร์สาธารณะ",--Public server filters
menu_toggle_friends_only = "เพื่อนเท่านั้น",--Friends only
menu_toggle_toggle_new_servers_only = "เซิฟเวอร์ใหม่เท่านั้น",--New servers only
menu_toggle_server_state_lobby = "เซิฟเวอร์ที่อยู่ในล็อบบี้เท่านั้น",--In lobby servers only
menu_toggle_job_appropriate_lobby = "เซิร์ฟเวอร์ระดับที่เหมาะสมกับเลเวลของคุณ",--Level appropriate servers
menu_preferred_plan_help = "รูปแบบการปล้น",--Preferred tactic
menu_preferred_plan= "รูปแบบการปล้น",--Tactic
menu_any= "ทั้งหมด",--Any
menu_plan_loud= "บู้แหลกแหกค่าย",--Loud
menu_plan_stealth= "ย่องเงียบตีนแมว",--Stealth
menu_max_lobbies_filter= "จำนวนสูงสุดในการค้นหาเซิร์ฟเวอร์",--Maximum servers
menu_dist_filter= "ขอบเขตในการค้นหาเซิฟเวอร์",--DISTANCE FILTER
menu_dist_filter_close= "เซิฟเวอร์ระยะใกล้",--Close
menu_dist_filter_far= "เซิฟเวอร์ระยะไกล",--Far
menu_dist_filter_worldwide= "เซิฟเวอร์ทั่วโลก",--Worldwide
menu_diff_filter= "ระดับความยากของเซิฟเวอร์",--DIFFICULTY FILTER
menu_difficulty_normal = "",--normal
menu_difficulty_hard = "",--Hard
menu_difficulty_very_hard = "",--Hard
menu_difficulty_overkill = "",--OVERKILL
menu_difficulty_apocalypse="",--Death Wish
menu_job_id_filter= "รูปแบบงานจ้าง",--Contract filter
menu_kicking_allowed_filter= "รูปแบบการขับไล่",--Kick filter
menu_kick_vote= "โหวตเพื่อขับไล่",--Vote Kick
menu_kick_server= "หัวหน้าห้องขับไล่เอง",--Host Kick
menu_kick_disabled= "ปิดใช้งานการขับไล่",--Kick Disabled
menu_apply_settings= "ใช้การตั้งค่าเหล่านี้",--Apply these settings
cn_menu_accept_contract = "ยอมรับ",--Accept
cn_menu_decline_contract = "ปฏิเสธ",--Decline
menu_toggle_allow_safehouses = "อนุญาติห้องที่เป็นเซฟเฮ้าส์",--Allow Safe House
menu_toggle_mutated_lobby = "อนุญาติห้องที่ปรับแต่งระบบการเล่น",--
menu_mutators = "ปรับแต่งระบบการเล่น",--
menu_mutators_help = "ปรับแต่งระบบการเล่นห้องของคุณ",--
menu_cs_top_floor = "ชั้นบนสุด",--
menu_cs_ground_floor = "ชั้นแนวเดียวกับดิน",--
menu_cs_basement = "ชั้นใต้ดิน",--
menu_gamemode_spree = "",--
menu_spree_difference_filter = "ระดับความยากของ Crime Spree",--
menu_off = "ปิดการใช้งาน",--
