menu_controller_normal= "ขณะเดิน",--On foot
menu_controller_type= "การควบคุม",--Controls
menu_button_move_forward= "เดินไปข้างหน้า",--Move forward
menu_button_move_back= "เดินกลับ",--Move back
menu_button_move_left= "เดินไปข้างซ้าย",--Move left (strafe)
menu_button_move_right= "เดินไปข้างขวา",--Move right (strafe)
menu_button_fire_weapon= "ยิงปืน",--Fire Weapon
menu_button_aim_down_sight= "เล็งปืน",--Aim Down Sight
menu_button_weapon_slot1= "ปืนรอง",--Secondary
menu_button_weapon_slot2= "ปืนหลัก",--Primary
menu_button_switch_weapon= "สลับปืน",--Switch Weapon
menu_button_reload= "เปลี่ยนกระสุนปืน",--Reload
menu_button_weapon_gadget= "เปิด/ปิดอุปกรณ์เพิ่มเติม",--Gadget on/off
menu_button_weapon_firemode= "เปลี่ยนรูปแบบการยิงของอาวุธ",--Weapon fire mode SINGLE/AUTO
menu_button_throw_grenade= "ขว้างระเบิด",--Throw grenade
menu_button_sprint_WIN32= "วิ่ง",--(press) Run
menu_button_sprint= "วิ่ง",--(press) Run
menu_button_jump= "กระโดด",--Jump
menu_button_crouch= "นั่ง",--Crouch
menu_button_melee_WIN32= "ใช้อาวุธระยะประชิต",--Melee Attack
menu_button_melee= "ใช้อาวุธระยะประชิต",--(press) Melee Attack
menu_button_shout= "ชี้เป้าหมาย",--Shout/Interact
menu_button_deploy= "วางอุปกรณ์เสริม",--Deploy Equipment/Throw Bag
menu_button_chat_message= "ข้อความแชท",--Chat message
menu_button_push_to_talk= "ใช้ไมค์",--Push to talk
menu_button_cash_inspect= "ตรวจสอบอาวุธ",--Inspect weapon
menu_button_deploy_bipod= "ใช้งานขาตั้งปืน",--Deploy bipod
menu_set_default_controller= "เรียกคืนการตั้งค่าดังเดิม",--USE DEFAULTS
menu_controller_vehicle= "ขณะใช้งานยานพาหนะ",--In vehicle
menu_button_accelerate= "ขับไปข้างหน้า",--Accelerate
menu_button_brake= "เบรค/ถอยหลัง",--Brake/Reverse
menu_button_turn_left= "เลี้ยวซ้าย",--Turn left
menu_button_turn_right= "เลี้ยวขวา",--Turn right
menu_button_handbrake= "ใช้เบรคมือ",--Handbrake
menu_button_vehicle_change_camera= "เปลี่ยนมุมมอง",--Change camera mode
menu_button_vehicle_rear_camera= "ดูข้างหลัง",--Look behind
menu_button_vehicle_shooting_stance= "ดูข้างหน้ากันชน",--Passenger shooting pose
menu_button_vehicle_exit= "เข้า/ออก จากยานพาหนะ",--Exit vehicle