menu_vsync = "วีซิงค์",--Vsync
menu_vsync_help = "ฟิคเฟรมเรทของเกม",--Turn vsync on or off. Vsync reduces tearing but caps framerate to the refresh rate of your screen.
menu_toggle_dof = "ระยะที่ให้ภาพคมชัด",--Depth of Field
menu_toggle_dof_help = "ระยะที่ให้ภาพคมชัดจากจุดที่เราโฟกัสลึกเข้าไปด้านหลังและด้านหน้า",--Turn Depth of Field on or off.
menu_toggle_gpu_flush = "ประมวลผลด้านกราฟฟิก",--Flush GPU
menu_toggle_gpu_flush_help = "ประมวลผลด้านกราฟฟิกจะต้องใช้ทรัพยากรจาก CPU",--Fixes render lag (can be perceived as mouse/controller lag). Can have minor impact on performance.
menu_use_thq_weapon_parts = "ใช้การเรนเดอร์อาวุธคุณภาพสูง",--Use HQ weapons
menu_use_thq_weapon_parts_help = "การเรนเดอร์อาวุธคุณภาพสูง",--Set to see other players weapons in high quality.
menu_texture_quality = "ความคมชัดของพื้นผิว",--TEXTURE QUALITY
menu_texture_quality_help = "ปรับเปลี่ยนความคมชัดของพื้นผิว",--Change the level of detail of the textures. Low increases performance, High increases visual quality.
menu_texture_quality_very_low = "ต่ำมาก",--Very Low
menu_texture_quality_low = "ต่ำ",--Low
menu_texture_quality_medium = "ปานกลาง",--Medium
menu_texture_quality_high = "สูง",--High
menu_texture_quality_very_high = "สูงมาก",--Very High
menu_shadow_quality = "คุณภาพเงา",--Shadow Quality
menu_shadow_quality_help = "ปรับเปลี่ยนคุณภาพเงา",--Change the level of detail of the shadow textures. Low increases performance, high increases visual quality.
menu_anim_lod = "คุณภาพการเคลื่อนไหว",--ANIMATION QUALITY
menu_anim_lod_help = "คุณภาพการเคลื่อนไหวหรือคุณภาพของอนิเมชั่นต่างๆ",--Change the level of detail of the animations. Low increases performance, High increases visual quality.
menu_anim_lod_1 = "ต่ำ",--Low
menu_anim_lod_2 = "ปานกลาง",--Medium
menu_anim_lod_3 = "สูง",--High
menu_fps_limit = "อัตราค่าเฟรมเรท",--FRAME RATE LIMIT
menu_fps_limit_help = "ปรับเฟรมเรทให้ดูลื่นไหลขึ้น",--Specify the maximum frame rate in frames per second. Use lower values to Decrease Overheating & Mouse Lag.
menu_lightfx = "เอฟเฟคแสง",--ALIENWARE LIGHTFX
menu_lightfx_help = "เอฟเฟคแสงของอุปกรณ์ของ Alienware",--Turn Alienware LightFX on or off, make sure your Alienware Command Center drivers are up to date.
menu_fov_adjustment = "มุมมองของปืน",--FOV adjustment
menu_fov_adjustment_help = "ปรับให้มุมมองของปืนให้มองได้ไกล/ใกล้ขึ้น",--Adjusts the width of the player field of view.
menu_headbob = "การเร่งความเร็วของกล้อง",--Use Acceleration Camera Effect
menu_headbob_help = "ปิด/เปิด เอฟเฟคส่ายหัวเวลาวิ่ง",--Turn acceleration camera effect on or off. Head bobbing makes your camera shake when walking/running.
menu_max_streaming_chunk = "การดาวน์โหลดข้อมูล",--Streaming Chunk KB
menu_max_streaming_chunk_help = "การดาวน์โหลดข้อมูลของแมพ",--The maximum amount of data per read operation the game will access synchronously from HDD.
menu_aa = "การลดรอยหยัก",--Anti aliasing
menu_aa_off = "ปิด",--Off
menu_ao = "คุณภาพสิ่งแวดล้อม",--Ambient Occlusion
menu_ao_off = "ปิด",--Off
menu_ao_help = "AOB จะทำให้ประสิทธิภาพความไหลลื่นสูงขึ้นแต่จะทำให้มุมมองประสิทธิภาพต่ำลง. SSAO สูงจะทำให้มุมมองมีประสิทธิภาพมากขึ้น",--AOB has higher performance but lower visual quality. SSAO has higher visual quality.
menu_ao_ssao_high = "SSAO สูง",--SSAO High
menu_ao_aob = "AOB",--AOB
menu_ao_ssao_low = "SSAO ต่ำ",--SSAO Low
menu_parallax = "ทำแผนที่ Parallax",--Parallax mapping
menu_anisotropic = "ความละเอียดของภาพระยะไกล",--ANISOTROPIC FILTERING
menu_corpse_limit = "ตั้งค่าขีดจำกัดของศพ",--Corpse Limit
menu_limit_low = "ต่ำ",--
menu_limit_normal = "ปกติ",--
menu_limit_increased = "สูง",--
menu_limit_high = "สูงขึ้น",--
menu_limit_very_high = "สูงมาก",--
menu_limit_ultra = "สูงสุด",--
menu_limit_unlimited = "ไม่จำกัด",--
menu_toggle_chromatic = "ความคลาดเคลื่อนสี",--
menu_toggle_chromatic_help = "เปิดหรือปิดการป้องกันความคลาดเคลื่อนของสี",--
menu_colorgrading = "โหมดของสี",--
menu_color_off = "ปิดการใช้งาน",--
menu_color_default = "ค่าพื้นฐาน",--
menu_colorgrading_help = "ปรับเปลี่ยนโหมดของสี",--
menu_corpse_limit_help = "ปรับแต่งจำนวนของศพที่ทิ้งไว้ในแผนที่ยิ่งมากเท่าไหร่ยิ่งใช้ทรัพยากรมากขึ้นเท่านั้น",--
menu_parallax_help = "ปิดหรือเปิดการเชื่อมแผนที่แบบ Parallax",--
menu_anisotropic_help = "ปรับการลดรอยหยักการประมานภาพในระยะไกล",--
menu_aa_help = "FXAA ประสิทธิภาพสูงกว่าแต่วิสัยทัศน์ต่ำลง SMAA ประสิทธิภาพต่ำกว่าแต่วิสัยทัศน์สูงกว่า",--
