pln_hb1_20_03 = "ตอนนี้แหละ",--Any second...
pln_hb1_22_03 = "เอาไปรถนั้นออกไปที",--You need to clear that car.
pln_hb1_14_03 = "นั้นแหละเยี่ยม",--It's working. Keep it that way.
pln_hb1_07_02 = "มีตะปูเรือใบบนถนนข้างหน้า จัดการที",--Stingers on the road. Get them out of the way.
pln_hb1_03_01 = "อย่ายิงมาทางรถสิโว้ย",--Draw fire from the truck, gang. 
pln_hb1_15_02 = "แฮคเข้าระบบซะ แล้วอย่าไห้ใครมาขวางหละ",--Reboot the hack. And keep the cops off it!
pln_hb1_03_03 = "ทำยังไงก็ได้ ไห้ตำรวจมันไม่สนใจมาทางรถนี้",--Engage the cops! Make them forget about the truck!
pln_hb1_17_01 = "เรียบร้อย ที่นี้ก็เอาไอที่กั้นนั้นลงซะ",--It's done. Now hit the button, and lower the bollards.
pln_hb1_12_02 = "เร่งมือเข้า ห้องควบคุมมันต้องอยู่ที่ไหนซักที่นี่แหละ",--Keep searching. The control room has to be here.
pln_hb1_20_01 = "พร้อมนะ",--Get ready!
pln_hb1_05_01 = "เวร!! รถตู้สวาทนั้นมันขวางเราอยู่ จัดการซะ",--Damn SWAT van's blocking the route. Move it!
pln_hb1_13_01 = "นั้นแหละ เข้าระบบมันเลย",--That's it. Hack that terminal.
pln_hb1_21_03 = "เอาหละ ลุยเลย",--Now! Drop them!
pln_hb1_26_03 = "เอาหละ เดี๋ยวก็จะได้เจอ Hoxton แล้ว มันหน้าจะอยุ่หลังกำแพงนี้ นี่แหละ",--Hoxton should be with you in a sec, I think he's still a bit shaky from that exploding wall.
pln_hb1_26_05 = "Hoxton มันคงมึนระเบิดเมื่อกี้นี้อยู่ แต่เดี๋ยวก็น่าจะไม่เป็นไร แล้วตามเรามาเอง",--Hoxton seems a bit disoriented - most likely from the explosion - but he'll come around.
pln_hb1_intro_01b = "เฮ้!! ดูนี่ดิ ฉันรวยแล้วโว้ย!!",--Look at this, I'm rich!
pln_hb1_20b_02 = "เราจะซิ่งกันแล้ว เอาเจ้าเหล็ก นี้ออกเร็ว",--Time to move fast, guys. Yank that armor off the truck.
pln_hb1_24_03 = "แย่หน่อย  ตำรวจมันปิดเมืองไว้ทั้งหมดเลย เราจำเป็นต้องไห้รถขับฟ้ามันไปทั้งแบบนี้เลย แต่คงขับไวมากไม่ได้ เพราะฉะนั้นพยายามอยู่ไห้ไกล้ตัวรถเข้าไว้",--Guys, the city is locked down! Cops are defending in depth, and you need to drive through. Loud is the only way. Driver's taking it easy, so stay with the truck!
pln_hb1_23_02 = "ที่นี้ก็ไปบอกคนขับไห้ไปต่อ",--Great! Signal the driver that it's clear.
pln_hb1_18_03 = "ยัดบัตรจอดรถเข้าไปซะ เราจะได้ไปกันซักที",--Put the ticket in the gate. Let's finish this.
pln_hb1_20_02 = "และ...",--And...
pln_hb1_08_02 = "ตัวกั้นถนน.. หาแพงควบคุมเร็ว",--Traffic barriers. Find the power box. Get 'em down.
pln_hb1_04_02 = "มีรถจอดขวางอยู่ จัดการเร็วเข้า",--That's some crappy parking. Get it moved!
pln_hb1_11_02 = "มันต้องมีห้องควบคุมไอตัวนี้อยู่ ลองหาดู ค้นประตูทีละบานเลย!!",--Find the room that controls those bollards. Gotta be here somewhere. Check the doors.
pln_hb1_intro_01c = "ได้เวลา PAYDAY แล้วเพื่อน",--It's PAYDAY fellas!
pln_hb1_07_03 = "นั้นตะปูเรือใบ จัดการมันที",--Cops got stingers across the street. Clear 'em!
pln_hb1_09_03 = "เคลียถนนไห้รถของเราหน่อย",--Clear a path for the truck, clowns.
pln_hb1_26_02 = "ระเบิดเมื้อกี้แรงน่าดู Hoxton มันคงมึนหัวแย่หวะ",--So... Hoxton is taking his good time. I think we might've given him a concussion.
pln_hb1_20b_03 = "ถอดเกราะนี้ออกเลย เดี๋ยวเราจะซิ่งกันแล้ว",--Feel the need for speed, gang. Strip the armor off the truck. 
pln_hb1_09_01 = "มาเร็ว ตามประกบรถไว้",--Come on, gang! Get the truck moving again!
pln_hb1_06_01 = "ถนนพัง หาอะไรมาทำทางข้ามไปหน่อย",--Roadworks! Look around. Gotta be a way to cross it.
pln_hb1_11_03 = "ที่กั้นนี้มันต้องมีตัวควบคุม ห้องควบคุม หรือที่ไหนสักที่ ลองหาดู",--The bollards will be controlled remotely. Security office or something. Find it, and get them down.
pln_hb1_22_01 = "ย้ายเจ้ารถบ้านั้นออกไป เราจะได้ไปต่อกันได้",--Move that car so we can get the hell out of here.
pln_hb1_15_01 = "ตำรวจมันมาตัดการเชื่อมต่อแล้ว จัดการหน่อยเร็ว",--They interrupted the hack! Get it going again.
pln_hb1_14_01 = "เยี่ยม!! ที่นี้ก็อย่าไห้ใครมันมาขวางเราได้อีก",--Great! Now keep the cops away from there.
pln_hb1_25_02 = "พา Hoxton ขึ้นมานี้เร็ว เราไม่ได้มีเวลาทั้งวันนะ ",--Get Hox outta there! Up to the street! Move it!
pln_hb1_24_01 = "ตำรวจมันเล่นปิดเมืองทั้งเมืองเลยหวะ เราคงต้องเล่นตามเกมมันแล้วหละ อยู่ไห้ไกล้ตัวรถเข้าไว้",--Gang, the cops have the city locked down. Fighting through is the only option, so we need you on the ground. That means the truck is going to stay with you. 
pln_hb1_20b_01 = "ต้องพึ่งความเร็วหน่อยแล้ว ถอดเกราะออกจากรถไห้หมด",--Gonna speed things up. Get that plating off the truck!
pln_hb1_04_01 = "เอารถนั้นออกจากทางหน่อย",--Get that car outta the way!
pln_hb1_01_02 = "ถ้าพร้อมแล้ว ก็เคาะรถบอกคนขับเลย",--When you're ready, give the driver the signal.
pln_hb1_13_03 = "นี่แหละ จะช่วยพาเราออกจากที่นี้ แฮคระบบมันเลย",--That terminal will drop the bollards. Hack it.
pln_hb1_23_01 = "ถ้าพร้อมแล้ว ก็บอกไห้คนขับรู้ด้วย เราจะได้ไปกันต่อ",--Alright. Let the driver know you're ready to move.
pln_hb1_03_02 = "กันตำรวจไห้ห่างออกจากรถไว้",--Don't let the cops focus on the truck.
pln_hb1_21_01 = "จัดการยาม เร็ว!!",--Shoot the guards!
pln_hb1_10_02 = "รับตั๋วจอดรถมาเร็ว เราจะได้เข้าไปข้างใน",--Grab that ticket at the machine. It'll open the gate.
pln_hb1_05_02 = "เราไปต่อไม่ได้ ถ้าไม่ย้ายไอรถตู้นี่ออกไป",--The truck isn't moving til you deal with that van.
pln_hb1_06_03 = "อะไรวะ!! ถนนพัง หาอะไรมาทำทางต่อที",--Goddamn roadworks! Find a way to bridge it.
pln_hb1_26_01 = " สงสัย Hoxton มันจะมึนระเบิดเมื่อกี้นี้น่าดูเลยหวะ ไห้มันตั้งตัวหน่อยละกัน",--Uh, guys, I think that Hoxton is a bit disoriented after that explosion earlier.
pln_hb1_02_03 = "คุ้มกันรถไว้ อย่าไห้ตำรวจพังมันซะหละ",--That truck needs to be safe. Draw fire away from it. 
pln_hb1_11_01 = "เราต้องลดที่กั้นนี่ลง หาห้องควบคุม มันต้องอยู่หลังประตูสักบานนี้แหละ",--We need to lower those bollards. Find the control room. Gotta be one of these doors. 
pln_hb1_25_03 = "รถจอดรอเราอยู่ข้างบนแล้ว พา Hox ขึ้นมาเร็ว",--Driver is waiting on the street. Get Hox up there.
pln_hb1_04_03 = "ย้ายเจ้ารถนั้นออกไปที่ มันขวางเราอยู่",--Car's blocking the truck. Move it!
pln_hb1_09_02 = "เคลียถนนหน่อย",--Clear the truck's route, gang!
pln_hb1_22_02 = "เอารถนั้นออกจากถนนที เราจะได้ไปต่อ",--Get that car out of the way.
pln_hb1_19_01 = "7 ดอลล่า !!?? มันไม่ใช้น้อยๆ นะเนี่ย",--Seven bucks!? We were hardly here!
pln_hb1_12_01 = "หาห้องควบคุมไห้เจอ มันต้องอยู่แถวนี้เนี่ยแหละ",--Keep looking for the control room. Must be here somewhere.
pln_hb1_05_03 = "สว่านเจาะไอรถนั้นซะ จะได้ย้ายมันอออกไปสักที",--Drill the van open. Get it outta the way!
pln_hb1_16_01 = "เอาละ ได้เวลายลุยแล้ว",--Now, let it do it's thing!
pln_hb1_08_03 = "มันต้องมีแพงควบคุมอยู่แถวนี้แหละ ลองหาดู",--Gotta be a power box that controls the barriers. Find it!
pln_hb1_25_01 = "พา Hoxton มานี่เร็ว จะได้พามันไปที่ Safe House",--Get Hoxton up to the street. Get him to the safe house!
pln_hb1_21_02 = "เอาหละ",--Safeties off!
pln_hb1_02_02 = "ปกป้องรถไว้",--Truck's moving. Stay with it!
pln_hb1_07_01 = "ตำรวจวางตะปูเรือใบข้างหน้า เอามันออกหน่อย",--Cops threw down road spikes. Clear them away.
pln_hb1_19_02 = "ค่าจอดรถงั้นหรอ ?? ฝันไปเถอะ ฮ่าๆๆ",--How much for parking? That's a robbery! 
pln_hb1_26_04 = "ระเบิดนั้นคงซัด Hoxton ซะมึนแน่หวะ ไห้มันพักฟื้นตัวสักแปปหน่อยละกัน",--That explosion must have shook up Hoxton pretty bad. Just let him walk it off.
pln_hb1_01_01 = "ส่งสัญญาณบอกคนขับด้วย ถ้าพร้อมจะไปต่อแล้ว",--Signal the driver when you're ready to go.
pln_hb1_17_02 = "แฮคเรียบร้อยแล้ว ทีนี้ก็เอาตัวกั้นลงเลย",--Into the system. Now just press the button and drop those bollards!
pln_hb1_14_02 = "โอเค มาลุยกันต่อเลย",--Good. Keep the cops off of it.
pln_hb1_24_02 = "ถนนถูกปิดไว้ทั้งเมือง แต่เป้าหมายเราอยู่แค่สามบล็อคข้างหน้านี้ เราอาจต้องฝ่าดงกระสุนสักหน่อย อยู่ไห้ไกล้รถไว้ แล้วทุกอย่างจะง่ายเอง",--Gang, cops have set up a three block perimeter. The hard way through is the only way, so you're boots on the ground. Stay with the truck, and the truck will stay with you. 
pln_hb1_10_01 = "หยิบตั๋วนั้นมา ประตูมันจะได้เปิดขึ้น",--Collect the ticket. Open the gate.
pln_hb1_02_01 = "เอาหละไปกันต่อเลย ปกป้องรถไว้ด้วย ",--OK, we're moving. Now keep the truck out of danger 'til you're clear.
pln_hb1_01_03 = " คนขับรอสัญญาณจากเราอยู่",--Driver's waiting on your signal, gang.
pln_hb1_06_02 = "ต้องมีอะไรสักอย่าง ที่มาวางแทนสะพานไห้เราเคลื่อนผ่านตรงนี้ไปได้ ลองหาดู",--Must be some way to build across those roadworks.
pln_hb1_08_01 = " ที่กั้นถนน หากล่องควบคุม แล้วตัดไฟมันซะ",--Barriers are up! Crack the power box. That should drop 'em.
pln_hb1_10_03 = "ใครก็ได้ หยิบตั๋วจอดรถที",--One of you clowns take that ticket. Easy!
pln_hb1_12_03 = "ห้องควบคุมต้องอยู่หลังประตูสักบานนี้แหละ",--Control room has to be here somewhere!
pln_hb1_13_02 = "นั้นแหละ ตัวควบคุม เข้าระบบเลย",--There's the control terminal. Hack it!
pln_hb1_15_03 = "ตำรวจรวจเล่นเราแล้ว เชื่อมต่อระบบกลับหน่อยเร็ว",--Cops screwed the hack. Reboot it!
pln_hb1_16_02 = "เอาหละ ลุยต่อได้เลย",--Good. We're in business again.
pln_hb1_16_03 = "โอเค เราเชื่อมต่อกลับได้แล้ว",--Alright, look's like it's working again. Great.
pln_hb1_17_03 = "เข้าระบบเสร็จแล้ว ทีนี้ก็เอาที่กั้นลงจะได้ออกจากที่นี้กันสักที ",--Great! Now, hit that button, drop the bollards and get out of there!
pln_hb1_18_01 = "ทีนี้ก็ใส่ตั๋วเข้าไปในเครื่องนั้น จะได้กลับไปนอนบนเตียงอุ่นๆ กันสักที",--Just put the ticket back in the gate and we're home free!
pln_hb1_18_02 = "ใครถือตั๋วอยู่?? ใส่มันเข้าไปเลย",--Who had that ticket? Get it to the gate.
pln_hb1_brf_01_01 = "The Dentis ช่วยเดินเรื่องการย้ายตัว Hoxton ไห้เราแล้ว เอ่อ... ใช้ฉันหมายถึง Hoxton อีกคน เอาเถอะ มันไม่ใช่เรื่องมาคุยตอนนี้ กาตัดสินมันไม่น่าใช้เวลานาน จากข้อมูลที่เรามี แผนของเราคือ เราจะรอจังหวะชิงตัวคืนตอนขนย้ายตัว หลังจาก  Hoxton ส่งสัญญาณ $NL;$NL; เราจะระเบิดกำแพงทะลุไป ชิงตัว แล้วรีบชิ่งออกมาไห้ไวที่สุด เราคงต้องเจองานยักแน่ๆ รอบนี้ $NL;$NL; เสียงระเบิดคงพาไห้ตำรวจแห่กันมา เตรียมปืนไห้พร้อม กระสุนไห้ครบ เราคงต้องใช้เยอะแน่ๆ",--The Dentist got Hoxton a re-trial. Uh, not you, Hox - I mean Old... Look, we'll sort out names later. The trial will be quick. With his record, he ain't gonna walk, but that's not the point. The point is he's moving, and we can hit him in transit. We're going to grab him right after the hearing. A nice little 'screw you' to the US justice system.$NL;$NL;The plan is as loud as it gets: we blast a wall in the courthouse, grab Hox and get him the hell out.$NL;$NL;Area's locked down for blocks around. They'll be expecting trouble. Have your guns ready and pack a lot of ammo.
pln_hb1_intro_01 = "Houston ชูววววว มาตรงนี้ อย่าส่งเสียงสิ",--Houston, come here. Shh, keep quiet.
dr1_hb1_01_01 = "โอเค ไปกันเลย",--OK, OK! I'm on it!
dr1_hb1_01_02 = "ทำไมชักช้ากันจัง?",--Took you long enough!
dr1_hb1_01_03 = "ไปกันเลย",--Here we go!
dr1_hb1_01_04 = "ได้ยินแล้วๆ",--I heard ya. We're moving!
dr1_hb1_01_05 = "รับทราบ ออกรถเดี๋ยวนี้แหละ",--Gotcha, moving!
dr1_hb1_02_01 = "อะไรวะเนี่ย!!?? ช่วยหน่อยสิ",--What the hell! A little help!?
dr1_hb1_02_02 = "เวรเอ้ย ไปต่อไม่ได้ ย้ายมันออกไปทีสิ",--Goddamnit! Can you guys move that?
dr1_hb1_02_03 = "ไปข้างหน้าต่อไม่ได้แล้ว ทำยังไงกันดี?",--Can't move forward. What do we do?
dr1_hb1_03_01 = "บอกว่าไห้คุ้มกันไงโว้ย มันยิงมาทางนี้กันเต็มไปหมดเห็นบ้างไหม?",--I told you to fucking protect me! I'm getting fired at here!
dr1_hb1_03_02 = "ช่วยจัดการกับตำรวจบ้านี่หน่อยเถอะ",--You gotta fuckin' keep 'em off me, goddamnit!
dr1_hb1_03_03 = "มันยิงมาทางรถแล้ว",--They're shootin' me up over here!
dr1_hb1_04_01 = "เร็วเข้า รีบๆ เปิดมันขึ้น",--Get this shit open!
dr1_hb1_04_02 = "เร็วเข้า รีบๆ เปิดมันขึ้น",--Hey! Get this gate open!
dr1_hb1_04_03 = "เร็วเข้า รีบๆ เปิดมันขึ้น",--Hurry and open the gate!
dr1_hb1_05_01 = "ซวยแล้วไง ที่กั้น เอามันลงเร็วเข้า",--Shit! Bollards are up?! Fix it!
dr1_hb1_05_02 = "เราต้องรีบจัดการกับที่กั้นนี้   เออ !! ฉันหมายถึงเอง เอง และก็เองด้วยโว้ย",--We gotta clear the bollards. I mean you. And by you I mean hey assholes.
dr1_hb1_05_03 = "จัดการไอที่กั้นนี่ที",--Just get these bollards out of my way!
dr1_hb1_06_01 = "พร้อมแล้ว พาขึ้นรถมาเลย",--I'm here! Get him in!
dr1_hb1_06_02 = "ซ่อนตัวตรงหลังรถเลย",--Get him in the back!
dr1_hb1_06_03 = "เร็วเข้า ขึ้นรถมาสักที",--Come on! Get him in!
dr1_hb1_07_01 = "เวรแล้วไง ตำรวจ",--Fucking cops! 
dr1_hb1_07_02 = "ตำรวจอยู่ข้างหน้าเต้มไปหมดเลย",--Cops ahead!
dr1_hb1_07_03 = "โอ้พระเจ้า ตำรวจแห่กันมาจนได้",--Christ, we got cops!
dr1_hb1_08_01 = "เราจะค่อยๆ เคลื่อนตัวไป จับปืนไห้แน่น แล้วอย่าออกห่างรถไห้มากนักหละ",--Gonna keep it slow so you guys with the guns can stay with me. 
dr1_hb1_08_02 = "คุ้มกันกันหน่อย แล้วช่วยเคลียทางไห้มันผ่านไปง่ายๆ ทีเถอะ",--Keeping my foot off the gas. Make sure you guys keep the road safe and clear.
dr1_hb1_08_03 = "เดี๋ยวจะพาไปส่งไห้ถึงที่เอง จัดการตำรวจไปเถอะ",--We'll move at your pace. Just keep the road clear of cops.
rb5_hb2_intro_01_01 = "นั้นแหละประตูทางเข้า ชนประตูเข้าไปเลย!!",--There's the entrance. Don't pussyfoot around, knock that front door down!
rb5_hb2_intro_01_01b = "ชนได้สวย",--Fuckin' nice one.
rb5_hb2_01_01 = "เร็วเข้าพวก เรามีงานต้องทำเยอะ",--Move! Last one in's a nonce!
rb5_hb2_01_02 = "เร็วเข้า รีบขึ้นไปชั้นบน ",--Get inside, lads! Got work to do.
rb5_hb2_01_03 = "เร็วเข้า ตรงขึ้นบรรไดนั้นไปเลย",--Get a shufty on, lads. Chop fucking chop!
rb5_hb2_02_01 = "ที่ห้องปฏิบัติการมีของที่เราต้องการอยู่ ไปหาห้องนั่นไห้เจอ",--We need to find the Operations Room. That's where we'll find the info we need.
rb5_hb2_02_02 = "ที่แรกที่เราต้องไปคือห้องปฏิการ ห้องโถงใหญ่ตรงกลาง ของที่เราต้องการอยู่ที่นั้นแหละ",--First stop is the Operations Room. It's the Feds' nerve centre. Should be able to find what we need there.
rb5_hb2_02_03 = "ของที่เราต้องการอยู่ที่ห้องปฏิการ เร็วเข้า",--Operations is our first stop. From there, we should be able to find what we need.
rb5_hb2_03_01 = "โอเค เข้าถึงเครื่องเซริฟเวอร์ได้แล้ว จัดการเด็ดหัวพวกตำรวจที่เหลือด้วย",--Here! I'm getting to that server. Kill every last fucker ya see!
rb5_hb2_03_02 = "ที่นี่สินะ ฉันต้องการใช้เจ้าเครื่องนั้น เคลียพวกตำรวจนี่ไห้หมด",--This is it. Right, I need to get on those servers. Clear the room!
rb5_hb2_03_03 = "โอเค ที่นี้แหละ ฉันต้องเข้าถึงเซริฟเวอร์ของที่นี้ จัดการพวกพวกตำรวจด้วย",--We're here! I need to get to the server. Drop these feds.
rb5_hb2_04_01 = "โอเค จะเริ่มการเข้าระบบแล้ว คุ้มกันด้วย",--OK, I'm inside. I'll get to work on these servers. Keep me covered!
rb5_hb2_04_02 = "จะเริ่มการแฮคแล้ว อย่าไห้ใครที่ไหนมาขัดตอนฉันกำลังทำงาน เข้าใจไหม",--I'm inside. Keep them fuckers off me while I work. 
rb5_hb2_04_03 = "คุ้มกันด้วย",--Cover me while I work!
rb5_hb2_05_01 = "เวร!! มีปัญหา นิดหน่อย เซริฟเวอร์มีการเข้ารหัสขั้นสูง เราต้องการรหัสที่อยู่ในคอมที่ห้องหน่วยรักษาความปลอดภัย นายต้องไปดาวน์โหลดมันมาไห้ฉัน",--Shite! Small problem - server's heavily encrypted. The encryption keys are kept in the Security Office. You need to grab them and bring them back here!
rb5_hb2_05_02 = "โอ ไห้ตายสิ  เซริฟเวอร์ถูกเข้ารหัสไว้ รหัสน่าจะอยู่ในคอมที่ห้องหน่วยรักษาความปลอดภัย ไปหามันมาแล้วรีบกลับมาไห้ไว",--Ah bollocks. Server's encrypted up the arse. The code keys should in the Security Office. Get over there, grab 'em and get them back here.
rb5_hb2_05_03 = "มีปัญหาเล็กน้อยหวะไอหนู เซริฟเวอร์มีการป้องกัน ต้องการการเข้ารหัส เราต้องใช้หรัสที่อยู่ในคอมที่ห้องหน่วยรักษาความปลอดภัย",--Got a little problem, lads. Server is all bolloxed up with encryption. Take ages to crack, so we need encryption keys. Security office should have some.
rb5_hb2_06_01 = "โธ่โว้ย เข้าไปดูไฟล์ที่บันทึก ไว้ไม่ได้ เราต้องการคำอณุญาติจากคอมพิวเตอร์ของ ผอ. FBI โดยตรง ไปลองดูที่ห้องมันหน่อยว่าเราจะจัดการกันเองได้ไหม",--Shit, can't access the interview files. Need direct approval from the FBI Director himself. Find his office. See if you can fill in for him.
rb5_hb2_06_02 = "โอ เวร!! ไฟล์บันทึกถูกล็อคไว้ จะเปิดดูได้ต้องการคำณุญาติจากคอมพิวเตอร์ของ ผอ. FBI โดยตรง เรื่องมากจริงๆ ว่าไง?? มีใครอยากเล่นบท ผอ. FBI ไหม?",--Ah shite. These interview files are locked. Can only be unlocked with approval from the Director himself. Fuck me, this goes to the top. Any of you guys fancy being king for a day? 
rb5_hb2_06_03 = "โอ ไห้ตายสิมีไฟล์ถูกเข้ารหัสไว้ ต้องการคำอณุญาติโดยตรงจากคอมพิวเตอร์ของ ผอ. FBI โดยตรง ห่าเอ้ย ไม่ว่าใครก็ตามที่ทรยศเรา มันได้รับการคุ้มกันในระดับสูงเลยหวะ",--Ah, bloody hell. Some interview files are locked. Need approval from... Fuck me, the Director himself. Whoever this rat is, he's connected. Get to the Director's office!
rb5_hb2_07_01 = "โอเค เข้ารหัสได้แล้ว กดรับคำขอเลย",--OK, you're in! I've sent a security clearance request. You need to approve it.
rb5_hb2_07_02 = "นั้นแหละพวก ฮ่าๆ รหัสเข้าเครื่องคือ iheartrainbows44 คำขอส่งไปแล้ว กดรับซะ",--You're in. Ha! His password was: iheartrainbows44. The requests are on the way. Approve them!
rb5_hb2_07_03 = "เอาหละพวก คำขอถูกส่งไปแล้ว ที่นี้ก็กดรับจากคอมของ ผอ. FBI ได้เลย",--Alright, you're in. You've got access to the PC of the fucking Director of the fuckin' FB fuckin' I! Approve the request.
rb5_hb2_08_01 = "รอก่อนพวก ขอไห้ฉันหาไฟล์ที่เราต้องการเจอก่อน",--Just keep yer lid on. Let me find all the files you need to sign off on.
rb5_hb2_08_02 = "รอก่อนพวก ฉันต้องการเวลาสักนิด เพื่อหาไฟล์ที่ต้องการก่อนที่จะไม่ต้องใช้คอมนั้นอีก",--Keep yer knickers on, lads. Need to find all the files for ya to sign off.
rb5_hb2_08_03 = "แปปนะพวก กำลังค้นหาไฟล์อยู่。",--Hold on, fellas. Just finding the files for ya.
rb5_hb2_09_01 = "โอเค อีกหนึ่งคำขอถูกส่งไปแล้ว",--OK, another request you need to approve!
rb5_hb2_09_02 = "โอเค ส่งขอคำขอไปไห้แล้ว ไห้ตายสิ อิจฉางานไอหมอนี่จริงๆ ",--Alright, just approve that request. Fuck me, he's got an easy job.
rb5_hb2_09_03 = "ส่งขอคำไปแล้ว อณุมัติซะด้วย",--Another request for you to sign off on.
rb5_hb2_10_01 = "เรียบร้อย ได้ไฟล์ที่ต้องการแล้ว กลับมาที่ห้องนี้แล้วแสดงโชว์ต่อได้เลย",--Great, I've got access to all the restricted files I needed! Get back here and keep this show going!
rb5_hb2_10_02 = "การเชื่อมต่อถูกตัด?? ปัดโธ่เว้ย! มาจัดการหน่อย เร็วเข้า",--Unrestricted access. Fuckin' get in! Now, get back here. Let's keep this going.
rb5_hb2_10_03 = "เฮ้!! สนใจกันหน่อย เรามีงานต้องอีกเยอะนะเว้ย",--We got a bollocks-load of clearance now. Get back here. Still work to do.
rb5_hb2_11_01 = "เอาหละ เราต้องการเอกสารการไห้ปากคำของพยาน มันน่าจะอยู่ที่ห้องเก็บเอกสาร",--OK, missing some files. Witness testimonies, kept in the Archives. Get me those files!
rb5_hb2_11_02 = "เวรเอ้ย มีไฟล์ที่ไม่ได้อยู่ในเซริฟเวอร์ที่ต้องการ คำไห้การของพยาน อยู่ห้องเอกสาร ชั้นไต้ดิน",--Shite. Need a few files not on the servers. Witness testimonies, kept in the Archives. Get down there.
rb5_hb2_11_03 = "โอเค เหมือนไฟล์คำไห้การจากพยานจะหายไป น่าจะมีก็อปปี้ของมันเก็บอยู่ในห้องเอกสาร ไปเอามาหน่อย",--Alright, looks like some witness testimonies were missing. Going to have to hit the hard copies. Get to the Archives and grab 'em.
rb5_hb2_12_01 = "มีปัญหานิดหน่อยหวะ เหมือนจะมีเครื่องเซริฟเวอร์หายไปเครึ่องหนึ่ง ในนี้แจ้งว่ามันถูกส่งไปซ้อมที่แผนก IT ไปเอามันมาที",--A little hickup; there's a server missing in here. Log says it was taken to the IT Department for maintenance. We need that server, so you'll have to retrieve it.
rb5_hb2_12_02 = "นี่ล้อกันเล่นใช่ไหมวะ !!?? เครื่องเซริฟเวอร์หายไปเครื่องนึง บันทึกบอกว่ามันถูกส่งไปซ่อมที่แผนก IT เราต้องใช้มัน!!  จัดการหน่อย",--Are you fuckin' havin' a laugh? There's a server missing. The log says it was taken to IT for maintenance. We need that server.
rb5_hb2_12_03 = "โอ ไห้ตายสิ ไปที่แผนก IT ที่นั้นมีเครื่องเซริฟเวอร์ที่ถูกส่งไปซ่อมอยู่ เอามันมา ข้อมูลที่เราต้องการอยู่ในนั้น",--Ah, come on! We're missing a server. According to the log, it was taken to IT. Get over there, and grab it.
rb5_hb2_13_01 = "ข้อมูลบอกว่า เราต้องหลักฐานทางนิติเวชของไอคนทรยศ ในห้องแลป ลองหาดู",--The case files here say that there's some forensic evidence linked to the traitor. Head to the labs and get a closer look.
rb5_hb2_13_02 = "น่าสนใจ ข้อมุลพวกนี้บอกเราว่าที่แลปนิติเวชมีข้อมูลที่สักทอดถึงไอคนทรยศที่เราต้องการตัวอยู่ ลองไปหาดู",--Interesting. Files on this server are pointin' to some evidence being held by forensics. Let's check it out.
rb5_hb2_13_03 = "นี่ล้อกันเล่นแน่ๆ ข้อมูลนี้มันเชื่อมต่อไปถึงข้อมูลเกี่ยวกับหลักฐานจากแลปนิติเวช เราต้องการมัน ไปเอามันมา",--Well, bugger me - files here are linking to some physical evidence down in the labs. Get down there, check it out!
rb5_hb2_14_01 = "โอเค เราได้ทุกอย่างที่ต้องการมาแล้ว เอาเครื่องเซริฟเวอร์นั้นมา แล้วออกจากที่นี้กัน",--OK, I've copied all the information I found to this server. Grab the server and let's get out of here.
rb5_hb2_14_02 = "เสร็จสักที!! ก็อปปี้ข้อมูลที่ต้องการทุกอย่างไว้ได้แล้ว ในเครื่องเซริฟเวอร์นี้.....  เอามันไปที่รถ",--Right. Fuck it. I gathered all the intel we need to one of the servers. Someone grab it and let's leg it.
rb5_hb2_14_03 = "นี่น่าจะเป็นทั้งหมดที่เราต้องการแล้ว เอาหละ เอาเจ้าเครื่องเซริฟเวอร์นี้ไป จะได้รู้สักทีว่าใครคือคนทรยศ",--That's as much as we can do here. I saved all the intel on this server. Grab it and let's get out and see if we can make sense of this. 
rb5_hb2_15_01 = "ไห้ตายสิพวก !!! ไฟฟ้า ชั้นต้องใช่มันไม่รู้เหรอ ??",--Come on, you wankers. Get that power up again.
rb5_hb2_15_02 = "ปัดโธ่เว้ย !! ไอพวกลูกหมา ไฟฟ้าโว้ย! ไฟฟ้า",--For fucks' sake! Lads! The power!
rb5_hb2_15_03 = "ไห้ตายสิ! ไอเครื่องนี้มันไม่ทำงานถ้าไม่มีไฟฟ้าหรอกนะ เข้าใจไหม!!??",--Gang, I can't do what I need to do without power. Fuckin' fix it!
rb5_hb2_16_01 = "ไฟกลับมาแล้ว แต่ต้องรีบูทระบบซะก่อน",--Power's back on, but I gotta reboot things here. Hold your horses.
rb5_hb2_16_02 = "โอเค เชื่อมต่อกลับมาแล้ว แต่ต้องรีบูทระบบก่อน",--Got power again, fellas. Need a sec to reboot this.
rb5_hb2_16_03 = "เอาหละ ไฟฟ้ามา ทำงานต่อได้แล้ว ",--Alright, we're working again. Just hold on.
rb5_hb2_17_01 = "โอเคเรียบร้อย แต่ช่วยอย่าไห้มันเกิดขึ้นอีก!!!",--Alright, I'm back up but keep that fucking power on.
rb5_hb2_17_02 = "ไฟกลับมาแล้ว อย่าไห้ตำรวจมันตัดไฟอีก!!",--Back to work. Keep 'em off it from now on.
rb5_hb2_17_03 = "เยี่ยม ไฟฟ้ากลับมาแล้ว แล้วอย่าไห้ใครไปเลื่อนสวิทชอีก เข้าใจไหม?",--Nice. But try and keep those tossers off the power, yeah?
rb5_hb2_18_01 = "โอเค เจอไฟล์ที่ต้องการแล้ว ขอดูก่อน",--OK, I found my case file, I'm digging through it.
rb5_hb2_18_02 = "เจอแล้ว !! ไหนขอดูหน่อยสิว่ามีอะไรบ้าง",--Got my file. Let's see what they have on me.
rb5_hb2_18_03 = "เข้าถึงไฟล์ได้แล้ว ไหนดูหน่อยสิว่าซ้อนอะไรไว้",--I'm into my file. Let's see what these twats have got.
rb5_hb2_19_01 = "เยี่ยม!! นี้มันพวกข้อมูลความลับสูงสุดทั้งนั้น กะไว้แล้วเชียว",--Fuck me, there's a reference to a "classified informant" here. I fucking knew it.  I'll keep digging.
rb5_hb2_19_02 = "เดี๋ยวก่อนนะ ?? ไฟล์พวกนี้มันไฟล์ความลับสูงสุดนี่หว่า กะไว้แล้วเชียว ต้องขอดูซะหน่อย ",--What's this? There's mention of a "classified informant" here, fucking knew it!
rb5_hb2_19_03 = "ดุนี่สิ ในไฟล์ความลับสูงสุดพวกนี้ กะไว้แล้วเชียว ไอพวกหนูสกปรกเอ้ย ",--Let's see. There! "Classified informant"! I knew I smelled a rat.
rb5_hb2_20_01 = "นี่มันไม่ใช้คดีระดับทั่วไปแล้ว ข้อมูลถูกจำกัดไว้หมด นี่กูสำคัญขนาดนั้นเลยหรอวะ!?? ",--This isn't an average case. Lots of information restricted. I'm not this important, am I?
rb5_hb2_20_02 = "นี่มันถูกยกระดับเป้นกรณีพิเศษเลย นี่ชั้นเป็นคนพิเศษขนาดนั้นเลยหรอ ?? แล้วทำไมถึงสำคัญขนาดนั้น",--This case is special. Why am I special? Who's leaking this stuff?
rb5_hb2_20_03 = "ไห้ตายสิ ไม่ว่าไอหนูสกปรกนั้นมันจะเป็นใคร  มันคือใครสักคนที่เราต้องรู้จักแน่ๆ",--Fuck, this is thorough. Whoever is ratting us out... They're close.
rb5_hb2_21_01 = "โว้ว พวก ข้อมูลพวกนนี้มันมากกว่าแค่กูแล้วหวะ มันโยงถึงพวกเอ็งด้วย ถ้าทางไอคนทรยศมันจะต้องรู้จักเราดีแน่ๆ",--Man, this case goes a lot further than just me. There's references to all you guys in here. No names though. Guess our rat is sitting on those.
rb5_hb2_21_02 = "อะไรวะ !! นี่มันข้อมูลทุกอย่างเลย !! ทุกการปล้น ว่าจ้าง โยงถึงเราทุกๆ คน ไอหนูสกปรกนี่มันต้องเป็นใครสักคนที่เราทำงานด้วยแน่ๆ",--They've got everything. Every heist, every job. References to you guys too. But no names - guess the traitor is holding onto those.
rb5_hb2_21_03 = "ไห้ตายสิ ไฟล์นี่มันใหญ่เป็นบ้า ข้อมูลทุกๆ อย่าง การปล้น แผน ว่าจ้างฆ่า มันมีทุกอย่างของเราหมดเลย เราทุกคน ไอคนทรยศนี่ เราต้องเคยเจอมันแน่ๆ",--What the fuck. This file is huge. They know everything about me. And there are references to you too! No names - maybe the informant is holding out for a better price, the fuck.
rb5_hb2_22_01 = "ไกล้จะเรียบร้อยแล้ว มันต้องมีอะไรไห้เราขุดคุ้ยอีกเยอะแน่ที่เซฟเฮาส์ แต่เราต้องเอามันไปทั้งหมดนี่แหละ แล้วจัดการไห้เรียบร้อย ก่อนที่จะไม่ทันได้ลากคอไอคนทรยศ",--I'm almost done here. There's gonna be a lot of information to dig through back at the safe house, but we're gonna find that fucking informant, and nail the twat before he rats you all out.
rb5_hb2_22_02 = "เอาหละ เดี๋ยวจะพร้อมไปจากที่นี้แล้ว ข้อมูลไม่ใช้น้อยๆ แต่เราต้องรีบจัดการหามัน ก่อนที่จะสายเกินกว่าจะได้ล่าไอคนทรยศ",--Alright, I'm wrapping up in here, almost done. There'll be lots of info to sort through. But we're going to find that arsehole. Silence him before he squeals.
rb5_hb2_22_03 = "ทำอะไรต่อที่นี้ไม่ได้แล้ว แต่ได้ข้อมกููลทั้งหมดไว้แล้ว เดี๋ยวค่อยไปจัดการต่อที่เซฟเฮาส์ แล้วเมื่อเรารู้ว่าใครที่ทรยศพวกเรา มันต้องไม่ตายดี  ",--Can't do much more in here, I've almost gone through all the intel. We're gonna have to piece this all together back at the safe house. When we nail that traitor, the bastard is goin' to die.
rb5_hb2_23_01 = "เดี๋ยวจะหลบอยู่ที่นี่ก่อน รอพวกเอ็งกลับมา",--I'll keep schtum in here til you're back.
rb5_hb2_23_02 = "จะพยามเนียนอยู่แถวนี้แหละ ไม่ต้องห่วง",--Gonna keep a low profile in here.
rb5_hb2_23_03 = "กุจะพยายามเงียบ ไห้มากที่สุดละกัน เร็วๆ เข้า",--I'll be quiet as a church mouse til you're back.
rb5_hb2_24_01 = "ได้หละ !! คุ้มกันด้วย",--Back to work, keep me covered.
rb5_hb2_24_02 = "จะสานงานต่อแล้ว คุ้มกันด้วย!",--I'll get to work. Cover me!
pln_hb2_01_01 = "ที่นี้ก็เอาข้อมูลกลับไปไห้ Hoxton เราจะได้เริ่มงานกันต่อสักที",--Now bring the encryption keys back to Hoxton so he can get to work on the next server.
pln_hb2_01_02 = "เยี่ยม ที่นี้ก็เอามันไไห้ Hoxton",--Good. Now get those keys back to Hox.
pln_hb2_01_03 = "เยี่ยม ที่นี้ก็เอามันไปไห้ Hox ข้อมูลนี้จะช่วยไห้เรารู้ว่าใคร คือคนที่ทรยศ",--Great. Now get the keys to Hox. Decrypting the servers will help pinpoint the traitor.
pln_hb2_02_01 = "คำไห้ปากคำ น่าจะมีบันทึกอยู่ในห้องเอกสาร ลองหาดู แล้วเอามันมา",--The testimonies are somewhere in the Archives. Search through their records and see if you can't find them.
pln_hb2_02_02 = "Hox ต้องการเอกคำไห้ปากคำ อยู่ห้องข้างล่าง ลองหาดู",--The testimonies Hox needs are down here somewhere. Search the records.
pln_hb2_02_03 = "เอกสารคำไห้ปากคำ!! หามันไห้เจอ ฉันต้องการมัน",--Get looking through the records. Find those testimonies.
pln_hb2_03_01 = "นั้นแหละที่เราต้องการ เอามันกลับไปไห้ Hox!",--Right, that's the files. Get them back to Hoxton!
pln_hb2_03_02 = "นั้นแหละที่เราต้องการ เอามันกลับไปไห้ Hox!",--That's them! Now, get them back to Hoxton.
pln_hb2_03_03 = "นั้นแหละพวก ที่นี้เอามันกลับไปที่ห้องปฏิบัติการ",--You got 'em! Now get back to Operations!
pln_hb2_04_01 = "โอเค เครื่องเซริฟเวอร์ต้องอยู่ไห้ห้องพวกนี้สักห้องแหละ ลองหาดู ",--OK, the server is in one of the offices in the IT Department. Figure out where it is and grab it!
pln_hb2_04_02 = "เครื่องเซริฟเวอร์ที่ส่งซ้อม น่าจะยังอยู่ที่โต๊ะทำงานของพวกแผนก IT สักคน ลองหาดู",--The missing server is probably lying on the desk of some IT monkey. Get down there and find it.
pln_hb2_04_03 = "แผนก IT อยู่ตรงนั้น มองหาเครื่องเซริฟเวอร์  แล้วเอามันกลับมา",--IT are nearby. Get over there, find the server and haul it back.
pln_hb2_05_01 = "เยี่ยม ที่นี้ก็เอากลับไปไห้ Hoxton!",--Good, now get it back to Hoxton!
pln_hb2_05_02 = "เยี่ยม ที่นี้ก็เอามันกลับไปที่ห้องปฏิบัติการ。",--Great. Now haul it back up to the Operations Room.
pln_hb2_05_03 = "เยี่ยม ที่นี้ก็เอากลับไปไห้ Hoxton!",--That's it. Great! Now return it to Hoxton.
pln_hb2_06_01 = "คุ้มกันคนที่หิ้วเซริฟเวอรืไว้ด้วย มันหนักเอาเรื่อง ระวังตำรวจที่มาสกัดเราด้วย",--Escort whoever is carrying that server. It's gonna be heavy, and I think the cops will try to liberate it from you.
pln_hb2_06_02 = "คอยคุ้มกันคนที่แบกเครื่องเซริฟเวอร์ไว้ด้วย เอาไห้มั่นใจ ว่าเราจะเอามันกลับไปได้",--Keep an eye on whichever of you is carrying the server. Make sure they get back safe.
pln_hb2_06_03 = "อย่าปล่อยคนที่แบกเครื่องเซริฟเวอร์ไว้ข้างหลัง มันหนักมาก เดี๋ยวจะโดนเล่นงานเอาง่ายๆ",--Stay with whoever is carrying the server. It's heavy. Don't leave them behind!
pln_hb2_07_01 = "เข้าไปในห้องเก็ยหลักฐาน หาไฟล์ที่เราต้องการ แล้วเอามันกลับไปหา Hoxton",--Get inside the evidence room and find evidence related to Hoxton's case.
pln_hb2_07_02 = "ไฟล์หลักฐานที่เราต้องการ อยู่หลังประตูนี้นี่แหละ ลองค้นดู มันน่าจะมีอะไรที่พอบอกได้ว่าเป็นไฟล์ไหน",--The evidence that Hoxton spoke of will be in that lock-up. Look for it. It should be marked out.
pln_hb2_07_03 = "ไฟล์ที่เราต้องการ อยู่ในห้องเก็บหลักฐาน ลองหาดู แล้วเอามันไปไห้ Hoxton",--You should find evidence related to Hoxton's case in the Evidence Room. Get searching.
pln_hb2_08_01 = "เราต้องการไฟล์หลักฐานที่โยงไปคดีการจับตัว Hoxton ลองค้นดู มันน่าจะเก็บไว้ในห้องนั้นนั่นแหละ",--You are looking for evidence related to the Hoxton's case. Take a look around. It will be stored throughout the room. Could be marked out.
pln_hb2_08_02 = "หลักฐานที่เราต้องการ น่าจะอยู่ที่นี้แหละ หามันไห้เจอ",--The evidence will be here somewhere. Search for it. 
pln_hb2_08_03 = "ไห้ตายสิ มันได้เรียงเป็นระเบียบบ้างไหมเนี่ย หาไฟล์ที่เชื่องโยงกับคดีของ Hoxton แล้วเอามันมา",--Christ, don't they organise this stuff. Search through it. Find that evidence. You're looking for evidence that's related to Hoxton.
pln_hb2_09_01 = "ดี เหมือนเราจะเจอไฟล์แล้ว ลองตรวจผลในแล็ป แล้วดูสิ ว่ามันจะพาเราไปเจอคนทรยศไหม",--Great, you found some evidence! Analyze it in the lab. Let's see if there's any trace of the traitor's DNA on it.
pln_hb2_09_02 = "เอามันไปตรวจผลดู ว่ามันจะบอกอะไรเกี่ยวกับคนทรยศนั้นบ้าง มันจะได้ช่วยไห้เราชี้ตัวเจ้าหนุูนี่ได้สักที",--Now take the evidence to the lab. If we can find some DNA that belongs to the traitor, we might be able to pinpoint who he is.
pln_hb2_09_03 = "เยี่ยม ที่นี้ก็เอามันตรวจผล DNA พวกนี้จะช่วยหาคนทรยศไห้เรา",--Nice. Now get that evidence to the lab. Any DNA might help us finger this rat.
pln_hb2_10_01 = "โอเค ตัวอย่าง DNA ของคนทรยศนี้ถูกปิดเป็นความลับอยู่ ไม่ต้องเสียเวลาแล้ว กลับไปหา Hoxton เลย",--OK, the traitor's identity is classified. Not a complete waste though - we got a sample of his DNA! Good work. Now, get back to Hoxton.
pln_hb2_10_02 = "ไห้ตายสิ มันไม่ถูกอนุญาติไห้เข้าดูข้อมูล แต่เราก็ได้มันมาแล้ว DNA ที่จะชี้ตัวคนทรยศ มันน่าจช่วยเราได้ในวันหลัง ตอนนี้กลับไปหา Hoxton ก่อน",--Damn, their system didn't allow us to see who the DNA belongs to. Still, we have a sample of the traitor's DNA, I'm sure we can put it to good use. Now get back to Hoxton.
pln_hb2_10_03 = "ชื่อของเจ้าของ DNA นีถูกปิดไว้ แต่เราได้มันมาแล้ว ไม่เป็นไร ตอนนี้กลับไปหา Hoxton ก่อน",--Couldn't get a positive ID on who the DNA belongs to, but we got a sample, so that will help. Now, get back to Hoxton.
pln_hb2_11_01 = "ไม่ตรงกับที่เราต้องการ ลองอันอื่นดู",--No luck! No DNA match found on the evidence. Keep looking and scanning!
pln_hb2_11_02 = "เวรเอ้ย! มันไม่ตรงกับที่เรามองหา ลองอันต่อไปดู",--Damn. No match. Keep looking!
pln_hb2_11_03 = "ไห้ตายสิ ผลออกมาว่างเปล่า ลองหาอันอื่นดู",--Ah crap... Came up blank. Keep searching and keep scanning.
pln_hb2_12_01 = "คุ้มกัน Hoxton ไว้ ระหว่างที่กำลังเจาะเข้าระบบ",--Keep defending Hoxton! If things are getting hairy, use cards to override the security barriers.
pln_hb2_12_02 = "คุ้มกัน Hoxton ไว้ก่อน ถ้ามีคีย์การ์ด ใช้มันปิดประตูเลย มันจะช่วยไห้เราทำงานง่ายขึ้น",--Defend Hoxton. If you have cards, you can seal off the entrances.
pln_hb2_12_03 = "ถ้ามีคีย์การ์ด เอามันไปเลื่อนประตูลงได้ น่าจะยื้อพวกตำรวจได้บ้าง",--If you have cards, you can close the barriers. That oughta hold 'em off Hoxton for a while. 
pln_hb2_13_01 = "ที่นี้นี้มีห้องอุปกรณ์ที่จะช่วยเราได้อยู่ แต่มันถูกล้อคไว้หมดเลย แต่คีย์การ์ดน่าจใช้ะเปิดมันได้ แต่ใช้ระวังหน่อย มันคงไม่ได้หาได้ง่ายๆ แน่",--This place is locked down tight, but you can use keycards to gain access to different areas. Choose wisely - you probably won't find a lot of 'em.
pln_hb2_13_02 = "ที่นี้คียืการ์ดก็เหมือนทองนั้นแหละ ปิดประตูป้องกัน เปิดห้อง ช่วยไห้อะไรมันง่ายขึ้น เลือกใช้ไห้ดีหละ",--Keycards are gold here. You can use 'em to open up areas, close areas down. Use them carefully!
pln_hb2_13_03 = "คียืการ์ดจะช่วยเราได้มาก ลองหามันดู แล้วใช้ระวังหน่อยหละ",--Keycards can be a great asset. Find 'em, but use 'em carefully. 
pln_hb2_14_01 = "คลังอาวุธนี้ถูกล็อคไว้ แต่ใช้คีย์การ์ดเปิดออกได้ น่าจะกระสุนกับระเบิด พอสำหรับงานนี้แน่",--An Armory! It's locked down, but a keycard should get you inside. Should be plenty of ammo in there.
pln_hb2_14_02 = "คลังอาวุธมันถูกปิดล้อคไว้ แต่คีย์การ์ดน่าจะใช้เปิดได้",--The Armory! Safely locked up, but spend a keycard and it should open up.
pln_hb2_14_03 = "คีย์การ์ดใช้เปิดคลังอาวุธนี้ได้ มั่นใจได้เลยว่าต้องมีกระสุนกองเท่าภุเขาอยู่แน่ๆ",--A keycard will get you into the Armory. Sure there must be plenty of ammo inside.
pln_hb2_15_01 = "ถ้ามีปัญหาเรื่องจำนวนอุปกรณ์พยาบาล ใช้คีย์การ์ดเปิดห้องพยาบาลนี่เลย",--If you're low on Doctor Bags, you should consider getting that Infirmary open.
pln_hb2_15_02 = "ถ้ามีปัญหาเรื่องจำนวนอุปกรณ์พยาบาล ใช้คีย์การ์ดเปิดห้องพยาบาลนี่เลย",--If you're feeling rough, maybe spend a keycard and crack the Infirmary open.
pln_hb2_15_03 = "คีย์การ์ดใช้เปิดห้องพยาบาลได้ ถ้าเกิดต้องการอุปกรณ์ประถมพยาบาลหละก็",--Spend a keycard to access the Infirmary, if you feel like you need a pick-me-up. 
pln_hb2_16_01 = "ตูม !!! หมดห่วงไปอีกหนึ่งทาง",--Bam! That's one less flank to worry about.
pln_hb2_16_02 = "โอเค ที่นี้ตำรวจก็ไม่น่ามาจากทางนั้นได้แล้ว",--They're not getting in that way!
pln_hb2_16_03 = "และ... ตูม แค่นี้ก็ไม่มีใครข้ามมาได้แล้ว",--And boom! They're not using that skywalk.
pln_hb2_17_01 = "ดีมาก ปิดทางเข้าสักทาง น่าจะช่วยไห้เรารับมือได้ง่ายขึ้น",--Good job. You sealed off one of the entrances. That should make it easier to defend.
pln_hb2_17_02 = "เยี่ยม แค่นี้พวกตำรวจก็เข้ามาทางนั้นไม่ได้แล้ว",--Nice. That cuts their options. Exploit that.
pln_hb2_17_03 = "ปิดทางไว้ ตำรวจจะได้ไม่แห่กันเข้ามา",--They ain't getting through this way!
pln_hb2_18_01 = "แก็สน้ำตา !! ระวัง ถอยก่อน รอไห้มันหายไปก่อน",--Gas, watch out! Wait for it to dissipate!
pln_hb2_18_02 = "พวกมันปล่อยแก็สน่ำตาออกมาแล้ว ถอยออกจากห้องก่อน รอไห้มันหายไปก่อน",--They're deploying gas! Get out of the room and wait for it clear.
pln_hb2_18_03 = "แก็สน้ำตา!! หาที่หลบก่อน รอไห้มันหมดไปก่อน",--Tear gas incoming! Stay clear and wait for it to die down.
pln_hb2_19_01 = "เอาหละพวก ตำรวจมันจะต้องพยามทุกอย่างเพื่อขัดขวางเรา ฝ่าออกไปไห้ได้",--Guys, they're throwing everything they have at you. Better make it out, fast!
pln_hb2_19_02 = "FBI มันต้องทำทุกอย่างเพื่อไห้เราหนีออกไปไม่ได้แน่ๆ  เร็วเข้า!!!",--The feds'll do everything they can to stop you from leaving. Get out of there - hurry!
pln_hb2_19_03 = "พวกตำรวจมันคงไม่ยอมปล่อยพวกเราไปแน่ๆ การบุกครั้งสุดท้ายเริ่มขึ้นแล้ว อย่าไห้มันมาขวางเราได้",--Cops are getting desperate, they're launching a final assault! Don't let them stop you.
dr1_hb2_01_01 = "รถเราพังแล้ว เดี๋ยวจะหาคันใหม่ไห้",--Truck's totalled. I'll find us another ride.
dr1_hb2_01_02 = "รถเจ๊งไปซะแล้ว เดี๋ยวขอหาคันใหม่ไห้ก่อน",--That's it for the truck. I'll find more wheels.
dr1_hb2_01_03 = "รถวิ่งต่อไม่ได้แล้ว เดี๋ยวจะลองหาคันใหม่ก่อน",--Truck's fucked. I'll secure a ride out.
dr1_hb2_02_01 = "เรียบร้อยกันหรือยังพวก ข้างล่างนี้ ลงมาเลย!! เตรียมรถรอไว้แล้ว",--You guys all finished? Get down here. Got us a sweet ride!
dr1_hb2_02_02 = "นี้ทำะไรกันอยู่บนนั้นวะนั่น?? เอาเถอะรู้น้อยไว้ดีกว่า เร็วเข้า รถพร้อมจะออกแล้ว",--What were you guys doing up there?! Nevermind. The less I know. Just get down here.
dr1_hb2_02_03 = "ตำรวจคงรอเราอยู่เต็มเมืองแน่ๆ แต่หารถไว้ไห้แล้วไม่ต้องห่วง",--Streets are calling with cops, but I got us a sweet ride. Just get down here!
dr1_hb2_03_01 = "รถสวยใช่ไหมหละ ขึ้นมาเลย!!",--How you like these wheels? Hop in!
dr1_hb2_03_02 = "ขึ้นมาเลย เราต้องไปกันแล้ว",--Get in. We should coast home in this!
dr1_hb2_03_03 = "จะไม่มีใครสงใสเรา ถ้าไปด้วยรถคันนี้แน่ ขึ้นมาเลย!",--No-one will look twice at us in this ride. Get in!