pln_branchbank_random_stage1_intro_a_01 = "เอาหละพวก ฉันมีข้อมูลทั้งหมดเกี่ยวกับธนาคารนี้ที่เราต้องรู้แล้ว เพราะฉะนั้นเตรียมสว่านไห้พร้อม ฉันเตรียมมันไว้ไห้ที่ลานจอดรถแล้ว บุกเข้าไปไห้ห้องเซฟ เอาทุกอย่างที่พวกนนายต้องการออกมาไห้หมด  อ่อ แล้วระวังด้วยหละ ที่นี่มีระบบความปลอยภัยที่ดีใช่ได้เลย",--OK, this is the bank. I advise casing the place, then grab the thermal drill from the back parking lot somewhere. Hit the vault however you want. There's usually a security room so be cautious. 
pln_branchbank_random_stage1_intro_a_02 = "ถึงเวาลหารายได้แล้วพวก สว่านรอพวกนายอยู่ที่ลานจอดรถแล้ว เลือกวิธีการเองได้เลย แต่ระวังกับพวกประชาชนไว้หน่อย เดี๋ยวมันอาจจะหางานมาไห้ได้ ไว้เจอกันที่เซฟเฮาส์",--Robbery time. Get the thermal drill stashed in the parking lot. Then it's up to you. I don't know what we're gonna get here but remember: keep the civilians in check, don't let 'em use alarms or phones. See you at the safe house.
pln_branchbank_random_stage1_intro_a_03 = "รู้ใช่ไหมว่าต้องจัดการกันยังไง ฉันไห้คนไปเตรียมสว่านไว้ไห้แล้ว แถวๆ ลานจอดรถ อย่าลืมหิ้วมันเข้าไปด้วยหละ แล้วก็ระวังพวกตัวดีจะตามตำรวจมาไห้หละ ",--Everyone, you know how it's done. My guy dropped the thermal drill in the parking lot, so grab that before you make your move inside. Some surveillance would be smart.
pln_branchbank_cash_stage1_intro_a_01 = "ฉันเตรียมสว่านสำหรับเจาะห้องเก้บเงินไว้ไห้แล้วที่ลานจอดรถ ระวังพวกพนักงานกับกล้องวงจรปิดไห้ดี วางแผนไห้ดีก่อนจะเริ่มงาน แล้วจำไว้หละ เงินเท่านั้นที่เราต้องการ",--OK, the thermal drill you need for the vault is somewhere in the parking lot. Get it before you do your takedown. Then you can go hit that vault. Watch for cameras and bank employees. Do your homework before you go in and remember cash is king.
pln_branchbank_cash_stage1_intro_a_02 = "เอาหละพวก ฉันไห้คนเตรียมสว่านไว้ที่ลานจอดรถแล้ว ไปเอามันมาไว้ก่อนเลย ระวังพวกยามกับกล้องไห้ดี มีกล้องก็ต้องมีห้องกล้องไห้จัดการ ปล้นไห้สนุกหละ ",--OK folks, my guy stashed the thermal drill for the bank vault in the parking lot, so get that first. Watch for guards, keep an eye out for cameras - where there's cameras there's usually a security room... Money time.
pln_branchbank_depositbox_stage1_intro_a_01 = "เอาหละ ฉันอยากไห้งานนี้มันมาดี และไว อย่างแรกสวน่ารออยู่ที่ลานจอดรถ หาตำแหน่งทางเข้าเซฟ ขนเงินออกมาไห้หมด แล้วระวังพวกยามตัวดีไว้ด้วย",--OK guys I want this to be a homerun. First get the thermal drill from the parking lot. Then head in to hit the vault. Watch for guards and cameras. 
pln_branchbank_depositbox_stage1_intro_a_02 = "มีคนจัดเตรียมสว่านรอพวกนายแล้วที่ลานจอดรถ เอาไว้สำหรับเจาะประตูเซฟ ไปเอามันมา แล้วพาเงินกลับบ้านกันเลย",--OK people, my contact thoughtfully stashed the thermal drill you're going to need to crack the bank vault somewhere in the parking lot. Get it, then hit the bank vault.
pln_branchbank_gold_stage1_intro_a_01 = "ธนาคารนี้แหละพวก ฉันไห้คนเตรียมสว่านรอไว้ไห้แล้ว อยู่แถวๆ ลานจอดด้านหลัง ไปเอามันมา เจาะเซฟซะ ทองรอเราอยู่",--Recon the bank. My guy dropped a thermal drill somewhere on the premises, around the back of the bank, find it. Then get in there and do your thing to the vault. Gold awaits.
pln_branchbank_gold_stage1_intro_a_02 = "เอาหละพวก ฉันไห้คนเตรียมสว่านสำหรับเจาะเซฟรอเราไว้แล้ว ที่ลานจอดรถหลังธนาคาร เริ่มกันได้เลยเมื่อพร้อม รับรองงานนี้คุ้มแน่",--OK folks, my inside man stashed the thermal drill you're gonna need for the vault around the back. recon the spot to find it. Make your move on the vault when you're ready. This job, It's gonna be golden.
pln_branchbank_gold_stage1_intro_a_03 = "พวกนายต้องการสว่านสำหรับเจาะเซฟ ซึ้งฉันเตรียมรอไว้ไห้แล้ว ที่ลานจอดรถหลังธนาคาร ระวังยาม กล้อง ไห้ดี ประชาชนก็ด้วย ปล้นทองไห้สนุกนะพวก",--OK, You're gonna need a thermal drill for this gig. My guy stashed it around the back of the bank. Get it and get to work on the vault.  Keep in mind there's security cameras and lots of civilians. Go win the gold, folks.
pln_branchbank_stage1_01_any_01 = "สว่านอยู่ที่ลานจอดรถหลังธนาคาร ลองหาดู",--Recon the bank. My guy dropped a thermal lance somewhere on the premises... Around the back of the bank, find it.
pln_branchbank_stage1_01_any_02 = "พวก ฉันไห้คนเตรียมสว่านรอไว้แล้ว ที่ด้านหลังของธนาคาร",--OK folks, my inside man stashed the thermal lance you're gonna need for the vault around the back. Recon the spot to find it.
pln_branchbank_stage1_01_any_03 = "สว่านอยู่ที่ลานจอดรถหลังธนาคาร ลองหาดู จะได้เริ่มงานกันสักที",--OK... You're gonna need a thermal drill for this gig... My guy stashed it around the back of the bank. Get it and get to work.
pln_branchbank_stage1_02_any_01 = "นั้นแหละห้องเซฟ จัดการกันเลย",--OK, the vault's got the gold. 
pln_branchbank_stage1_03_any_01 = "อย่าลืมหละ เรามาเพื่อจัดการกับกล่องฝากของ",--Alright, we're in for deposit boxes.
pln_branchbank_stage1_04_any_01 = "รู้กันอยูใช่ไหม ว่าเราต้องการยังไงกับเงินพวกนน้",--It's a straight cash hit. You know how this goes.
pln_branchbank_stage1_05_any_01 = "ฉันชอบธนาคารจริงๆ กลิ่นมันเหมือนเงินเลยว่าไหม",--I love banks. The smell of all that money.
pln_branchbank_stage1_05_any_02 = "ใครเขาอยากปล้นธนคารเล็กๆ กันหละ",--Who wants to do a little banking?
pln_branchbank_stage1_05_any_03 = "เอาหละ ได้เวลาถอนเงินกันแล้ว",--Everyone get ready to make a little withdrawal now.
pln_branchbank_stage1_06_any_01 = "เซฟเปิดแล้ว แพคของเลยพวก",--It's open! Bag the money!
pln_branchbank_stage1_07_any_01 = "กล่องฝากของพวกนั้น น่าจะมีของดีอยู่ไม่น้อย",--You might wanna look through some of the deposit boxes, could be something valuable.
pln_branchbank_stage1_08_any_01 = "เอากระเป๋าไปไว้ที่รถตู้เลย จอดรอตรงหัวมุมแล้ว",--Alright, bring it to the van, it's right around the corner.
pln_branchbank_stage1_09_any_01 = "อีกแค่ 3 กระเป่า แล้วเราไปกันเลย",--OK, 3 more then we can get out of here.
pln_branchbank_stage1_10_any_01 = "ใบเดียว อีกแค่ใบเดียว",--Come on now, 1 more.
pln_branchbank_stage1_11_any_01 = "นี่คือที่เราต้องการแล้ว แต่ถ้ามีอีกจะเอามาก็ได้",--OK, we can leave now, but try and take it all if you can.
pln_branchbank_stage1_12_any_01 = "นี่มันเหมือนถูกรางวัลเลยว่าไหม!",--Looks like we've hit the jackpot!
pln_branchbank_stage1_12_any_02 = "นี่มันเหมืองทองหรือไงกันเนี่ย",--Well this looks like a gold mine now,doesn' it.
pln_branchbank_stage1_13_any_01 = "เอากระเป๋าไปที่รถตู้เลย จอดอยู่อีกฝากของถนน",--Alright, bring it to the van, it's right across the street.
pln_branchbank_stage1_14_any_01 = "พ่อมืงมากันแล้ว",--Cops just pulled up!
pln_branchbank_stage1_15_any_01 = "นี่ยังไม่ตายกันใช่ไหม??",--You guys OK in there?
pln_branchbank_stage1_15_any_02 = "โยนลงกระเป๋าเลย",--Bag it up!
pln_branchbank_stage1_15_any_03 = "เซฟเปิดแล้ว!!",--OK the vault's open!
pln_branchbank_stage1_15_any_04 = "ขนทองพวกนั้นมาไห้หมด!",--Get that gold wrapped up!
pln_branchbank_stage1_15_any_05 = "เอาทองใส่กระเป่ามาเลย",--It's open! Bag the gold!
pln_branchbank_stage1_15_any_06 = "เซฟเปิดออกแล้ว ขนเงินมาไห้หมดเลย",--Vault's open! Bag the cash!
pln_branchbank_stage1_15_any_07 = "ได้เวลาเข้าเซฟแล้ว แล้วขนเงินมาไห้หมด",--Get in there folks, bag that cash.
pln_branchbank_stage1_15_any_08 = "เจาะเซฟเสร็จแล้ว ไหนดูสิอะไรเราอยู่??",--Vault's cracked, let's see what we got!
pln_branchbank_stage1_15_any_09 = "เข้าไปเลย ไปดุหน่อยว่างานนี้จะได้อะไรกลับบ้าน",--Go on in, see what we got!
pln_branchbank_stage1_16_any_01 = "ได้เวลาเบิกเงินแล้วพวก",--Cash time. Bag it!
pln_branchbank_stage1_17_any_01 = "แจ็คพ็อต!! ดูเงินพวกนี้สิ ขนมาได้เลย",--Jackpot... Look at all the cash... Get it out now!
pln_branchbank_stage1_17_any_02 = "เซฟเปิดแล้ว แต่เราคงต้องเหนื่อยแงะกล่องกันหน่อย",--It's open... No cash... Hit the deposit boxes...
pln_branchbank_stage1_18_any_01 = "เงินก็ไม่มี ทองด้วย!!?? หวังว่านายจะพกเลื่อยติดมือมาบ้างนะ",--No gold... No cash... Crack the deposit boxes. Hope you brought a saw.
pln_branchbank_stage1_19_any_01 = "กำลังเสริมมากันแล้ว!!",--More cops on the way.
pln_branchbank_stage1_20_any_01 = "ตำรวจแห่กันมาแล้วพวก",--They're coming into the bank! 
pln_branchbank_stage1_21_any_01 = "อย่าลืมเช็คกล่องนิรภัยด้วยหละ ต้องมีของดีบ้างแน่",--Don't forget about those safe deposit boxes folks, can be good stuff in there.
pln_branchbank_stage1_22_any_01 = "เหมือนจะพอได้พักบ้างแล้วพวก",--Street's clear for now!
pln_branchbank_stage1_23_any_01 = "ยังเจาะไม่เสร็จอีกหรอ ไห้ตายสิ!!",--Vault's not open yet... Dammit.
pln_branchbank_stage1_23_any_02 = "หวังว่าธนาคารจะมีประกันนะ",--I hope they're insured... 
pln_branchbank_stage1_23_any_03 = "ไม่ได้ลืมใช่ไหม ว่าเราต้องเข้าไปในเซฟหนะ มัวทำอะไรกันอยู่??",--Guys let's keep things moving along here.
pln_branchbank_stage1_24_any_01 = "หวังว่างานนี้จะไม่หนักนะ",--Hope they respond as poorly as they usually do... 
pln_branchbank_stage1_25_any_01 = "ตำรวจเริ่มถอยกลับบไปแล้ว",--The cops are doubling down...
pln_branchbank_stage1_26_any_01 = "ฉันว่าพวกนายน่าจะเริ่มขนของมาที่รถได้แล้ว",--My recommendation is you hustle those bags to the van.
pln_branchbank_stage1_27_any_01 = "รถตู้มาแล้ว!!",--Van's here, folks.
pln_branchbank_stage1_28_any_01 = "เราไม่ได้มารบกันนะ รีบๆ ทำงานไห้เสร็จ",--This isn't a war folks, in and out.
pln_branchbank_stage1_29_any_01 = "ได้ของตามเป้าแล้ว จะไปเลยหรืออยู่ต่อ เลือกเอาเอง",--OK! you've got enough... Or you can stay for more.
pln_branchbank_stage1_30_any_01 = "เหมือนอะไรๆ จะไม่เป็นตามแผน ยังอยากจะอยู่ต่อหรือไปเลย?",--Getting pretty unpleasant out there. You guys sure you wanna stick around?
pln_branchbank_stage1_31_any_01 = "พวกตำรวจกระจายตัวเต็มถนนแล้ว",--Cops all over the street!
pln_branchbank_stage1_32_any_01 = "ตำรวจบนดาดฟ้า!!",--They're on the roof!
pln_branchbank_stage1_32_any_02 = "ตำรวจเข้ามาแล้ว!!",--They're in the bank!
pln_branchbank_stage1_33_any_01 = "ตำรวจเข้ามาแล้ว!!",--They're inside!
pln_branchbank_stage1_33_any_02 = "จัดการพวกตำรวจหน่อย",--Keep controlling that room people.
pln_branchbank_stage1_33_any_03 = "รักษาที่มั่นไว้พวก",--Hold them in position.
pln_branchbank_stage1_34_any_01 = "ทำทุกอย่างไห้ตามแผนนะพวก",--Keep it under control.
pln_branchbank_stage1_34_any_02 = "ทุกอย่างไปได้สวย โอเคเลยยยยย",--We're looking good... Looking good.
pln_branchbank_stage1_34_any_03 = "ฉันหละชอบอะไรแบบนี้จริงๆ",--I like what I'm seeing in there.
pln_branchbank_stage1_34_any_04 = "นั้นแหละ จัดการได้ดี",--Promising... Very promising...
pln_branchbank_stage1_34_any_05 = "จัดการกันได้เลย",--Close... Come on folks... Getting there.
pln_branchbank_stage1_35_any_01 = "จนได้สินะ!!",--Now it's just a matter of time.
pln_branchbank_stage1_35_any_02 = "ไหนบอกว่าจะจัดการกันเงียบๆ ไง?",--...And yeah, there goes the alarm.
pln_branchbank_stage1_35_any_03 = "ได้เวลาจัดหนักแล้วหละพวก",--Dammit. Now we go the painful way.
pln_branchbank_stage1_36_any_01 = "ของจริงกำลังจะเริ่มสินะ",--Now the hard part.
pln_branchbank_stage1_37_any_01 = "ระวัง แก็ส แก็ส!!!",--Damnit! Gas! Gas!
pln_branchbank_stage1_38_any_01 = "ห้องเปิดออกแล้ว ขนทองออกมาได้เลย",--It's open! Bag the gold!
pln_branchbank_stage1_39_any_01 = "เจาะเสร็จแล้ว ได้เวลาค้นกล่องนิรภัย",--It's open! Search through the deposit boxes!
pln_branchbank_stage1_40_any_01 = "เจาะเสร็จแล้ว ไหนดูหน่อยว่าข้างในมีอะไร",--It's open! Let's see what we got!
pln_branchbank_stage1_41_any_01 = "เยี่ยม เงินสักบาทก็ไม่มี แงะกล่องได้เลย",--Well, no giant piles of money, search through the deposit boxes for valuables.
pln_branchbank_stage1_42_any_01 = "เงินอื้อเลยหวะ ขนสิจะรออะไร",--Loads of cash! Bag it up boys!
pln_branchbank_stage1_43_any_01 = "เหมือนเราจะเปิดเจอรางวัลที่ 1 นะเนี่ย",--Looks like we've hit the jackpot! Bag it up!
pln_branchbank_stage1_44_any_01 = "รถจอดอยู่อีกฝากของถนน ขนของมาเลย",--Alright, bring it to the van, it's right across the street.
pln_branchbank_stage1_80_any_01 = "นี่แหละธนาคารของเราวันนี้ คงต้องขอดูหน่อยว่ามีอะไรรอเราอยุ่ในเซฟ",--OK people, there's the bank, I don't know what's in there but it's gonna be good...
pln_branchbank_stage1_81_any_01 = "เยี่ยม!! เงินพวกนี้ก็ไม่เลว ขนกลับกันเลย",--Nice, seems the surprise loot was cash. Bag it.
pln_branchbank_stage1_82_any_01 = "ตำรวจกำลังมากันแล้ว น่าจะสัก 20 วินาที",--Listen up. Police are closing in. They are here in 20 seconds.
pln_branchbank_stage1_83_any_01 = "สว่าน !! เราต้องใช้มัน",--Guys, the thermal drill. Go get it.
pln_branchbank_stage1_84_any_01 = "เอาหละ ที่นี้ก็เอามันไปที่ประตูห้องเซฟ",--OK, great. Now get that thing to the vault door.
pln_branchbank_stage1_85_any_01 = "เยี่ยม ที่นี้ก็เดินเครื่องได้เลย",--Nice. Now start her up.
pln_branchbank_stage1_86_any_01 = "ที่นี้ก็หาอะไรทำรอ สักสาม สี่นาที",--Here we go. We should be through in a couple of minutes.
pln_branchbank_stage1_87_any_01 = "เฮลิคอปเปอร์บนดาดฟ้า!!",--Chopper coming in! Roof guys, roof!
pln_branchbank_stage1_88_any_01 = "พวกมันส่งสไนเปอร์มาแล้ว หาที่กำบังไว้",--I got snipers incoming. Stay indoors guys!
pln_branchbank_stage1_89_any_01 = "ไอเดียดี ใช้ไม้พวกนี้กันทางเข้าออกไว้ น่าจะช่วยได้มาก",--Good thinking, boards will slow them down.