--Info
menu_russian = "ดาลัส",--Dallas
russian_desc = "สัญชาติ: อเมริกัน$NL;อายุ: 44 ปี$NL;$NL;มากประสบการณ์. ฉลาดแกมโกง. รอบครอบไร้ที่ติ. ในวัย 30 ปี ดาลาสเคยพยายามทำให้กลุ่มมหาอำนาจสองกลุ่มแห่งชิคาโกหันมาปะทะกันเอง แต่มันกลับทำให้บรรดาบอสของเหล่ากลุ่มนักเลงต่าง$NL;ต้องการหัวเขามาประดับที่ห้อง แต่ดาลาสลอดมาได้จากการรู้จักวิธีที่จะทำให้ตนหายไป และเมื่อเรื่องถุกลืมเลือน เขากลับมาเพื่อถวงตำแหน่งแนวหน้าแห่งอาชญากรณ์$NL;คืนและตอนนี้ใบหน้าของเขาคือฝันร้ายของเหล่ากลุ่ม",--Nationality: American$NL;Age: 44$NL;$NL;Experienced, cunning, methodical. At the age of 30 he tried to play two of Chicago's mob families against each other. It went south and several mob bosses ordered Dallas' head on a plate, but somehow he managed to go underground and survive. After things calmed down he worked his way back up the criminal ladder.$NL;$NL;Now he's the face that everyone fears.$NL;$NL;When you select Dallas as your preferred character, you will always play as Dallas if he is available.
russian_desc_codex = "มากประสบการณ์. ฉลาดแกมโกง. รอบครอบไร้ที่ติ. ในวัย 30 ปี ดาลาสเคยพยายามทำให้กลุ่มมหาอำนาจสองกลุ่มแห่งชิคาโกหันมาปะทะกันเอง แต่มันกลับทำให้บรรดาบอสของเหล่ากลุ่มนักเลงต่าง$NL;ต้องการหัวเขามาประดับที่ห้อง แต่ดาลาสลอดมาได้จากการรู้จักวิธีที่จะทำให้ตนหายไป และเมื่อเรื่องถุกลืมเลือน เขากลับมาเพื่อถวงตำแหน่งแนวหน้าแห่งอาชญากรณ์$NL;คืนและตอนนี้ใบหน้าของเขาคือฝันร้ายของเหล่ากลุ่ม",--Nationality: American$NL;Age: 44$NL;$NL;Experienced, cunning, methodical. At the age of 30 he tried to play two of Chicago's mob families against each other. It went south and several mob bosses ordered Dallas' head on a plate, but somehow he managed to go underground and survive. After things calmed down he worked his way back up the criminal ladder.$NL;$NL;Now he's the face that everyone fears.$NL;$NL;When you select Dallas as your preferred character, you will always play as Dallas if he is available.
menu_german = "วูล์ฟ",--Wolf
german_desc = "สัญชาติ: สวีเดน$NL;อายุ: 34 ปี$NL;$NL;ที่จริงวูฟล์เป็นเพียงประชาชนที่ใช้ชีวิตปรกติคนหนึ่ง แต่ในช่วงปลายศตวรรษที่ 20 เศรษฐกิจตกต่ำ จนทำให้บริษัทของเขาเหลือลูกค้าเพียงไม่กี่รายและเขากำลังจะล้มละลาย ทำให้เขาตัดสินใจมาเดินในทางแห่งอาชญากรณ์ด้วยวิธีเดียวกันในแบบที่เขาใช้ในการบริหารบริษัทของเขา",--Nationality: Swedish$NL;Age: 34$NL;$NL;Wolf was a law abiding citizen for most of his life. During the worldwide economic slump of the late 2000's, Wolf's company temporarily had only one client that got cold feet and wanted out. His company went bankrupt.$NL;$NL;He now pursues a criminal career with the same determination that drove him when he used to run his company.$NL;$NL;When you select Wolf as your preferred character, you will always play as Wolf if he is available.
german_desc_codex = "ที่จริงวูฟล์เป็นเพียงประชาชนที่ใช้ชีวิตปรกติคนหนึ่ง แต่ในช่วงปลายศตวรรษที่ 20 เศรษฐกิจตกต่ำ จนทำให้บริษัทของเขาเหลือลูกค้าเพียงไม่กี่รายและเขากำลังจะล้มละลาย ทำให้เขาตัดสินใจมาเดินในทางแห่งอาชญากรณ์ด้วยวิธีเดียวกันในแบบที่เขาใช้ในการบริหารบริษัทของเขา",--Nationality: Swedish$NL;Age: 34$NL;$NL;Wolf was a law abiding citizen for most of his life. During the worldwide economic slump of the late 2000's, Wolf's company temporarily had only one client that got cold feet and wanted out. His company went bankrupt.$NL;$NL;He now pursues a criminal career with the same determination that drove him when he used to run his company.$NL;$NL;When you select Wolf as your preferred character, you will always play as Wolf if he is available.
menu_spanish = "เซน",--Chains
spanish_desc = "สัญชาติ: อเมริกัน$NL;อายุ: 37 ปี$NL;$NL;ในช่วงวัยรุ่นเชนมักจะต้องเจอกับปัญหา และใช้ช่วงเวลาของวัยุร่นไปกับการย้ายไปมาระหว่าง$NL;บ้านอุปถัมพ์กับสถาพินิจสุดท้ายเขาได้สมัครเข้าเป็นทหาร และกลายเป็นทหารชั้นเลิศของกองทัพ แต่เขากลับเกลียดการต้องทำตามคำสั่ง เชนตัดสินใจออกจากการเป็นทหารและหันมาใช้วิชา$NL;ทหารของเขาให้กับคนที่จ่ายสูงกว่าแทน",--Nationality: American$NL;Age: 37$NL;$NL;As a teenager, Chains always got into trouble. After years of jumping between foster homes and juvenile institutions , he ended up in the military. There he became an excellent soldier but he always hated being told what to do.$NL;$NL;Chains left the military and became a soldier of fortune, offering his military expertise to the highest bidder.$NL;$NL;When you select Chains as your preferred character, you will always play as Chains if he is available.
spanish_desc_codex = "ในช่วงวัยรุ่นเชนมักจะต้องเจอกับปัญหา และใช้ช่วงเวลาของวัยุร่นไปกับการย้ายไปมาระหว่าง$NL;บ้านอุปถัมพ์กับสถาพินิจสุดท้ายเขาได้สมัครเข้าเป็นทหาร และกลายเป็นทหารชั้นเลิศของกองทัพ แต่เขากลับเกลียดการต้องทำตามคำสั่ง เชนตัดสินใจออกจากการเป็นทหารและหันมาใช้วิชา$NL;ทหารของเขาให้กับคนที่จ่ายสูงกว่าแทน",--Nationality: American$NL;Age: 37$NL;$NL;As a teenager, Chains always got into trouble. After years of jumping between foster homes and juvenile institutions , he ended up in the military. There he became an excellent soldier but he always hated being told what to do.$NL;$NL;Chains left the military and became a soldier of fortune, offering his military expertise to the highest bidder.$NL;$NL;When you select Chains as your preferred character, you will always play as Chains if he is available.
menu_american = "ฮูสตัน",--Houston
american_desc = "สัญชาติ: อเมริกัน$NL;อายุ: 31 ปี$NL;$NL;ฮูสตันเป็นชายไม่เอาถ่านคนนึงที่ไม่เคยรักษางานไว้ได้ แม้มันสำคัญกับเขามาก จนทำให้เขาต้องกลายมาเป็นพวกลักเล็กขโมยน้อย แต่หนีสินของเขามากยิ่งกว่าและเพิ่มขึ้นเรื่อยๆ จำนวนคนที่ถูกเขาโกง หลอกและขโมยเพิ่มขึ้นเรื่อยๆ เขายังคงต้องการเงินก้อนโตจากเหยื่อรายอื่นๆต่อไป เพื่อเป็นสะพานที่จะพาเขาออกจากวงเวียนแห้งหนี้สิน ในวัย 24 ปี เขาตัดสินใจเริ่มการเดิมพันครั้งแรกของเขา และนั้นก็คือตอนที่เรื่องราวของเขาได้เริ่มขึ้น",--Nationality: American$NL;Age: 31$NL;$NL;Houston could never hold a job even if his life would depend on it. His life style turned him to a life of cons and burglary. His debts grew, as did his collection of enemies from years of swindlery. He needed to gather larger and larger sums of money to keep the loan sharks at bay. He committed his first major felony at the age of 24 and the stakes have only increased since.$NL;$NL;When you select Houston as your preferred character, you will always play as Houston if he is available.
american_desc_codex = "ฮูสตันเป็นชายไม่เอาถ่านคนนึงที่ไม่เคยรักษางานไว้ได้ แม้มันสำคัญกับเขามาก จนทำให้เขาต้องกลายมาเป็นพวกลักเล็กขโมยน้อย แต่หนีสินของเขามากยิ่งกว่าและเพิ่มขึ้นเรื่อยๆ จำนวนคนที่ถูกเขาโกง หลอกและขโมยเพิ่มขึ้นเรื่อยๆ เขายังคงต้องการเงินก้อนโตจากเหยื่อรายอื่นๆต่อไป เพื่อเป็นสะพานที่จะพาเขาออกจากวงเวียนแห้งหนี้สิน ในวัย 24 ปี เขาตัดสินใจเริ่มการเดิมพันครั้งแรกของเขา และนั้นก็คือตอนที่เรื่องราวของเขาได้เริ่มขึ้น",--Nationality: American$NL;Age: 31$NL;$NL;Houston could never hold a job even if his life would depend on it. His life style turned him to a life of cons and burglary. His debts grew, as did his collection of enemies from years of swindlery. He needed to gather larger and larger sums of money to keep the loan sharks at bay. He committed his first major felony at the age of 24 and the stakes have only increased since.$NL;$NL;When you select Houston as your preferred character, you will always play as Houston if he is available.
houston_desc_codex = "",--Dallas younger brother might be able to keep the Hoxton mask, but he's not keeping the name. The consensus among the PAYDAY gang was that from now on, New Hoxton will go by the nicknamed Houston. It's a relatively cheap price to pay to calm Hoxton down and - if anything - partially forgive the PAYDAY gang for leaving him in jail.
menu_jowi = "จอห์นวิค",--John Wick
jowi_desc = "สัญชาติ: อเมริกัน$NL;อายุ: 40 ปี$NL;$NL;จอห์นวิคเป็นมือสังหารที่ลงมือได้อย่างเงียบงันไร้ที่ติ และเหมือนร่างกายของเขาเองจะยังแกร่งและทนสุดๆ อาจจะได้มาจากการที่เขาเคยเป็นนักมวยมาก่อน จอห์นและเชนเคยรู้จักกันมาก่อนเพราะทั้งสองคนอยู่$NL;หน่วยเดียวกันตอนเป็นทหาร หลังจากที่กลายเป็นมือสังหาร เขาได้ช่วยเชนออกจากสถานการณ์ที่ละเอียดอ่อน และบอกกับเชนว่าเขาต้องการตั้งกลุ่มขึ้น ซึ้งเชนเองก็ไม่มีทางที่จะปฏิเสธคำชวนของเพื่อนเก่า",--Nationality: American$NL;Age: 40s$NL;$NL;John Wick is a quiet and calm former hitman. He has a seemingly ageless physique, probably from his background as a boxer. John and Chains know each other from before as they used to be in the military together.$NL;$NL;After having gone dark, John recently resurfaced and helped Chains out of a delicate situation. In return, John told Chains he was in need of a crew. How could Chains say no to an old friend?
jowi_desc_codex = "จอห์นวิคเป็นมือสังหารที่ลงมือได้อย่างเงียบงันไร้ที่ติ และเหมือนร่างกายของเขาเองจะยังแกร่งและทนสุดๆ อาจจะได้มาจากการที่เขาเคยเป็นนักมวยมาก่อน จอห์นและเชนเคยรู้จักกันมาก่อนเพราะทั้งสองคนอยู่$NL;หน่วยเดียวกันตอนเป็นทหาร หลังจากที่กลายเป็นมือสังหาร เขาได้ช่วยเชนออกจากสถานการณ์ที่ละเอียดอ่อน และบอกกับเชนว่าเขาต้องการตั้งกลุ่มขึ้น ซึ้งเชนเองก็ไม่มีทางที่จะปฏิเสธคำชวนของเพื่อนเก่า",--Nationality: American$NL;Age: 40s$NL;$NL;John Wick is a quiet and calm former hitman. He has a seemingly ageless physique, probably from his background as a boxer. John and Chains know each other from before as they used to be in the military together.$NL;$NL;After having gone dark, John recently resurfaced and helped Chains out of a delicate situation. In return, John told Chains he was in need of a crew. How could Chains say no to an old friend?
menu_old_hoxton = "ฮ็อกตั้น",--Hoxton
old_hoxton_desc = "สัญชาติ: อังกฤษ$NL;อายุ: 32 ปี$NL;$NL;ชื่อของฮอกส์ทอนได้มากจากตอนที่เขาถูกจับกับกลุ่ม$NL;เก่าของเขา ในย่านตะวันออกของลอนดอน หลังจากหมดเวลามากมายกับการใช้ชีวิตในคุก เขาได้ออกมาทำงานร่วมกับกลุ่มอาจชญากรมากมายจนสุดท้ายก็ได้เข้าร่วมกับกลุ่ม PAYDAY ในศตวรรษที่ 20 หลังจากจบภารกิจการปล้นในปี 2011 เขาถูกจับกุมอีกครั้งโดย FBI และในปี 2014 เขาถูกช่วยออกมาระหว่างเคลื่อนย้ายตัวโดยกลุ่ม PAYDAY และมาสืบจนรู้ว่าการที่เขาถูกจับในปี 2011 เป็นการจัดฉากขึ้น",--Nationality: English$NL;Age: 32$NL;$NL;Hoxton got his name from being caught with his old gang in the East End of London. After doing time in HMYOI he worked with several crime syndicates in his 20s until he finally joined the PAYDAY gang. After a successful stint of major heists up until 2011, Hoxton was captured by the FBI and sent to prison.$NL;$NL;In 2014, the PAYDAY gang helped him escape. Ever since he got out, he has been convinced someone set him up.
old_hoxton_desc_codex = "ชื่อของฮอกส์ทอนได้มากจากตอนที่เขาถูกจับกับกลุ่ม$NL;เก่าของเขา ในย่านตะวันออกของลอนดอน หลังจากหมดเวลามากมายกับการใช้ชีวิตในคุก เขาได้ออกมาทำงานร่วมกับกลุ่มอาจชญากรมากมายจนสุดท้ายก็ได้เข้าร่วมกับกลุ่ม PAYDAY ในศตวรรษที่ 20 หลังจากจบภารกิจการปล้นในปี 2011 เขาถูกจับกุมอีกครั้งโดย FBI และในปี 2014 เขาถูกช่วยออกมาระหว่างเคลื่อนย้ายตัวโดยกลุ่ม PAYDAY และมาสืบจนรู้ว่าการที่เขาถูกจับในปี 2011 เป็นการจัดฉากขึ้น",--Nationality: English$NL;Age: 32$NL;$NL;Hoxton got his name from being caught with his old gang in the East End of London. After doing time in HMYOI he worked with several crime syndicates in his 20s until he finally joined the PAYDAY gang. After a successful stint of major heists up until 2011, Hoxton was captured by the FBI and sent to prison.$NL;$NL;In 2014, the PAYDAY gang helped him escape. Ever since he got out, he has been convinced someone set him up.
menu_female_1 = "โคลเวอร์",--Clover
menu_clover = "โคลเวอร์",--Clover
female_1_desc = "สัญชาติ: ไอริช$NL;อายุ: 27 ปี$NL;$NL;โคลเวอร์โตมาในครอบครัวที่ไม่อบอุ่นเท่าไหร่นักในย่าน$NL;สลัมของเมืองบรรพบุรุษของเธอทุกคนล้วนเป็นนักสู้ เธอมักจะไม่ชอบที่ใครมาว่าชาวไอริช เธอจะสวมสร้อยรุปใบโคลฟเวอร์ไว้ เพราะเธอเชื่อว่ามนันจะพาโชคดีมาหาเธอ และเธอชอบที่จะพูดว่าเธอ ภูมิใจที่เกิดเป็นไอริช",--Nationality: Irish$NL;Age: 27$NL;$NL;Clover grew up in a rough house in a rough part of town. Her ancestors were fighters in every generation, and she is fiercely dedicated to her Irish heritage. She wears the clovers for luck, as well as a way to say "I'm Irish, and I'm proud".$NL;$NL;When you select Clover as your preferred character, you will always play as Clover if she is available.
menu_clover_desc_codex = "โคลเวอร์โตมาในครอบครัวที่ไม่อบอุ่นเท่าไหร่นักในย่าน$NL;สลัมของเมืองบรรพบุรุษของเธอทุกคนล้วนเป็นนักสู้ เธอมักจะไม่ชอบที่ใครมาว่าชาวไอริช เธอจะสวมสร้อยรุปใบโคลฟเวอร์ไว้ เพราะเธอเชื่อว่ามนันจะพาโชคดีมาหาเธอ และเธอชอบที่จะพูดว่าเธอ ภูมิใจที่เกิดเป็นไอริช",--Nationality: Irish$NL;Age: 27$NL;$NL;Clover grew up in a rough house in a rough part of town. Her ancestors were fighters in every generation, and she is fiercely dedicated to her Irish heritage. She wears the clovers for luck, as well as a way to say "I'm Irish, and I'm proud".$NL;$NL;When you select Clover as your preferred character, you will always play as Clover if she is available.
menu_dragan = "ดราแกน",--Dragan
dragan_desc = "สัญชาติ: โครเอเชีย$NL;อายุ: 45 ปี$NL;$NL;ดราแกนเคยเป็นตำรวจมาก่อน ตำรวจชาวโครเอเชีย แต่สำหรับชาวโครเอเชียตำรวจไม่ได้รับความเคารพและดูไม่ต่างจากพี่เลี้ยงเด็ก เขาจึงตัดสินใจรับคำตอบรับ และเดินทางมายังอเมริกาเพื่อเข้ารวมแก็ง PAYDAY และยังเป็นคนโปรดของผู้ว่าจ้างนาม The Butcher ถึงแม้จะมีคนในแก็งข้องใจเกี่ยวกับความซื่อสัตย์ของ$NL;เขา แต่ความสามารถและความมุ่งมั่นของเขาก็ทำให้เขาถูกยอมรับ",--Nationality: Croatian$NL;Age: 45$NL;$NL;Dragan may be a former cop, but he's a former Croatian cop, which means his methods make the MPDC look like timid babysitters. He was brought to America and accepted into the PAYDAY gang as a favor to The Butcher. While there were some early suspicions regarding his true loyalties, his ability and commitment are indisputable.$NL;$NL;When you select Dragan as your preferred character, you will always play as Dragan if he is available.
menu_dragan_desc_codex = "ดราแกนเคยเป็นตำรวจมาก่อน ตำรวจชาวโครเอเชีย แต่สำหรับชาวโครเอเชียตำรวจไม่ได้รับความเคารพและดูไม่ต่างจากพี่เลี้ยงเด็ก เขาจึงตัดสินใจรับคำตอบรับ และเดินทางมายังอเมริกาเพื่อเข้ารวมแก็ง PAYDAY และยังเป็นคนโปรดของผู้ว่าจ้างนาม The Butcher ถึงแม้จะมีคนในแก็งข้องใจเกี่ยวกับความซื่อสัตย์ของ$NL;เขา แต่ความสามารถและความมุ่งมั่นของเขาก็ทำให้เขาถูกยอมรับ",--Nationality: Croatian$NL;Age: 45$NL;$NL;Dragan may be a former cop, but he's a former Croatian cop, which means his methods make the MPDC look like timid babysitters. He was brought to America and accepted into the PAYDAY gang as a favor to The Butcher. While there were some early suspicions regarding his true loyalties, his ability and commitment are indisputable.$NL;$NL;When you select Dragan as your preferred character, you will always play as Dragan if he is available.
menu_jacket = "แจ็คเก็ต",--Jacket
jacket_desc = "สัญชาติ: อเมริกัน$NL;อายุ: ไม่ทราบ$NL;$NL;เคยมีคนเล่าว่า เขาเป็นคนจัดการมาเฟียรัสเซียทั้งไมอามี่ด้วยตัวคน$NL;เดียวในภูมิหลังของเขาสมัยเป็นทหาร $NL;เขานั้นมีความเชื่ออย่างมุ่งมันว่าการใช้กำลังจะนำพาเขาไปยังจุดสูงสุด และมันทำให้เขากลายเป็นมือสังหารชั้นเยี่ยม หรือที่เขาใเรียกกันว่า คนส่งสาร แต่ด้วยเหตุผลที่ไม่ทราบได้ เขาไม่เคยพูดเลย และเลือกที่จะใช้เทปบันทึกเสียงในการสื่อสารเท่านั้น",--Nationality: American$NL;Age: Unknown$NL;$NL;Allegedly, he once wiped out the entire Russian Mafia in Miami all on his own. His background in the military and his unflinching attitude towards over-the-top violence has made him an excellent hitman - or "messenger" as some like to call it. For unknown reasons he is completely mute and chooses to communicate only with the help of a tape recorder - playing back bits and pieces of language learning tapes, PAs and documentary narrations instead of speaking.$NL;$NL;When you select Jacket as your preferred character, you will always play as Jacket if he is available.
menu_jacket_desc_codex = "เคยมีคนเล่าว่า เขาเป็นคนจัดการมาเฟียรัสเซียทั้งไมอามี่ด้วยตัวคน$NL;เดียวในภูมิหลังของเขาสมัยเป็นทหาร $NL;เขานั้นมีความเชื่ออย่างมุ่งมันว่าการใช้กำลังจะนำพาเขาไปยังจุดสูงสุด และมันทำให้เขากลายเป็นมือสังหารชั้นเยี่ยม หรือที่เขาใเรียกกันว่า คนส่งสาร แต่ด้วยเหตุผลที่ไม่ทราบได้ เขาไม่เคยพูดเลย และเลือกที่จะใช้เทปบันทึกเสียงในการสื่อสารเท่านั้น",--Nationality: American$NL;Age: Unknown$NL;$NL;Allegedly, he once wiped out the entire Russian Mafia in Miami all on his own. His background in the military and his unflinching attitude towards over-the-top violence has made him an excellent hitman - or "messenger" as some like to call it. For unknown reasons he is completely mute and chooses to communicate only with the help of a tape recorder - playing back bits and pieces of language learning tapes, PAs and documentary narrations instead of speaking.$NL;$NL;When you select Jacket as your preferred character, you will always play as Jacket if he is available.
menu_bonnie = "บอนนี่",--Bonnie
bonnie_desc = "สัญชาติ: สก็อต$NL;อายุ: 43 ปี$NL;$NL;โบนี่มาจากเมือง กลาสโกลว แค่นั้นก็มากพอแล้วที่ยะเยียดความกลัวลงในใจของชายกล้า แต่ไม่ใช่แค่น้้นเพราะเธอเกิดในช่วง 1980 ยุคของ แทรทเชอร์ ช่วงเวลาที่เมืองเถื่อน เถื่อนยิ่งกว่าเก่า ช่วงเวลาแห่งการล้างเผ่าพันธุ์ชาวสก็อต นั้นแหละคือช่วงเวลาที่เธอเติบโตมา โบนี่เป็นคนสก็อต",--Nationality: Scottish$NL;Age: 43$NL;$NL;Bonnie is from Glasgow. That should be enough to strike fear into a man's heart, but Bonnie is also from 1980's Glasgow. These years, the Thatcher era, made already tough towns even harder, and bred a generation of determined, unforgiving Scots. Bonnie is cut from this cloth.$NL;$NL;When you select Bonnie as your preferred character, you will always play as Bonnie if she is available.
menu_bonnie_desc_codex = "โบนี่มาจากเมือง กลาสโกลว แค่นั้นก็มากพอแล้วที่ยะเยียดความกลัวลงในใจของชายกล้า แต่ไม่ใช่แค่น้้นเพราะเธอเกิดในช่วง 1980 ยุคของ แทรทเชอร์ ช่วงเวลาที่เมืองเถื่อน เถื่อนยิ่งกว่าเก่า ช่วงเวลาแห่งการล้างเผ่าพันธุ์ชาวสก็อต นั้นแหละคือช่วงเวลาที่เธอเติบโตมา โบนี่เป็นคนสก็อต",--Nationality: Scottish$NL;Age: 43$NL;$NL;Bonnie is from Glasgow. That should be enough to strike fear into a man's heart, but Bonnie is also from 1980's Glasgow. These years, the Thatcher era, made already tough towns even harder, and bred a generation of determined, unforgiving Scots. Bonnie is cut from this cloth.$NL;$NL;When you select Bonnie as your preferred character, you will always play as Bonnie if she is available.
menu_sokol = "โซโคล",--Sokol
sokol_desc = "สัญชาติ: รัสเซีย$NL;อายุ: 25 ปี$NL;$NL;ในวัยหนุ่ม โซโคลมีประสบการณ์และเพรียบพร้อมในฐานะ$NL;อาชญากรระดับตำนาน ด้วยพรสวรรค์ทางกีฬา ทำให้เขาเป็นนักกีฬาที่ชาญฉลาดและเข้าใจหน้าที่ตัวเอง$NL;ในทีมเป็นอย่างดี เขาเกิดมาโดยไร้ซึ้งความกลัว และเขาใช้มันเพื่อถล่มศัตรู ไม่ว่าจะเป็นทีมฮอกกี้หรือหน่วยสวาท",--Nationality: Russian$NL;Age: 25$NL;$NL;Though young, Sokol has everything to become a legendary heister. A gifted athlete, Sokol also possesses keen intelligence and understands his role in a team. He is fearless and physical, and uses this to get amongst the enemy, whether that be a team of hockey players or a team of SWAT.
menu_sokol_desc_codex = "ในวัยหนุ่ม โซโคลมีประสบการณ์และเพรียบพร้อมในฐานะ$NL;อาชญากรระดับตำนาน ด้วยพรสวรรค์ทางกีฬา ทำให้เขาเป็นนักกีฬาที่ชาญฉลาดและเข้าใจหน้าที่ตัวเอง$NL;ในทีมเป็นอย่างดี เขาเกิดมาโดยไร้ซึ้งความกลัว และเขาใช้มันเพื่อถล่มศัตรู ไม่ว่าจะเป็นทีมฮอกกี้หรือหน่วยสวาท",--Nationality: Russian$NL;Age: 25$NL;$NL;Though young, Sokol has everything to become a legendary heister. A gifted athlete, Sokol also possesses keen intelligence and understands his role in a team. He is fearless and physical, and uses this to get amongst the enemy, whether that be a team of hockey players or a team of SWAT.
menu_dragon = "จิโร่",--Jiro
dragon_desc = "สัญชาติ: ญี่ปุ่น$NL;อายุ: 52 ปี$NL;$NL;จิโร่ในวัยหนุ่มไม่เคยถูกยอมรับจากคนรอบตัวของเขา$NL;เลย แม้กระทั่งเขาเข้าร่วมกับกลุ่มยากูซ่า ก็ยังคงถูกหักหลัง แม้เขาจะเปี่ยมไปด้วยความสามรถและความภักดี หลังจากที่พ้นโทษ จิโร่ได้ตัดสินเดินทางไปยังอเมริกาเพื่อตามหาลูกชายที่$NL;ไม่ได้เจอกันนานของเขา เคนโตะ ",--Nationality: Japanese$NL;Age: 52$NL;$NL;In his youth, Jiro was never accepted, until he found his way into the yakuza. Yet even here, despite his loyalty and ability, he was never fully embraced and was ultimately betrayed. Following a lengthy prison term, Jiro has come to America to find his long-lost son, Kento.$NL;$NL;When you select Jiro as your preferred character, you will always play as Jiro if he is available.
menu_dragon_desc_codex = "จิโร่ในวัยหนุ่มไม่เคยถูกยอมรับจากคนรอบตัวของเขา$NL;เลย แม้กระทั่งเขาเข้าร่วมกับกลุ่มยากูซ่า ก็ยังคงถูกหักหลัง แม้เขาจะเปี่ยมไปด้วยความสามรถและความภักดี หลังจากที่พ้นโทษ จิโร่ได้ตัดสินเดินทางไปยังอเมริกาเพื่อตามหาลูกชายที่$NL;ไม่ได้เจอกันนานของเขา เคนโตะ ",--Nationality: Japanese$NL;Age: 52$NL;$NL;In his youth, Jiro was never accepted, until he found his way into the yakuza. Yet even here, despite his loyalty and ability, he was never fully embraced and was ultimately betrayed. Following a lengthy prison term, Jiro has come to America to find his long-lost son, Kento.$NL;$NL;When you select Jiro as your preferred character, you will always play as Jiro if he is available.
menu_bodhi = "โบดี่",--Bodhi
bodhi_desc = "สัญชาติ: ไม่ทราบ$NL;Age: ไม่ทราบ$NL;$NL;โบดี่ถูกรู้จักในฐานะตำนานแห่งโลกอาชญากร แต่ใครจะรู้ว่าภายไต้หน้ากากเขาคือผู้ก่อตั้งกลุ่ม EX-President โบดี่โด่งดังจากการโจรกรรมที่สุดเหวี่ยง การโจรกรรมของเขาในมุมใบ และออสเตรีย ทำให้เบนสนใจและส่งบัตรเชิญให้เขามารวมแก็ง PAYDAY",--Nationality: Unknown$NL;Age: Unknown$NL;$NL;Bodhi is known as one of the greatest legends in the world of crime, but few know the man behind the mask. As the founding father of the Ex-Presidents gang, Bodhi's renowned in the criminal underworld for his extreme athleticism and daring heists. His recent feats of strength in Mumbai and Austria got Bain's attention, granting him an invitation to the PAYDAY gang.
menu_bodhi_desc_codex = "โบดี่ถูกรู้จักในฐานะตำนานแห่งโลกอาชญากร แต่ใครจะรู้ว่าภายไต้หน้ากากเขาคือผู้ก่อตั้งกลุ่ม EX-President โบดี่โด่งดังจากการโจรกรรมที่สุดเหวี่ยง การโจรกรรมของเขาในมุมใบ และออสเตรีย ทำให้เบนสนใจและส่งบัตรเชิญให้เขามารวมแก็ง PAYDAY",--Nationality: Unknown$NL;Age: Unknown$NL;$NL;Bodhi is known as one of the greatest legends in the world of crime, but few know the man behind the mask. As the founding father of the Ex-Presidents gang, Bodhi's renowned in the criminal underworld for his extreme athleticism and daring heists. His recent feats of strength in Mumbai and Austria got Bain's attention, granting him an invitation to the PAYDAY gang.
menu_jimmy = "จิมมี่",--Jimmy
jimmy_desc = "สัญชาติ: ไม่ทราบ$NL;อายุ: ไม่ทราบ$NL;$NL;ตอนแรกมันก็ดูน่าสงใสแต่สุดท้ายแล้วเราก็ต้องยอมรับในตัวของเขาจิมมี่ปรากฏตัวพร้อมกับทักษะทุกๆอย่างที่เราต้องการสำหรับร่วมงานกับ crime.net ไม่เคยปฏิเสธไม่ว่างานประเภทไหนเขาใช้ชีวิตได้ราวกับ$NL;วันนั้นจะเป็นวันสุดท้ายของเขาและเขาได้พิสูจให้เห็นถึง$NL;ความสามารถในแบบไร้ที่ติในแบบที่ฉันไม่เคยคิดว่าเรา$NL;ต้องการมาก่อน",--Nationality: Unknown$NL;Age: Unknown$NL;$NL;I had my doubts at first, I'll admit, but Jimmy has turned out to have all the skills to excel as a heister of Crime.Net caliber. He has no limits, never turning down a contract and lives every day like it's his last. He is loyal and has proven to be an excellent addition I never thought we needed.
menu_jimmy_desc_codex = "ตอนแรกมันก็ดูน่าสงใสแต่สุดท้ายแล้วเราก็ต้องยอมรับในตัวของเขาจิมมี่ปรากฏตัวพร้อมกับทักษะทุกๆอย่างที่เราต้องการสำหรับร่วมงานกับ crime.net ไม่เคยปฏิเสธไม่ว่างานประเภทไหนเขาใช้ชีวิตได้ราวกับ$NL;วันนั้นจะเป็นวันสุดท้ายของเขาและเขาได้พิสูจให้เห็นถึง$NL;ความสามารถในแบบไร้ที่ติในแบบที่ฉันไม่เคยคิดว่าเรา$NL;ต้องการมาก่อน",--Nationality: Unknown$NL;Age: Unknown$NL;$NL;I had my doubts at first, I'll admit, but Jimmy has turned out to have all the skills to excel as a heister of Crime.Net caliber. He has no limits, never turning down a contract and lives every day like it's his last. He is loyal and has proven to be an excellent addition I never thought we needed.



--Menu
bm_menu_btn_set_preferred = "กำหนดช่องให้กับตัวละคร",--Set as preferred character
bm_menu_btn_set_preferred_to_slot = "เลือกตัวละคร",--Set Preferred
bm_menu_btn_swap_preferred_slots = "เลือกตัวละคร",--Swap Preferred
bm_menu_btn_clear_preferred = "เคลียร์ลำดับของตัวละคร",--Clear Preferred Characters