----------Shotgunner----------
st_menu_enforce_shotgun = "หน่วยปืนลูกซอง",--Shotgunner
menu_underdog_beta = "",--Underdog
menu_underdog_beta_desc = "พื้นฐาน: ##$basic;##$NL;เมื่อมีศัตรูมากกว่าหรือเท่ากับสามในระยะ ##$multibasic;## เมตรที่กำลังเล็งคุณอยู่, คุณจะได้โบนัสความเสียหายของอาวุธเพิ่มขึ่น ##$multibasic2;## เป็นระยะเวลา ##$multibasic3;## วินาที.$NL;$NL;ขั้นสูง: ##$pro;##$NL;เมื่อมีศัตรูมากกว่าหรือเท่ากับสามในระยะ ##$multipro;## เมตรที่กำลังเล็งคุณอยู่, คุณจะได้โบนัสรับความเสียหายน้อยลง ##$multipro2;## เป็นระยะเวลา ##$multipro3;## วินาที.$NL;$NL;Note: ความสามารถนี้ไม่ส่งผลกับ อาวุธระยะประชิด, อาวุธขว้าง, หรือปืนยิงระเบิด.",--BASIC: ##$basic;##$NL;When three or more enemies within ##$multibasic;## meters are targeting you, you receive a ##$multibasic2;## damage bonus that lasts for ##$multibasic3;## seconds.$NL;$NL;ACE: ##$pro;##$NL;When three or more enemies within ##$multipro;## meters are targeting you, you also receive a ##$multipro2;## damage reduction that lasts for ##$multipro3;## seconds.$NL;$NL;Note: Does not apply to melee damage, throwables, grenade launchers or rocket launchers.
menu_shotgun_cqb_beta = "",--Shotgun CQB
menu_shotgun_cqb_beta_desc = "พื้นฐาน: ##$basic;##$NL;ปืนลูกซองรีโหลดกระสุนไวขึ้น ##$multibasic2;##.$NL;$NL;ขั้นสูง: ##$pro;##$NL;ปืนลูกซองรีโหลดกระสุนไวขึ้น ##$multipro;##.$NL;คุณจะเล็งอาวุธได้ไวขึ้น ##$multipro2;## เมื่อใช้ปืนลูกซอง.",--BASIC: ##$basic;##$NL;You reload Shotguns ##$multibasic2;## faster.$NL;$NL;ACE: ##$pro;##$NL;You reload Shotguns ##$multipro;## faster. You gain a ##$multipro2;## increased steel sight zoom speed when using Shotguns.
menu_shotgun_impact_beta = "",--Shotgun Impact
menu_shotgun_impact_beta_desc = "พื้นฐาน: ##$basic;##$NL;เพิ่มค่าความมั่นคงให้กับปืนลูกซอง$NL;ทุกกระบอก ##$multibasic;##. $NL;คุณสร้างความเสียหายเพิ่มขึ้น ##$multibasic2;## เมื่อใช้ปืนลูกซอง .$NL;$NL;ACE: ##$pro;##$NL;สร้างความเสียหายมากขึ้น ##$multipro;## เมื่อใช้ปืนลูกซอง.",--BASIC: ##$basic;##$NL;Your weapon stability with all shotguns is increased by ##$multibasic;##. You deal ##$multibasic2;## more damage with Shotguns.$NL;$NL;ACE: ##$pro;##$NL;You deal an additional ##$multipro2;## more damage with shotguns.
menu_far_away_beta = "",--Far Away
menu_far_away_beta_desc = "พื้นฐาน: ##$basic;##$NL;คุณจะได้รับโบนัสความแม่นยำเพิ่มขึ้น ##$multibasic;##$NL;เมื่อเล็งด้วยปืนลูกซอง.$NL;$NL;ACE: ##$pro;##$NL;ประสิทธิภาพระยะไกลของปืนลูกซองจะเพิ่มขึ้น ##$multipro;## เมื่อเล็งด้วยปืนลูกซอง.",--BASIC: ##$basic;##$NL;Your accuracy bonus while aiming down sights with Shotguns is increased by ##$multibasic;##.$NL;$NL;ACE: ##$pro;##$NL;You gain a ##$multipro;## increased effective range with Shotguns when aiming down sights.
menu_close_by_beta = "",--Close By
menu_close_by_beta_desc = "พื้นฐาน: ##$basic;##$NL;สามารถวิ่งและยิงโดยไม่เล็งเมื่อใช้ปืนลูกซองได้.$NL;$NL;$NL;ACE: ##$pro;##$NL;ความเร็วการลั่นกระสุนเพิ่มขึ้น ##$multipro;## เมื่อยิงโดยไม่เล็ง. $NL;ลูกซองที่บรรจุกระสุนด้วยแม็กกาซีน$NL;จะมีความจุเพิ่มขึ้น ##$multipro2;## นัด.",--BASIC: ##$basic;##$NL;You can now hip-fire with your Shotguns while sprinting.$NL;$NL;ACE: ##$pro;##$NL;Your rate of fire is increased by ##$multipro;## while firing from the hip with single shot Shotguns. Shotguns with magazines have their magazine sizes increased by ##$multipro2;## shells.
menu_overkill_beta = "",--OVERKILL
menu_overkill_beta_desc = "พื้นฐาน: ##$basic;##$NL;เมื่อคุณสังหารศัตรูด้วยปืนลูกซอง$NL;หรือเลื่อยไฟฟ้า OVE9000 $NL;คุณจะได้รับโบนัสความเสียหาย ##$multibasic;## $NL;โดยจะมีผลเป็นระยะเวลา ##$multibasic2;## วินาที.$NL;$NL;ACE: ##$pro;##$NL;โบนัสความเสียหายเพิ่มให้กับอาวุธทุกชนิด$NL;แต่ยังคงต้องใช้ลูกซองหรือเลื่อยไฟฟ้า OVE9000 $NL;ในการเปิดใช้งานความสามารถนี้ $NL;ลดระยะเวลาในการสลับอาวุธลง ##$multipro;##$NL;$NL;Note: ความสามารถนี้ไม่ส่งผลกับ อาวุธระยะประชิด, อาวุธขว้าง, หรือปืนยิงระเบิด.",--BASIC: ##$basic;##$NL;When you kill an enemy with a Shotgun or the OVE9000 portable saw, you receive a ##$multibasic;## damage increase for ##$multibasic2;## seconds.$NL;$NL;ACE: ##$pro;##$NL;The damage bonus now applies to all weapons. Skill must still be activated using a Shotgun or the OVE9000 portable saw. Your weapon swap speed is increased by ##$multipro;##$NL;$NL;Note: Does not apply to melee damage, throwables, grenade launchers or rocket launchers.
----------Armorer----------
st_menu_enforcer_armor = "หน่วยเกราะ",--Armorer
menu_oppressor_beta = "",--Oppressor
menu_oppressor_beta_desc = "พื้นฐาน: ##$basic;##$NL;เพิ่มอัตราการฟื้นฟูเกราะของคุณ ##$multibasic2;##.$NL;$NL;ขั้นสูง: ##$pro;##$NL;ลดผลกระทบที่เกิดจากระเบิดแฟลชลง ##$multipro2;##.",--BASIC: ##$basic;##$NL;Increases your armor recovery rate by ##$multibasic2;##.$NL;$NL;ACE: ##$pro;##$NL;Reduces the visual effect duration of Flashbangs by ##$multipro2;##.
menu_show_of_force_beta = "",--Die Hard
menu_show_of_force_beta_desc = "พื้นฐาน: ##$basic;##$NL;คุณจะได้รับความเสียหายน้อยลง ##$multibasic;## $NL;เมื่อคุณกำลังตอบโต้กับวัตถุอื่นๆอยู่.$NL;$NL;ACE: ##$pro;##$NL;เพิ่มปริมาณเกราะให้ชุดเกราะกลุ่ม Ballistic ขึ้นอีก ##$multipro2;##.",--BASIC: ##$basic;##$NL;You take ##$multibasic;## less damage while interacting with objects.$NL;$NL;ACE: ##$pro;##$NL;Increases the armor of all Ballistic vests by ##$multipro2;##.
menu_pack_mule_beta = "",--Transporter
menu_pack_mule_beta_desc = "พื้นฐาน: ##$basic;##$NL;คุณจะขว้างกระเป๋าได้ไกลขึ้น ##$multibasic;## .$NL;$NL;ACE: ##$pro;##$NL;ทุก ๆ ##$multipro2;## หน่วยของค่าเกราะ จะช่วยลดน้ำหนักของสัมภาระที่แบกลง ##$multipro3;##",--BASIC: ##$basic;##$NL;You can throw bags ##$multibasic;## further.$NL;$NL;ACE: ##$pro;##$NL;For each ##$multipro2;## armor points the bag movement penalty is reduced by ##$multipro3;##
menu_iron_man_beta = "",--Bulletproof

menu_iron_man_beta_desc = "พื้นฐาน: ##$basic;##$NL;ลดระยะเวลาการฟื้นฟูเกราะของคุณและเพื่อนร่วมทีม ##$multibasic2;##.$NL;$NL;ขั้นสูง: ##$pro;##$NL;คุณสามารถทำให้ศัตรูเสียหลักโดยการโจมตีของคุณได้.$NL;สำหรับอาวุธระยะไกลโอกาสที่จะทำให้ศัตรูเสียหลัก$NL;จะขึ้นอยู่กับความเสียหายของอาวุธ. $NL;อาวุธระยะประชิดจะมีโอกาส ##$multipro2;## ที่จะทำให้ศัตรูเสียหลัก.",--BASIC: ##$basic;##$NL;Increases the armor recovery rate for you and your crew by ##$multibasic2;##.$NL;$NL;ACE: ##$pro;##$NL;Enables your weapons to have a chance to knock back Shield enemies when attacking them. Ranged weapons' knock back chance is increased the higher the total damage of the weapon is. Melee weapons' knock back chance is ##$multipro2;##.
menu_prison_wife_beta = "",--Bullseye
menu_prison_wife_beta_desc = "พื้นฐาน: ##$basic;##$NL;คุณจะฟื้นฟูเกราะ ##$multibasic3;## ในแต่ละการยิงหัว. $NL;โดยจะใช้ได้ทุก ๆ ##$multibasic2;## วินาที .$NL;$NL;ขั้นสูง: ##$pro;##$NL;คุณจะฟื้นฟูเกราะเพิ่มขึ้นอีก ##$multipro3;##.",--BASIC: ##$basic;##$NL;You regenerate ##$multibasic3;## armor for each successful headshot. This can not occur more than once every ##$multibasic2;## seconds.$NL;$NL;ACE: ##$pro;##$NL;You regenerate an additional ##$multipro3;## armor for each successful headshot.
menu_juggernaut_beta = "",--Iron Man
menu_juggernaut_beta_desc = "พื้นฐาน: ##$basic;##$NL;ค่าเกราะของคุณจะเพิ่มขึ้น ##$multibasic;##.$NL;$NL;ขั้นสูง: ##$pro;##$NL;ปลดล็อคเกราะหนักสุด หรือ Improved Combined Tactical Vest ให้ใช้งาน",--BASIC: ##$basic;##$NL;Your total armor value is increased by ##$multibasic;##.$NL;$NL;ACE: ##$pro;##$NL;Unlocks the ability to wear the Improved Combined Tactical Vest.
----------Ammo Specialist----------
st_menu_enforcer_ammo = "หน่วยเชี่ยวชาญด้านกระสุน",--Ammo Specialist
menu_scavenging_beta = "",--Scavenging
menu_scavenging_beta_desc = "พื้นฐาน: ##$basic;##$NL;ระยะของการเก็บกระสุนเพิ่มขึ้น ##$multibasic;##.$NL;$NL;ขั้นสูง#$pro;##$NL;ทุก กล่องกระสุนใบที่ 6 จากการฆ่าของคุณ$NL;จะให้กระสุนมากกว่าปกติ.",--BASIC: ##$basic;##$NL;Your ammo box pick up range is increased by ##$multibasic;##.$NL;$NL;ACE: ##$pro;##$NL;Every 6th enemy you kill will drop an extra ammo box.
menu_ammo_reservoir_beta = "",--Bullet Storm
menu_ammo_reservoir_beta_desc = "พื้นฐาน: ##$basic;##$NL;เมื่อวางกระเป๋ากระสุนจะสามารถยิงโดย$NL;ไม่สูญเสียกระสุนเป็นเวลา ##$multibasic;## วินาที $NL;หากมีคนเติมกระสุนในระยะเวลาความสามารถจะช่วยยืดระยะเวลาของความสามารถออกไปได้อีก .$NL;$NL;ขั้นสูง: ##$pro;##$NL;เพิ่มระยะเวลาของความสามารถออกเป็น ##$multipro2;## วินาที.",--BASIC: ##$basic;##$NL;Ammo bags placed by you grant players the ability to shoot without depleting their ammunition for up to ##$multibasic;## seconds after interacting with it. The more ammo players replenish, the longer the duration of the effect.$NL;$NL;ACE: ##$pro;##$NL;Increases the base duration of the effect by up to ##$multipro2;## seconds.
menu_portable_saw_beta = "",--Portable Saw
menu_portable_saw_beta_desc = "พื้นฐาน: ##$basic;##$NL;ปลดล็อคเลื่อยไฟฟ้า OVE9000 ให้ใช้ได้ในส่วนของอาวุธสำรอง.$NL;$NL;ขั้นสูง: ##$pro;##$NL;ได้รับใบเลื่อยเพิ่มขึ้นอีก ##$multipro;## ใบ และเปลี่ยนใบเลื่อนเป็นใบเลื่อยแบบคาร์บอน ทำให้เลื่อยได้มีประสิทธิภาพขึ้นอีก ##$multipro2;##.",--BASIC: ##$basic;##$NL;Unlocks the OVE9000 portable saw for you to use as a secondary weapon.$NL;$NL;ACE: ##$pro;##$NL;You gain ##$multipro;## extra saw blade for the OVE9000 portable saw. You replace your saw blades with carbon blades, increasing your saw efficiency by ##$multipro2;##.
menu_ammo_2x_beta = "",--Ammo Specialist
menu_ammo_2x_beta_desc = "พื้นฐาน: ##$basic;##$NL;ได้รับกระเป๋ากระสุนสำหรับใช้ระหว่างภารกิจเป็น ##$multibasic;## ใบ. $NL;$NL;ขั้นสูง: ##$pro;##$NL;กระเป๋ากระสุนบรรจุกระสุนเพิ่มขึ้นอีก ##$multipro;## .",--BASIC: ##$basic;##$NL;You can now place ##$multibasic;## ammo bags instead of just one. $NL;$NL;ACE: ##$pro;##$NL;Each ammo bag now contains ##$multipro;## more ammunition.
menu_carbon_blade_beta = "",--Carbon Blade
menu_carbon_blade_beta_desc = "พื้นฐาน: ##$basic;##$NL;ลดการเสียหายของใบเลื่อยเมื่อถูกใช้งานลง ##$multibasic2;##.$NL;$NL;ขั้นสูง: ##$pro;##$NL;สามารถใช้เลื่อยไฟฟ้าเพื่อเลื่อยทะลุตำรวจโล่ได้ และเมื่อฆ่าด้วยเลื่อยสำเร็จมีโอกาศ ##$multipro;## ทำให้ตำรวจที่อยู่รอบข้างในระยะ ##$multipro3;## เมตร ตกอยู่ในอาการหวาดกลัว อาการหวาดกลัวจะส่งผลให้ตำรวจเสียการ$NL;ควบคุมหยุดโจมตีและพยายามหนี.",--BASIC: ##$basic;##$NL;Reducing the wear down of the blades on enemies by ##$multibasic2;##.$NL;$NL;ACE: ##$pro;##$NL;You can now saw through shield enemies with your OVE9000 portable saw. When killing an enemy with the saw, you have a ##$multipro;## chance to cause nearby enemies in a ##$multipro3;## m radius to panic. Panic will make enemies go into short bursts of uncontrollable fear.
menu_bandoliers_beta = "",--Fully Loaded
menu_bandoliers_beta_desc = "พื้นฐาน: ##$basic;##$NL;ปริมาณกระสุนสูงสุดของคุณจะเพิ่มขึ้น ##$multibasic;##.$NL;$NL;ขั้นสูง: ##$pro;##$NL;เพิ่มปริมาณกระสุนที่ได้จากการเก็บ ##$multipro2;##. และจะมีโอกาศ ##$multipro3;## ที่จะได้รับอาวุธขว้างจากการเก็บ$NL;กล่องกระสุนโดยโอกาศจะเพิ่มขึ้น ##$multipro4;## $NL;ตามจำนวนกล่องกระสุนที่คุณเก็บได้จนกว่าจะได้อาวุธขว้าง $NL;และเมื่อเก็บได้อาวุธขว้าง โบนัสส่วนที่เพิ่มจะถูกเริ่มนับใหม่.$NL;$NL;Note: ไม่ส่งผลร่วมกับเพิร์คความสามารถ Walk in Closet",--BASIC: ##$basic;##$NL;Your total ammo capacity is increased by ##$multibasic;##.$NL;$NL;ACE: ##$pro;##$NL;Increases the amount of ammo you gain from ammo boxes by ##$multipro2;##. You also gain a ##$multipro3;## base chance to get a throwable from an ammo box. The base chance is increased by ##$multipro4;## for each ammo box you pick up that does not contain a throwable. When a throwable has been found, the chance is reset to its base value.$NL;$NL;Note: Does not stack with the perk deck skill "Walk-in Closet".