--menu_cs_daily_desc = "",--Every day a heister in the safe house will have a challenge for you! Meet with them in the safe house to accept their challenge, and then go out into the world to complete the requirements. Complete the challenge, and they'll give you a few Continental Coins for your troubles.$NL;$NL;Wick managed to get the PAYDAY crew membership to The Continental, so they're giving you coins for every heist you pull off. With enough coins, Charlie and his boys will come in and do a little redecorating for us, and make sure that any work done stays off the books.
menu_cs_help_jacket_3 = "ตู้เล่นเกมเก่า ๆ ของ Jacket เขาไม่มีเหตุผลที่จะออกจากห้องนี้เลย นั่นแหละฝันที่แท้จริง",--An old arcade for Jacket. He's got no reason to ever leave this room now. Dream come true.
menu_cs_title_bonnie = "โต๊ะการพนันของ Bonnie",--Bonnie's Gambling Den
menu_cs_help_hoxton_3 = "เป็นสำนักงานที่เรียบร้อย ทกอย่างอยู่ในนี้หมดเลย Hoxton ทำมันเอง คุณควรเชื่อมัน Aldstone สอนเขาเอง",--A tidy and neat office, with everything in its place. Hoxton did this, would you believe it. Aldstone taught him well.
menu_cs_help_wolf_1 = "นี่คือห้องออกแบบของใหม่ ๆ ของ WOlf ซึ่งสามารถทำให้แก๊งค์เราเนี่ยดูขึงขังขึ้น",--This is where Wolf designs and builds new equipment that can give the gang an edge on the heists.
menu_cs_title_vault = "ห้องนิรภัย",--The Vault
--menu_cs_trophy_counter = "",--$completed; of $total; trophies completed
menu_cs_title_houston = "โรงรถของ Houston",--Garage - Houston's Workshop
menu_cs_help_clover_2 = "Clover ได้มีคอมพิวเตอร์ที่เหมาะสมแล้ว ณ ตอนนี้ ระบบรักษาความปลอดภัยที่นี่ไม่ได้เป็นแบบยุดหินหรอกนะ เธอกล่าวไว้",--Clover has got some proper computers in here now. The security system has finally left the stone age, she says.
menu_cs_help_bodhi_3 = "กระดานโต้คลื่นที่โคตรสมบูรณ์แบบทำให้ Bodhi ได้รับความรู้สึกตามที่เขาต้องการ ตอนนี้เขาพร้อมที่จะเผชิญกับความท้าทายต่าง ๆ",--Perfecting the creation of a surfboard has brought Bodhi to the state of mind he needs to be. He is now ready for the challenges that lies ahead.
--menu_cs_help_vault_2 = "",--Bigger and fancier is better. The gang's ill-gotten gains needs to be secure.
menu_cs_title_sokol = "ยิมเล่น Hocky ของ Sokol",--Sokol's Hockey Gym
menu_cs_help_jimmy_3 = "บาร์ได้รับการขยาย และ Aldstone ได้หาบาร์เทนเดอร์มา แน่นอน เขาได้จับ Jimmy ขึ้นมานั่ง ซึ่งไม่ได้ต่างอะไรกับที่ทำงานเก่าของเขาเลย",--The bar has been extended, and Aldstone has managed to find a permanent bartender. Apparently, putting up with Jimmy is nothing compared to his old workplace.
menu_cs_upgrade_owned = "คุณได้ Upgrade ห้องนี้ไปแล้ว",--You have already purchased this room upgrade.
menu_cs_help_bodhi_1 = "Bodhi ได้ล่าคลื่นเป็นอย่างมาก กระดานโต้คลื่นช่วยให้เขามีสมาธิ และเตรียมพร้อมสำหรับการทดสอบของ Ozaki 8",--Bodhi hunts the waves as much as the next challenge. Building surfboards helps him meditate and prepare for the ordeals of the Ozaki 8.
menu_cs_enter_safehouse = "เข้า Safe House",--Enter your safe house
menu_cs_title_sydney = "สตูดิโอของ Sydney",--Sydney's Studio
menu_cs_rooms_help_hover = "Upgrade ห้องโดยกดปุ่มนี้",--Upgrade room by clicking on it
menu_cs_rooms_help_hover_no_upgrade = "คุณไม่สามารถ Upgrade ห้องได้ในขณะนี้",--You can't upgrade this room any further
menu_cs_help_sydney_3 = "หากพื้นที่การทำงานศิลปะของคุณรู้สึกไม่สมบูรณ์ การทำงานแบบนี้จะไม่มีวันเกิดขึ้นอีก สตูดิโอทำหน้ากากที่น่าสนใจที่สุดในวอชิงตันได้อยู่ตรงนี้แล้ว",--If an artist workspace doesn't feel complete, the work in it never will too. The fanciest mask creation studio in Washington right here.
--menu_cs_ground_floor_desc = "",--The ground floor is where the main hall and lounge is. Bonnie is getting installed nicely with her own gambling den, right next to Jiro's corner lounge. And Jimmy's at the bar, of course.$NL;$NL;Out in the garage, Houston and Rust are both working on their own projects. Sydney has set up a mask painting studio there as well.
menu_cs_title_jowi = "ห้องทดสอบปืนของ John Wick",--John Wick's Shooting Range
menu_cs_help_chains_1 = "ห้องของคนเร่ร่อน มีอาวุธปืน และมีสัตว์เลี้ยงของตัวเอง",--Chains' room where he tinkers with the gang's weapons and his own pet projects.
menu_cs_help_bonnie_1 = "นี่คือที่ที่ Bonnie กำลังวางแผนที่จะตั้งโต๊ะบ่อนของตัวเองที่นี่ แต่ไม่แน่ใจว่าจะหาคนเล่นด้วยได้หรือเปล่านะ",--This is where Bonnie is planning to set up her own little gambling den. There's no guarantee she'll find people to play with, though.
menu_cs_help_houston_1 = "Houston เป็นผู้รับผิดชอบในการหลบหนีด้วยรถตู้ และปรับแต่งรถตู้ เขาสามารถเปลี่ยนสีของรถตู้เมื่อใดก็ได้ ตามที่แก๊งต้องการ",--Houston is in charge of the escape van and tuning the gang's cars. He can switch out the color of the escape van whenever the gang needs it.
menu_cs_title_hoxton = "คลังข้อมูลของ Hoxton",--Hoxton's Files
menu_cs_help_hoxton_2 = "สิ่งที่อยู่ในออฟฟิศกำลังไปด้วยดี ไฟล์และเอกสารอยู่ในสถานที่ของพวกเขาส่วนใหญ่ ยังเกี่ยวหับการหาผู้ทรยศอยู่",--Things in the office are getting better organized. Files and papers are in their places, mostly. He is clearly still looking for the traitor.
menu_cs_help_dragan_2 = "อุปกรณ์มากกว่าเดิม กล้ามเนื้อที่ดีกว่า ถึงจะแก่แต่ก็ไม่อ้วนละกัน Dragan กล่าว",--More equipment, better muscles. Old and grey maybe but never fat, Dragan says.
menu_cs_help_sokol_2 = "เร็ว ๆ นี้จะเริ่มมองหาลานสเก็ตฮอกกี้ที่เหมือนจริงยิ่งขึ้น",--This will soon start looking like a real fake hockey rink.
menu_cs_help_chains_2 = "ห้องของ Chain ตอนนี้มีที่ว่างสำหรับอาวุธเพิ่มเติมและแสงที่ดีขึ้นในการทำงานด้วย สิ่งที่ยิ่งใหญ่จะเกิดขึ้นที่นี่แน่นอน",--Chains now has room for more weapons, and better lighting to work with. Great things will happen here.
menu_cs_help_sokol_1 = "Sokol ได้ตั้งโรงยิมฮ็อกกี้เพื่อเพิ่มทักษะการ slapshot ของเขา",--Sokol's setting up a hockey gym to keep his slapshot skills tuned.
menu_cs_help_rust_1 = "Rust รู้สึกเหมือนอยู่ที่บ้านในโรงรถและความรู้สึกนั้นไม่เคยเปลี่ยนแปลง",--Rust always felt right at home in a garage and that will never change.
menu_cs_help_sokol_3 = "นี่เป็นเหมือนวัดเล็ก ๆ ของฮอกกี้น้ำแข็งตอนนี้ Sokol รู้สึกดี ยังไม่มีใครชนะคะแนนสูงสุดของเขาได้",--This is like a small temple to ice hockey now. Makes Sokol feel right at home. Nobody has beat his high score, yet.
menu_cs_help_dallas_2 = "พื้นที่ที่สะดวกสบายกับชุดทีวีขนาดเล็ก Dallas ได้รู้สึกว่านี่มันคือสิ่งที่มีคุณภาพ และคุ้มค่าสำหรับแก้งค์ Payday",--A more comfortable space with a small TV set. Dallas is starting to feel that this may yet become a worthy HQ for the PAYDAY gang.
menu_cs_help_jowi_1 = "Wick มีแผนการใหญ่ ๆ และมีพื้นที่ใหญ่ที่สุดที่จะทำให้มันเกิดขึ้น",--Wick has got some big plans and got the biggest space to make it happen.
menu_cs_help_common_room_1 = "ห้องครัว, ห้องน้ำ และห้องนั่งเล่นขนาดใหญ่ พื้นที่ทั่วไปที่ทุกคนใช้กัน",--Kitchen, bathrooms, a big lounge... the common areas that everyone uses.
menu_cs_help_dragon_3 = "ญี่ปุ่นยังคงมีชีวิตอยู่ในหัวใจของจิโร่และอยู่ในมุมของ Safe House เพื่อนเก่าแก่ของ Jiro มาร่วมกับเขาในเรื่องหนี้และความเคารพ",--Japan still lives in Jiro's heart and also in his corner of the Safe House. A couple of loyal friends from Jiro's old days joins him out of debt and respect.
menu_cs_total_upgrades_value = "",--$owned;/$total;
menu_cs_help_dragon_2 = "ดาบ Katana ที่ดูคม และวางเด่นอยู่กลางห้อง จุ้บ ๆ",--A sandsteel Katana really sharpens the look of this room.
menu_cs_upgrade_cost = "จะต้องเสียค่าใช้จ่ายเป็น ##$cost;## Continental Coins เพื่ออัพเกรดห้องนี้",--It will cost ##$cost;## Continental Coins to upgrade this room.
menu_cs_div_safehouse_daily = "",--Safe House Daily
menu_cs_help_jowi_2 = "ที่ยิงเป้าใหม่ ถึงเวลาแล้วสำหรับการฝึกฝนทักษะและเตรียมพร้อมสำหรับภารกิจต่อไป โดย Wick จะไม่ลงเพราะขาดการฝึกอบรม",--A new shooting range, it's time for honing skills and preparing for the next mission. Wick will not go down for lack of training.
menu_cs_upgrade_max = "ห้องนี้อยู่ในระดับสูงสุดและไม่สามารถอัพเกรดได้อีกต่อไป",--This room is at its maximum level and can not be upgraded further.
menu_cs_upgrade_room = "อัพเกรดห้อง",--Upgrade Room
menu_cs_title_clover = "ศูนย์เฝ้าระวังของ Clover",--Clover's Surveillance Center
menu_cs_help_common_room_2 = "สิ่งอำนวยความสะดวกที่ดีขึ้นและที่นั่งมาก เป็นจุดเริ่มต้นที่ดูดีจริง ๆ",--Better facilities and a much nicer lounge. This is beginning to look really good.
menu_cs_help_bodhi_2 = "ความรักคลื่นของ Bodhi แสดงให้เห็นในการสร้างกระดานของเขา การเตรียมพร้อมของจิตจะก้าวไปอีกขั้นหนึ่งสำหรับการทำบอร์ดแต่ละบอร์ดที่เขาจะทำเสร็จ",--Bodhi's love for the waves shows in the creation of his boards. The mental preparation reaches one step further for each board he completes.
menu_cs_basement = "ชั้นใต้ดิน",--Basement
menu_cs_help_bonnie_2 = "ด้วยเครื่องสล็อตขนาดใหญ่ที่ดี Bonnie เริ่มที่จะรู้สึกดีที่บ้านที่นี่",--With a nice big slot machine, Bonnie is starting to feel right at home here.
menu_cs_help_jacket_1 = "Jacket ไม่ได้มีความต้องการสูงเพื่อความสะดวกสบาย โซฟารุ่นเก่าและฮาร์ดแวร์บางส่วนที่มีเทปนั้นมีค่อนข้างมาก",--Jacket doesn't have high requirements for comfort. An old couch and some hardware to mix tapes with is quite enough.
menu_cs_help_rust_3 = "Rust มีเครื่องมือทั้งหมดของเขาแล้ว และในที่สุดเขาก็สามารถปูในมุมของเขาในความสงบ",--Rust got all of his tools unpacked and can finally brood in his corner in peace.
menu_cs_help_dragon_1 = "มุมของ Jiro ซึ่งเขาชอบที่จะผ่อนคลายและนั่งสมาธิระหว่างการปล้น",--Jiro's corner, where he likes to relax and meditate between heists.
menu_cs_help_vault_1 = "ห้องเก็บของเก่ามีขนาดเล็กเกินไปกับความทะเยอทะยานที่ยิ่งใหญ่ของแก๊งค์",--The old vault was too small to fit the gang's big ambitions.
menu_cs_help_jimmy_2 = "บาร์ตอนนี้นั้นดีมากขึ้น และ Jimmy กำลังดื่มอย่างหนักให้เร็วที่สุดเท่าที่ Aldstone สามารถเติมมันได้",--The bar is now much more well stocked, and Jimmy is working hard at emptying it as fast as Aldstone can fill it up.
menu_cs_help_hoxton_1 = "Hoxton กำลังพยายามจัดเตรียมเอกสารและไฟล์ของแก๊งอย่างเป็นระเบียบ แต่เขายังคงเก็บรักษาแท็บไฟล์ FBI ไว้ที่นี่",--Hoxton is trying to get the gang's papers and files organized. It's all a mess but he still keeps tabs on the FBI's files from here.
menu_cs_help_chains_3 = "นี่เป็นคลังสรรพาวุธที่สมบูรณ์แบบเหมาะสำหรับการจัดเก็บและบำรุงรักษาคลังแสงเพื่อใช้ในกองจัดการตำรวจวอชิงตันทั้งหมด",--This is the perfect armory - excellent for storing and maintaining an arsenal to take on the entire Washington area police force.
menu_cs_title_dallas = "สำนักงานของ Dallas",--Dallas' Office
menu_cs_select_challenge = "เลือกความท้าทาย",--Select Challenge
menu_cs_title_dragon = "ที่นั่งของ Jiro",--Jiro's Lounge
menu_cs_total_upgrades = "รวมการอัพเกรดที่ซื้อแล้ว",--Total Upgrades Purchased
menu_cs_help_rust_2 = "เครื่องมือที่ดีกว่า เบียร์ที่มากกว่า Rust เป็นคนง่าย ๆ ถ้าคุณทำถูกต้อง",--Better tools, more beer. Rust is an easy man to please if you do it right.
menu_cs_help_jowi_3 = "การยิงที่ดีที่สุดจำเป็นจะต้องมีการเคลื่อนที่ John ได้สร้าง Killhouse โดยเขาจะเก็บบันทึกและให้คำแนะนำแก่ผู้ที่ต้องการ",--The best shot needs to also hit their mark on the move. John builds a Killhouse where he holds the record and gives advice to those who need it.
menu_cs_title_jacket ="ห้องพักผ่อนของ jacket",--Jacket's Hangout
menu_cs_help_sydney_2 = "ด้วยเครื่องมือและวัสดุที่ดียิ่งขึ้น Sydney มีพื้นที่ทำงานที่สวยงามและสามารถวางหน้ากากได้มากขึ้นสำหรับการแสดงผล",--With better tools and materials, Sydney's got a much nicer workspace and can put up more masks for display.
menu_cs_title_dragan = "ยิมของ Dragan",--Dragan's Gym
menu_cs_map = "แผนที่ห้อง",--Room Map
menu_cs_help_dragan_3 = "ห้องออกกำลังกายที่เหมาะสมและกระสอบทรายเพื่อลองอาวุธต่อสู้ระยะประชิดของแก๊งค์ทั้งหมด นี่คือสิ่งที่ Dragan ชอบมาเล่น",--A proper gym, and a punching bag for trying out all of the gang's melee weapons. This is the kind of stuff that Dragan likes. Come and play.
menu_cs_help_dallas_3 = "นี่เป็นห้องทำงานทำเพอร์เฟคสำหรับดาลัสไม่ว่าจะเป็นที่ไหนก็ตามเขาก็จะนั่งวางแผนสำหรับงานจ้างใหม่ๆ",--This is now the perfect office for Dallas, where he has everything he needs to calmly sit down and plan the details of upcoming heists.
menu_cs_top_floor = "ชั้นบนสุด",--Top Floor
menu_cs_ground_floor = "ชั้นแนวดิน",--Ground Floor
menu_cs_help_wolf_2 = "โต๊ะทำงานที่ดีกว่าและอุปกรณ์ที่จำเป็นสำหรับไอเดียแจ่มๆ",--A better workbench and more tools have been acquired. Same old insane ideas, though. This could go somewhere.
menu_cs_top_floor_desc = "นี่เป็นชั้นบนสุดของเซฟเฮ้าส์ดาลัสและฮ็อกตั้นใช้ห้องนี้ประจำในการวางแผนและโคลเวอร์ก็คอยจับตาดูที่กล้องเพื่อรักษาความปลอดภัย",--This is the top floor of the Safe House. Dallas and Hoxton usually hang out in the planning room, while Clover keeps an eye on security in the surveillance room.
menu_cs_help_dallas_1 = "มุมของดาลัสที่ดูงานจ้างใหม่ๆและดูสถานะการณ์ภายนอกนี่แหละทำให้เขาเข้าถึง Crime.net และหางานง่ายขึ้น",--Dallas' corner where he plans out new heists and keeps tabs on the outside world. Here he can easily access Side Jobs and Crime.Net
menu_cs_help_jimmy_1 = "จิมมี่ที่บาร์ เขาจะอยู่ที่ไหนอีกละ",--Yes, Jimmy's at the bar. Where else would he be?
menu_cs_title_chains = "ห้องปรับแต่งอาวุธ เซน",--Chains' Weapons Workshop
menu_cs_help_clover_3 = "เซฟเฮาส์หลังนี้เป็นเหมือนป้อมปราการมันมีกล้องอยู่ทุกที่ คุณไม่สามารถเข้าห้องน้ำได้ถ้าหากไม่บอกโคลเวอร์ก่อน",--The house is now like a fortress. There are cameras everywhere - you can't even go to the bathroom without Clover registering it.
menu_cs_cant_afford = "เหรียญของคุณไม่พอที่จะอัพเกรด",--You don't have enough Continental Coins for this upgrade.
menu_cs_title_common_room = "ห้องทั่วไป",--The Common Rooms
menu_cs_daily_challenge = "งานเสริม",--Side Jobs
menu_cs_change_floor = "เปลี่ยนชั้น",--Change Floor
menu_cs_help_houston_3 = "โรงจอดรถที่เฟอร์เฟคและรถที่เฟอร์เฟคกับช่างที่ชำนาญ",--A perfect garage with a perfect car in it. And a morally flawed but technically proficient mechanic.
menu_cs_vault = "ตู้นิรภัย",--Vault
menu_cs_help_bonnie_3 = "บอนนี่ได้มุมของเขาเธอชอบมันมากเธอยังมีรูเล็ตเกมของตัวเองกับเจ้ามืออีกด้วย",--Bonnie's got her corner sorted the way she likes it now. She's even got her own roulette with an actual croupier.
menu_cs_help_wolf_3 = "นี่เป็นที่อันตรายมากและเป็นห้องสำหรับช่างผู้เชี่ยวชาญจริงๆ",--This is getting dangerously close to the perfect synergy of the brilliant engineer with an excellent workspace. Beware, world.
menu_cs_daily_available = "$character; มีภารกิจสำหรับคุณลองไปหาเขาและรับภารกิจมาสิ",--$character; has a challenge available for you. Visit them in the safe house to accept their challenge.
menu_cs_title_wolf = "ห้องทำงานของวูฟ",--Wolf's Workshop
menu_cs_title_jimmy = "บาร์จิมมี่",--Jimmy's Bar
menu_cs_help_dragan_1 = "ดราแกนมองตัวเองผ่านกระจกเมื่อเขาดูไม่ดีเขาก็จะพยายามทำให้ดูดีไม่สำคัญว่าอะไรก็ตามเข้าก็เลยสร้างยิมนี้เพื่อสิ่งนั้น",--Dragan took a look in the mirror when Chains wasn't looking. He will keep himself and the rest of the gang in shape from now on, no matter what, and is building a gym to do it.
menu_cs_claim_reward = "รับรางวัล",--Collect Reward
menu_cs_help_sydney_1 = "ซิดนีย์ได้รับงานให้ปรับแต่งหน้ากากที่อยู่ในโรงรถและมีคอมพิวเตอร์เพื่อให้ง่ายต่อการทำหลายๆลายของหน้ากาก",--Sydney's got a mask painting studio set up in the garage and set up a computer to easily browse different skin designs for the gang's weapons.
menu_cs_basement_desc = "ในชั้นใต้ดินจอห์นวิคทำให้มีจุดทดสอบการยิงกับวูล์ฟที่อยู่ใกล้ๆกับโซโคลและยิมเป็นเหมือนห้องที่ดีสำหรับการอยู่แบบครอบครัวเลย",--In the basement John Wick is setting up a shooting range, with Wolf's workshop right next door. At the other end, Sokol and Dragan have their gym and training facilities. Bodhi has set up a workshop for his surfboards, too. And then there's Jacket's corner.$NL;$NL;The basement is also home to the vault, where the gang keeps all that sweet loot.
menu_cs_coins = "",--Continental Coins
menu_cs_unlock_prev_tier = "คุณต้องอัพเกรดอันเก่าก่อนถึงจะสามารถอัพเกรดได้",--You need to purchase the previous upgrade before you can buy this.
menu_cs_trophies = "ถ้วยรางวัล",--Trophies
menu_cs_common_room = "ห้องปกติ",--Common Rooms
menu_cs_daily_title = "",--Safe House Daily
menu_cs_help_clover_1 = "โคลเวอร์พยายามที่จะทำระบบรักษาความปลอดภัยเพื่อป้องกันจากการถูกโจมตีและเธอจะทำให้เซฟเฮาส์ปลอดภัยและทางกลับกันมาก็ทำให้เขารู้สึกสบายใจ",--Clover is trying to set up a security system to protect the house from raids and infiltration. She will put the "safe" in Safe House.
menu_cs_help_common_room_3 = "ห้องน้ำสวยๆและห้องนั่งเล่นกับห้องครัวที่ดูดีที่สุดถ้าให้เดา",--Fancy bathrooms, a luxurious lounge and a swanky kitchen that's looking better than ever. Guests will be impressed.
menu_cs_help_houston_2 = "โรงจอดรถที่อัพเกรดแล้วและรถเก่าแก่ที่มาด้วยกันฮูสตันให้ชีวิตกับมันและ",--The garage is being upgraded, and with it the old car is coming together. Houston is giving it a new life, and in return it gives him peace of mind.
menu_cs_help_jacket_2 = "ทีวีที่จำเป็นสำหรับคนบ้าคลั่งที่ไม่พูดไม่จา",--A TV is essential for any den of a mute crazy person.
menu_cs_help_vault_3 = "ตู้นิรภัยที่คุ้มค่าที่เก็บเงินของธนาคารรายใหญ่ๆ",--A vault worthy of a major bank. Or of those who repeatedly rob major banks.
menu_cs_title_bodhi = "ห้องกระดานโต้คลื่นของบอดี่",--Bodhi's Surfboard Workshop
menu_cs_title_rust = "โรงจอดรถ - มุมของรัซ",--Garage - Rust's Corner
