--Framing Frame / Art Gallery
--Heist Info
heist_gallery_crimenet = "เบนต้องการให้เรากลับไปยังหอศิลป์.$NL;$NL;» ตรวจสอบสถานที่อย่างระมัดระวัง.$NL;» ตรวจสอบยามและกล้องวงจรปิด.$NL;» ขโมยรูปภาพที่ถูกประกาศขายและหลบหนี",--Bain wants you to head back to the Art Gallery.$NL;$NL;» Case the place carefully.$NL;» Check for guards and cameras$NL;» Bag the marked out paintings and get to the escape van

--Objective
hud_e_framing_frame_stage1_mission1_hl = "เข้าไปในหอศิลป์",--Enter the gallery
hud_e_framing_frame_stage1_mission1 = "หาทางเข้าไปในหอศิลป์",--Find a way to get inside the gallery
hud_e_framing_frame_stage1_mission2_hl = "ขโมยรูปที่ทำเครื่องหมายไว้",--Steal the marked paintings
hud_e_framing_frame_stage1_mission2 = "มองหาภาพวาดที่มีสติกเกอร์สีแดงติดอยู่",--Look for paintings that have the red "sold" sticker on them
hud_e_framing_frame_stage1_mission3_hl = "เอาภาพวาดใส่รถตู้",--Take the paintings to the van
hud_e_framing_frame_stage1_mission3 = "เอาภาพวาดใส่รถตู้",--Carry the paintings and throw them into the van
hud_e_framing_frame_stage1_mission4_hl = "ปิดระบบป้องกัน",--Disable the barriers
hud_e_framing_frame_stage1_mission4 = "เข้าไปในห้องรักษาความปลอดภัยและแฮกระบบรักษาความปลอดภัย",--To reach the paintings, access the security room and hack the security system
hud_e_framing_frame_stage1_mission5_hl = "หนี!",--Escape is available!
hud_e_framing_frame_stage1_mission5 = "ขึ้นยานพาหนะเพื่อหลบหนี",--Get to the escape vehicle
hud_e_framing_frame_stage2_mission1_hl = "รับสายโทรศัพย์",--Answer the phone
hud_e_framing_frame_stage2_mission1 = "รับสายโทรศัพย์เพื่อสร้างการแลกเปลี่ยน",--Answer the phone to make the trade
hud_e_framing_frame_stage2_mission2_hl = "วางภาพวาดบนโต๊ะ",--Place the paintings
hud_e_framing_frame_stage2_mission2 = "วางภาพวาดบนโต๊ะ",--Place the paintings on the table
hud_e_framing_frame_stage2_mission3_hl = "เข้าไปยังโบกี้รถไฟ",--Get into the train cart
hud_e_framing_frame_stage2_mission3 = "เพื่อดำเนินต่อการแลกเปลี่ยนให้แน่ใจว่าทุกคนที่อยู่ในรถเข็นโบกี้รถไฟ",--To continue the trade, make sure everyone is in the train cart
hud_e_framing_frame_stage2_mission4_hl = "แลกเปลี่ยน",--Do the trade
hud_e_framing_frame_stage2_mission4 = "โยนกระเป๋าเพื่อแลกเปลี่ยน",--Throw the bags to do the trade
hud_e_framing_frame_stage2_mission5_hl = "ซุ่มโจมตี!",--Ambushed
hud_e_framing_frame_stage2_mission5 = "เกิดการซุ่มโจมตี ให้หลบหนี",--It's an ambush! Make for the escape
hud_e_framing_frame_stage2_mission6_hl = "หลบหนี",--Escape is available
hud_e_framing_frame_stage2_mission6 = "ขึ้นยานพาหนะเพื่อหลบหนี",--Get to the escape vehicle
hud_e_framing_frame_stage3_mission1_hl = "เข้าไปในอพาร์ทเม้นท์",--Get into the apartment
hud_e_framing_frame_stage3_mission1 = "เข้าไปในอพาร์ทเม้นท์",--Get into the Democrat's apartment
hud_e_framing_frame_stage3_mission2_hl = "ขโมยของ",--Steal the items
hud_e_framing_frame_stage3_mission2 = "ขโมย แลปท็อป, แท็บแลต, ฮาร์ดไดรฟ์,โทรศัพย์",--Find the laptop, harddrive, USB stick, tablet and the phone
hud_e_framing_frame_stage3_mission3_hl = "เซ็ตอุปกรณ์ทุกอย่างบนดาดฟ้า",--Set-up everything at the roof
hud_e_framing_frame_stage3_mission3 = "เซ็ตอุปกรณ์ทุกอย่างบนดาดฟ้า",--Set-up all the devices at your station on the roof
hud_e_framing_frame_stage3_mission4_hl = "แฮกคอมพิวเตอร์",--Access the computer
hud_e_framing_frame_stage3_mission4 = "เข้าไปในออฟฟิศ และแฮกคอมพิวเตอร์ของเขา",--Get into the democrat's office and access his stationary computer
hud_e_framing_frame_stage3_mission5_hl = "หาตู้นิรภัย",--Find the hidden vault
hud_e_framing_frame_stage3_mission5 = "หาตู้นิรภัย",--Locate and get into the hidden vault
hud_e_framing_frame_stage3_mission6_hl = "วางโคเคนข้างหน้าตู้นิรภัย",--Plant the coke infront of the vault door
hud_e_framing_frame_stage3_mission6 = "วางโคเคนข้างหน้าตู้นิรภัย",--Carry the bags with coke from the roof and place it infront of the vault door
hud_e_framing_frame_stage3_mission7_hl = "เปิดตู้นิรภัย",--Open the vault door
hud_e_framing_frame_stage3_mission7 = "แฮกคอมพิวเตอร์เพื่อเปิดตู้นิรภัย",--Use the stationary computer and open the vault door
hud_e_framing_frame_stage3_mission8_hl = "ขโมยทอง",--Get the gold
hud_e_framing_frame_stage3_mission8 = "ระวังเลเซอร์และขโมยทองมายังจุดส่งของ",--Take care of the lasers and carry the gold to the insertion point
hud_e_framing_frame_stage3_mission9_hl = "หลบหนี",--Escape
hud_e_framing_frame_stage3_mission9 = "หลบหนีด้วยซิปไลน์บนดาดฟ้า",--Escape via the zip line on the roof next to the insertion point
hud_e_framing_frame_stage3_mission10_hl = "หาห้องเซิฟเวอร์",--Locate the server room
hud_e_framing_frame_stage3_mission10 = "หาห้องเซิฟเวอร์ในอพาร์ทเม้นท์",--Find the server room somewhere in the democrats' apartment
hud_e_framing_frame_stage3_mission11_hl = "อัพโหลดไฟล์",--Upload the files
hud_e_framing_frame_stage3_mission11 = "แฮกคอมพิวเตอร์เพื่ออัพโหลดไฟล์ไปยังเอฟบีไอ",--Use the computer in the server room to start uploading the files to the FBI
hud_e_framing_frame_stage3_mission12_hl = "เปิดระบบจ่ายไฟ",--Turn the power back on
hud_e_framing_frame_stage3_mission12 = "เปิดระบบจ่ายไฟ เพื่ออัพโหลดไฟล์ต่อ",--Find the circuitbreaker to turn the power back on and continue the upload
hud_e_framing_frame_stage3_mission13_hl = "หลบหนี",--Escape is available
hud_e_framing_frame_stage3_mission13 = "ขึ้นยานพาหนะเพื่อหลบหนี",--Get to the escape vehicle
hud_e_framing_frame_stage3_mission14_hl = "แฮกคอมพิวเตอร์ต่อ",--Reactivate the computer
hud_e_framing_frame_stage3_mission14 = "แฮกคอมพิวเตอร์ต่อ",--Use the keyboard to reactivate the computer and continue the hacking
--Subtitle replance it to Form -pln to pln
pln_framing_stage1_intro_a_01 = "ギャラリーは目と鼻の先だ。そっと侵入して、カメラや警備員、動体検知器は避けろ。爆弾を警戒して、警備員はハイになってる。",--You're almost at the gallery. Slip in, avoid cameras, guards, and motion detectors. Security's high because of a bomb threat.
pln_framing_stage1_intro_a_01b = "とにかく、SOLDと印づけられている絵画を探して奪ってこい。万全を期するためには最低でも4枚は確保したいところだな。",--Anyway, find the paintings marked as sold and take them. We need at least four to be safe.
pln_framing_stage1_intro_a_02 = "ここがギャラリーだ。赤いsoldマークのシールが貼られた絵を探せ。最低でも4枚は必要だな。施設は施錠されてるから侵入口は自分で探せ。始めろ。",--This is the gallery.  You're looking for the paintings marked by a red sold sticker. We need at least four to make this work. The place is closed and locked down. Find a way in. Go.
pln_framing_stage1_intro_a_03 = "よし、ギャラリーは目の前だ。動体検知器、カメラ、警備員に注意しろ。中に侵入して4枚の赤いSOLDステッカーが貼られた絵画を奪ってこい。時間は今も進んでるぞ。",--OK, gallery's just ahead. Watch out for motion detectors, cameras and guards. Get in there and bring me four of the paintings marked with a red sold sticker. Time is ticking guys.
pln_framing_stage1_intro_a_04 = "警備員や警報装置に引っかからない限りは簡単な仕事だ。あー、やっぱり簡単じゃないな。赤いステッカーの貼ってある絵画を盗みだすんだ。最低でも4枚は必要になる。",--This is gonna be easy as long as you steer clear of the security systems and guards. Well maybe not so easy. Take the paintings with red sold stickers and clear out. We need four at least.
pln_framing_stage1_01_any_01 = "OK、中に入って芸術品を探せ。赤いステッカーの貼っている絵画がお目当ての品だ。警備員やカメラに見つかるなよ。",--OK guys, get inside and locate the art. We want the paintings with the red stickers on. Look out for guards and cameras.
pln_framing_stage1_01_any_02 = "",--OK, here's the setup: we're looking for the paintings with red stickers on them. Security is going to be on the heavy side, cameras and guards. 
pln_framing_stage1_01_any_03 = "武器は準備できたか?よし、聞け。お前たちは今、赤いステッカーで印付けられた絵画を探している。だが奴ら、ここに異常なほどの警備を敷かせてる。大量のカメラに警備室まである。だがそれでもやり遂げるんだ。",--Ready for the shot? OK listen: you are looking for the paintings marked with red stickers. They've got unusually tight security here. A lot of cameras, even a security room, so do your homework.
pln_framing_stage1_02_any_01 = "よし、侵入したな。赤いステッカーが貼られた絵画を探せ、最低でも4枚は欲しい。",--OK, you're inside. Find the paintings with the red stickers on them, we want at least four.
pln_framing_stage1_02_any_02 = "わかった... OK、最低でも4枚の絵画が必要だ。 覚えておけ、目標には赤いステッカーが付いてる。",--Alright... OK, we need at least four paintings, remember, the ones with red stickers.
pln_framing_stage1_02_any_03 = "よし、入ったな。いいぞ。最低でも4枚の絵画が必要だ。良さそうなやつには赤いステッカーが貼ってある・・・俺たちの絵画好きの顧客が買いたがってるやつにな。",--OK you're in, good. Now you need at least four paintings, the good ones have red stickers - those are the ones our art lover intends to buy.
pln_framing_stage1_02_any_04 = "よくやった、皆。お目当ては赤いステッカー付きの絵画だ。例の民主主義者さんはそれを欲しがってる。最低4枚入手しろ。",--Nice work, folks. Now what you're looking for are paintings with red stickers. Those are the ones the democrat wants. Get at least four. 
pln_framing_stage1_03_any_01 = "ちくしょう! アラームだ!",--Damn it! That's the alarm!
pln_framing_stage1_04_any_01 = "聞いてくれ、鉄格子を開くなら監視室のコンピューターにアクセスさせてくれ。",--Listen up, if you can get me access to the computer in the surveillance room I'll get it open.
pln_framing_stage1_04_any_02 = "OK、こうなりゃやりたい放題だ。監視室のコンピューターに俺をアクセスさせろ、こっちから対処してみる。",--OK we can't screw around anymore. Just get me access to the computer in the surveillance room, I'll deal with it remotely.
pln_framing_stage1_04_any_03 = "",--We don't have enough paintings yet! Can someone get me access to the computer in the surveillance room, fast? I'll get it open, don't you worry about your pretty little heads.
pln_framing_stage1_05_any_01 = "",--Alright, that's enough to go now if you want, but if we want more - get me access to the surveillance room so I can see what's on their network.
pln_framing_stage1_05_any_02 = "",--OK crew, you have enough to get the hell out now. If you want more then I need access to the surveillance room. I'll do the rest once you get in.
pln_framing_stage1_06_any_01 = "",--Dammit! If you want everything open again, you're going to need to get into the surveillance room.
pln_framing_stage1_06_any_02 = "",--Everything's locked down - if you want me to fix it then I need to get into the surveillance room.
pln_framing_stage1_06_any_03 = "閉じ込められちまったか。開けて欲しいなら監視室のドアを先に開けろ。",--We're locked down... if you want me to open it up you need to get the surveilance room open fast.
pln_framing_stage1_07_any_01 = "もう待てないぞ、急いであの建物に侵入してくれ。屋上からやってみろ。",--Can't wait around out here - get into that building as fast as you can. Try the roof.
pln_framing_stage1_07_any_02 = "",--We don't have the time to wait around - can't you find a way in? What about the roof?
pln_framing_stage1_08_any_01 = "",--Have a look around - there has to be a way in, we're losing precious time.
pln_framing_stage1_08_any_02 = "",--Have you checked any of the vertical options? There's got to be access to the interior up there.
pln_framing_stage1_08_any_03 = "屋根を確認しろ、侵入経路を探し出せ。仕事を続けろ、時間は無い。",--Check the roof - find your route inside. Get creative, we don't have time.
pln_framing_stage1_09_any_01 = "",--Great, we need at least 3 more, get it to the van. It's in the parking lot next to the gallery.
pln_framing_stage1_09_any_02 = "",--Good, now we need at least 3 more just like this and you need to get them to the van. It's in the parking lot next to the gallery.
pln_framing_stage1_09_any_03 = "",--OK, that's a start, we need three more just like it. Get 'em! Take them to the van in the parking lot next to the gallery and we're in business.
pln_framing_stage1_10_any_01 = "これで半分、あと2つは必要だ。",--That's half, we need 2 more.
pln_framing_stage1_10_any_02 = "",--That's half the required paintings, you need to get the rest before we can roll out.
pln_framing_stage1_10_any_03 = "",--Halfway there with the painting collection. Now just get the rest and we're home free.
pln_framing_stage1_11_any_01 = "",--Thats four, we're good to go now. If you want to get the rest of the paintings thats up to you.
pln_framing_stage1_11_any_02 = "今、4つ手に入れた。必要な4つ分がな。もっと欲しいなら、行け。",--We have four now and four's what we need - now if you want to get more, your move.
pln_framing_stage1_12_any_01 = "バタン、そのドアのかよ。絵画のほうはまだ取り掛かってる。",--Bam, that's the doors, I'm still working on the paintings.
pln_framing_stage1_12_any_02 = "",--There we go, off like a prom dress, I'm still working on the paintings.
pln_framing_stage1_13_any_01 = "よし!ハッキング完了だ、全てロック解除されるぞ。",--Yes! Hack's done, everything should be unlocked now.
pln_framing_stage1_13_any_02 = "OK、OK、セキュリティのハッキングに成功したぞ、ロックは全部解除した。",--OK, OK, I'm done with the security hack, everything's unlocked.
pln_framing_stage1_14_any_01 = "",--Good, with that guy out of the picture, no more cameras.
pln_framing_stage1_14_any_02 = "いいぞ, カメラの警報はこんなもんだろ。",--Great, so much for the camera alarm.
pln_framing_stage1_15_any_01 = "",--SWAT responders, coming in hard. Dig in.
pln_framing_stage1_15_any_02 = "SWAT部隊が建物に突入し始めてるぞ、攻撃に備えろ!",--SWAT units are moving into the building, get ready!
pln_framing_stage1_15_any_03 = "SWATが現場に来るぞ... 押っ始めるか。",--SWATs on the scene... Here we go.
pln_framing_stage1_16_any_01 = "奴ら壁に穴を開けやがった! 押し返せ!",--They just blew a hole in the wall! Hold them back!
pln_framing_stage1_16_any_02 = "SWATが壁を破壊したぞ!",--SWATs just breached the wall! 
pln_framing_stage1_16_any_03 = "奴ら壁を壊してやがるぞ!",--They're breaching the wall!
pln_framing_stage1_16_any_04 = "奴ら壁を爆破してるぞ!",--They're blowing the wall!
pln_framing_stage1_17_any_01 = "接続している... これはちょっとかかるぞ。",--Connecting... This might take a minute.
pln_framing_stage2_intro_a_01 = "よし、到着だ。中に乗りこんで連絡を待て。奴らは車両を取引場所にしてきた。絵を取引しておさらばだ。ここまでは上出来だ。この調子でいこう。",--Right, this is the place. Get to the traincar and look for your contact. They said they'd meet you there. So far it all looks good. Just trade the paintings and get out fast. Keep it rolling.
pln_framing_stage2_01_any_01 = "OKお前達、携帯を取れ。速やかに取引を始めよう。",--OK people, get the phone. Let's get this trade out of the way.
pln_framing_stage2_01_any_02 = "電話が鳴ったな。出てやれ。",--Head over to the phone, the phone's ringing. Make the contact there.
pln_framing_stage2_01_any_03 = "電話が鳴っている。取引を始めるぞ。",--Phone's ringing, time to pick it up and start this trade off.
pln_framing_stage2_02_any_01 = "誰か電話を取れ...",--Someone pick up the phone...
pln_framing_stage2_02_any_02 = "まず電話を取らなければ、取引が始まらないぞ。",--Is someone going to get that? Can't start the trade until you do..
pln_framing_stage2_03_any_01 = "奴らピリピリしてるな。机に絵画を並べて、変な部分が無いか両目を開けてろ。",--They're pretty antsy - just get the paintings on the table and keep both eyes open for anything weird.
pln_framing_stage2_03_any_02 = "嫌な感じだ… さっさとすまそう。机に絵を並べるんだ。",--I don't like it... Let's get this over with as soon as we can, get the paintings on the table. 
pln_framing_stage2_03_any_03 = "騙されてそうだがわからねえ。絵画を机に並べて、スパイダーセンスをピリピリさせてろ。",--This seems fishy but I don't know - get the paintings on the table and keep your spider sense tingling.
pln_framing_stage2_05_any_01 = "これで全部だな。電話を待つぞ。",--That's everything, wait for their call.
pln_framing_stage2_05_any_02 = "OK、奴らがさっさと連絡してくれるよう祈ろう。",--OK, now let's just hope they call you fast.
pln_framing_stage2_05_any_03 = "オーライ、次は奴らが電話をかけるはずだ。早いとこしてくれよ。",--Alright, they just need to call you back. Faster the better.
pln_framing_stage2_06_any_01 = "それだな、電話に出ろ。",--There it is, get the phone.
pln_framing_stage2_06_any_02 = "ビンゴ。回収しろ。",--Bingo. Pick it up.
pln_framing_stage2_06_any_03 = "OK、奴らからの電話だな。",--OK, that's them calling.
pln_framing_stage2_07_any_01 = "OK、全員列車の中に入れ。",--OK folks, everyone into the train.
pln_framing_stage2_07_any_02 = "全員列車の中に入ってくれ。",--Get everyone into the train.
pln_framing_stage2_09_any_01 = "OK、いいか、絵一枚で札束一袋だ。",--OK now remember, one bag of cash for every painting. 
pln_framing_stage2_09_any_02 = "よし、ここで待とう。ヘリに全ての絵画を投げ渡して現金の入ったバッグを回収するぞ。俺達に必要なことは我慢と幸運だ。",--Now we wait. Remember we get a bag of cash for every painting we throw into the chopper. All we need to do is be patient and lucky. 
pln_framing_stage2_10_any_01 = "よし、いいぞ。建物の反対側にVanを待たせてある。そのまま行って車に積み込んだら、今日の仕事は終わりだ。",--OK good, now there is a van waiting for you on the other side of that building. Go through, load up the car, and we're done for the day.
pln_framing_stage2_10_any_02 = "よし、これで終わりだ。建物の向こう側にVanを待たせてある。中を通って、車に積み込んだら、完了だ。",--We're done here, there's a van waiting on the other side of the building. Go on through, load the car up, and we're done.
pln_framing_stage2_12_any_01 = "よし、よし。これであの民主主義者を襲う時楽になるはずだ…",--Good, good. This'll make our lives easier when we hit the Democrat...
pln_framing_stage2_12_any_02 = "これであの民主主義者の屋敷に侵入する時楽になる。",--This is definitely going to make our lives easier when we go in to hit the Democrat's place.
pln_framing_stage2_13_any_01 = "SWATだ! 順調すぎると思ったぜ!",--SWAT! I knew it was too easy!
pln_framing_stage2_13_any_02 = "ちくしょう! SWATの待ち伏せだ、気付かなかった!",--Dammit! SWAT ambush. I didn't see it!
pln_framing_stage2_13_any_03 = "現金を穫って空っぽにしろ、今すぐだ!",--Get the money and clear out ASAP!
pln_framing_stage2_16_any_01 = "ドアだ、奴らドアを塞ぎやがった! 他に脱出路があるはずだ!",--That's the doors, they blocked off the doors! There's gotta be another way out!
pln_framing_stage2_17_any_01 = "ECM jammerならドアを開けられるが... 無いなら別の方法が必要だな。",--Only an ECM jammer's going to get that door open...Otherwise you need another way around.
pln_framing_stage2_17_any_02 = "クソ、誰かECM jammerは持ってるか？ドアを突破するにはそれしかない。 無理なら別のルートを行け。",--Dammit does anyone have an ECM jammer - that's about the only thing that'll crack that door. Othewise you need another route.
pln_framing_stage2_18_any_01 = "このトンネルで倉庫に行ける。",--Those tunnels will lead you into the warehouse.
pln_framing_stage2_18_any_02 = "このトンネルで倉庫とやらに入れると思う。",--I think those tunnels will get you into the warehouse folks.
pln_framing_stage2_18_any_03 = "良いぞ‥これで倉庫に行けるはずだ。",--Good move.. that's bound to lead to the warehouse.
pln_framing_stage2_19_any_01 = "",--You clever bastards, you'll get around them using those tunnels.
pln_framing_stage2_19_any_02 = "",--Very smart to use the tunnels like that - very professional.
pln_framing_stage2_19_any_03 = "",--Hell of a good move to use the tunnels - they'll be off-balance.
pln_framing_stage2_20_any_01 = "作業員に見つかるな、でないと全部バレちまうぞ。",--Don't let the workers see you or they might blow the whole deal.
pln_framing_stage2_20_any_02 = "作業員の近くでは安全のために姿勢を低くしろ。",--Keep a low profile near the workers to be safe.
pln_framing_stage2_20_any_03 = "まだサツに見つけられたくないなら、あの作業員共に注意したほうがいいぞ。",--Unless you still want the cops to show up you better be careful around those workers
pln_framing_stage2_20_any_04 = "たぶんただの作業員だろうが、全く無視していいってわけでもないぞ。姿勢を低くしろ。",--Hey they might be workers but they're not dumb and blind - keep your profile low.
pln_framing_stage3_intro_01 = "ここは警備員でいっぱいになってるぞ。お前たちがそこから持ってこなきゃならない電子機器は・・・携帯電話、ラップトップ、ハードドライブだ。忍び込み、金庫を探すぞ。",--This place is crawling with guards. You need to grab anything technological of his that isn't nailed down - mobile phones, laptops, hard drives. Slip in and find the vault.
pln_framing_stage3_intro_01b = "バンッとやって機械を屋上に持ってきてお金持ち・・・ということだ。",--Get to the roof with the gadgets and bang, we're gold - literally. 
pln_framing_stage3_01_any_01 = "さてプランは、進入し、指定した物を回収することだ。そしたら屋上で俺たちのお仕事場に接続してやるんだ。",--So the plan is, go in, get me the following objects. When you have them we'll connect them to our station on the roof.
pln_framing_stage3_02_any_01 = "必要なのは議員のPhone、Tablet、Laptop、 それと外付けHard driveが2つだ。",--We need his phone, his tablet, his laptop and two external hard drives.
pln_framing_stage3_03_any_01 = "屋上の端末から仕掛けた隠しカメラにアクセス出来るぞ。",--You can access the hidden cameras in the paintings with the laptop on the roof.
pln_framing_stage3_04_any_01 = "カメラがたくさん有ると良いな。全てのデバイスの捜索が楽になるからな。",--I hope you got a lot of cameras. It'll make it easier for us to find all the devices.
pln_framing_stage3_05_any_01 = "よくやった、Laptopを見つけたな。",--Great, you found the laptop.
pln_framing_stage3_06_any_01 = "議員のPhoneだ、いいぞ。",--That's his phone. Good.
pln_framing_stage3_07_any_01 = "議員のTablet PCだな。カンペキだ。",--That's the tablet PC. Perfect.
pln_framing_stage3_08_any_01 = "よし、それが外付けHard driveだ。",--That's the external hard drive. Nice.
pln_framing_stage3_09_any_01 = "それが外付けHard driveの1つだ。",--That's one of the external hard drives.
pln_framing_stage3_10_any_01 = "それが外付けHard driveの2つ目だ。",--That's the second external hard drive.
pln_framing_stage3_11_any_01 = "もう1つ、探し続けろ。",--One more, keep looking.
pln_framing_stage3_12_any_01 = "あと2つだ、よく探せ。",--Two more, keep on searching.
pln_framing_stage3_13_any_01 = "これで全部だ。",--Thats all of them.
pln_framing_stage3_14_any_01 = "やったな! 早速屋上の拠点に運んで、 デバイスを接続しろ。",--Great! Now get them up to the station on the roof and connect them.
pln_framing_stage3_15_any_01 = "屋上の拠点でデバイスを接続しろ。",--Connect the devices to the station on the roof.
pln_framing_stage3_16_any_01 = "大丈夫だ、アクセスしたぞ。そのまま待ってろ...",--Alright now, I have access, hold on a sec...
pln_framing_stage3_17_any_01 = "OK! 上手くいったな。必要なものはそろった。これで奴のパソコンに接続できるはずだ。",--OK! We're gold. I think I got everything we need. You should be able to access his desktop computer now.
pln_framing_stage3_18_any_01 = "パソコンはオフィスにある。",--It's located in his office.
pln_framing_stage3_19_any_01 = "いいぞ、OK、もう金庫を開けられるぞ。ついでに金庫カメラも操作出来る様にしたからな。",--Good, OK, you can open the vault now. I have turned on the vault's camera feed as well.
pln_framing_stage3_20_any_01 = "ちょっと問題が出たな... 実は金庫が何処か解らないんだ、物理的にな。",--There's just a little problem... I don't actually know where the vault is, physically.
pln_framing_stage3_21_any_01 = "つまり、お前らが金庫を探さなきゃなんねえってことだ。資料によると……本棚に繋がってるらしい。言っとくが、そのままにしておくと警備員に通報されるぞ。",--So this means you have to find it. References seem to indicate it's... Connected to a bookshelf. I know, leave it to a politician to be cliche.
pln_framing_stage3_22_any_01 = "本棚を探せ、 棚を動かして何か無いか確認するんだ。",--Look for bookshelves, see if you can move them and find something.
pln_framing_stage3_23_any_01 = "ほら、さっさとヤツに濡れ衣を着せてやろう。屋上に登って、手下からCokeを受け取れ。",--There you go.  Now let's frame this guy, get up to the roof, and our guy will throw you the coke.
pln_framing_stage3_24_any_01 = "Cokeを金庫に運んで金庫室の前に配置しろ。",--Carry the coke down to the vault and plant it outside in the pre vault room.
pln_framing_stage3_25_any_01 = "そうだ、いい仕事っぷりだ。ズラかる準備はできたが突っ込んで金庫をキレイにしたいってんなら話は別だ。待ってるよ。",--That's it, fine work. The escape is ready for you. Unless you want to stick around and clean out the vault. Either way the vehicle's waiting.
pln_framing_stage3_26_any_01 = "よくやった、逃げるぞ。",--Good job, we are gone.
pln_framing_stage3_27_any_01 = "もっと儲けたいなら、奴のデスクトップPCを使え。金庫を開けることができるはずだ。",--If you want to go for more, use his desktop PC, it should open the vault up for you.
pln_framing_stage3_28_any_01 = "よーし、金庫の御開帳だ。だがレーザーには気をつけろよ、警報と直結している。",--Alright, vault is popped, but watch out for those lasers, they connect directly to the alarm
pln_framing_stage3_29_any_01 = "センサーを止めなくちゃな。",--We have to shut them off.
pln_framing_stage3_30_any_01 = "もう一度議員のコンピュータを使え。気をつけろ、センサーは少しの間しか消せないからな。",--Use his computer again, be careful, they only go down for a small amount of time.
pln_framing_stage3_31_any_01 = "カメラを使って確認してくれ。もう一度センサーを切るんだ。",--Use the camera to see when they turn on, and then turn them off again.
pln_framing_stage3_32_any_01 = "クソッタレアラームだ！PlanBにシフトするぞ、お前ら！",--That's the damn alarm! Time to shift to plan B, folks. 
pln_framing_stage3_33_any_01 = "奴のサーバー室を見つけて侵入してくれ。",--Find his server room and get in there.
pln_framing_stage3_34_any_01 = "侵入する為のKeycardがあるか確かめろ、無いならドアをドリルで開けなきゃならないぞ。",--See if you can find the keycards to  get in there, otherwise we have to drill the doors.
pln_framing_stage3_35_any_01 = "いいぞ、そこがサーバー室だ。そのコンピュータを操作しろ、全ファイルをアップロードするぞ。",--Great, that's the server room, start the computer in there, we need to upload all the files.
pln_framing_stage3_36_any_01 = "時間をくれ、データが多いし回線が遅い",--It'll take some time, lots of data to up and a small pipe.
pln_framing_stage3_37_any_01 = "",--Now hopefully they won't notice anything. Because we're just that lucky.
pln_framing_stage3_39_any_01 = "絶対に電源供給を途絶させるな。",--Make sure you keep the power up.
pln_framing_stage3_40_any_01 = "奴ら電源を切りやがった! 戻すんだ!",--They cut the power! Get it back up!
pln_framing_stage3_41_any_01 = "電源を戻してこい!",--Get the power back up!
pln_framing_stage3_42_any_01 = "ブレーカーを探せ、電源を復旧しろ。",--Look for a circuit breaker to get the power back up.
pln_framing_stage3_43_any_01 = "よし、ファイルは全てアップロードした、 これでいけるだろ。",--Alright, the files are all uploaded, it should do the trick.
pln_framing_stage3_44_any_01 = "俺達のヘリは報道のヘリに紛れて、そっちに向かってる。",--Our chopper is coming in, he'll blend in with all the news choppers.
pln_framing_stage3_45_any_01 = "脱出ヘリに乗り込め!",--Get to the chopper to escape!
pln_framing_stage3_46_any_01 = "奴ら電源を落とそうとしてるぞ!させるな!",--They're gonna try to kill the power! Don't let them!
pln_framing_stage3_46_any_02 = "仕事を成功させたければサツをブレーカーに近づけるな!",--Keep the cops off the circuit breakers if you want to make it!
pln_framing_stage3_46_any_03 = "奴らに電源を落とさせる訳にはいかないぞ、進行が全部遅くなっちまう!",--You can't let them kill the power, it'll slow everything down!
pln_framing_stage3_47_any_01 = "何がなんでもあのウジ虫共に電源を落とさせるな!",--Whatever you do don't let the sons of bitches cut the power!
pln_framing_stage3_47_any_02 = "奴らをブレーカーから引き剥がし続けるんだ、聞こえてるか？",--Keep them the hell away from the circuit breaker, you hear me?
pln_framing_stage3_48_any_01 = "じゃあこの生中継をそのまま全てのメディアに垂れ流すぞ。奴らは食い付くだろうさ。",--So I'm going to send this feed live to all the media outlets as you're uploading. They're gonna eat this up.
pln_framing_stage3_48_any_02 = "よし、もうちょい面白いことしよう。メディアに中継を垂れ流してやった、アップロード中にな。釘付けだぜ。",--OK, to make things a little more interesting I'm sending this feed live to all the big media outlets while we upload. Lots of coverage.
pln_framing_stage3_50_any_01 = "すぐマスコミのヘリが押し寄せてくるぞ。逃走ヘリか？それ紛れ込ませた",--Pretty soon we're going to be swamped with news choppers. Our escape chopper? Blend right in.
pln_framing_stage3_50_any_02 = "メディアがヘリで見物にきやがっても、俺らの逃走ヘリちゃんなんか気にしてるヒマねぇな",--When all that media shows up in their choppers, no one's gonna look sideways at our escape bird. 
pln_framing_stage3_50_any_03 = "俺の考えじゃ、報道ヘリ共が俺たちの乗るヘリをうまくカモフラージュしてくれると思うんだが、どうだ?",--Bain's got a little plan - I think all those media choppers are a convenient smokescreen for our escape chopper, don't you?
pln_framing_stage3_51_any_01 = "OK!もうすぐだ！",--OK, we're almost done!
pln_framing_stage3_51_any_02 = "すぐ着くぞ！",--It's getting there!
pln_framing_stage3_51_any_03 = "",--Almost! Almost, almost...
pln_framing_stage3_51_any_04 = "",--This upload isn't going fast enough, dammit!
pln_framing_stage3_51_any_05 = "",--We're going to be done soon - I hope.
pln_framing_stage3_51_any_06 = "",--It's uploading... It's almost there.
pln_framing_stage3_51_any_07 = "",--Christ... Is it buffering? Go faster! Why don't they have Google fiber... Goddam American broadband.
pln_framing_stage3_52_any_01 = "",--Get that gold up to the roof, put it in the bag on the zip line, we are bringing it home!
pln_framing_stage3_52_any_02 = "",--Hustle that gold onto the roof, get it into the bag on the zipline, we're taking it. 
pln_framing_stage3_53_any_01 = "",--Whenever you're ready, I want you on the roof, then we'll get you outta there with the zipline.
pln_framing_stage3_53_any_02 = "",--When you're ready, get to the roof and we'll get you clear with the zipline.
