savefile_progress_description = "สถิติของผู้เล่น",--Player statistics and game progression.
savefile_game_title = "PAYDAY 2",--PAYDAY 2
savefile_autosave = "บันทึกอัตโนมัติ",--$TEXT_WITH_DATE; - AUTO SAVE
savefile_removing = "กำลังลบ...",--Removing...
savefile_loading = "โหลด...",--Loading...
savefile = "",--$TEXT; - $DATE;
savefile_empty = "[เซฟใหม่]",--[New Save File]
savefile_setting_description = "การตั้งค่าของผู้เล่น",--User specific game settings.
savefile_progress = "บันทึกของผู้เล่นอยู่ในเวอร์ชั่น: $VERSION; หรือสูงกว่า.",--Player progression: Version $VERSION; or higher is required.
savefile_setting = "การตั้งค่าอยู่ในเวอร์ชั่น: $VERSION; หรือสูงกว่า",--Game settings: Version $VERSION; or higher is required.
savefile_saving = "บันทึก...",--Saving...
