wp_xsub_watervalve = "เปิดวาล์ว",--Open the Valve
wp_uc_computer = "ดำเนินการเจาะระบบต่อ",--Continue Hack
wp_xsub_waterhose = "ดึงสายยาง",--Pull the Hose
wp_xsub_safe = "ตรวจสอบตู้นิรภัย",--Investigate the Safe
wp_xsub_door = "เปิดประตู",--Open the Door
wp_ap_escape = "หลบหนี!",--Escape!
wp_xsub_hack = "เขียนทับระบบ",--Override the System
wp_xsub_shelter = "เข้าไปในเชลเตอร์",--Get to the Shelter
wp_xsub_sewer = "ท่อระบายน้ำเสีย",--Sewer
wp_uc_saw = "เจาะรถลิโม",--Saw the Limo
wp_xsub_tnt = "วางอุปกรณ์",--Place the Charge
wp_xsub_watertap = "เปิดก็อกน้ำ",--Open the Tap
wp_xsub_outlet = "เสียบปลั๊กไฟ",--Plug into Power Outlet
wp_xsub_bbq = "พูดคุยกับ Mitchell",--Talk to Mitchell
wp_bridge_escape = "หลบหนี!",--Escape!
wp_xsub_escape = "หลบหนี!",--Escape!
wp_bank_escape = "หลบหนี!",--Escape!
wp_xsub_power = "เปิดการจ่ายพลังงาน",--Turn on the Power
wp_uc_check_limo = "ตรวจสอบรถลิโม่",--Check the Limo
wp_uc_escape = "หลบหนี!",--Escape!
wp_uc_power = "เปิดการจ่ายพลังงาน",--Get the Power Back On
wp_uc_interogate = "ถามรหัสผ่าน",--Get the Code Words
wp_uc_keyboard = "ใช้งานคีย์บอร์ด",--Use the Keyboard
wp_str_esc = "หลบหนี!",--Escape!
wp_slaughterhouse_escape = "หลบหนี!",--Escape!
