dialog_cheated_host = "ไม่สามารถเล่นเซิฟเวอร์ที่โกงได้",--Couldn't play on an cheated server.
dialog_new_unlock_title = "ขอแสดงความยินดี!",--Congratulations!
dialog_ask_save_progress_backup = "ต้องการที่จะบันทึกเซฟสำรองหรือไม่",--Save progress backup?
dialog_the_host_has_left_the_game = "โฮสต์ได้ออกจากเกม",--The host has left the game
dialog_information_title = "ข้อมูล",--Information
dialog_dropin_title = "ผู้เล่น $USER; กำลังเข้าร่วมเกม",--$USER; is joining the game
dialog_mp_groupinvite_message = "คุณต้องการที่จะเข้ากลุ่ม $GROUP; หรือไม่?",--Do you wish to join $GROUP;?
dialog_new_patch = "ต้องการการอัปเดตเพื่อเข้าสู่โหมดออนไลน์",--An update is needed to access online features.
dialog_transaction_successful = "การดำเนินการเสร็จสิ้น",--TRANSACTION SUCCESSFUL
dialog_fail_load_dlc_corrupt = "ส่วนเสริมของเกมได้รับความเสียหาย กรุณายืนยันเกมอีกครั้ง",--Corrupted downloadable content detected. Please go to the Memory section of the Dashboard, delete the corrupted content and download it again.
dialog_error_title = "ผิดพลาด",--Error
dialog_mp_send_invite_message = "คุณต้องที่จะเชิญ $FRIEND; หรือไม่",--Do you wish to send a game invite to $FRIEND;?
dialog_err_not_signed_in_PS3 = "คุณต้องเข้าสู่ระบบ PlayStation ก่อนถึงจะใช้โหมดออนไลน์ได้",--You must sign in to "PlayStation Network" to make use of network modes.
dialog_npcommerce_checkout_fail = "การตรวจสอบผิดพลาด",--Checkout failed
dialog_blackmarket_lost_mods_warning = "(ชิ้นส่วนการปรับแต่งจะถูกคืนเข้าสู่ช่องเก็บของหลังจากลบ)",--(Your removed modifications will be placed in the inventory)
screen_autosaving_warning_PS3 = "เกมนี้เป็นระบบเซฟอัตโนมัติ $NL;กรุณาอย่าปิดเครื่อง Playstation ระหว่างเห็นสัญลักษณ์นี้ :",--This game saves data automatically at certain points.$NL;Please don't turn off your PlayStation®4 system when the following icon is displayed:
dialog_cs_claim_rewards = "รับรางวัล",--Claim Rewards
dialog_cant_continue_cs_title = "ไม่สามรถทำต่อ",--This can not Continue
dialog_blackmarket_slot_item = "[ช่อง $slot;] $item;",--[SLOT $slot;] $item;
dialog_safehouse_text = "คุณยังไม่ได้เยี่ยมชมเซฟเฮ้าส์เลย ต้องการที่จะไปดูตอนนี้ไหม?",--You haven't visited the safe house yet. Would you like to go there now?
dialog_blackmarket_buy_mask_slot = "การซื้อนี้จะปลดล็อคช่องเก็บของสำหรับหน้ากาก.$NL;$NL;จะมีค่าใช้จ่าย $money;",--Buying this will unlock one more mask slot.$NL;$NL;This will cost you $money;.
dialog_err_failed_creating_lobby = "เกิดข้อผิดพลาดในการสร้างเกม",--Failed to create game.
dialog_err_room_is_full = "ห้องนี้เต็มแล้ว กรุณาลองห้องอื่น",--This room has been filled, please try another one.
dialog_return_to_cs_lobby = "คุณแน่ใจหรือไม่ที่จะกลับไปยังล็อบบี้ Crime Spree",--Are you sure you want to return to the Crime Spree lobby?
dialog_no = "ไม่",--No
dialog_mp_vote_kick_message = "การโหวตเพื่อเตะผู้เล่น $name; ออกจากเกมและจะสิ้นสุดภายใน $time; วินาที.",--A vote has been initiated to kick $name; from the game. The vote will end in $time; seconds.
sm_moving_up_desc = "โอเค ฉันบอกไว้แล้วนะว่ามีคนกำลังมองอยู่ คนหนึ่งกำลังสนใจในตัวคุณอยู่ ฉันคิดว่าน่าจะมีผู้ติดต่อรายใหญ่เข้ามา แต่งานก็จะยากขึ้นและคุณก็ต้องเตรียมตัวให้พร้อมกลับมาเมื่อเตรียมตัวเสร็จแล้วละกันเดี๋ยวจะจัดการให้",--OK, I told you before that people are watching you, One guy in particular has an interest in you. I might have something big coming up with this new contact, but the job he has in mind will be difficult and you have to get ready for it. Come back when you've prepped a bit more and I will set you up.
dialog_unlock_skill_switch_free = "สิ่งนี้ไม่เสียค่าใช้จ่าย",--This one is free of charge.
dialog_cs_claim_rewards_text = "คุณแน่ใจหรือไม่ที่จะรับรางวัล Crime Spree?$NL;$NL;การกระทำนี้จะสิ้นสุดการเล่น Crime Spree ของคุณและคุณต้องเริ่มอันใหม่ถ้าหากคุณต้องการจะเพิ่มรางวัลอีกครั้ง.",--Are you sure you want to claim your Crime Spree rewards?$NL;$NL;This will end your current Crime Spree lobby, and you will have to start a new one to gain rewards again.
dialog_blackmarket_mod_conflict = "การปรับแต่งนี้ไม่เข้ากันกับและจะถูกลบออก :$mods;",--These modifications are not compatible and will be removed:$mods;
dialog_blackmarket_finalize_item = "$ITEM;$NL; คุณกำลังจะยืนยันการปรับแต่ง, การกระทำนี้ไม่สามารถย้อนกลับได้และจะมีค่าใช้จ่าย $money;",--$ITEM;$NL; You are about to finalize your customizations, this process is irreversible and will cost you $money;.
dialog_dlc_require_restart = "โปรดทราบ",--Attention
dialog_fail_load_progress_corrupt = "การบันทึกเสียหาย ข้อมูลนี้จะถูกลบออก",--Progress corrupt. Data will now be deleted.
dialog_game_is_installing_menu = "ส่วนนี้ยังไม่ถูกติดตั้งกรุณาลองอีกครั้งหลักจากติดตั้งสำเร็จ",--This portion of the title has not been installed yet. Please try again when installation is complete.
dialog_too_low_level_ovk145 = "OVERKILL 145+ ไม่สามารถเล่นได้กับผู้เล่นที่มีระดับต่ำกว่า 145.",--OVERKILL 145+ cannot be played with people below reputation level 145.
dialog_mp_kick_player_message = "ผู้เล่น $PLAYER; จะถูกขับไล่ออกจากเกม คุณต้องการดำเนินการต่อหรือไม่",--Player $PLAYER; will be kicked from this game. Do you wish to continue?
dialog_cant_continue_cs_text = "คุณไม่สามารถเล่น Crime Spree ของคุณต่อได้เนื่องจาก Continental Coins ของคุณมีไม่เพียงพอ ที่จะเล่นต่อในระดับ $level;$BTN_SPREE_TICKET; และคุณต้องการ Continental Coins อีก $cost;",--You can not continue your Crime Spree as you do not have enough Continental Coins. In order to continue from $level;$BTN_SPREE_TICKET; you need $cost; Continental Coins.
dialog_connection_to_host_lost = "การเชื่อมต่อล้มเหลว",--Connection to the host has been lost
dialog_skills_reseted_title = "โปรดทราบ",--Please note
dialog_abort_mission_text = "คุณต้องการที่จะยกเลิกงานจ้างปัจจุบันหรือไม่? $NL;$NL;คุณและทีมของคุณจะกลับไปยังหน้าวางแผนเพื่อเลือกงานจ้างใหม่.",--Are you sure you would like to terminate the current contract?$NL;$NL;You and your crew will be returned to the planning phase where a new contract can be selected.
ps4_presence_Idle = "",--In the menus
dialog_dlc_require_restart_desc = "คุณต้องเริ่มเกมใหม่เพื่อเข้าถึงเนื้อหาใหม่",--You need to restart PAYDAY 2 to access your new items.
dialog_cs_crash_fail_text = "Crime Spree ของคุณล้มเหลวเนื่องจา  การปิดตัวที่ผิดพลาดของตัวเกม.$NL;คุณยังสามารถจ่าย Continental Coin เพื่อเล่นต่อ",--Your Crime Spree has failed due to an unexpected closure of the game.$NL;You can still pay the Continental Coin cost to continue.
dialog_mp_pending_invite_message = "คุณมีคำเชิญเข้าร่วมเกมค้างไว้อยู่ เข้าสู่ระบบ PlayStation และเลือกเมนูเล่นออนไลน์",--YOU HAVE A PENDING GAME INVITE. SIGN IN TO "PlayStation Network" USING THE 'PLAY ONLINE' OPTION IN THE MAIN MENU TO JOIN THE GAME.
dialog_bm_mask_custom_final_title = "คุณแน่ใจแล้วหรือไม่ ?",--Are you sure?
dialog_skills_place_title = "คุณแน่ใจแล้วหรือไม่ ?",--Are you sure?
dialog_are_you_sure_you_want_stop_cs = "คุณแน่ใจแล้วหรือไม่ที่จะหยุดเล่น Crime Spree ?$NL;$NL;การกระทำนี้จะสิ้นสุด Crime Spree ของคุณและไม่มีรางวัลสำหรับคุณ",--Are you sure you want to stop your Crime Spree?$NL;$NL;This will end your current Crime Spree, and no rewards will be given to you.
dialog_xp_to_specialization = "ค่าประสบการณ์ที่ถูกแปลงเป็นค่า Perk",--XP to Perk Conversion
dialog_connect_controller_text_X360 = "กรุณาเชื่อมต่อ Xbox โทรลเลอร์อีกครั้งและกดปุ่ม $BTN_A;",--Please reconnect the Xbox One Wireless Controller and press $BTN_A;.
dialog_mp_kicked_out_title = "ถูกขับไล่ออก",--Kicked out
dialog_mp_invite_wrong_version_message = "เกมที่คุณได้รับเชิญนั้นมีเวอร์ชั่นที่สูงกว่า",--The game you have been invited to is running another version of PAYDAY 2. You are unable to join.
dialog_blackmarket_mod_cost = "จะมีใช้ค่าใช้จ่าย $money;",--This will cost you $money;.
dialog_err_wrong_version_message = "เกมที่คุณกำลังเข้าร่วมนั้นเป็นเวอร์ชั่นอื่น",--The game you are trying to join is running another version of PAYDAY 2. You are unable to join.
dialog_key_binding_collision = "ปุ่ม '$KEY;' ถูกใช้งานกับ '$MAPPED;' แล้ว",--Key "$KEY;" is already mapped to "$MAPPED;", please remap it first.
dialog_accept = "ยอมรับ",--Accept
dialog_blackmarket_buy_item = "คุณต้องการที่จะซื้อ $item;$NL;ในราคา $money; หรือไม่?$NL;$NL;$num_in_inventory;",--Do you really want to buy $item;?$NL;$NL;It will cost you $money;.$NL;$NL;$num_in_inventory;
dialog_show_restart_game_message = "คุณต้องการที่จะเริ่มเกมใหม่หรือไม",--Are you sure you want to restart current game?
dialog_inactive_user_accepted_invite = "คำเชิญได้รับการยอมรับจากผู้ใช้แล้วคำเชิญนี้จะสำเร็จหลังจากกดปุ่ม Start",--An invitation has been accepted by an inactive user. The invitation is successfully completed after pressing START.
dialog_blackmarket_mask_sell_mod_readded = "$mod; จะถูกคืนเข้าคลังเก็บของ ของคุณ",--$mod; will return to your inventory.
dialog_new_unlock_weapon_mods = "คุณพึ่งได้ทำการปรับแต่งอาวุธครั้งแรก. คุณสามารถที่จะซื้ออาวุธแล้วเลือก ปรับแต่งอาวุธ จากเมนูได้.$NL;จากเครื่องหมายที่เห็นคืออุปกรณ์ปรับแต่งอาวุธที่คุณได้รับล่าสุด",--You just got your first weapon modification. You can access the weapon modification screen by selecting a bought weapon and choosing MODIFY WEAPON from the menu.$NL;Follow the exclamation marks on your bought weapons to find your latest drops.
dialog_are_you_sure_you_want_leave = "คุณต้องการที่จะออกจากล็อบบี้นี้หรือไม่",--Are you sure you want to leave this lobby?
dialog_unlock_skill_switch = "คุณแน่ใจที่จะปลดล็อคเซ็ตความสามารถใหม่หรือไม่.$NL;$NL;$cost_text;",--You are about to unlock a new skill set.$NL;$NL;$cost_text;
dialog_fail_load_progress_wrong_version_WIN32 = "ไฟล์ความคืบหน้าผิดเวอร์ชั่น ข้อมูลจะถูกลบ",--Progress file wrong version. Data will now be deleted.
dialog_game_permission_changed = "การตั้งค่าของเกมถูกเปลี่ยน คุณไม่สามารถเข้าร่วมได้อีกต่อไป",--The game settings have changed, you no longer have permission to join
dialog_err_failed_joining_lobby = "การเข้าร่วมเกมล้มเหลว",--Failed joining game.
dialog_on_server_left_message_cs = "$message;$NL;Crime Spree ของคุณจะยังอยู่ แต่ค่าของคุณจะไม่ถูกเปลี่ยน$NL;$NL;คุณสามารถกลับไปที่เมนูหลักได้แล้ว",--$message;$NL;Your Crime Spree is still active, but your rank has not changed.$NL;$NL;You will now be returned to the main menu.
dialog_mp_vote_kick_response_title = "โหวตขับไล่",--Vote Kick
dialog_new_unlock_textures = "คุณเพิ่งได้รับส่วนประกอบชิ้นแรกสำหรับการปรับแต่งหน้ากาก.$NL;เพื่อปรับแต่งหน้ากากคุณต้องการพื้นผิวและสีของพื้นผิว",--You just got your first pattern for mask customization.$NL;To customize a mask you will need a material, pattern and a pair of colors.
dialog_mp_vote_restart_response_title = "โหวตเริ่มเกมใหม่",--Vote Restart
dialog_fail_load_progress_wrong_version_retry = "ไฟล์ความคืบหน้าผิดเวอร์ชั่น. ต้องการเวอร์ชั่น $VERSION; หรือสูงกว่า ต้องการที่จะลองโหลดไฟล์ใหม่หรือไม่?",--Progress file wrong version. Version $VERSION; or higher is required. Try loading again?
dialog_blackmarket_slot_mask_remove_suffix = "การปรับแต่งจะถูกขายด้วยจำนวน $money;",--Customizations will be sold for $money;.
dialog_vote_kick_no = "ไม่ขับไล่",--Don't Kick
dialog_connect_controller_title = "ไม่พบคอลโทรเลอร์ไร้สาย",--No Wireless Controller
dialog_unlock_skill_switch_spending_offshore = "มีค่าใช้จ่ายโดยเงินสดทั้งหมด $spending; และค่าใช้จ่ายจากเงิน Offshore ทั้งหมด $offshore;",--It will cost you $spending; spending cash and $offshore; offshore cash.
dialog_signin_change_title_X360 = "เปลี่ยนการเข้าสู่ระบบ",--Sign-in change
dialog_authentication_host_fail = "Steam ไม่สามารถยืนยันตัวตน Steam ID สำหรับโฮสต์ได้",--Steam could not authenticate Steam ID for the host.
dialog_npcommerce_empty_store = "ยังไม่มีเนื้อหาที่พร้อมให้ดาวน์โหลด. กรุณาลองใหม่ภายหลัง",--There is no content available for download at this time. Please try again later.
dialog_continue_cs_title = "ดำเนินการ Crime Spree ต่อ",--Continue Crime Spree
dialog_are_you_sure_you_want_stop_cs_refund = "คุณต้องการที่จะสิ้นสุด Crime Spree ของคุณหรือไม่?$NL;$NL;การกระทำนี้จะสิ้นสุด Crime Spree ของคุณและไม่มีรางวัลสำหรับคุณ. เหรียญ Continental Coins ที่คุณได้ลงทุนไปทั้งหมด $coins; จะถูกคืนเข้าสู่ตัวคุณ",--Are you sure you want to stop your Crime Spree?$NL;$NL;This will end your current spree, and no rewards will be given to you. Your initial investment of $coins; Continental Coins will be returned to you.
dialog_blackmarket_item = "$item;",--$item;
dialog_gage_assignment_completed_title = "คุณได้รับข้อความใหม่",--YOU HAVE A NEW MESSAGE
dialog_connect_controller_text_WIN32 = "กรุณาเชื่อมต่อคอลโทรเลอร์",--Please insert controller.
dialog_internet_connection_required = "ต้องการการเชื่อมต่อเพื่อใช้งานเนื้อหานี้",--A network connection is needed to access the online portions of this title.
legal_text = "PAYDAY 2 © 2016 Starbreeze AB. สงวนลิขสิทธิ์.  PAYDAY 2, PAYDAY, Starbreeze, Starbreeze Studios, และเครื่องหมาย Starbreeze เป็นเครื่องหมายจดทะเบียนการค้าของ Starbreeze AB ในประเทศสวีเดนและประเทศอื่นๆ. จัดจำหน่ายโดย 505 Games. 505 Games และเครื่องหมาย 505 Games เป็นเครื่องหมายจดทะเบียนการค้าของ 505 Games S.r.l. เครื่องหมายการค้าอื่นๆ ทั้งหมดที่เป็นทรัพย์สินของเจ้าของที่เกี่ยวข้อง.",--PAYDAY 2 © 2019 Starbreeze AB. All rights reserved.  PAYDAY 2, PAYDAY, Starbreeze, Starbreeze Studios, and the Starbreeze logo are trademarks or registered trademarks of Starbreeze AB in Sweden and/or other countries. Published by 505 Games. 505 Games and the 505 Games logo are registered trademarks of 505 Games S.r.l. All other trademarks are the property of their respective owners.
dialog_load_wrong_user_WIN32 = "ข้อมูลของการบันทึกอยู่ภายใต้ชื่อผู้ใช้อื่น จะไม่มีการโหลดบันทึก",--Save data belongs to a different user. No progress will be loaded.
dialog_does_not_own_heist = "คุณไม่ได้เป็นเจ้าของงานจ้างนี้และไม่สามารถเข้าร่วมได้",--You do not own this heist and are unable to join this server.
dialog_new_unlock_armors = "การอัพเกรดเกราะครั้งแรกของคุณถูกปลดล็อคแล้ว. คุณสามารถเปลี่ยนเกราะของคุณจากคลังเก็บของได้เลย",--Your first armor upgrade has been unlocked. You can change your armor from both Inventory and Job Overview.
dialog_skilltree_reseted = "เกิดการเปลี่ยนกับความสามารถ$NL;$NL;ความสามารถจะถูกคืนค่าและคืนเงินของคุณเช่นกัน",--Changes have been made to the skill tree.$NL;$NL;All your skills have been reset and your skill points as well as your cash has been refunded.
dialog_new_unlock_masks = "คุณเพิ่งได้รับหน้ากากมาครั้งแรก หน้ากากทั้งหมดจะถูกเก็บไว้ในที่เก็บของของคุณ คุณสามารถย้ายไปยังช่องว่างไหนก็ได้และคุณสามารถสวมใส่และปรับแต่งได้อย่างเต็มที่",--You just got your first mask. All masks dropped will be placed in your stash. They can then be moved to an empty mask slot from where you can wear them and also customize if you got all the components for it.
dialog_new_unlock_colors = "คุณเพิ่งได้สีแรกสำหรับการตกแต่งหน้ากาก$NL; ในการตกแต่งหน้ากากคุณจะต้องใช้วัสดุรูปแบบและคู่ของสี",--You just got your first pair of colors for mask customization.$NL;To customize a mask you will need a material, pattern and a pair of colors.
dialog_the_host_has_left_the_game_cs = "เจ้าของห้องได้ออกจากเกม Crime Spree ของคุณยังคงอยู่แต่เลเวลจะไม่เปลี่ยน$NL;$NL;และตอนนี้คุณจะกลับสู่เมนูหลัก",--The host has left the game. Your Crime Spree is still active, but your level has not changed.$NL;$NL;You will now be returned to the main menu.
dialog_ask_load_progress_backup_corrupt = "ความคืบหน้าของโปรไฟล์เสียหาย ลองโหลดจากไฟล์สำรองหรือไม่? การเลือก ไม่ จะเป็นการลบความคืบหน้าของคุณ",--Progress profile corrupt. Load from Backup? Chosing NO will delete your progress.
dialog_npcommerce_browse_fail = "ไม่สามารถเปิดร้านค้า PlayStation®Store ได้",--COULD NOT OPEN PlayStation®Store
dialog_new_unlock_secondaries = "คุณได้ปลดล็อค $value; และสามารถซื้อได้ผ่านช่องอาวุธสำรอง",--$value; has been unlocked and can be purchased into one of your empty secondary weapon slots.
dialog_skills_respec_title = "คุณแน่ใจหรือไม่?",--Are you sure?
dialog_demo_info_title = "ยินดีต้อนรับสู่ PAYDAY 2 เวอร์ชั่นทดลอง!",--Welcome to the demo of PAYDAY 2!
dialog_respec_skilltree = "คุณกำลังจะเรียนรู้ความสามารถใหม่$NL;$NL;การกระทำนี้จะรีเซ็ตค่าความสามารถในหมวดหมู่ $tree;",--You are about to respec this skill tree.$NL;$NL;Doing a respec resets all skill points in the $tree; skill tree.
dialog_are_you_sure_you_want_to_leave_game_crime_spree = "คุณแน่ใจหรือไม่ว่าต้องการออกจากเกมปัจจุบัน?$NL;$NL;การกระทำนี้จะทำให้ Crime Spree ปัจจุบันของคุณล้มเหลวทันที และคุณต้องจ่ายเพื่อเล่นต่อ หรือกดรับรางวัลจากหน้าเมนูของ Crime Spree",--Are you sure you want to leave current game?$NL;$NL;This will cause your current Crime Spree to fail, and you must pay to continue, or claim your rewards from a Crime Spree lobby.
dialog_mp_invite_title = "PAYDAY 2",--PAYDAY 2
dialog_parental_control = "การเล่นออนไลน์ถูกปิดเนื่องจากระบบการควบคุมจากผู้ปกครองจากบัญชี Sony Entertainment Network ของคุณ",--Online service is disabled on your Sony Entertainment Network account due to parental control restrictions.
dialog_npcommerce_need_install = "เพื่อที่จะเล่นตัวเกมเวอร์ชั่นเต็มคุณต้องเริ่มเกมใหม่อีกครั้งหลังจากติดตั้งตัวเกมเสร็จ",--To play the full version, you will need to restart the game after the installation is completed.
dialog_cs_ga_in_progress_text = "อุปกรณ์เสริมไม่สามารถชื้อได้หลังจากเริ่มภารกิจไปแล้ว",--Gage Boosts can not be purchased after the mission has been started.
dialog_getting_world_list = "กำลังโหลดข้อมูลโลก",--Getting world list
dialog_mp_pending_invite_short_message = "คุณได้รับคำเชิญเข้าร่วมเกม",--YOU HAVE A PENDING GAME INVITE.
dialog_vote_kick_yes = "ขับไล่",--Kick
dialog_mp_vote_restart_message = "การโหวตได้เริ่มต้นขึ้นแล้วและจะสิ้นสุดภายใน $time; วินาที",--A vote has been initiated to restart. The vote will end in $time; seconds.
dialog_err_not_signed_in_X360 = "คุณยังไม่ได้เข้าสู่ระบบ Xbox Live หรือคุณไม่มีสิทธิ์ที่จะใช้งาน Xbox Live",--You are not signed into Xbox Live, or you do not have the correct permissions to access Xbox Live functionality.
dialog_age_restriction = "การเล่นออนไลน์ถูกปิดเนื่องจากระบบการควบคุมจากผู้ปกครองจากบัญชี Sony Entertainment Network ของคุณ",--Online service is disabled on your Sony Entertainment Network account due to parental control restrictions.
screen_autosaving_warning_WIN32 = "เกมนี้บันทึกข้อมูลอัตโนมัติ$NL;กรุณาอย่าออกจากเกมเมื่อเกมกำลังบันทึกข้อมูล",--This game saves data automatically at certain points.$NL;Please don't turn off the game when it is saving.
dialog_safehouse_goto_text = "คุณต้องการไปที่เซฟเฮ้าส์หรือไม่",--Do you want to go to your safe house?
dialog_blackmarket_buy_weapon_slot = "การซื้อครั้งนี้จะปลดล็อคช่องอาวุธของคุณ$NL;$NL;จะมีค่าใช้จ่าย $money;",--Buying this will unlock one more weapon slot.$NL;$NL;This will cost you $money;.
dialog_fail_load_setting_corrupt_retry = "ไฟล์ตั้งค่าเกมเสียหาย ต้องการที่จะโหลดใหม่หรือไม่?",--Settings file corrupt. Try loading again?
dialog_mp_invite_message = "กรุณาเข้าร่วมเกม PAYDAY 2 ของฉัน",--Please Join my PAYDAY 2 Game
dialog_too_low_level = "ค่าประสบการณ์ของคุณน้อยเกินไปที่จะเข้าร่วมเซิฟเวอร์นี้",--Your reputation is too low to join this server.
dialog_signin_question_X360 = "หากต้องการที่จะบันทึก คุณต้องเข้าสู่ระบบก่อน ต้องการที่จะเข้าสู่ระบบหรือไม่?",--In order to save, you must be signed into a profile. Do you want to sign in now?
dialog_buy_weapon_message = "คุณต้องการที่จะชื้อ '$WEAPON;' ในราคา $COST; หรือไม่?",--Do you want to buy weapon "$WEAPON;" for $COST;?
ps4_presence_SPPlaying = "กำลังเล่นคนเดียว",--Playing single player heist
dialog_ask_load_progress_backup_low_lvl = "ไฟล์บันทึกในเครื่องของคุณไม่ตรงกับไฟล์ใน Steam $NL;$NL;กดใช่ถ้าหากคุณต้องการที่จะโหลดไฟล์ที่บันทึกไว้ในเครื่อง",--Your local backup save is more recent than the last Steam save.$NL;$NL;Press YES if you want to load your local backup save.
dialog_new_unlock_materials = "",--You just got your first material for mask customization.$NL;To customize a mask you will need a material, pattern and a pair of colors.
dialog_warning_title = "คำเตือน",--Warning
dialog_ok = "ตกลง",--Ok
dialog_allocate_skillpoint = "การกระทำนี้จะปลดล็อคความสามารถ $skill;$NL;$NL; และจะมีค่าใช้จ่าย $cost; และแต้มอีก $points; จากทั้งหมด $remaining_points; แต้ม",--This will unlock the $skill; skill.$NL;$NL;It will cost $cost; and $points; out of $remaining_points; points.
dialog_bm_weapon_buy_title = "คุณแน่ใจหรือไม่ ?",--Are you sure?
dialog_leaving_lobby_title = "กำลังออกจากเกม",--Leaving game
dialog_accept_changes = "คุณต้องเก็บการตั้งค่าการแสดงผลปัจจุบันหรือไม่? การตั้งค่าก่อนหน้านี้จะถูกกลับมาใช้งานในอีก $TIME;",--Do you wish to keep these display settings? They will be reverted in $TIME;.
dialog_key_binding_forbidden = "ปุ่ม '$KEY;' ถูกตั้งค่าโดยเกมไว้อยู่แล้ว กรุณาลองปุ่มอื่น",--Key "$KEY;" is reserved by the game, please try something else.
dialog_unlock_infamyitem = "คุณกำลังจะปลดล็อก $item;$NL;$NL; จะมีค่าใช้จ่าย $points; จากทั้งหมด $remaining_points;",--You are about to unlock $item; item.$NL;$NL;It will cost $points; out of $remaining_points; points.
dialog_blackmarket_slot_mask_remove = "นำหน้ากากนี้กลับไปที่ที่เก็บของของคุณหรือไม่? $suffix;",--Return this mask back to your stash? $suffix;
dialog_join_pd2_clan = "ไปที่หน้าชุมชนของเกม PAYDAY 2",--Go to PAYDAY 2 community page
dialog_are_you_sure_you_want_leave_cs = "คุณแน่ใจหรือไม่ว่าต้องการออกจากล็อบบี้นี้?$NL;$NL;Crime Spree ของคุณจะถูกหยุดไว้จนกว่าคุณจะดำเนินการเล่นต่อ",--Are you sure you want to leave this lobby?$NL;$NL;Your Crime Spree will be suspended until you continue it.
dialog_fail_load_progress_wrong_version = "ไฟล์ความคืบหน้าผิดเวอร์ชั่นต้องการเวอร์ชั่น $VERSION; หรือสูงกว่าและข้อมูลจะถูกลบออก",--Progress file wrong version. Version $VERSION; or higher is required. Data will now be deleted.
dialog_cs_ga_already_purchased = "ซื้อเรียบร้อยแล้ว",--Already Purchased
dialog_cs_ga_already_purchased_text = "คุณสามารถซื้อ Gage Boost ได้แค่หนึ่งอย่างต่อหนึ่งภารกิจของ Crime Spree",--You can only purchase one Gage Boost per Crime Spree mission.
dialog_challenge_warn_choose_reward_title = "คุณแน่ใจแล้วหรือไม่",--Are you sure?
dialog_mp_disconnected_internet_X360 = "คุณถูกตัดการเชื่อมต่อจาก Xbox Live คุณต้องเชื่อมต่อเพื่อใช้งานเนื้อหาส่วนนี้",--You have been disconnected from Xbox Live. You must be connected to access the online portions of this title.
dialog_fail_load_setting_wrong_version_WIN32 = "การตั้งค่าไฟล์ผิดเวอร์ชั่น ข้อมูลจะถูกลบออก",--Settings file wrong version. Data will now be deleted.
dialog_does_not_own_heist_info = "ภารกิจ '$HEIST;' ไม่สามารถเล่นกับผู้เล่น $PLAYER; ได้",--Heist "$HEIST;" cannot be played with player $PLAYER;.
dialog_storage_removed_warning_X360 = "อุปกรณ์จัดเก็บข้อมูลที่เลือกถูกนำออกแล้ว ความคืบหน้าของคุณจะไม่ได้รับการบันทึกอีกต่อไป",--Selected storage device has been removed. Your progress will no longer be saved
dialog_wait_title = "กรุณารอ",--Please wait
dialog_cs_ga_in_progress = "อยู่ระหว่างการดำเนินภารกิจ",--Heist In Progress
dialog_creating_lobby_title = "กำลังสร้างเกม",--Creating game
dialog_bm_mask_assemble_title = "คุณแน่ใจแล้วหรือไม่?",--Are you sure?
dialog_mp_send_invite_title = "ส่งคำเชิญ",--Send game invite
dialog_apply = "ยืนยัน",--Apply
dialog_connect_controller_title_X360 = "คอลโทรเลอร์ถูกตัดการเชื่อมต่อ",--Controller Disconnected
dialog_game_is_installing = "ไม่สามารถเข้าร่วมเชิญได้ในขณะนี้ลองอีกครั้งเมื่อการติดตั้งเสร็จสิ้น",--Cannot join invite at this time. Try again when the game has completed installing.
dialog_unlock_skill_switch_offshore = "จะเสียค่าใช้จ่ายจากเงิน Offshore $offshore;",--It will cost you $offshore; offshore cash.
sm_hoxton_revenge_desc = "Hoxton ได้ใช้เวลาของเขาอย่างคุ้มค่า หลังจากที่เข้าไม่ได้ถอดชุดนักโทษมานานมากแล้วหลังจากโดนจับโดย FBI และเขาจะทำทุกสิ่งที่เขาสามารถทำได้เพื่อหาหนอนบ่อนไส้ เขาไม่รู้หรอกว่าเป็นใครแต่ที่นี่แหละเซฟเฮ้าส์ที่เก็บมันไว้ได้เวลาจบเรื่องนี้สักที",--Hoxton used his time on the inside well. He wasn't even out of his prison pyjamas before busting in the FBI headquarters and getting everything he could about the rat. No name - the Feds are too canny for that - but the location of the safehouse where the rat is being held. Time to finish this.
dialog_assets_buy_title = "คุณแน่ใจแล้วหรือไม่?",--Are you sure?
dialog_skip_signin_warning_X360 = "คุณไม่ได้เข้าสู่ระบบ ความคืบหน้าจะไม่ถูกบันทึก$NL;$NL;ต้องการที่จะดำเนินการต่อโดยไม่บันทึกหรือไม่?",--Without signing in your progress will not be saved.$NL;$NL;Continue without saving?
dialog_yes = "ใช่",--Yes
dialog_mp_invite_wrong_room_message = "ไม่สามารถค้นหาคำเชิญได้ คุณไม่สามารถเข้าร่วมได้",--The game you have been invited to no longer exists. You are unable to join.
dialog_require_dlc_gage_pack_jobs = "ต้องการส่วนเสริม Gage Mod Courier!",--Requires Gage Mod Courier DLC!
dialog_continue_cs_text = "คุณต้องการดำเนินการต่อ Crime Spree ต่อไปหรือไม่?$NL;การกระทำนี้จะทำให้คุณเล่น Crime Spree ต่อจาก $level;$BTN_SPREE_TICKET; เพื่อเพิ่ม Crime Spree Ranks และสะสมผลตอบแทนที่มากขึ้น$NL;$NL; จะเสียค่าใช้จ่าย Continental Coins $cost; เหรียญ",--Do you want to continue your Crime Spree?$NL;This will allow you to continue your Crime Spree from $level;$BTN_SPREE_TICKET; to gain Crime Spree Ranks and accumulate greater rewards.$NL;$NL;This will cost you $cost; Continental Coins.
dialog_joining_lobby_title = "กำลังเข้าร่วมเกม",--Joining game
dialog_retrieving_servers_title = "กำลังเรียกข้อมูล",--Retrieving games
screen_autosaving_warning_X360 = "เกมนี้บันทึกข้อมูลโดยอัตโนมัติในบางจุด$NL; กรุณาอย่าปิด Xbox One ของคุณเมื่อไอคอนต่อไปนี้ปรากฏขึ้น:",--This game saves data automatically at certain points.$NL;Please don't turn off your Xbox One when the following icon is displayed:
dialog_connect_controller_text = "ไม่สามารถตรวจพบคอลโทรเลอร์ได้กรุณาเชื่อมต่อคอลโทรเลอร์ใหม่",--No Wireless Controller, Please Reconnect Controller
dialog_blackmarket_mod_replace = "การกระทำนี้จะแทนที่การปรับแต่ง $mod;",--This will replace your current modification $mod;.
dialog_default_options_message = "คุณต้องการที่จะคืนการตั้งค่าทั้งหมดหรือไม่ ?",--Do you wish to reset all options to their default state?
dialog_bm_mask_custom_abort = "คุณแน่ใจหรือไม่ ?",--Are you sure?
dialog_no_chat_parental_control = "ระบบสนทนาถูกปิดเนื่องจากระบบการควบคุมจากผู้ปกครองจากบัญชี Sony Entertainment Network ของคุณ",--CHAT IS DISABLED ON YOUR Sony Entertainment Network Account DUE TO PARENTAL CONTROL RESTRICTIONS.
dialog_blackmarket_mod_add = "คุณกำลังจะเพิ่มการปรับแต่ง $mod; กับอาวุธของคุณ",--You are about to add modification $mod; to your weapon.
dialog_save_settings_failed = "การบันทึกล้มเหลว",--Saving operation failed
dialog_mp_disconnected_internet_PS3 = "คุณถูกตัดการเชื่อมต่อจาก 'PlayStation Network' คุณต้องเชื่อมต่อเพื่อเข้าถีงเนื้อหาส่วนนี้",--You have been disconnected from "PlayStation Network". You must be connected to access the online portions of this title.
dialog_unlock_skill_switch_title = "คุณแน่ใจหรือไม่ ?",--Are you sure?
dialog_fail_load_setting_corrupt = "ไฟล์การตั้งค่าเสียหาย ข้อมูลจะถูกลบออก",--Settings file corrupt. Data will now be deleted.
dialog_accept_changes_title = "ต้องการยืนยันการเปลี่ยนแปลงหรือไม่?",--CONFIRM CHANGE?
dialog_cs_crash_fail = "Crime Spree ล้มเหลว",--Crime Spree Failed
dialog_fail_load_progress_corrupt_retry = "ไม่สามารถโหลดความคืบหน้าได้ ลองโหลดอีกครั้งหรือไม่?",--Progress could not be loaded. Try loading again?
dialog_err_not_signed_in = "คุณต้องเชื่อมต่อเพื่อเข้าใช้งานโหมดออนไลน์",--YOU MUST BE ONLINE TO MAKE USE OF NETWORK MODES.
dialog_no_connection_to_game_servers = "ไม่สามารถเชื่อมต่อกับเซิร์ฟเวอร์ได้",--Connection to game servers could not be established.
dialog_ask_load_progress_backup_wrong_version = "โปรไฟล์ความคืบหน้าผิดพลาดต้องการที่จะโหลดจากไฟล์สำรองหรือไม่? การเลือก ไม่ จะเป็นการลบความคืบหน้าของคุณ",--Progress profile wrong version. Load from Backup? Chosing NO will delete your progress.
dialog_connect_controller_title_WIN32 = "ไม่พบคอนโทรเลอร์",--No controller
dialog_default_options_title = "รีเซ็ตการตั้งค่า",--Reset options
dialog_mp_restart_level_title = "เริ่มเกมใหม่",--Restart
dialog_bm_mask_sell_title = "คุณแน่ใจหรือไม่?",--Are you sure?
dialog_mp_restart_level_message = "คุณต้องการที่จะโหวตขอเริ่มเกมใหม่หรือไม่",--Are you sure you want to create a vote for restarting?
dialog_safehouse_title = "เซฟเฮ้าส์",--Safe house
dialog_bm_weapon_modify_title = "คุณแน่ใจหรือไม่?",--Are you sure?
dialog_are_you_sure_you_want_to_clear_progress = "คุณต้องการที่จะล้างความคืบหน้าทั้งหมดหรือไม่? การกระทำนี้จะทำการรีเซ็ตเงินเลเวลและช่องเก็บของของคุณ",--Are you sure you want to clear your progress? This will reset your cash, reputation level and your inventory.
dialog_mp_kick_player_title = "ขับไล่ผู้เล่น",--Kick player
dialog_mp_groupinvite_title = "คำขอเกม",--Game Request
err_load = "กำลังโหลดถ้วยรางวัล",--Loading trophies...
dialog_item_list_macro = "$num;x $item;",--$num;x $item;
dialog_fail_load_setting_wrong_version = "การตั้งค่าไฟล์ผิดเวอร์ชั่นต้องการเวอร์ชั่น $VERSION; หรือสูงกว่าและข้อมูลจะถูกลบออก",--Settings file wrong version. Version $VERSION; or higher is required. Data will now be deleted.
dialog_blackmarket_abort_mask_warning = "การตกแต่งหน้ากากของคุณยังไม่เสร็จสมบูรณ์ การที่จะยกเลิกการปรับแต่งหน้ากากหรือไม่",--Your mask has not been finalized. Aborting will leave the mask unchanged.
dialog_are_you_sure_you_want_to_quit = "คุณแน่ใจหรือไม่ว่าต้องการจะออก",--Are you sure you want to quit?
dialog_gage_assignment_completed = "จาก: Gage [gage@///REDACTED///]$NL;ถึง: $player;$NL;วันที่: $date; $time;$NL;หัวข้อ: GAGE COURIER ASSIGNMENTS$NL;$NL;เยี่ยมมาก!$NL;$NL;แจ่มแมว,$player;. ขอบใจมากที่ไปไล่เก็บแพคเกจมาให้.ได้เวลาตอบแทนบ้างแล้วหละ. ไปที่ช่องเก็บของของคุณแล้วหาแพคเกจตามที่ได้เก็บมาซะ:$NL;$completed;$NL;$NL;- Gage",--From: Gage [gage@///REDACTED///]$NL;To: $player;$NL;Date: $date; $time;$NL;Subject: GAGE COURIER ASSIGNMENTS$NL;$NL;GOOD JOB!$NL;$NL;Well done, $player;. Thanks for collecting the packages. It's time to get your reward. Go to your inventory and you will find the content of the following packages:$NL;$completed;$NL;$NL;- Gage
dialog_game_started = "เกมปัจจุบันไม่สามารถเข้าร่วมได้",--The game is currently not joinable
dialog_infamous_info_desc = "คุณยังไม่สามารถเลื่อนขึ้นได้ คุณต้องมีเลเวลที่ $level; และมีเงิน offshore $cash; และการเลื่อนชั้นจะทำการรีเซ็ตเงินสดของคุณรวมถึงค่าทักษะทั้งหมด",--You don't have what it takes yet. To become infamous, you will need to get to reputation level $level; and pay a fee of $cash; from your offshore account along with your skill points and the rest of your spending cash.
dialog_mp_kicked_out_message = "คุณถูกขับไล่ออกจากเกมแล้ว",--You've been kicked from the game.
dialog_can_become_infamous_desc = "คุณสามารถที่จะเลื่อนระดับขั้นไปขั้นต่อไปได้แล้วและสามารถทำได้ในหน้าเมนู '$become_infamous_menu_item;'",--You have fulfilled the conditions for the next level of infamy. To become infamous, press '$become_infamous_menu_item;' in the main menu.
dialog_challenge_warn_choose_reward = "นี่เป็นรางวัลที่คุณต้องการหรือไม่ ?",--Is this the reward you want?$NL;$reward;
dialog_infamytree_reseted = "การเปลี่ยนแปลงได้เกิดขึ้นกับ Infamy .$NL;$NL;ค่า Infamy ทั้งหมดจะถูกรีเซ็ตและจะได้รับค่าพ้อยคืนทั้งหมด",--Changes have been made to the infamy tree.$NL;$NL;All your infamy items have been reset and your infamy points have been refunded.
dialog_vote_cancel = "งดออกเสียง",--Abstain
dialog_load_wrong_user = "ไฟล์บันทึกเป็นของผู้ใช้รายอื่น ความคืบหน้าจะไม่ได้รับการบันทึกและไม่สามารถปลดล็อคถ้วยรางวัลได้",--Save data belongs to a different user. No progress will be saved and trophies cannot be unlocked.
dialog_continue = "ทำต่อ",--Continue
dialog_err_cant_join_from_game = "คุณต้องออกจากเกมปัจจุบันของคุณก่อนจะเข้าร่วมเกมอื่นๆ",--You must leave your current game before joining a new one.
dialog_repair_weapon_message = "คุณต้องการที่จะซ่อมอาวุธ '$WEAPON;' ในราคา $COST; หรือไม่?",--Do you want to repair weapon "$WEAPON;" for $COST;?
ps4_presence_SPEnd = "ภารกิจเล่นคนเดียวได้จบลงแล้ว",--Singleplayer heist ended
dialog_err_room_no_longer_exists = "ไม่มีห้องนี้อีกต่อไปแล้ว กรุณาลองห้องอื่น",--This room no longer exists, please try another one.
dialog_authentication_fail = "Steam ไม่สามารถตรวจสอบ ID Steam ของคุณได้",--Steam could not authenticate your Steam ID.
dialog_err_room_is_closed = "ห้องนี้ถูกปิดแล้ว กรุณาลองห้องอื่น",--This room is closed, please try another one.
dialog_account_picker = "การเปลี่ยนโปรไฟล์อาจทำให้เกิดความคืบหน้าที่ไม่ได้บันทึกหายไป คุณต้องการดำเนินการต่อหรือไม่?",--Switching profiles might cause unsaved progress to be lost. Do you wish to continue?
dialog_wait = "กรุณารอ",--Please wait
dialog_err_failed_searching_lobbys = "ไม่สามารถเรียกข้อมูลเกมได้",--Failed retrieving games.
dialog_blackmarket_num_in_inventory = "คุณเป็นเจ้าของ $item; อยู่แล้ว $amount; ชิ้น",--You own $amount; $item; already.
dialog_blackmarket_mod_remove = "คุณกำลังจะถอดการติดตั้งส่วนเสริมอาวุธ $mod; จากอาวุธของคุณ",--You are about to remove modification $mod; from your weapon.
dialog_unlock_skill_switch_spending = "จะมีค่าใช้จ่ายโดยเงินสดทั้งหมด $spending;",--It will cost you $spending; spending cash.
dialog_new_unlock_primaries = "ปลดล็อค $value; สามารถซื้อได้ที่หน้าอาวุธหลัก",--$value; has been unlocked and can be purchased into one of your empty primary weapon slots.
dialog_logging_in = "กำลังเข้าสู่ระบบ",--Logging in
dialog_bm_crafted_sell_title = "คุณแน่ใจหรือไม่?",--Are you sure?
err_ins = "เกิดข้อผิดพลาดขณะโหลดถ้วยรางวัล โปรดออกจากเกมและลองอีกครั้ง",--An error occurred while loading trophies. Please exit the game and try again.
dialog_signin_change_X360 = "การเข้าสู่ระบบล้มเหลว$NL;คุณจะกลับไปที่หน้าเข้าเกม",--A sign-in change occurred.$NL;You have been returned to the Title screen.
dialog_err_room_allready_joined = "คุณเข้าร่วมห้องนี้อยู่แล้ว",--You have already joined this room.
dialog_fetching_status_title = "กำลังอัปเดตสถานะออนไลน์",--Updating online state.
dialog_mp_restart_level_host_message = "คุณแน่ใจหรือไม่ว่าต้องการเริ่มต้นใหม่",--Are you sure you want to restart?
dialog_mp_disconnected_internet = "คุณถูกตัดการเชื่อมต่อ",--YOU HAVE BEEN DISCONNECTED
dialog_remove_dead_peer = "ไม่สามารถสร้างการเชื่อมต่อกับผู้เล่นได้",--Connection to one or more players could not be established.
dialog_waiting_for_server_response_title = "กำลังรอเกมตอบสนอง",--Waiting for game to respond
dialog_blackmarket_assemble_item = "คุณต้องการที่จะนำหน้ากาก $item; วางทับในช่องเก็บของ $NL;$NL;ช่องที่ $num_in_inventory; ของคุณหรือไม่?",--Do you really want to put together $item; mask and place it into your inventory?$NL;$NL;$num_in_inventory;
dialog_are_you_sure_you_want_to_reset_statistics = "คุณแน่ใจหรือไม่ว่าต้องรีเซ็ตค่าสถิติของคุณใหม่",--Are you sure you want to reset your statistics?
dialog_skip_storage_warning_X360 = "ไม่สามารถตรวจพบที่จัดเก็บข้อมูลได้.$NL;ถ้าหากคุณเลือกที่จะทำต่อโดยที่ไม่ติดตั้งที่จัดเก็บไฟล์เซฟคุณจะไม่สามารถบันทึกเกมได้.$NL;$NL;ต้องการที่จะดำเนินการต่อโดยไม่บันทึกหรือไม่?",--No storage device selected.$NL;If you proceed without selecting a storage device, you will not be able to save the game.$NL;$NL;Continue without saving?
dialog_buy_weapon_title = "ซื้อ",--Buy
dialog_fail_load_setting_wrong_version_retry = "ไฟล์ตั้งค่าผิดเวอร์ชั่นต้องการเวอร์ชั่น $VERSION; หรือสูงกว่าต้องการที่จะลองใหม่หรือไม่?",--Settings file wrong version. Version $VERSION; or higher is required. Try loading again?
dialog_are_you_sure_you_want_to_leave_game = "คุณแน่ใจหรือไม่ว่าต้องการออกจากเกมปัจจุบัน?",--Are you sure you want to leave current game?
dialog_mp_invite_join_message = "โปรดเข้าร่วมเกมนี้โดยใช้ตัวเลือก 'ดูคำเชิญ' ในเมนู Crime.net",--Please join this game using the 'View Invites' option in the Crime.net menu.
dialog_demo_info_text = "ขอบคุณที่ติดตั้ง!$NL;$NL;ตัวทดลองเกม PAYDAY 2,คุณสามารถมีเลเวลที่ 10. และโปรดจำไว้เสมอว่าไฟล์เซฟของตัวทดลองไม่สามารถใช้กับตัวเต็มได้.$NL;$NL;พวกเราทีมงาน OVERKILL หวังว่าคุณจะสนุกกับตัวทดลองของเรา. ถ้าหากคุณชอบ, ก็อย่าลืมที่จะซื้อจับจองเป็นเป็นเจ้าของเพื่ออาวุธที่หลากหลายกว่างานจ้างที่หลากหลายและอื่นๆอีกมากมายในตัวเต็ม.$NL;$NL;- ทีมงาน OVERKILL",--Thanks for installing our demo!$NL;$NL;In this demo of PAYDAY 2, you can level up with your character to level 10. Please note that your save file for the demo can not be brought over to the full game.$NL;$NL;We in the OVERKILL crew hope you enjoy this demo. If you like what you see, you can buy PAYDAY 2 where you may gain may more levels through our Infamy system. The full game also includes more content like more heists, weapons, weapon modifications, masks and more.$NL;$NL;- The OVERKILL crew
dialog_inactive_user_accepted_invite_error = "คำเชิญได้รับการยอมรับจากผู้ใช้แล้ว คำเชิญจะถูกยกเว้น",--An invitation has been accepted by an inactive user. The invitation will be ignored.
dialog_blackmarket_slot_item_sell = "ถ้าคุณขายสิ่งนี้คุณจะได้รับ $money;",--If you sell this, you will be paid $money;.
dialog_cs_cant_claim_rewards_text = "คุณไม่มีรางวัลให้รับ",--You have no rewards to claim.
dialog_err_room_is_full_X360 = "เกมนี้ได้เต็มแล้วโปรดลองอีกครั้งหนึ่ง",--This game has been filled, please try another one.
dialog_err_room_no_longer_exists_X360 = "เกมนี้ไม่มีอยู่แล้วโปรดลองใหม่",--This game no longer exists, please try another one.
dialog_fail_load_game_corrupt = "ไฟล์บันทึกเสียหาย ไม่สามารถโหลดเกมได้",--Save file corrupt. Unable to load game.
dialog_infamous_info_title = "อินฟามี่",--Infamy
dialog_infamy_reseted_title = "เตือนความจำ",--Please note
dialog_mission_asset_buy = "อุปกรณ์ใช้งาน $asset_desc;$NL;$NL;จะมีค่าใช้จ่าย: $cost;",--$asset_desc;$NL;$NL;Cost: $cost;.
dialog_mp_no_invites_message = "คุณไม่มีคำเชิญเกม",--You have no game invites.
dialog_mp_vote_kick_unknown_message = "การโหวตขับไล่ผู้เล่นที่กำลังเชื่อมต่ออยู่เริ่มขึ้นแล้วการโหวตจะสิ้นสุดลงใน $time; วินาที",--A vote has been initiated to kick someone currently connecting. The vote will end in $time; seconds.
dialog_npcommerce_fail_open = "ไม่สามารถเริ่มต้นร้านค้า PlayStation®Store ได้",--FAILED INITIALIZING PlayStation®Store
dialog_npcommerce_opening = "กำลังเริ่มต้นร้านค้า PlayStation®Store",--INITIALIZING PlayStation®Store
dialog_repair_weapon_title = "ซ่อมแซม",--Repair
dialog_request_timed_out_message = "คำขอให้เข้าร่วมเกมหมดได้เวลาแล้ว",--Request to join game timed out
dialog_request_timed_out_title = "หมดเวลา",--Timed out
dialog_signin_title_X360 = "ไม่ได้ลงชื่อเข้าใช้",--Not signed in
dialog_unlock_skilltree = "คุณกำลังจะเริ่มทักษะ $skill;$NL;$NL;จะมีค่าใช้จ่ายทั้งหมด $cost; และค่าพ้อยอีก $points; จากทั้งหมด $remaining_points; พ้อย",--You are about to start $skill; skill tree.$NL;$NL;It will cost $cost; and $points; out of $remaining_points; points.
dialog_use_default_keys_message = "คุณต้องการที่จะรีเซ็ตค่าปุ่มทั้งหมดไปค่าพื้นฐานหรือไม่?",--Do you wish to reset all keys to their default state?
err_disk = "ไม่สามารถโหลดถ้วงรางวัลได้กรุณาออกจากเกมและมีพื้นที่ว่างอย่างน้อย $MB; เมกะไบต์และลองใหม่อีกครั้ง",--Not enough available space to load trophies. Please exit the game, ensure there is at least $MB;MB space available and try again.
ps4_presence_MPEnd = "ภารกิจเล่นหลายคนได้จบลงแล้ว",--Multiplayer heist ended
ps4_presence_MPLobby = "ล็อบบี้เล่นหลายคน",--Multiplayer lobby
ps4_presence_MPPlaying = "กำลังทำภารกิจผู้เล่นหลายคน",--Playing multiplayer heist
ps4_presence_SafeHousePlaying = "อยู่ในเซฟเฮาส์",--In the safe house
sm_2_desc = "โอเค ฉันคิดว่ามันจะได้ผลนะ การวางแผนสำคัญที่สุด คุณคือมือโปรใช่ไหมละและคุณต้องการอุปกรณ์ที่เหมาะสมสำหรับงานด้วย ของพวกนี้มันอาจจะยังไม่มากมายอะไมากนักในตอนนี้แต่ถ้าหากทำงานเรื่อยๆละก็ฉันว่ามันน่าจะมีอะไรมากกว่านี้นะ",--Okay, so this might just work out. Preparation is important though. You're a professional. You need the right gear for the job. Okay, there may not be much in the cupboard right now, but as you keep pulling off heists, get notorious, we'll get those racks and cabinets filled with all the right gear.
sm_first_safehouse_desc = "ตั้งแต่ที่คุณกำลังจะเข้าสู่วงการ คุณต้องการสิ่งเล็กๆที่เรียกว่าบ้านสักหน่อย เซฟเอาส์ไงหละไม่ยังไม่อะไรมากหรอกแต่ก็ยังไม่หมดเท่านี้หรอกมันก็แค่ตอนนี้อะหนะอย่าลืมไปแวะดูด้วยละแล้วเราจะมาสร้างเงินล้านกัน",--Since you'll be out on the streets wreaking havoc, you're gonna need a place to call home- a safe house. I got just the place. It's nothing too fancy but it will have to do for now. Head over there and check it out, then later we can go about making some money.
