menu_legend_broker_favorite = "$BTN_X; ชื่นชอบ",--$BTN_X; Favorite
menu_legend_update_WIN32 = "$BTN_UPDATE; อัพเดต",--$BTN_UPDATE; UPDATE
menu_legend_crimenet_move = "$STICK_L;$STICK_R; เคลื่อนย้าย",--$STICK_L;$STICK_R; Move
menu_legend_achievements_clear_filter = "$BTN_BACK; ล้างฟิลเตอร์",--$BTN_BACK; CLEAR FILTERS
menu_legend_sm_start_mission = "$MY_BTN; เริ่มด่าน",--$MY_BTN; START LEVEL
menu_legend_claim_challenge_reward = "$BTN_Y; เก็บรางวัล",--$BTN_Y; Collect reward
menu_legend_track_achievement = "$MY_BTN; บันทึกไว้",--$MY_BTN; TRACK
menu_legend_skill_spec_swap = "$BTN_BOTTOM_L;$BTN_BOTTOM_R; สกิล / สกิลเพิ่มเติม",--$BTN_BOTTOM_L;$BTN_BOTTOM_R; Skilltree / Perk Deck
menu_legend_zoom_rotate = "$STICK_R; หมุน / ซูม",--$STICK_R; Rotate / Zoom
menu_legend_open_preplanning = "$BTN_X; วางแผน",--$BTN_X; Preplanning
menu_legend_claim_reward = "$BTN_Y; รับรางวัล",--$BTN_Y; Claim Reward
menu_legend_achievements_track_btn = "$MY_BTN; แสดงที่บันทึกไว้",--$MY_BTN; SHOW TRACKED
menu_legend_show_all = "$BTN_X; แสดงทั้งหมด",--$BTN_X; Show All
menu_legend_scroll = "$STICK_R; เลื่อน",--$STICK_R; Scroll
menu_legend_achievements_all_btn = "$MY_BTN; แสดงทั้งหมด",--$MY_BTN; SHOW ALL
menu_legend_hide_all = "$BTN_X; ซ่อนทั้งหมด",--$BTN_X; Hide All
menu_legend_crew_help = "$BTN_BACK; ช่วยเหลือ",--$BTN_BACK; HELP
menu_legend_blackmarket = "$BTN_BACK; ตลาดมืด",--$BTN_BACK; Black Market
menu_legend_show_hide = "$BTN_X; แสดง / ซ่อน",--$BTN_X; Show / Hide
menu_legend_preview = "$BTN_Y; แสดงข้อมูล",--$BTN_Y; Preview
menu_legend_scroll_left_right = "$STICK_L;$STICK_R; เลื่อน",--$STICK_L;$STICK_R; Scroll
menu_legend_manual_switch_page = "$BTN_BOTTOM_L;$BTN_BOTTOM_R; เปลี่ยนหน้า",--$BTN_BOTTOM_L;$BTN_BOTTOM_R; Change Page
menu_legend_back = "$BTN_CANCEL; ย้อนกลับ",--$BTN_CANCEL; BACK
menu_legend_update = "$BTN_Y; อัพเดต",--$BTN_Y; UPDATE
menu_legend_choose_challenge_reward = "$BTN_BOTTOM_L;$BTN_BOTTOM_R; เลือกรางวัล",--$BTN_BOTTOM_L;$BTN_BOTTOM_R; Choose reward
menu_legend_crimenet_zoom = "$BTN_BOTTOM_L;$BTN_BOTTOM_R; ซูม",--$BTN_BOTTOM_L;$BTN_BOTTOM_R; Zoom
menu_legend_forced = "$MY_BTN; ให้แสดง UI ในเกม",--$MY_BTN; FORCED IN UI
menu_legend_inventory = "$BTN_BACK; ช่องเก็บของ",--$BTN_BACK; Inventory
menu_legend_payday = "$BTN_Y; PAYDAY",--$BTN_Y; PAYDAY
menu_legend_preplanning_move = "$STICK_R; ย้าย",--$STICK_R; Move
menu_legend_preview_move = "$STICK_L; ย้าย",--$STICK_L; Move
menu_legend_preview_zoom = "$STICK_R; ซูม",--$STICK_R; Zoom
menu_legend_respec = "$BTN_Y; RESPEC",--$BTN_Y; RESPEC
menu_legend_select = "$BTN_ACCEPT; เลือก",--$BTN_ACCEPT; SELECT
menu_legend_switch = "$BTN_BOTTOM_L;$BTN_BOTTOM_R; สลับ",--$BTN_BOTTOM_L;$BTN_BOTTOM_R; Switch
menu_legend_toggle_unlocked = "$MY_BTN; ปลดล็อคแล้ว",--$MY_BTN; TOGGLE UNLOCKED
menu_achievements = "รางวัลความสำเร็จ",--Achievements
menu_achievements_rewards = "รางวัลที่ได้รับ",--Rewards Acquired
menu_achievements_sort_order_help = "",--
menu_achievements_progress = "ดำเนินการ",--Progress
menu_achievements_tags_intro = "แท็ก:$NL;",--Tags:$NL;
menu_achievements_hide_unlocked_help = "ซ่อนที่ปลดล็อคไปแล้ว",--Hides all unlocked achievements
menu_achievements_tracking_notify = "ที่บันทึกไว้",--TRACKING
menu_achievements_hide_unlocked = "ซ่อนที่ปลดล็อคแล้ว",--Hide unlocked
menu_achievements_clear_filter_btn = "ล้างค่าฟิลเตอร์ $MY_BTN;",--CLEAR FILTERS $MY_BTN;
menu_achievements_recent_unlocked = "ปลดล็อคไปแล้ว $COUNT;",--$COUNT; ACHIEVEMENTS UNLOCKED
menu_achievements_tracking = "บันทึกไว้อยู่ $COUNT;",--TRACKING: $COUNT;
menu_achievements_forced = "บังคับให้แสดงใน UI $CURRENT; / $MAX;",--FORCED IN UI: $CURRENT; / $MAX;
menu_achievements_levels_left_intro = "ด่านที่จะต้องทำ:$NL;",--Levels left to do:$NL;
menu_achievements_forced_notify = "บังคับให้แสดงใน UI",--FORCED IN UI
menu_achievements_filter_btn = "ฟิลเตอร์ $MY_BTN;",--FILTERS $MY_BTN;
menu_achievements_hide_ladder_help = "แสดงอันแรกเฉพาะที่ล็อคไว้ในรายการ",--Only shows the first locked in each ladder
menu_achievements_help = "บันทึกและแสดงครามสำเร็จของคุณ",--Track and view your achievements.
menu_achievements_hide_ladder = "ซ่อนรายการ",--Hide ladder
menu_default = "ค่าพื้นฐาน",--
menu_sort_progress = "ดำเนินการอยู่",--Progress
menu_sort_alphabetic = "เรียงตามตัวอักษร",--Alphabetic
menu_sort_chronologic = "เรียงตามลำดับ",--Chronologic
menu_achievements_sort_order = "การคัดกรอง",--Sort Order
menu_total_achievements = "รางวัลความสำเร็จทั้งหมด",--
menu_filtered_achievements = "รางวัลความสำเร็จที่คัดกรองไว้",--
