hud_skip_blackscreen = "กด $BTN_ACCEPT; ค้างเพื่อข้าม",--Hold $BTN_ACCEPT; to skip
hud_int_access_camera = "กด $BTN_INTERACT; เพื่อดูกล้อง",--Press $BTN_INTERACT; to view the cameras
hud_int_answer_phone = "กด $BTN_INTERACT; เพื่อรับโทรศัพย์",--Press $BTN_INTERACT; to answer the phone
hud_int_bag_zipline = "กด $BTN_INTERACT; เพื่อใช้สลิงส่งของ",--Press $BTN_INTERACT; to attach bag
hud_int_bank_note = "กด $BTN_INTERACT; เพื่อค้นหาโค้ด",--press $BTN_INTERACT; to search for code
hud_int_barrier_numpad = "กด $BTN_INTERACT; เพื่อปิดระบบป้องกัน",--Press $BTN_INTERACT; to open bandit barrier
hud_int_big_computer_hackable = "กด $BTN_INTERACT; ค้างเพื่อแฮกคอมพิวเตอร์",--Hold $BTN_INTERACT; to hack computer
hud_int_big_computer_server = "กด $BTN_INTERACT; ค้างเพื่อแฮกคอมพิวเตอร์",--Hold $BTN_INTERACT; to remotely access computer
hud_int_big_computer_unhackable = "คุณสามารถแฮกคอมพิวเตอร์ได้เครื่องเดียวในเวลาเดียวกัน",--You can only hack one computer at a time
hud_int_break_open = "กด $BTN_INTERACT; เพื่องัดออก",--Press $BTN_INTERACT; to break open
hud_int_close_cargo_door = "กด $BTN_INTERACT; เพื่อปิดประตู",--Press $BTN_INTERACT; to close cargo door
hud_int_crane_left = "กด $BTN_INTERACT; เพื่อควบคุมเครน",--Press $BTN_INTERACT; to turn crane to the left
hud_int_crane_lift = "กด $BTN_INTERACT; เพื่อยกเครนขึ้น",--Press $BTN_INTERACT; to lift crane
hud_int_crane_release = "กด $BTN_INTERACT; เพื่อปล่อยเครน",--Press $BTN_INTERACT; to release crane
hud_int_crane_right = "กด $BTN_INTERACT; เพื่อควบคุมเครน",--Press $BTN_INTERACT; to turn crane to the right
hud_int_cut_glass = "กด $BTN_INTERACT; ค้างเพื่อตัดกระจก",--Hold $BTN_INTERACT; to cut glass
hud_int_disable_alarm_pager = "กด $BTN_INTERACT; ค้างเพื่อตอบเพจเจอร์",--Hold $BTN_INTERACT; to answer the pager
hud_int_dispose_corpse = "กด $BTN_INTERACT; ค้างเพื่อเก็บศพ",--Hold $BTN_INTERACT; to bag the corpse
hud_int_enter_code = "กด $BTN_INTERACT; เพื่อใส่โค้ด",--Hold $BTN_INTERACT; to enter the code
hud_int_equipment_drill = "กด $BTN_INTERACT; ติดตั้งเครื่องเจาะ",--Hold $BTN_INTERACT; to use the drill
hud_int_equipment_drill_jammed = "กด $BTN_INTERACT; ค้างเพื่อซ่อมเครื่องเจาะ",--Hold $BTN_INTERACT; to restart the drill
hud_int_equipment_drill_upgrade = "กด $BTN_INTERACT; อัพเกรดเครื่องเจาะ",--Hold $BTN_INTERACT; to upgrade the drill
hud_int_equipment_ecm_feedback = "กด $BTN_INTERACT; เปืดใช้งาน ECM FEEDBACK",--Hold $BTN_INTERACT; to turn on ECM feedback
hud_int_equipment_huge_lance = "กด $BTN_INTERACT; เพื่อติดตั้งเครื่องเจาะ",--Hold $BTN_INTERACT; to use the Beast
hud_int_equipment_huge_lance_jammed = "กด $BTN_INTERACT; ค้างเพื่อซ่อมเครื่องเจาะ",--Hold $BTN_INTERACT; to fix the Beast
hud_int_equipment_keycard = "กด $BTN_INTERACT; เพื่อใช้คีย์การ์ด",--Press $BTN_INTERACT; to use the keycard
hud_int_equipment_lance = "กด $BTN_INTERACT; เพื่อติดตั้งเครื่องเจาะ",--Hold $BTN_INTERACT; to use the thermal drill
hud_int_equipment_lance_jammed = "กด $BTN_INTERACT; เพื่อซ่อมเครื่องเจาะ",--Hold $BTN_INTERACT; to reignite the thermal drill
hud_int_equipment_lance_upgrade = "กด $BTN_INTERACT; เพื่ออัพเกรดเครื่องเจาะ",--Hold $BTN_INTERACT; to upgrade the thermal drill
hud_int_equipment_no_drill = "คุณต้องการเครื่องเจาะ",--You need the drill
hud_int_equipment_no_keycard = "คุณต้องการคีย์การ์ด",--You need a keycard
hud_int_equipment_no_lance = "คุณต้องมีเครื่องเจาะ",--You need the thermal drill
hud_int_equipment_no_lance_part = "คุณต้องมีเครื่องมื่อซ่อมเพื่อที่จะซ่อมเครื่องเจาะ",--You need spare parts to fix the Beast
hud_int_equipment_normal_mode_trip_mine = "กด $BTN_INTERACT; เปิดโหมดระเบิด",--Press $BTN_INTERACT; to Switch Trip Mine to Explosive Mode
hud_int_equipment_sensor_mode_trip_mine = "กด $BTN_INTERACT; เปิดโหมดเซ็นเซอร์",--Press $BTN_INTERACT; to Switch Trip Mine to Sensor Mode
hud_int_equipment_shaped_charge = "กด $BTN_INTERACT; ค้างเพื่อติดตั้งระเบิด",--Hold $BTN_INTERACT; to use a shaped charge
hud_int_exit_to_crimenet = "กด $BTN_INTERACT; ค้างเพื่อออก Crime.net",--Hold $BTN_INTERACT; to exit to Crime.net
hud_int_fork_lift_sound = "กด $BTN_INTERACT; ค้างเพื่อใช้เครื่องยก",--Hold $BTN_INTERACT; to start the fork lifter
hud_int_grab_server = "กด $BTN_INTERACT; ค้างเพื่อเอาเครื่อง Server",--Hold $BTN_INTERACT; to take the server
hud_int_hack_box = "กด $BTN_INTERACT; แฮกกล่องสัญญานไฟ",--Hold $BTN_INTERACT; to hack electrical box
hud_int_hack_timelock = "กด $BTN_INTERACT; ค้างเพื่อแฮก TimeLock",--Hold $BTN_INTERACT; to force time lock
hud_int_hold_activate_camera = "กด $BTN_INTERACT; ค้างเพื่อวางกล้องวงจรปิด",--Hold $BTN_INTERACT; to place the camera
hud_int_hold_activate_reader = "กด $BTN_INTERACT; ค้างเพื่อตรวจสอบบาร์โค้ด",--Hold $BTN_INTERACT; to activate the barcode reader
hud_int_hold_activate_sprinklers = "กด $BTN_INTERACT; เพื่อเปิดใช้งานหัวฉีด",--Hold $BTN_INTERACT; to activate sprinklers
hud_int_hold_add_blade = "กด $BTN_INTERACT; เพื่อเพิ่มใบเลี่อย",--Hold $BTN_INTERACT; to add the saw blade
hud_int_hold_analyze_evidence = "กด $BTN_INTERACT; เพื่อตรวจสอบหลักฐาน",--Hold $BTN_INTERACT; to analyze evidence
hud_int_hold_approve_request = "กด $BTN_INTERACT; เพื่อยอมรับคำขอ",--Hold $BTN_INTERACT; to approve request
hud_int_hold_assemble_thermite = "กด $BTN_INTERACT; to assemble thermite rig",--Hold $BTN_INTERACT; to assemble thermite rig
hud_int_hold_bag_sa_armor = "กด $BTN_INTERACT; ค้างเพื่อหยิบชิ้นส่วนของเกราะซามูไร",--Hold $BTN_INTERACT; to bag a piece of samurai armor
hud_int_hold_barcode = "กด $BTN_INTERACT; ค้างเพื่อหยิบบาร์โค้ด",--Hold $BTN_INTERACT; to take the barcode
hud_int_hold_call_captain = "กด $BTN_INTERACT; ค้างเพื่อเรียกกัปตัน",--Hold $BTN_INTERACT; to call the captain
hud_int_hold_check_evidence = "กด $BTN_INTERACT; เพื่อตรวจหลักฐาน",--Hold $BTN_INTERACT; to check the evidence
hud_int_hold_close_crate = "กด $BTN_INTERACT; เพื่อปิดกล่อง",--Hold $BTN_INTERACT; to close shipping crate
hud_int_hold_connect_equip = "กด $BTN_INTERACT; ค้างเพื่อเชื่อมต่อกับอุปกรณ์",--Hold $BTN_INTERACT; to connect the equipment
hud_int_hold_connect_hose = "กด $BTN_INTERACT; ค้างเพื่อเชื่อมต่อสายยาง",--Hold $BTN_INTERACT; to connect the hose
hud_int_hold_crack_crate = "กด $BTN_INTERACT; ค้างเพื่อเปิดกล่อง",--Hold $BTN_INTERACT; to open shipping crate
hud_int_hold_cut_cable = "กด $BTN_INTERACT; ค้างเพื่อตัดสาย",--Hold $BTN_INTERACT; to cut the cable
hud_int_hold_cut_fence = "กด $BTN_INTERACT; ค้างเพื่อตัดรั้ว",--Hold $BTN_INTERACT; to cut the fence
hud_int_hold_cut_tree = "กด $BTN_INTERACT; ค้างเพื่อตัดต้นไม้",--Hold $BTN_INTERACT; to cut the tree
hud_int_hold_disarm_bomb = "กด $BTN_INTERACT; เพื่อกู้ระเบิด",--Hold $BTN_INTERACT; to disarm the bomb
hud_int_hold_disassemble_cro_loot = "กด $BTN_INTERACT; ค้างเพื่อหยิบชิ้นส่วนระเบิด",--Hold $BTN_INTERACT; to take the bomb part
hud_int_hold_disassemble_turret = "กด $BTN_INTERACT; ค้างเพื่อแยกชิ้นส่วนป้อมปืน",--Hold $BTN_INTERACT; to disassemble turret
hud_int_hold_download_keys = "กด $BTN_INTERACT; ค้างเพื่อดาวน์โหลดคีย์",--Hold $BTN_INTERACT; to download encryption keys
hud_int_hold_gather_evidence = "กด $BTN_INTERACT; ค้างเพื่อรวมหลักฐาน",--Hold $BTN_INTERACT; to gather evidence
hud_int_hold_grab_the_bag = "กด $BTN_INTERACT; ค้างเพื่อหยิบกระเป๋า",--Hold $BTN_INTERACT; to grab the bag
hud_int_hold_grab_the_painting = "กด $BTN_INTERACT; ค้างเพื่อหยิบรูปภาพ",--Hold $BTN_INTERACT; to grab the painting
hud_int_hold_hack_computer = "กด $BTN_INTERACT; ค้างเพื่อแฮกคอมพิวเตอร์",--Hold $BTN_INTERACT; to hack the computer
hud_int_hold_hack_numpad = "กด $BTN_INTERACT; ค้างเพื่อแฮกรหัสผ่าน",--Hold $BTN_INTERACT; to hack the numpad
hud_int_hold_ignite_money = "กด $BTN_INTERACT; ค้างเพื่อเผาเงิน",--Hold $BTN_INTERACT; to ignite the money
hud_int_hold_ignite_thermite = "กด $BTN_INTERACT; ค้างเพื่อใช้งานเธอไมท",--Hold $BTN_INTERACT; to ignite the thermite
hud_int_hold_ignite_thermite_paste = "กด $BTN_INTERACT; ค้างเพื่อเผาด้วยเธอไมท",--Hold $BTN_INTERACT; to ignite the thermite paste
hud_int_hold_move_car = "กด $BTN_INTERACT; ค้างเพื่อย้ายรถ",--Hold $BTN_INTERACT; to move the car
hud_int_hold_open_case = "กด $BTN_INTERACT; ค้างเพื่อเปิดกล่อง",--Hold $BTN_INTERACT; to open the case
hud_int_hold_open_circuitbreaker = "กด $BTN_INTERACT; ค้างเพื่อเปิดกล่อง",--Hold $BTN_INTERACT; to open the circuit breaker box
hud_int_hold_open_display = "กด $BTN_INTERACT; ค้างเพื่อเปิด",--Hold $BTN_INTERACT; to open display
hud_int_hold_open_slash_close_sec_box = "กด $BTN_INTERACT; ค้างเพื่อ ปิด/เปิด กล่องรักษาความปลอดภัย",--Hold $BTN_INTERACT; to open/close security box
hud_int_hold_open_vault = "กด $BTN_INTERACT; ค้างเพื่อเปิดตู้นิรภัย",--Hold $BTN_INTERACT; to open the vault
hud_int_hold_open_xmas_present = "กด $BTN_INTERACT; ค้างเพื่อเปิดกล่องของขวัญ",--Hold $BTN_INTERACT; to open Xmas present
hud_int_hold_pack_shells = "กด $BTN_INTERACT; ค้างเพื่อเก็บกระสุนใส่กระเป๋า",--Hold $BTN_INTERACT; to pack Shells
hud_int_hold_pickup_boards = "กด $BTN_INTERACT; ค้างเพื่อหยิบไม้บอร์ด",--Hold $BTN_INTERACT; to pick up boards
hud_int_hold_pickup_lance = "กด $BTN_INTERACT; ค้างเพื่อหยิบเครื่องเจาะ",--Hold $BTN_INTERACT; to grab the thermal drill
hud_int_hold_pku_equipment = "กด $BTN_INTERACT; ค้างเพื่อหยิบอุปกรณ์",--Hold $BTN_INTERACT; to grab the equipment
hud_int_hold_place_gps_tracker = "กด $BTN_INTERACT; ค้างเพื่อติดจีพีเอส",--Hold $BTN_INTERACT; to place the gps tracker
hud_int_hold_raise_balloon = "กด $BTN_INTERACT; ค้างเพื่อปั้มลูกโป่ง",--Hold $BTN_INTERACT; to raise balloon
hud_int_hold_read_barcode = "กด $BTN_INTERACT; ค้างเพื่ออ่านบาร์โค้ด",--Hold $BTN_INTERACT; to read the barcode
hud_int_hold_remove_armor_plating = "กด $BTN_INTERACT; ค้างเพื่อถอดเกราะ",--Hold $BTN_INTERACT; to remove armor plating
hud_int_hold_remove_cover = "กด $BTN_INTERACT; ค้างเพื่อลบออก",--Hold $BTN_INTERACT; to remove the cover
hud_int_hold_remove_ladder = "กด $BTN_INTERACT; ค้างเพื่อยกบันไดออก",--Hold $BTN_INTERACT; to remove the ladder
hud_int_hold_resume_upload = "กด $BTN_INTERACT; ค้างเพื่ออัพโหลดไฟล์ต่อ",--Hold $BTN_INTERACT; to resume upload
hud_int_hold_roll_carpet = "กด $BTN_INTERACT; ค้างเพื่อหมุนพรม",--Hold $BTN_INTERACT; to roll the carpet
hud_int_hold_start_motor = "กด $BTN_INTERACT; ค้างเพื่อเริ่มเครื่องยนต์",--Hold $BTN_INTERACT; to start the engine
hud_int_hold_steal_meth = "กด $BTN_INTERACT; ค้างเพื่อหยิบสารเสพติด",--Hold $BTN_INTERACT; to steal back the meth
hud_int_hold_take_artifact = "กด $BTN_INTERACT; ค้างเพื่อวัตถุโบราณ",--Hold $BTN_INTERACT; to take the artifact
hud_int_hold_take_blade = "กด $BTN_INTERACT; ค้างเพื่อหยิบใบเลื่อย",--Hold $BTN_INTERACT; to take the saw blade
hud_int_hold_take_blueprints = "กด $BTN_INTERACT; ค้างเพื่อหยิบบลูปริ้น",--Hold $BTN_INTERACT; to take the blueprints
hud_int_hold_take_cocaine = "กด $BTN_INTERACT; ค้างเพื่อหยิบสารเสพติด",--Hold $BTN_INTERACT; to take the cocaine
hud_int_hold_take_gas = "กด $BTN_INTERACT; ค้างเพื่อแก็สลีน",--Hold $BTN_INTERACT; to take the gasoline
hud_int_hold_take_hdd = "กด $BTN_INTERACT; ค้างเพื่อหยิบฮาร์ดไดรฟ์",--Hold $BTN_INTERACT; to take the Hard Drive
hud_int_hold_take_jewelry = "กด $BTN_INTERACT; ค้างเพื่อหยิบเพรช",--Hold $BTN_INTERACT; to take the jewelry
hud_int_hold_take_meth = "กด $BTN_INTERACT; ค้างเพื่อหยิบสารเสพติด",--Hold $BTN_INTERACT; to take the meth
hud_int_hold_take_painting = "กด $BTN_INTERACT; ค้างเพื่อหยิบภาพวาด",--Hold $BTN_INTERACT; to take the painting
hud_int_hold_take_pure_cocaine = "กด $BTN_INTERACT; ค้างเพื่อสารเสพติด",--Hold $BTN_INTERACT; to take pure Colombian cocaine
hud_int_hold_take_reaktor = "กด $BTN_INTERACT; ค้างเพื่อหยิบเครื่องปฏิกรณ์",--Hold $BTN_INTERACT; to take the fusion reactor prototype
hud_int_hold_take_sandwich = "กด $BTN_INTERACT; ค้างเพื่อหยิบขนมปังผสมสารเสพติด",--Hold $BTN_INTERACT; to take Almir's toast
hud_int_hold_take_server = "กด $BTN_INTERACT; ค้างเพื่อหยิบเครื่องเซิฟเวอร์",--Hold $BTN_INTERACT; to take the server
hud_int_hold_turn_on_power = "กด $BTN_INTERACT; ค้างเพื่อเปิดไฟ",--Hold $BTN_INTERACT; to Turn on the Power
hud_int_hold_use_computer = "$BTN_INTERACT; ค้างเพื่อใช้งานคอมพิวเตอร์",--Hold $BTN_INTERACT; to use the computer
hud_int_hold_use_device = "กด $BTN_INTERACT; ค้างเพื่อวางอุปกรณ์",--Hold $BTN_INTERACT; to place device
hud_int_hostage_convert = "กด $BTN_INTERACT; ค้างเพื่อให้ตำรวจมาเป็นพวก",--Hold $BTN_INTERACT; to convert the enemy
hud_int_ignite_flare = "กด $BTN_INTERACT; ค้างเพื่อจุดแฟร์",--Press $BTN_INTERACT; to ignite flare
hud_int_invisible_interaction_close = "กด $BTN_INTERACT; ค้างเพื่อปิด",--Hold $BTN_INTERACT; to close
hud_int_invisible_interaction_open = "กด $BTN_INTERACT; ค้างเพื่อเปิด",--Hold $BTN_INTERACT; to open
hud_int_keyboard_hox_1 = "กด $BTN_INTERACT; ค้างเพื่อเอาที่กั้นลง",--Hold $BTN_INTERACT; to lower bollards
hud_int_ladyjustice_statue = "กด $BTN_INTERACT; ค้างเพื่อวางเงิน",--Press $BTN_INTERACT; to place the money clips
hud_int_methlab_bubbling = "กด $BTN_INTERACT; ค้างเพื่อใส่สารเอชิส",--Hold $BTN_INTERACT; to add the muriatic acid
hud_int_methlab_caustic_cooler = "กด $BTN_INTERACT; ค้างเพื่อใส่โซดา",--Hold $BTN_INTERACT; to add the caustic soda
hud_int_methlab_drying_meth = "กด $BTN_INTERACT; ค้างเพื่อสารเสพติด",--Hold $BTN_INTERACT; to add the liquid meth
hud_int_methlab_gas_to_salt = "กด $BTN_INTERACT; ค้างเพื่อใส่ไอโดรเจน",--Hold $BTN_INTERACT; to add the hydrogen chloride
hud_int_need_thermite_paste = "คุณต้องมีเทอไมท",--You need thermite paste
hud_int_no_acid = "คุณต้องมีเอซิส",--Requires muriatic acid
hud_int_no_caustic_soda = "คุณต้องมีโซดา",--Requires caustic soda
hud_int_no_hydrogen_chloride = "คุณต้องมีไฮโดรเจน",--Requires hydrogen chloride
hud_int_no_liquid_meth = "Requires liquid meth",--Requires liquid meth
hud_int_numpad_keycard = "กด $BTN_INTERACT; ค้างเพื่อแฮกระบบเตือนภัย",--Press $BTN_INTERACT; to disable the display case alarm
hud_int_numpad_no_keycard = "คุณต้องการคีย์การ์ดเพื่อปิดระบบป้องกันความปลอดภัย",--You need a keycard to disable the display case alarm
hud_int_open_cargo_door = "กด $BTN_INTERACT; เพื่อเปิดประตู",--Press $BTN_INTERACT; to open cargo door
hud_int_open_slash_close = "กด $BTN_INTERACT; เพื่อปิด/เปิด",--Press $BTN_INTERACT; to open/close
hud_int_pick_lock = "กด $BTN_INTERACT; ค้างเพื่อสะเดาะล็อค",--Hold $BTN_INTERACT; to pick the lock
hud_int_pickup_asset = "กด $BTN_INTERACT; หยิบกุญแจผี",--Press $BTN_INTERACT; to pick up the keychain
hud_int_pickup_keycard = "กด $BTN_INTERACT; เพื่อหยิบคีย์การ์ด",--Press $BTN_INTERACT; to pick up the keycard
hud_int_pickup_phone = "กด $BTN_INTERACT; เพื่อหยิบโทรศัพย์",--Press $BTN_INTERACT; to take the phone
hud_int_pickup_tablet = "Press $BTN_INTERACT; to take the tablet",--Press $BTN_INTERACT; to take the tablet
hud_int_pickup_tiara = "Press $BTN_INTERACT; to take the tiara",--Press $BTN_INTERACT; to take the tiara
hud_int_place_camera = "กด $BTN_INTERACT; เพื่อวางกล้อง",--Press $BTN_INTERACT; to place the camera
hud_int_place_flare = "กด $BTN_INTERACT; เพื่อวางแฟลร์ ",--Press $BTN_INTERACT; to place flare
hud_int_place_harddrive = "กด $BTN_INTERACT; ค้างเพื่อวางฮาร์ดไดรฟ์",--Hold $BTN_INTERACT; to place the hard drive
hud_int_press_for_info = "กด $BTN_INTERACT; เพื่อฟังข้อมูล",--Press $BTN_INTERACT; for info
hud_int_push_button = "กด $BTN_INTERACT; เพื่อกดปุ่ม",--Press $BTN_INTERACT; to push the button
hud_int_remove_stinger = "กด $BTN_INTERACT; ค้างเพื่อย้ายตะปูเรือใบ",--Hold $BTN_INTERACT; to remove police stinger
hud_int_rewire_box = "กด $BTN_INTERACT; แฮกกล่องสัญญานไฟ",--Hold $BTN_INTERACT; to rewire
hud_int_rewire_timelock = "กด $BTN_INTERACT; เพื่อต่อ TimeLock",--Hold $BTN_INTERACT; to re-wire the time lock
hud_int_search_files = "กด $BTN_INTERACT; เพื่อหาไฟล์",--Press $BTN_INTERACT; to search for the files
hud_int_set_off_alarm = "กด $BTN_INTERACT; เพื่อแฮกระบบสัญญานแจ้งเตือน",--Hold $BTN_INTERACT; to set off the alarm
hud_int_setup_zipline = "กด $BTN_INTERACT; เพื่อตัดตั้งซิปไลน์",--Hold $BTN_INTERACT; to set up the zip-line
hud_int_signal_driver = "กด $BTN_INTERACT; เพื่อบอกคนขับรถ",--Hold $BTN_INTERACT; to signal the driver
hud_int_take = "กด $BTN_INTERACT; เพื่อหยิบ",--Press $BTN_INTERACT; to take
hud_int_take_acid = "กด $BTN_INTERACT; เพื่อหยิบเอซิส",--Press $BTN_INTERACT; to take the muriatic acid
hud_int_take_artifact = "กด $BTN_INTERACT; เพื่อหยิบวัตถุโบราณ",--Press $BTN_INTERACT; to take the artifact
hud_int_take_bridge = "กด $BTN_INTERACT; เพื่อหยิบแผ่นโลหะ",--Hold $BTN_INTERACT; to pick up the metal sheet
hud_int_take_c4 = "กด $BTN_INTERACT; เพื่อหยิบซีโฟร์",--Press $BTN_INTERACT; to take the c4
hud_int_take_camera = "กด $BTN_INTERACT; เพื่อหยิบกล้อง",--Press $BTN_INTERACT; to take the camera
hud_int_take_caustic_soda = "กด $BTN_INTERACT; เพื่อหยิบโซดา",--Press $BTN_INTERACT; to take the caustic soda
hud_int_take_chainsaw = "กด $BTN_INTERACT; เพื่อหยิบเลื่อย",--Press $BTN_INTERACT; to take the chainsaw
hud_int_take_confidential_folder = "กด $BTN_INTERACT; เพื่อหยิบข้อมูล",--Press $BTN_INTERACT; to take the intel
hud_int_take_confidential_folder_event = "กด $BTN_INTERACT; เพื่อหยิบที่อยู่",--Press $BTN_INTERACT; to take the address
hud_int_take_crowbar = "กด $BTN_INTERACT; เพื่อหยิบที่ชะแลง",--Press $BTN_INTERACT; to take the crowbar
hud_int_take_harddrive = "กด $BTN_INTERACT; ค้างเพื่อหยิบฮาร์ดไดรฟ์",--Hold $BTN_INTERACT; to take the hard drive
hud_int_take_hydrogen_chloride = "กด $BTN_INTERACT; เพื่อหยิบไฮโดรเจน",--Press $BTN_INTERACT; to take the hydrogen chloride
hud_int_take_jewelry = "กด $BTN_INTERACT; เพื่อหยิบเพรช",--Press $BTN_INTERACT; to take the jewelry
hud_int_take_keys = "กด $BTN_INTERACT; เพื่อหยิบกุญแจ",--Press $BTN_INTERACT; to take keys
hud_int_take_lance_part = "กด $BTN_INTERACT; ค้างเพื่อหยิบชิ้นส่วนอุปกรณ์",--Press $BTN_INTERACT; to take Beast spare parts
hud_int_take_mask = "กด $BTN_INTERACT; เพื่อหยิบหน้ากาก",--Press $BTN_INTERACT; to take the mask
hud_int_take_supplies = "กด $BTN_INTERACT; เพื่อหยิบอุปกรณ์",--Press $BTN_INTERACT; to take medical supplies
hud_int_take_thermite = "กด $BTN_INTERACT; เพื่อหยิบเธอไมท",--Press $BTN_INTERACT; to take the thermite
hud_int_take_thermite_paste = "กด $BTN_INTERACT; เพื่อหยิบเธอไมท",--Press $BTN_INTERACT; to take the thermite paste
hud_int_take_ticket = "กด $BTN_INTERACT; ค้างเพื่อหยิบตั๋ว",--Hold $BTN_INTERACT; to take ticket
hud_int_take_weapons = "กด $BTN_INTERACT; ค้างเพื่อหยิบปืน",--Hold $BTN_INTERACT; to take the weapons
hud_int_taking_supplies = "กำลังหยิบอุปกรณ์",--Taking medical supplies
hud_int_tape_loop = "กด $BTN_INTERACT; ค้างเพื่อแฮกกล้อง",--Hold $BTN_INTERACT; to apply camera loop
hud_int_timelock_numpad = "กด $BTN_INTERACT; ค้างเพื่อเริ่มนับถอยหลัง",--Press $BTN_INTERACT; to start timelock
hud_int_timelock_panel = "กด $BTN_INTERACT; ค้างเพื่อใช้คีย์การ์ด",--Press $BTN_INTERACT; to use keycard
hud_int_trick_treat = "00000000000000",--Trick or treat
hud_int_try_keys = "กด $BTN_INTERACT; ค้างเพื่อใช้กุญแจผี",--Hold $BTN_INTERACT; to try a key
hud_int_use_bridge = "กด $BTN_INTERACT; ค้างเพื่อสร้างสะพาน",--Hold $BTN_INTERACT; to bridge the gap
hud_int_use_computer = "กด $BTN_INTERACT; ค้างเพื่อหยิบคอมพิวเตอร์",--Hold $BTN_INTERACT; to take the computer
hud_int_use_ecm_jammer = "กด $BTN_INTERACT; ค้างเพื่อใช้งานเครื่องตัดสัญญาณ",--Hold $BTN_INTERACT; to use the ECM jammer
hud_int_use_files = "กด $BTN_INTERACT; ค้างเพื่อส่งไฟล์",--Hold $BTN_INTERACT; to pass the files under the door
hud_int_use_flare = "กด $BTN_INTERACT; เพื่อจุดแฟร์",--Press $BTN_INTERACT; to use the flare
hud_int_use_phone_signal_bus = "กด $BTN_INTERACT; เพื่อใช้โทรศัพย์เรียกรถ",--Press $BTN_INTERACT; to use the phone and signal the bus
hud_int_use_scanner = "กด $BTN_INTERACT; เพื่อใช้สแกนเนอร์",--Press $BTN_INTERACT; to use scanner
hud_int_use_ticket = "กด $BTN_INTERACT; ค้างเพื่อใช้ตั๋ว",--Hold $BTN_INTERACT; to use ticket
hud_int_use_zipline = "กด $BTN_INTERACT; เพื่อใช้ซิปไลน์",--Press $BTN_INTERACT; to use the zipline
hud_move_ship_gps_coords = "กด $BTN_INTERACT; ค้างเพื่อใส่พิกัดจีพีเอสใหม่",--Hold $BTN_INTERACT; to enter new GPS coordinates
hud_moving_ship_gps_coords = "กำลังใส่พิกัดใหม่",--Entering new GPS coordinates
hud_pku_manifest = "กด $BTN_INTERACT; เพื่อหยิบข้อมูล",--Press $BTN_INTERACT; to take the manifest
hud_int_play_tape = "กด $BTN_INTERACT; ค้างเพื่อเล่นเสียงเทป",--Hold $BTN_INTERACT; to play the tape
hud_int_open_panicroom = "กด $BTN_INTERACT; ค้างเพื่อใช้คีย์การ์ด",--Hold $BTN_INTERACT; to swipe the keycard
hud_int_hold_unlock_car = "กด $BTN_INTERACT; ค้างเพื่อปลดล็อครถ",--Hold $BTN_INTERACT; to unlock the car
hud_int_hold_take_evidence = "กด $BTN_INTERACT; ค้างเพื่อหยิบกล่องหลักฐาน",--Hold $BTN_INTERACT; to bag the evidence
hud_int_break_planks = "กด $BTN_INTERACT; ค้างเพื่อทำลายไม้",--Hold $BTN_INTERACT; to break the planks
hud_int_driving_drive = "กด $BTN_INTERACT; ค้างเพื่อขึ้นรถ",--Hold $BTN_INTERACT; to enter vehicle
hud_int_grab_code = "กด $BTN_INTERACT; ค้างเพื่อหยิบโค้ด",--Hold $BTN_INTERACT; to grab the code
hud_int_hack_laptop = "กด $BTN_INTERACT; ค้างเพื่อหยิบแลปท็อป",--Hold $BTN_INTERACT; to hack the laptop
hud_int_hack_timelock = "กด $BTN_INTERACT; ค้างเพื่อเริ่มนับถอยหลัง",--Hold $BTN_INTERACT; to force time lock
hud_cas_close_door = "กด $BTN_INTERACT; เพื่อปิดประตู",--Press $BTN_INTERACT; to close the door
hud_cas_ignite_fireworks = "กด $BTN_INTERACT; ค้างเพื่อจุดดอกไม้ไฟ",--Hold $BTN_INTERACT; to ignite the fireworks
hud_cas_open_compartment = "กด $BTN_INTERACT; ค้างเพื่อเปิดช่องลม",--Press $BTN_INTERACT; to open the compartment
hud_cas_open_door = "กด $BTN_INTERACT; เพื่อเปิดประตู",--Press $BTN_INTERACT; to open the door
hud_cas_open_guitar_case = "กด $BTN_INTERACT; ค้างเพื่อเปิดกล่องกีต้าร์",--Hold $BTN_INTERACT; to open the guitar case
hud_cas_open_powerbox = "กด $BTN_INTERACT; ค้างเพื่อสะเดาะล็อคกล่องไฟ",--Hold $BTN_INTERACT; to pick the powerbox lock
hud_cas_security_door = "กด $BTN_INTERACT; ค้างเพื่อสะเดาะล็อค",--Hold $BTN_INTERACT; to pick the lock
hud_cas_take_fireworks_bag = "กด $BTN_INTERACT; ค้างเพื่อหยิบ",--Hold $BTN_INTERACT; to take the fireworks
hud_cas_take_gear = "กด $BTN_INTERACT; ค้างเพื่อหยิบอุปกรณ์",--Hold $BTN_INTERACT; to take your gear
hud_check_customer_database = "กด $BTN_INTERACT; ค้างเพื่อดาวน์โหลดรายชื่อ",--Hold $BTN_INTERACT; to download guest list
hud_close_cas_elevator = "กด $BTN_INTERACT; เพื่อปิดประตูลิฟท์",--Press $BTN_INTERACT; to close the elevator door
hud_connect_cable = "กด $BTN_INTERACT; ค้างเพื่อเสียบปลั๊กไฟ",--Hold $BTN_INTERACT; to connect the cable to the power socket
hud_connect_which_hook = "กด $BTN_INTERACT; ค้างเพื่อใช้กัย BFD",--Hold $BTN_INTERACT; to connect the winch to the BFD
hud_disable_lasers = "กด $BTN_INTERACT; ค้างเพื่อปิดเลเซอร์",--Hold $BTN_INTERACT; to disable the lasers
hud_fix_bfd_drill = "กด $BTN_INTERACT; ค้างเพื่อซ่อม BFD",--Hold $BTN_INTERACT; to fix the BFD
hud_hack_skylight_barrier = "กด $BTN_INTERACT; เพื่อแฮกที่กั้นสกายไลท์",--Hold $BTN_INTERACT; to hack the skylight barrier
hud_hack_skylight_panel = "กด $BTN_INTERACT; เพื่อเริ่มแฮกที่กั้นสกายไลท์",--Press $BTN_INTERACT; to start hacking the skylight control panel
hud_insert_hotel_room_key = "กด $BTN_INTERACT; เพื่อใส่คีย์การ์ด",--Press $BTN_INTERACT; to insert keycard
hud_insert_usb = "กด $BTN_INTERACT; เพื่อก็อปปี้ข้อมูลจากแฟรชไดร์",--Press $BTN_INTERACT; to copy data from the USB stick
hud_int_are_turn_on_tv = "กด $BTN_INTERACT; เพื่อเปิดทีวี",--Press $BTN_INTERACT; to turn on the TV
hud_int_copy_data_usb = "กด $BTN_INTERACT; เพื่อเริ่มก็อปปี้รายชื่อ",--Press $BTN_INTERACT; start copying the guest list
hud_int_equipment_fire_extinguisher = "เครื่องดับเพลิง",--Fire extinguisher
hud_int_hold_answer_call = "กด $BTN_INTERACT; ค้างเพื่อตอบโทรศัพย์",--Hold $BTN_INTERACT; to answer call
hud_int_hold_extinguish_fire = "กด $BTN_INTERACT; ค้างเพื่อใช้ถังดับเพลิง",--Hold $BTN_INTERACT; to extinguish fire
hud_int_hold_jam_vent = "กด $BTN_INTERACT; ค้างเพื่อปิดช่องลม",--Hold $BTN_INTERACT; to jam the vent
hud_int_hold_place_laptop = "กด $BTN_INTERACT; ค้างเพื่อวางแลปท็อป",--Hold $BTN_INTERACT; to place the laptop
hud_int_hold_play_slots = "กด $BTN_INTERACT; ค้างเพื่อเล่นสล็อต",--Hold $BTN_INTERACT; to play the slots
hud_int_hold_scan_blueprints = "กด $BTN_INTERACT; ค้างเพื่อสแกนบลูปริ้น",--Hold $BTN_INTERACT; to scan the blueprints
hud_int_hold_search_c4 = "กด $BTN_INTERACT; ค้างเพื่อหาซีโฟร์",--Hold $BTN_INTERACT; to Search for C4
hud_int_hold_take_circle_cutter = "กด $BTN_INTERACT; ค้างเพื่อหยิบเครื่องตัด",--Hold $BTN_INTERACT; to take the circle cutter
hud_int_hold_take_fire_extinguisher = "กด $BTN_INTERACT; ค้างเพื่อหยิบถังดับเพลิง",--Hold $BTN_INTERACT; to take the fire extinguisher
hud_int_hold_take_warhead = "กด $BTN_INTERACT; ค้างเพื่อหยิบหัวรบนิวเคลีย์",--Hold $BTN_INTERACT; to take the warhead
hud_int_pour_drink = "กด $BTN_INTERACT; เพื่อใส่เครื่องดื่มผสมยาพิษ",--Press $BTN_INTERACT; to pour the spiked drink
hud_int_press_0 = "กด $BTN_INTERACT;  เพื่อใส่เลข 0",--Press $BTN_INTERACT; to enter 0
hud_int_press_01 = "กด $BTN_INTERACT; เพื่อใส่เลข 1 ",--Press $BTN_INTERACT; to enter 1
hud_int_press_02 = "กด $BTN_INTERACT; เพื่อใส่เลข 2 ",--Press $BTN_INTERACT; to enter 2
hud_int_press_03 = "กด $BTN_INTERACT; เพื่อใส่เลข 3 ",--Press $BTN_INTERACT; to enter 3
hud_int_press_04 = "กด $BTN_INTERACT; เพื่อใส่เลข 4 ",--Press $BTN_INTERACT; to enter 4
hud_int_press_05 = "กด $BTN_INTERACT; เพื่อใส่เลข 5 ",--Press $BTN_INTERACT; to enter 5
hud_int_press_06 = "กด $BTN_INTERACT; เพื่อใส่เลข 6 ",--Press $BTN_INTERACT; to enter 6
hud_int_press_07 = "กด $BTN_INTERACT; เพื่อใส่เลข 7 ",--Press $BTN_INTERACT; to enter 7
hud_int_press_08 = "กด $BTN_INTERACT; เพื่อใส่เลข 8 ",--Press $BTN_INTERACT; to enter 8
hud_int_press_09 = "กด $BTN_INTERACT; เพื่อใส่เลข 9 ",--Press $BTN_INTERACT; to enter 9
hud_int_press_clear = "กด $BTN_INTERACT; เพื่อใส่โค้ดใหม่",--Press $BTN_INTERACT; to clear the code
hud_int_press_enter = "กด $BTN_INTERACT; เพื่อใส่โค้ด",--Press $BTN_INTERACT; to enter the code
hud_int_search_blueprints = "กด $BTN_INTERACT; ค้างเพื่อหาบลูปริ้น",--Hold $BTN_INTERACT; to search for the blueprints
hud_int_send_blueprints = "กด $BTN_INTERACT; ค้างเพื่อส่งไปหาเบน",--Press $BTN_INTERACT; to fax scanned documents to Bain
hud_int_take_bottle = "กด $BTN_INTERACT; ค้างเพื่อหยิบเครื่องดื่มผสมยาพิษ",--Hold $BTN_INTERACT; to spike and pick up the bottle
hud_int_take_hotel_keycard = "กด $BTN_INTERACT; เพื่อหยิบห้องคีย์การ์ด",--Press $BTN_INTERACT; to take the hotel room keycard
hud_int_take_win_slip = "กด $BTN_INTERACT; เพื่อหยิบสลิปเงิน",--Press $BTN_INTERACT; to take the winning slip
hud_open_cas_briefcase = "กด $BTN_INTERACT; ค้างเพื่อเปิดกระเป๋าเอกสาร",--Hold $BTN_INTERACT; to open the briefcase
hud_open_cas_elevator = "กด $BTN_INTERACT; เพื่อเปิดประตูลิฟท์",--Press $BTN_INTERACT; to open the elevator door
hud_open_cas_securityroom_door = "กด $BTN_INTERACT; ค้างเพื่อเปิดประตูห้องรักษาความปลอดภัย",--Hold $BTN_INTERACT; to open the Security Center door
hud_place_sleeping_gass = "กด $BTN_INTERACT; ค้างเพื่อใส่แก๊สไปในช่องลม",--Hold $BTN_INTERACT; to pump gas into the vent
hud_screw_down = "กด $BTN_INTERACT; ค้างเพื่อขันน็อต",--Hold $BTN_INTERACT; to screw the winch down
hud_start_drill = "กด $BTN_INTERACT; ค้างเพื่อเริ่มเครื่อง BFD",--Hold $BTN_INTERACT; to start the BFD
hud_start_winch = "กด $BTN_INTERACT; ค้างเพื่อเริ่มอุปกรณ์",--Hold $BTN_INTERACT; to start the winch
hud_stop_drill = "กด $BTN_INTERACT; ค้างเพื่อหยุดเครื่อง BFD",--Hold $BTN_INTERACT; to stop the BFD
["hud_take_???"] = "กด $BTN_INTERACT; ค้างเพื่อหยิบของของ The Dentist",--Hold $BTN_INTERACT; to take The Dentist's loot
hud_take_bfd_tool = "กด $BTN_INTERACT; เพื่อหยิบเครื่องมือ BFD",--Press $BTN_INTERACT; to take the BFD tool
hud_take_casino_chips = "กด $BTN_INTERACT; เพื่อหยิบชิปคาสิโน",--Press $BTN_INTERACT; to pick up casino chips
hud_take_elevator_key = "กด $BTN_INTERACT; เพื่อหยิบกุญแจลิฟท์",--Press $BTN_INTERACT; to take the elevator key
hud_take_hook = "กด $BTN_INTERACT; ค้างเพื่อดึง",--Hold $BTN_INTERACT; to take the hook
hud_take_sleeping_gas = "กด $BTN_INTERACT; ค้างเพื่อหยิบแก๊สผสมยานอนหลับ",--Hold $BTN_INTERACT; to pick up the sleeping gas
hud_take_usb_key = "กด $BTN_INTERACT; เพื่อหยิบแฟรชไดร์",--Press $BTN_INTERACT; to take the USB stick
hud_take_usb_key_data = "กด $BTN_INTERACT; เพื่อหยิบแฟรชไดร์",--Press $BTN_INTERACT; to take the USB stick
hud_take_watertank = "กด $BTN_INTERACT; ค้างเพื่อหยิบถังน้ำ",--Hold $BTN_INTERACT; to take the water tank
hud_unpack_turret = "กด $BTN_INTERACT; ค้างเพื่อแกะป้อมปืน",--Hold $BTN_INTERACT; to unpack the sentry gun
hud_use_elevator_key = "กด $BTN_INTERACT; เพื่อเปิดระบบการควบคุมลิฟท์",--Press $BTN_INTERACT; to enable elevator controls
debug_interact_being_revived = "เพื่อนกำลังช่วยคุณอยู่",--You are Being Helped Up
hud_deploying_equipment = "กำลังวาง $EQUIPMENT;",--Deploying $EQUIPMENT;
hud_equipment_need_car_keys = "คุณต้องมีกุญแจรถ",--You need car keys
hud_equipment_need_barcode = "คุณต้องมีบาร์โค้ด",--You need a barcode
hud_equipment_need_boards = "คุณต้องมีไม้บอร์ด",--You need boards
hud_equipment_need_evidence = "คุณต้องมีกล่องหลักฐาน",--You need the evidence!
hud_equipment_need_files = "คุณต้องมีไฟล์",--You need the files!
hud_equipment_need_glass_cutter = "คุณต้องมีที่ตัดกระจก",--You need a glass cutter
hud_equipment_need_harddrive = "คุณต้องมีฮาร์ดไดรฟ์",--You need the hard drive!
hud_equipment_no_saw_blade = "คุณต้องมีใบเลื่อย",--You need a saw blade
hud_equipment_use_bridge = "หาอะไรก็ได้เพื่อสร้างทางผ่าน",--Find something to bridge the gap
hud_equipment_use_ticket = "คุณต้องมีตํ่ว",--You need the ticket!
hud_equipment_bfd_tool = "",--BFD Tool
hud_equipment_blueprints = "บูลปริ้น",--Blueprints
hud_equipment_bottle = "เครื่องดื่มผสมยาพิษ",--Spiked bottle
hud_equipment_circle_cutter = "เครื่องตัด",--Circle cutter
hud_equipment_data_usb_key = "แฟรชไดร์",--USB stick with guest list
hud_equipment_elevator_key = "",--Elevator Maintenance Key
hud_equipment_hotel_room_keycard = "คีย์การ์ดห้องพัก",--Hotel room keycard
hud_equipment_need_circle_cutter = "คุณต้องมีที่ตัด",--You need the circle cutter
hud_equipment_need_fire_extinguisher = "คุณต้องมีถังดับเพลิง",--You need a fire extinguisher
hud_equipment_sleeping_gas = "แก๊สผสมยานอนหลับ",--Sleeping gas
hud_equipment_usb_key = "แฟรชไดร์์",--USB stick
hud_equipment_winch_hook = "",--Winch hook
hud_int_cut_wire = "กด $BTN_INTERACT; เพื่อตัดสายไฟ",--Press $BTN_INTERACT; to cut the wire
hud_int_equipment_saw_upgrade = "กด $BTN_INTERACT; เพื่ออัพเกรดเลื่อย",--Hold $BTN_INTERACT; to upgrade the saw
hud_int_equipment_sensor_trip_mine = "กด $BTN_INTERACT; ค้างเพื่อ押して爆破とセンサーのモードを切り替える",--Press $BTN_INTERACT; to toggle between explosive and sensor mode
hud_int_hold_close_shutters = "กด $BTN_INTERACT; เพื่อปิดม่าน",--Press $BTN_INTERACT; to close the shutters
hud_int_hold_ignite_trap = "กด $BTN_INTERACT; ค้างเพื่อเผากับดัก",--Hold $BTN_INTERACT; to ignite the trap
hud_int_hold_open_shutters = "กด $BTN_INTERACT; เพื่อเปิดม่าน",--Press $BTN_INTERACT; to open the shutters
hud_int_hold_open_vent = "กด $BTN_INTERACT; ค้างเพื่อเปิดตู้นิรภัย",--Hold $BTN_INTERACT; to open the vent
hud_int_hold_pku_knife = "กด $BTN_INTERACT; ค้างเพื่อหยิบมีด",--Hold $BTN_INTERACT; to Pick up the Knife
hud_int_hold_poison_bottle = "กด $BTN_INTERACT; ค้างเพื่อใส่ยาพิษ",--Hold $BTN_INTERACT; to spike the bottle
hud_int_hold_start_crane = "กด $BTN_INTERACT; ค้างเพื่อใช้งานเครน",--Hold $BTN_INTERACT; to start the crane
hud_int_hold_take_pig = "กด $BTN_INTERACT; ค้างเพื่อหยิบหมู",--Hold $BTN_INTERACT; to take a Pig
hud_int_hold_take_pills = "กด $BTN_INTERACT; ค้างเพื่อหยิบยา",--Hold $BTN_INTERACT; to take the Pills
hud_int_hold_take_safe = "กด $BTN_INTERACT; ค้างเพื่อหยิบเซฟ",--Hold $BTN_INTERACT; to take the safe
hud_int_hold_take_saw = "กด $BTN_INTERACT; ค้างเพื่อเลื่อย",--Hold $BTN_INTERACT; to take the saw
hud_int_press_respawn = "กด $BTN_INTERACT; เพื่อสปอว์นรถใหม่",--Press $BTN_INTERACT; to respawn the vehicle
hud_int_shaped_sharge = "กด $BTN_INTERACT; ค้างเพื่อวางระเบิด",--Hold $BTN_INTERACT; to place shaped charge
hud_int_take_envelope = "กด $BTN_INTERACT; เพื่อหยิบซอง",--Press $BTN_INTERACT; to take the Envelope
hud_int_use_chute = "กด $BTN_INTERACT; ค้างเพื่อใช้งานอุปกรณ์",--Press $BTN_INTERACT; to Use Chute
hud_int_vehicle_close_trunk = "กด $BTN_INTERACT; ค้างเพื่อปิดกระบะรถ",--Hold $BTN_INTERACT; to close the trunk
hud_int_vehicle_drive = "กด $BTN_INTERACT; ค้างเพื่อขับรถ",--Hold $BTN_INTERACT; to drive the vehicle
hud_int_vehicle_enter = "กด $BTN_INTERACT; ค้างเพื่อขับรถ",--Hold $BTN_INTERACT; to enter the vehicle
hud_int_vehicle_loot = "กด $BTN_INTERACT; ค้างเพื่อเอาของจากรถ",--Hold $BTN_INTERACT; to take loot from the vehicle
hud_int_vehicle_open_trunk = "กด $BTN_INTERACT; ค้างเพื่อเปิดกระบะรถ",--Hold $BTN_INTERACT; to open the trunk
hud_int_vehicle_repair = "กด $BTN_INTERACT; ค้างเพื่อซ่อมรถ",--Hold $BTN_INTERACT; to repair the vehicle
hud_fill_watertank = "กด $BTN_INTERACT; ค้างเพื่อเติมถังน้ำ",--Hold $BTN_INTERACT; to fill the water tank
hud_place_watertank = "กด $BTN_INTERACT; ค้างเพื่อวางถังน้ำ",--Hold $BTN_INTERACT; to place the water tank
savefile_empty = "[เซฟไฟล์ใหม่]",--[New Save File]
savefile_game_title = "เพย์เดย์ 2",--PAYDAY 2
savefile_setting = "Game settings: Version $VERSION; or higher is required.",--Game settings: Version $VERSION; or higher is required.
savefile_progress = "Player progression: Version $VERSION; or higher is required.",--Player progression: Version $VERSION; or higher is required.
savefile_setting_description = "User specific game settings.",--User specific game settings.
savefile_progress_description = "Player statistics and game progression.",--Player statistics and game progression.
savefile_saving = "กำลังเซฟ...",--Saving...
savefile_loading = "กำลังโหลด...",--Loading...
savefile_removing = "กำลังลบ...",--Removing...
debug_interact_sewer_manhole = "กด $BTN_INTERACT; ค้างเพื่อเปิดฝาท่อ",--Hold $BTN_INTERACT; to Open the Manhole
debug_interact_security_station = "กด $BTN_INTERACT; ค้างเพื่อแฮกระบบ",--Hold $BTN_INTERACT; to Start the Override
debug_interact_hostage_move = "กด $BTN_INTERACT; ค้างเพื่อย้ายตัวประกัน",--Hold $BTN_INTERACT; to move the hostage
debug_interact_hostage_stay = "กด $BTN_INTERACT; ค้างเพื่อสั่งตัวประกันนอนลง",--Hold $BTN_INTERACT; to sit the hostage down
debug_interact_intimidate = "กด $BTN_INTERACT; ค้างเพื่อมัดมือตัวประกัน",--Hold $BTN_INTERACT; to Tie Hands
hud_deploy_valid_help = "เล็งตรงพื้นเพื่อวางอุปกรณ์",--Aim at a valid surface
debug_interact_c4 = "กด $BTN_INTERACT; ค้างเพื่อวางระเบิด",--Hold $BTN_INTERACT; to Place the Explosives
debug_interact_gage_assignment_take = "กด $BTN_INTERACT; ค้างเพื่อหยิบแพคแกจ",--Hold $BTN_INTERACT; to pick up the package
hud_action_taking_ammo = "กำลังใช้งานกล่องกระสุน",--Taking ammo
hud_action_taking_artifact = "กำลังหยิบวัตถุโบราณ",--Taking artifact
hud_action_taking_blueprints = "กำลังหยิบบูลปริ้น",--Taking blueprints
hud_action_taking_cocaine = "กำลังหยิบสารเสพติด",--Taking cocaine
hud_action_taking_gage_assignment = "กำลังหยิบของ",--Picking it up
hud_action_taking_gasoline = "กำลังหยิบแก๊สโซลีน",--Taking gasoline
hud_action_taking_gold = "กำลังหยิบทอง",--Taking gold
hud_action_taking_grenades = "กำลังหยิบระเบิด",--Grabbing grenade
hud_action_taking_jewelry = "กำลังหยิบเพรช",--Taking jewelry
hud_action_taking_meth = "กำลังหยิบสารเสพติด",--Taking meth
hud_action_taking_money = "กำลังหยิบเงิน",--Taking money
hud_action_taking_painting = "กำลังหยิบรูปภาพ",--Taking painting
hud_action_taking_pure_cocaine = "กำลังหยิบขนมปังผสมสารเสพติด",--Taking pure Colombian
hud_action_taking_reaktor = "กำลังหยิบเครื่องจักร",--Taking fusion reactor prototype
hud_action_taking_sandwich = "กำลังหยิบ",--Taking Almir's toast
hud_action_taking_saw_blade = "กำลังหยิบเลื่อย",--Taking saw blade
hud_action_taking_server = "กำลังหยิบเครื่องเซิฟเวอร์",--Taking server
hud_action_taking_weapons = "กำลังหยิบแาวุธปืน",--Taking weapons
hud_action_tape_looping = "กำลังปิดใช้งานกล้องชั่วคราว",--Applying the camera loop
hud_action_trading = "กำลังแลกเปลี่ยน",--Trading
hud_action_try_keys = "กำลังใช้กุญแจผี",--Trying keys
hud_action_barcode = "กำลังหยิบบาร์โค้ด",--Taking the barcode
hud_action_disassemble_cro_loot = "กำลังหยิบส่วนประกอบของระเบิด",--Taking bomb part
hud_int_taking_supplies = "กำลังใช้งานกล่องยา",--Taking medical supplies
debug_interact_sewer_manhole = "กด $BTN_INTERACT; ค้างเพื่อเปิดฝาท่อ",--Hold $BTN_INTERACT; to Open the Manhole
debug_interact_bodybags_bag_take_bodybag = "กด $BTN_INTERACT; ค้างเพื่อหยิบกระเป๋าศพ",--Hold $BTN_INTERACT; to grab a body bag
debug_interact_doctor_bag_heal = "กด $BTN_INTERACT; ค้างเพื่อใช้กระเป๋ายา",--Hold $BTN_INTERACT; to Patch Yourself Up
debug_interact_open_door = "กด $BTN_INTERACT; เพื่อเปิดประตู",--Press $BTN_INTERACT; to Open The Door
debug_interact_equipment_stash_planks = "คุณต้องมีไม้",--You need some Planks
debug_interact_stash_planks = "กด $BTN_INTERACT; ค้างเพื่อเสริมกำบัง",--Hold $BTN_INTERACT; to Barricade
debug_interact_stash_planks_pickup = "กด $BTN_INTERACT; ค้างเพื่อหยิบไม้",--Hold $BTN_INTERACT; to Take the Planks
debug_interact_interaction_ball = "กด $BTN_INTERACT; ค้างเพื่อต่อสายยาง",--Hold $BTN_INTERACT; to Pull the Hose
debug_interact_money_printed_take_money = "กด $BTN_INTERACT; เพื่อหยิบเงิน",--Hold $BTN_INTERACT; to take the Money
hud_action_try_keys_no_key = "คุณต้องมีกุญแจผี",--Requires keychain to unlock
debug_interact_grenade_crate_take_grenades = "กด $BTN_INTERACT; ค้างเพื่อหยิบระเบิด",--Hold $BTN_INTERACT; to grab a grenade
debug_interact_hospital_security_cable = "กด $BTN_INTERACT; ค้างเพื่อตัดสายไฟ",--hold $BTN_INTERACT; to cut the cable
hud_int_hold_cut_cable = "กด $BTN_INTERACT; ค้างเพื่อตัดสายไฟ",--Hold $BTN_INTERACT; to cut the cable
debug_interact_saw_jammed = "กด $BTN_INTERACT; ค้างเพื่อซ่อมเลื่อย",--Hold $BTN_INTERACT; to Restart the Saw
debug_interact_glass_cutter = "กด $BTN_INTERACT; เพื่อวางเครื่องตัดเหล็ก",--Hold $BTN_INTERACT; to Place the Cutter
debug_interact_circuit_breaker = "กด $BTN_INTERACT; เพื่อเปิดไฟฟ้า",--Press $BTN_INTERACT; to Turn on the Power
debug_interact_hack_ipad_jammed = "กด $BTN_INTERACT; ค้างเพื่อเริ่มระบบใหม่",--Hold $BTN_INTERACT; to reboot
debug_interact_equipment_cable_tie = "สายมัดมือของคุณหมดแล้ว",--You need cable ties
hud_starting_heist = "กำลังใส่หน้ากาก",--Preparing mask
hud_instruct_mask_on = "กด $BTN_USE_ITEM; ค้างเพื่อใส่หน้ากาก",--$BTN_USE_ITEM; to put on mask
debug_interact_ammo_bag_take_ammo = "กด $BTN_INTERACT; ค้างเพื่อเติมกระสุน",--Hold $BTN_INTERACT; to Take Ammo
debug_interact_money_wrap_take_money = "กด $BTN_INTERACT; ค้างเพื่อหยิบเงิน",--Hold $BTN_INTERACT; to Fill the Money bag
menu_hud_cheater = "ขยะสังคม",--Cheater
menu_hud_cheater = "ขยะสังคม",--Cheater
debug_interact_thermite = "กด $BTN_INTERACT; ค้างเพื่อเผา",--Press $BTN_INTERACT; to place the Thermite
debug_interact_crowbar = "กด $BTN_INTERACT; ค้างเพื่องัดประตู",--Hold $BTN_INTERACT; to Breach the Door
debug_interact_crowbar2 = "กด $BTN_INTERACT; ค้างเพื่องัดตู้",--Hold $BTN_INTERACT; to Breach the Trunk
debug_interact_crowbar_breach = "กด $BTN_INTERACT; ค้างเพื่องัด",--Hold $BTN_INTERACT; to Breach
debug_interact_hold_to_breach = "กด $BTN_INTERACT; ค้างเพื่องัด",--Hold $BTN_INTERACT; to Breach
hud_escape_jolly_mission5_hl = "ใช้ซีโฟร์เพื่อทำลายพนัง",--Use c4 to breach the wall
debug_interact_revive = "กด $BTN_INTERACT; ค้างเพื่อช่วยเพื่อร่วมทีม",--Hold $BTN_INTERACT; to Help your Teammate Up
hud_action_reviving = "กำลังช่วย",--Helping
debug_interact_c4_bag = "กด $BTN_INTERACT; ค้างหยิบระเบิด",--Hold $BTN_INTERACT; to Pick up Explosives
debug_interact_money_wrap_single_bundle_take_money = "กด $BTN_INTERACT; เพื่อหยิบเงิน",--Press $BTN_INTERACT; to Take the Money
hint_full_health = "เลือดของคุณเต็มอยู่แล้ว",--You already have full health.
hint_full_ammo = "กระสุนของคุณเต็มอยู่แล้ว",--You already have full ammo.
hint_full_bodybags = "กระเป๋าศพของคุณเต็มอยู่แล้ว",--You already have the max amount of body bags.
hint_full_grenades = "อาวุธขว้างของคุณเต็มอยู่แล้ว",--You already have the max amount of grenades.
hint_full_keycard = "คุณมีคีย์การ์ดอยู่แล้ว",--You already have a keycard.
hud_hint_tape_loop_limit_reached = "คุณสามารถแฮกกล้องวงจรปิดเพียงหนึ่งเครื่องต่อครั้งเท่านั้น",--Can only have one active camera loop
hud_hint_body_bag_limit_reached = "คุณไม่มีกระเป๋าศพเหลือแล้ว",--You have no more body bags.
hud_hint_hostage_follow_limit = "ตัวประกันกำลังตามคุณอยู่แล้ว",--Maximum number of following hostages reached.
hud_hint_convert_enemy_failed = "คุณมีตำรวจที่เป็นพวกอยู่แล้ว",--Your persuasion techniques were resisted
hud_hint_carry_block = "คุณกำลังแบกกระเป๋าอยู่ในตอนนี้",--You are already carrying something
hud_hint_zipline_no_bag = "คุณต้องแบกกระเป๋าเพื่อส่งของ",--You need to carry a bag to attach it
hint_max_special_equipment = "คุณกำลังแบกกระเป๋าอยู่ในตอนนี้",--You can't carry more
hint_no_bfd_tool = "คุณต้องมีเครื่องมือเพื่อซ่อมแซม",--You need a BFD tool to fix the BFD
hint_no_blueprints = "คุณต้องมีบูลปริ้น",--You need blueprints to scan them!
hint_no_bottle = "คุณต้องมียาพิษ",--You need a spiked bottle!
hint_no_data_usb_key = "คุณต้องก็อปปี้รายชื่อลูกค้าลงในแฟรชไดร์ฟก่อน",--You need to copy the guest list to the USB stick first
hint_no_elevator_key = "คุณต้องมีรหัสผ่าน",--You need the elevator maintenance key
hint_no_hotel_room_key = "คุณต้องมีคีย์การ์ดเพื่อเข้าไปในห้อง",--You need a keycard to enter the hotel room
hint_no_sleeping_gas = "คุณต้องมีแก๊สผสมยานอนหลับ",--You need sleeping gas
hint_no_usb_key = "คุณต้องมีแฟรชไดร์ฟ",--You need a USB stick
hint_no_winch_hook = "คุณต้องดึงที่เกี่ยวจากเครื่องจักรก่อน",--You need to take the hook from the winch first
debug_interact_trade = "กด $BTN_INTERACT; ค้างเพื่อแลกเปลี่ยนตัวประกัน",--Hold $BTN_INTERACT; to Trade your Teammate
menu_victory_goto_next_stage = "กด $CONTINUE; เพื่อทำภารกิจในวันถัดไป",--$CONTINUE; Proceed to next day
hud_civilian_killed_title = "คุณได้ฆ่าตัวประกัน!",--Civilian killed!
hud_civilian_killed_message = "หักเงินเป็นจำนวน $AMOUNT;",--Deducting $AMOUNT; in cleaner costs
hud_action_generic = "กำลังดำเนินการ",--Interacting
hud_interact_sentry_gun_switch_fire_mode = "กด $BTN_INTERACT; เพื่อเปลี่ยนเป็นโหมดยิง",--Press $BTN_INTERACT; to switch fire mode
hud_interact_pickup_sentry_gun = "กด $BTN_INTERACT; เพื่อหยิบป้อมปืน",--Hold $BTN_INTERACT; to pick up
hud_int_hold_remove_debris = "กด $BTN_INTERACT; ค้างเพื่อเอาสิ่งกีดขวางออก",--Hold $BTN_INTERACT; to remove debris
hud_int_hold_fasten_strap = "กด $BTN_INTERACT; ค้างเพื่อติดตั้งสายยึด",--Hold $BTN_INTERACT; to fasten the strap
hud_hack_ship_control = "กด $BTN_INTERACT; ค้างเพื่อแฮกระบบข้อมูลของเรือขนส่ง",--Hold $BTN_INTERACT; to hack the ship control terminal
hud_int_hold_grab_goat = "กด $BTN_INTERACT; ค้างเพื่อหยิบแพะ",--Hold $BTN_INTERACT; to grab the goat
hud_man_apply_tape = "กด $BTN_INTERACT; ค้างเพื่อมัดเทป",--Hold $BTN_INTERACT; to apply tape
hud_man_remove_bars = "กด $BTN_INTERACT; ค้างเพื่อมัดเทป",--Hold $BTN_INTERACT; to apply tape







