menu_system_message = "ระบบ",--
menu_chat_peer_cheated_many_bags_server = "ผู้เล่น $name; ได้พยายามโกงโดยการโยนกระเป๋ามากเกินไป",--$name; tried to cheat by throwing too many bags.
menu_chat_vote_kick_no_unknown = "ผู้เล่น $name; ได้โหวตเตะคนอื่นที่กำลังเชื่อมต่ออยู่",--$name; voted against kicking someone currently connecting.
menu_chat_peer_cheated_many_bags = "ผู้เล่น $name; ได้โกงโดยการโยนกระเป๋ามากเกินไป",--$name; cheated by throwing too many bags.
menu_chat_peer_unlocked_asset = "ผู้เล่น $name; ได้ปลดล็อคอุปกรณ์ช่วยเหลือ $asset;",--$name; unlocked asset: $asset;.
menu_chat_peer_cheated_many_equipments_server = "ผู้เล่น $name; ได้พยายามโกงโดยการเพิ่มอุปกรณ์มากเกินไป",--$name; tried to cheat by adding too many deployables.
menu_chat_peer_added = "ผู้เล่น $name; กำลังเข้าร่วมเกม",--$name; is joining.
menu_chat_preplanning_unreserved = "ผู้เล่น $name; ได้ลบ $type;",--$name; removed $type;
menu_chat_peer_cheated_invalid_weapon = "ผู้เล่น $name; ได้โกงโดยการใช้อาวุะหรือของแต่งปืนที่ไม่มีจริง",--$name; cheated by using invalid weapon or weapon mod.
menu_chat_peer_cheated_many_grenades_server = "ผู้เล่น $name; ได้พยายามโกงโดยการปาระเบิดมากเกินไป",--$name; tried to cheat by throwing too many grenades.
menu_chat_peer_cheated_invalid_job = "ผู้เล่น $name; ได้โกงโดยการสร้างด่านที่ไม่มีจริง",--$name; cheated by creating invalid contract.
menu_chat_peer_unlocked_gage_asset = "ผู้เล่น $name; ปลดล็อค  Gage Perk $asset;",--$name; unlocked Gage Perk: $asset;.
menu_chat_vote_kick_no = "ผู้เล่น $name; ได้โหวตเตะ $kick_name;",--$name; voted against kicking $kick_name;.
menu_chat_vote_kick_yes_unknown = "ผู้เล่น $name; ได้ลงมติเห็นชอบที่จะเตะคนที่กำลังเชื่อมต่ออยู่",--$name; voted in favor of kicking someone currently connecting.
menu_chat_peer_cheated_many_grenades = "ผู้เล่น $name; ได้โกงโดยการปาระเบิดมากเกินไป",--$name; cheated by throwing too many grenades.
menu_chat_peer_cheated_invalid_henchmen = "ผู้เล่น $name; โกงโดยการใช้หน้า Loadout Crew ที่ไม่ถูกต้อง",--$name; cheated by using invalid crew loadout.
menu_chat_restart_timer = "ด่านจะเริ่มใหม่ใน $time; วินาที",--Restarting in $time; seconds.
menu_chat_vote_kick_started = "การโหวตเตะกำลังดำเนินอยู่",--Vote kicking is in progress.
menu_chat_peer_lost = "ผู้เล่น $name; ได้ตัดการเชื่อมต่อแล้ว",--$name; disconnected.
menu_chat_peer_cheated_wrong_equipment_server = "ผู้เล่น $name; ได้พยายามที่จะโกงโดยการเพิ่มอุปกรณ์ที่ไม่มี",--$name; tried to cheat by adding wrong deployable.
menu_chat_peer_cheated_invalid_character = "ผู้เล่น $name; ได้โกงโดยการใช้ตัวละครที่ไม่มี",--$name; cheated by using invalid character.
menu_chat_vote_restart_started = "โหวตเริ่มด่านใหม่อยู่ในการดำเนินการ",--Vote restart is in progress.
menu_chat_vote_restart_no = "ผู้เล่น $name; โหวตให้รีสตาร์ท",--$name; voted against restarting.
menu_chat_peer_cheated_many_equipments = "ผู้เล่น $name; ได้โกงโดยการเพิ่มอุปกรณ์มากเกินไป",--$name; cheated by adding too many deployables.
menu_chat_vote_restart_yes = "ผู้เล่น $name; โหวตให้รีสตาร์ท",--$name; voted in favor of restarting.
menu_chat_peer_kicked = "ผู้เล่น $name; ถูกเตะออกจากห้องแล้ว",--$name; has been kicked.
menu_chat_vote_restart_ended = "การโหวตเริ่มด่านใหม่ได้ยุติแล้ว",--Vote restart has ended.
menu_chat_peer_cheated_many_assets = "ผู้เล่น $name; ได้โกงโดยการสร้างอุปกรณ์ช่วยเหลือมากเกินไป",--$name; cheated by creating too many equipment assets.
menu_chat_vote_kick_ended = "การโหวตเตะได้ยุติแล้ว",--Vote kicking has ended.
menu_chat_peer_cheated_many_bags_pickup_server = "ผู้เล่น $name; ได้พยายามโกงโดยการหยิบกระเป๋ามากเกินไป",--$name; tried to cheat by picking up too many bags.
menu_chat_vote_kick_yes = "ผู้เล่น $name; ได้โหวตเตะ $kick_name;",--$name; voted in favor of kicking $kick_name;.
menu_chat_preplanning_reserved = "ผู้เล่น $name; วาง $type;",--$name; placed $type;
menu_chat_gage_assignment_pickup = "ผู้เล่น $name; ได้หยิบ Packgage เหลืออีก $remaining; ชิ้น",--$name; picked up a package. $remaining; remains.
menu_chat_peer_cheated_many_bags_pickup = "ผู้เล่น $name; ได้โกงโดยการหยิบกระเป๋ามากเกินไป",--$name; cheated by picking up too many bags.
menu_chat_peer_cheated_invalid_mask = "ผู้เล่น $name; ได้โกงโดยการใช้หน้ากากที่ไม่มีจริง",--$name; cheated by using invalid mask.
menu_chat_peer_cheated_wrong_equipment = "ผู้เล่น $name; ได้โกงโดยการเพิ่มอุปกรณ์ที่ไม่มี",--$name; cheated by adding wrong deployable.
menu_chat_peer_kicked_unknown = "บางคนที่กำลังเชื่อมต่ออยู่ได้ถูกเตะออกแล้ว",--Someone currently connecting has been kicked.
menu_chat_peer_left = "ผู้เล่น $name; ได้ออกจากด่านแล้ว",--$name; left.
menu_chat_peer_failed = "ผู้เล่น $name; การยืนยันผิดพลาด",--$name; failed authentication.
menu_chat_peer_added_modded = "ผู้เล่น $name; ได้ติดตั้ง Mod สามารถเช็คข้อมูลเพิ่มเติมได้ที่ รายชื่อผู้เล่น",--$name; has mods installed. Check the player list for more information.
menu_chat_vote_cancel = "ผู้เล่น $name; ได้งดออกเสียง",--$name; abstained from voting.
