menu_crew_eager = "",--Accelerator
menu_crew_character_order = "",--AI TEAMMATE CHARACTER PRIORITY
menu_crew_inspire_desc = "",--Your team AI can now use Inspire once every $value1; minutes. Reduced by $value2; minutes for every other AI present.
menu_crew_management = "",--Crew management
menu_crew_evasive_desc = "",--Players' dodge is increased by $value1;.
menu_crewpage = "",--Planning Phase
menu_crew_ai_ap_ammo = "",--Piercing
menu_crew_interact_desc = "",--Players interact $value1; faster. This bonus is increased by $value2; for every other AI present.
menu_crew_evasive = "",--Distractor
menu_crew_scavenge_desc = "",--Players pickup $value1; more ammunition. This bonus is increased by $value2; for every other AI present.
menu_crew_quiet = "",--Concealer
menu_crew_interact = "",--Quick
menu_crew_generous = "",--Stockpiler
menu_crew_motivated_desc = "",--Players have $value1; more stamina and the armor speed penalty is reduced by $value2;.
menu_crew_eager_desc = "",--Players reload $value1; faster and swap weapons $value2; faster.
menu_crew_healthy = "",--Reinforcer
menu_crew_regen_desc = "",--Players heal $value1; health every $value2; seconds.
menu_crew_management_help = "",--Manage your AI Crew: Characters and Loadouts
menu_crew_quiet_desc = "",--Players gain $value1; more concealment.
menu_crew_sturdy = "",--Protector
menu_crew_loadout_order = "",--AI LOADOUTS
menu_crew_slot_index = "",--LOADOUT $index;
menu_crew_generous_desc = "",--Players are granted an extra throwable for every $value1; kills.
menu_crew_healthy_desc = "",--Players' health is increased by $value1;.
menu_crew_ai_ap_ammo_desc = "",--Your team AI will now use armor piercing rounds. This enables them to shoot through shields and armor.
menu_crew_none = "",--NONE
menu_crew_motivated = "",--Invigorator
menu_crew_defualt = "",--DEFAULT
menu_crew_inspire = "",--Inspiring
menu_crew_regen = "",--Healer
menu_crew_scavenge = "",--Sharpeyed
menu_crew_sturdy_desc = "",--Players' armor is increased by $value1;.
