menu_cs_select_modifier = "เลือกการปรับแต่ง",--
menu_cs_modifiers_loud = "การปรับแต่งบู้",--
menu_cs_modifiers = "การปรับแต่ง",--
menu_cs_select_next_heist = "เลือกด่านต่อไป",--
menu_cs_rewards = "รางวัล",--
menu_cs_modifiers_forced = "การปรับแต่งแบบบังคับ",--
menu_cs_modifiers_forced_multiple = "ได้เพิ่มการปรับแต่งแบบบังคับไปแล้ว $count; การปรับแต่ง",--$count; modifiers have been added to the crime spree
cn_crime_spree_starting = "เริ่มที่เลเวล",--
menu_cs_maximum = "จำนวนสูงสุด",--Maximum
menu_cs_stop_spree = "หยุดการเล่น Crime Spree",--
menu_cs_suspend_spree = "พักการเล่น Crime Spree",--
menu_challenge_cash_drop = "เงิน",--
menu_cs_next_modifier_forced = "การปรับแต่งแบบบังคับ",--
menu_cs_modifiers_stealth = "การปรับแต่งย่องเงียบ",--
menu_cs_modifier_dozer_rage = "เมื่อหน้ากาก Bulldozer แตก Bulldozer จะเข้าโหมดบ้าคลั่งจะทำดาเมจมากขึ้น $damage;%",--When a Bulldozer's face plate is destroyed, the Bulldozer enters a berserker rage, receiving a $damage;% increase to their base damage output.
menu_cs_modifier_shield_phalanx = "Shield ทุกตัวจะถูกแทนที่ด้วย Captain Winter's Shield",--All Shield units in the game are replaced by Captain Winter's Shield units.
menu_cs_modifier_shield_reflect = "Shields จะสะท้อนลูกระเบิดกลับมา",--Shields will reflect projectiles.
menu_cs_modifier_medic_deathwish = "เมื่อไหร่ก็ตามที่ Menu ถูกฆ่าตำรวจทุกตัวที่อยู่ในระยะจะถูกฮีล",--Whenever a Medic is killed, all cops within the Medic's healing range are instantly healed.
menu_cs_modifier_medic_speed = "ลดคูลดาวน์ของ Medic ลง $speed;%",--Medics heal cooldown is $speed;% faster.
menu_cs_modifier_total_generic_percent = "รวมทั้งหมด: $value;%.",--(Total: $value;%.)
menu_cs_modifier_cloaker_tear_gas = "เมื่อฆ่า Cloakers สำเร็จจะวางระเบิดแก็สนำตาแก็สจะอยู่นาน $duration; วินาทีในระยะ $diameter เมตรและทำดาเมจ $damage; ต่อวินาที",--Killed Cloakers will instantly drop a tear gas grenade. The tear gas has a duration of $duration; seconds, covers a $diameter; meter diameter area and deals $damage; damage per second to any heister who stands in it.
menu_cs_modifier_enemy_damage = "ศัตรูทำดาเมจเพิ่มขึ้น $damage;%",--Enemies deal an additional $damage;% more damage.
menu_cs_modifier_enemy_health_damage = "ศัตรูเลือดเพิ่มขึ้น $health;% และทำดาเมจเพิ่มขึ้น $damage;%",--Enemies have an additional $health;% more health and deal an additional $damage;% more damage.
menu_cs_modifier_medic_rage = "สำหรับตำรวจที่ตายใกล้ระยะของ Medic จะทำให้ Medic ทำดาเมจเพิ่มขึ้น $damage;% และสามารถซ้อนทับกันได้",--For every cop that dies within a Medic's healing range, that Medic sees his base damage output increased by $damage;%. This effect stacks indefinitely.
menu_cs_modifier_concealment = "ค่าอำพรางอย่างต่ำจะถูกเพิ่มขึ้นอีก $conceal; ในโหมดย่องเงียบ",--The minimum concealment level is increased by $conceal; in stealth.
menu_cs_modifier_no_hurt = "ศัตรูจะไม่เดินเซจากการทำดาเมจแล้ว",--Enemies can not be staggered from damage.
menu_cs_modifier_assault_extender = "ช่วง Assaults จะนานขึ้น $duration;% สามารถลดได้จากการตัวประกันและตำรวจเปลี่ยนฝั่ง $deduction;% หนึ่งตัวและสามารถซ้อนทับกันสูงสุดที่ $max_hostages; ตัว",--Police Assaults will have a $duration;% longer duration. This gets reduced by $deduction;% for every hostage and converted cop - up to a maximum of $max_hostages;
menu_cs_modifier_dozer_minigun = "จะมีโอกาสเกิด Bulldozer เดินช้าแต่ถือ Mini Gun",--Whenever a Bulldozer spawns, there is a chance that it will be a slow-moving minigun-wielding Bulldozer.
menu_cs_modifier_dozer_immune = "Bulldozer จะไม่ได้รับดาเมจจากการระเบิด",--Bulldozers are immune to explosive damage.
menu_cs_modifier_taser_overcharge = "การซ็อตของ Taser จะทำให้ผู้เล่นล้มลงเร็วขึ้น $speed;%",--The tasing knockout effect of the Taser now knocks a player out $speed;% faster.
menu_cs_modifier_cloaker_smoke = "Cloakers จะวางระเบิดควันเมื่อเตะผู้เล่น",--Cloakers will drop a smokebomb when they kick a player.
menu_cs_modifier_dozer_medic = "มีโอกาสที่ Bullzoder จะเกิดเป็น Medic-Bulldozer ที่มีความสามารถเหมือน Medic",--Whenever a Bulldozer spawns, there is a chance that it will be a Medic Bulldozer. A Medic Bulldozer counts as both a Medic and a Bulldozer.
menu_cs_modifier_dozer_lmg = "ทำให้ Skulldozers เกิดแล้ว",--Skulldozers will now spawn.
menu_cs_modifier_medics = "Medic สองรูปแบบถูกอนุญาตให้เข้าแผนที่แล้ว",--Two additional Medics are allowed into the level.
menu_cs_modifier_medic_adrenaline = "เมื่อ Medic ชุบตำรวจตัวอื่นจะทำให้ตำรวจที่ชุบทำดาเมจได้มากขึ้น $damage;%",--Whenever a Medic revives another cop, the revived cop gets a $damage;% increase to their base damage output.
menu_cs_modifier_health_damage_total = "(เพิ่มเลือดทั้งหมด: $health;% และดาเมจอีก, $damage;%)",--(Total: $health;% more health, $damage;% more damage.)
menu_cs_modifier_dozers = "Bulldozers สองรูปแบบถูกอนุญาตให้เข้าแผนที่แล้ว",--Two additional Bulldozers are allowed into the level.
menu_cs_modifier_pagers = "การตอบเพจเจอร์ได้ลดลง $count; ครั้งสำหรับการปล้น",--$count; less pager(s) can be answered per heist.
menu_cs_modifier_civs = "การเตือนภัยจะดังทันทีหากผู้เล่นฆ่าตัวประกัน $count; ตัว",--The alarm will be sounded if more than $count; civilians are killed.
menu_cs_modifier_heavy_sniper = "สำหรับหน่วย Heavy SWAT จะถูกแทนที่ด้วยหน่วย ZEAL Heavy SWAT Marksman",--For every Heavy SWAT that spawns, there is a chance that it will be replaced by a ZEAL Heavy SWAT Marksman.
menu_cs_modifier_cloaker_arrest = "Cloakers จะใส่กุญแจเมื่อผู้เล่นแทนการล้มผู้เล่นลง",--Cloakers executing a successful charge now cuffs the player instead of downing them.
menu_cs_modifier_enemy_health = "เลือดศัตรูจะเพิ่มขึ้น $health;%",--Enemies have an additional $health;% more health.
menu_cs_modifier_heavies = "หน่วย FBI SWATS ทุกตัวจะถูกแทนที่ด้วย HEAVY SWATS",--All FBI Swats will be replaced with Heavy Swats.
menu_cs_modifier_total_generic_value = "(รวมทั้งหมด: $value;.)",--(Total: $value;.)
