victory_cash_postponed = "เกิดความผิดพลาดระหว่างหลบหนีคุณต้องหลบหนีให้เสร็จสิ้น",--No money awarded. You need to escape first.
victory_cash_postponed_bonus = "คุณต้องทำงานจ้างให้เสร็จสิ้น",--No money awarded. You need to complete bonus contract first.
victory_stage_cash_summary_name_job = "คุณได้รับเงิน $stage_cash; on your contract day rate and an additional $job_cash; for completing the contract.",--You earned $stage_cash; on your contract day rate and an additional $job_cash; for completing the contract.
victory_stage_cash_summary_name = "คุณได้รับเงิน $stage_cash; ในระหว่างวันทำภารกิจ",--You earned $stage_cash; on your contract day rate.
victory_stage_cash_summary_name_bags = "You also made it out with $bag_amount; bag(s) with a total value of $bag_cash;.",--You also made it out with $bag_amount; bag(s) with a total value of $bag_cash;.
victory_stage_cash_summary_name_vehicles = "You also made it out with $vehicle_amount; vehicle(s) with a total value of $vehicle_cash;.",--You also made it out with $vehicle_amount; vehicle(s) with a total value of $vehicle_cash;.
victory_stage_cash_summary_name_crew = "$winners; members of the crew made it out, earning each of you an additional $crew_cash;.",--$winners; members of the crew made it out, earning each of you an additional $crew_cash;.
victory_stage_cash_summary_name_loose = "You stole an additional $loose_cash; in loose items and cash.",--You stole an additional $loose_cash; in loose items and cash.
victory_stage_cash_summary_name_civ_kill = "However, you had to pay $civ_killed_cash; in cleaner costs for killing innocent civilians.",--However, you had to pay $civ_killed_cash; in cleaner costs for killing innocent civilians.
victory_stage_cash_summary_name_assets = "คุณใช้ค่าจ่าบสำหรับอุปกรณืช่วยเหลือทั้งหมด $asset_cash;",--You spent $asset_cash; on assets.
victory_stage_cash_summary_name_offshore = "โอนเงินสู่เงินนอกระบบทั้งหมด $offshore;: $cash;",--Sent to $offshore;: $cash;.
victory_stage_cash_summary_name_spending = "ได้รับเงินสดทั้งหมด: $cash;.",--Change in available spending cash: $cash;.
victory_stage_cash_summary_name_total = "Today's total earnings: $total_cash;.",--Today's total earnings: $total_cash;.
failed_summary_name = "คุณถูกจับ !",--You failed. No money will be paid out, all assets have been locked, and any valuables you held have been confiscated.
victory_best_killer_name = "",--$PLAYER_NAME; ($SCORE;)
victory_best_special_name = "",--$PLAYER_NAME; ($SCORE;)
victory_best_accuracy_name = "",--$PLAYER_NAME; ($SCORE;%)
victory_most_downs_name = "",--$PLAYER_NAME; ($SCORE;)
victory_best_accuracy = "ผู้เล่นที่ยิงแม่นยำที่สุด:",--BEST ACCURACY:
victory_best_killer = "ผู้เล่นที่ฆ่าได้เยอะที่สุด:",--HIGHEST BODY COUNT:
victory_best_special = "ผู้เล่นที่ฆ่าตัวพิเศษเยอะที่สุด:",--HIGHEST SPECIALS BODY COUNT:
victory_civilians_killed_penalty = "ฆ่าประชาชน:",--CIVILIANS KILLED:
victory_completed_objectives = "เป้าหมายที่สุดเร็จ:",--COMPLETED OBJECTIVES:
victory_completed_objectives_bonus = "เป้าหมายที่สุดเร็จ:",--COMPLETED OBJECTIVES:
victory_completion_bonus_title = "เป้าหมายที่สุดเร็จ:",--COMPLETION CASH BONUS:
victory_criminals_finished = "จำนวนเพื่อนร่วมทีมที่อยู่รอด:",--SURVIVING CREW:
victory_favourite_weapon = "ปืนที่ชอบใช้:",--FAVORITE WEAPON:
victory_group_hit_accuracy = "ความแม่นยำของทีม:",--CREW HIT ACCURACY:
victory_group_stats = "สถานะของทีม",--CREW STATISTICS:
victory_group_total_downed = "เพื่อนร่วมทีมล้ม:",--CREW DOWNED:
victory_group_total_head_shots = "จำนวนที่เพื่อนร่วมทีมยิงหัว:",--CREW HEAD SHOTS:
victory_group_total_kills = "จำนวนที่เพื่อนร่วมทีมฆ่า:",--CREW BODY COUNT:
victory_group_total_specials_kills = "จำนวนที่เพื่อนร่วมทีมฆ่าตัวพิเศษ:",--CREW SPECIALS BODY COUNT:
victory_hit_accuracy = "ความแม่นยำ:",--HIT ACCURACY:
victory_last_completed_challenge = "LAST COMPLETED CHALLENGE:",--LAST COMPLETED CHALLENGE:
victory_money = "จำนวนเงิน:",--MONEY:
victory_most_downs = "ล้มเยอะที่สุด:",--MOST DOWNED:
victory_personal_stats = "",--PERSONAL STATISTICS:
victory_stage_cash_summary = "",--Today's cash summary:
victory_stage_cash_summary_name_bags_day = "",--You also made it out with $bonus_bags; bag(s).
victory_time_played = "จำนวนเวลาเล่น:",--TIME PLAYED:
victory_total_completion_bonus = "เงินทั้งหมด:",--TOTAL CASH:
victory_total_downed = "จำนวนที่ล้ม:",--DOWNED:
victory_total_head_shots = "จำนวนที่ยิงหัว:",--HEAD SHOTS:
victory_total_kills = "จำนวนที่ฆ่า:",--BODY COUNT:
victory_total_specials_kills = "จำนวนที่ฆ่าตัวพิเศษ:",--SPECIALS BODY COUNT:
victory_xp_postfix = "",--K
menu_es_calculating_experience = "กำลังนับค่าประสบการณ์...",--Calculating experience...
menu_success = "สำเร็จ",--Success
menu_failed = "ล้มเหลว",--Failed
debug_undecided = "Undecided",--Undecided
menu_es_summary = "ผลสรุป",--Summary
menu_es_stats_crew = "ค่าสถานะของทีม",--Crew stats
menu_es_stats_personal = "ค่าสถานะส่วนบุคคล",--Personal stats
menu_es_stats_gage_assignment = "แพคเกจ",--Packages
menu_cash_income = "เงินเข้า",--Income
menu_cash_job = "จำนวนค่าจ้าง: $money;",--Contract pay: $money;
menu_es_alive_players_bonus = "โบนัสผู้เล่นที่เหลือรอด",--Crew alive bonus
hud_instant_cash = "เงินสด",--Instant cash
menu_risk = "ความยาก:",--Risk:
cash_sign = "",--$
menu_es_level_progress = "ความคืบหน้าของเลเวล",--Level progress
menu_es_cash_job = "จำนวนเงินที่งานจ้างจ่าย",--Contract pay
menu_cash_bonus_bags = "เงินที่ได้จากกระเป๋า",--Bag Loot Items
menu_cash_balance = "สรุปจำนวนเงิน",--Balance
menu_cash_spending = "เงินที่สามารถซื้อของได้",--spending cash
menu_es_mission_xp_bonus = "ค่าประสบการ์ณจากงานจ้าง:",--Contract experience:
menu_es_skill_bonus = "ค่าประสบการ์ณจากทักษะ",--Skill bonus
menu_es_ghost_bonus = "ค่าประสบการ์ณจากการย่องเงียบ",--Stealth bonus 
menu_es_ghost_bonus_job = "คุณได้รับโบนัส ##stealth bonus##:$NL;+$bonus;% ค่าประสาการ์ณสำหรับงานจ้างต่อไป",--You have earned a ##stealth bonus##:$NL;+$bonus;% XP for your next contract.
menu_es_xp_gained = "ค่าประสาการ์ณที่ได้รับ:",--Exp gained:
menu_es_current_xp = "ค่าประสาการ์ณในปัจจุบัน:",--Current exp:
menu_es_next_level = "คุณจะอัพเมื่อคุณได้ค่าประสบการ์ณ:",--Next level in:
menu_es_skill_points_gained = "ได้รับทักษะพ้อยท์:",--Skill points gained:
menu_es_skill_points_info = "ไปที่หน้า [$SKILL_MENU;] เพื่อดูจำนวนพ้อยท์ใหม่!",--Visit [$SKILL_MENU;] menu to spend your new earned points!
menu_es_risk_bonus = "โบนัสจากความยาก",--Risk bonus
menu_es_infamy_bonus = "โบนัสจากการเลื่อนขั้น",--Infamy bonus
menu_es_alive_players_bonus = "โบนัสจากทีมที่เหลือรอด",--Crew alive bonus
menu_es_gage_assignment_bonus = "โบนัสจากการเก็บของแต่งปืน",--Gage Bonus
menu_es_gage_assignment_package = "คุณได้เจออุปกรณ์ปรับแต่งปืนบางส่วน",--You found some Gage Courier packages!
menu_es_challenge_completed = "คุณได้ทำงานพิเศษสำเร็จแล้ว ! คุณสามารถรับรางวัลได้ที่ Crime.net",--Side Job completed! Go to Crime.net to claim your rewards
menu_es_gage_assignment_package_complete = "คุณได้สะสมอุปกรณ์แต่งปืนบางชิ้นครบเรียบร้อยแล้ว",--You have completed a Gage Mod Courier assignment! The rewards have been added to your inventory.


