hud_assault_assault = "อยู่ระหว่างการเข้าจับกุม",--Police assault in progress
hud_assault_point_no_return = "เวลาในการหลบหนี",--Point of no return
hud_assault_vip = "กำจัดกัปตันเพื่อหยุดการเข้าจับกุม",--Defeat Captain to end assault
hud_equipment_boards = "ไม้แปรรูป",--Boards
hud_equipment_chainsaw = "เลื่อย",--Chainsaw
hud_equipment_evidence = "หลักฐาน",--EVIDENCE
hud_equipment_files = "ไฟล์",--FILES
hud_equipment_harddrive = "ฮาร์ดไดรฟ์",--HARD DRIVE
hud_equipment_lance = "เครื่องเจาะ",--Thermal drill
hud_equipment_lance_part = "เครื่องเจาะ",--The Beast drill part
hud_equipment_manifest = "ข้อมูลภายใน",--Manifest
hud_equipment_mus_glass_cutter = "เครื่องตัดกระจก",--Glass Cutter
hud_equipment_pickup_c4 = "ซีโฟร์",--C4
hud_equipment_saw_blade = "เลื่อย",--Saw blade
hud_equipment_take_bridge = "แผ่นโลหะ",--METAL SHEET
hud_equipment_take_ticket = "ตั๋ว",--TICKET
hud_equipment_thermite = "เธอไมท",--Thermite
hud_equipment_thermite_paste = "เธอไมท",--Thermite paste
hud_int_equipment_acid = "เอซิส",--Muriatic acid
hud_int_equipment_hydrogen_chloride = "ไฮโดรเจน",--Hydrogen chloride
hud_int_equipment_caustic_soda = "โซดา",--Caustic soda
hud_int_equipment_barcode_brickell = "จอร์จทาวน์",--Barcode: Georgetown
hud_int_equipment_barcode_downtown = "ดาวทาวน์วอซิงตัน",--Barcode: Downtown Washington
hud_int_equipment_barcode_edgewater = "เวสต์เอน",--Barcode: West End
hud_int_equipment_barcode_isles_beach = "ฟ็อกกี้บอททอม",--Barcode: Foggy Bottom
hud_int_equipment_barcode_opa_locka = "ซอว์",--Barcode: Shaw
hud_int_equipment_c_keys = "คีย์การ์ด",--Car Keys
hud_int_equipment_pickup_keycard = "คีย์การ์ด",--Keycard
hud_int_equipment_pickup_keychain = "กุญแจผี",--Keychain
mission_objective_updated = "เป้าหมายใหม่ :",--OBJECTIVE UPDATED: 
mission_objective_activated = "เป้าหมาย :",--OBJECTIVE ACTIVATED: 
mission_objective_completed = "บรรลุเป้าหมาย :",--OBJECTIVE COMPLETED: 
hud_objective_reminder = "เป้าหมายที่เหลือ",--Objective reminder:
present_obtained_mission_equipment_title = "อุปกรณ์ใชในภารกิจ:",--OBTAINED MISSION EQUIPMENT: 
message_obtained_equipment = "อุปกรณ์:",--OBTAINED MISSION EQUIPMENT: 
hud_detected = "ถูกจับได้",--Detected
hud_suspicion_detected = "ถูกจับได้",--Detected
hud_carrying = "กำลังแบก:",--Carrying:
hud_instruct_throw_bag = "กด $BTN_USE_ITEM; เพื่อโยน",--$BTN_USE_ITEM; to throw
hud_custody_in = "ติดคุก",--Custody in
hud_uncuffed_in = "ปลดกุญแจมือ",--Uncuffed in
hud_gage_assignment_progress = "$peer_name; ได้หยิบแพคเกจของ $assignment; และเหลือแพคแกจอีก: $remaining; อัน",--$peer_name; picked up $assignment;. Remaining packages: $remaining;.
hud_loot_secured_title = "สิ่งที่ปล้นได้",--Loot secured
hint_damage_pad = "คุณกำลังเจ็บอยู่ - รีบเข้าที่กำบัง!",--You are hurt - take cover!
hint_cant_stand_up = "คุณจะลุกขึ้นยืนตรงนี้ไม่ได้",--You can't stand up here.
hint_been_tasered = "คุณถูกช็อตอยู่ !!",--A Taser is stunning you!
hint_you_helpedup = "คุณได้ช่วย $TEAMMATE; ลุกขึ้น!",--You helped $TEAMMATE; up!
hud_hint_met_criminal = "สัญญานเตือนภัยทำงานเนื่องจาก : เครื่องตรวจจับตรวจเจออาวุธ",--Alarm tripped: Metal detector was activated
hud_hint_mot_criminal = "สัญญานเตือนภัยทำงานเนื่องจาก : เลเซอร์ตรวจจับความเคลื่อนไหวได้",--Alarm tripped: Criminal triggered a motion sensor
hud_hint_alarm_glass = "สัญญานเตือนภัยทำงานเนื่องจาก : กระจกนิรภัยแตก",--Alarm tripped: Alarmed glass broke
hud_hint_blame_blackmailer = "สัญญานเตือนภัยทำงานเนื่องจาก : มีคนโทรแจ้งตำรวจ",--Alarm tripped: Blackmailer called the police
hud_hint_blame_gensec = "สัญญานเตือนภัยทำงานเนื่องจาก : หน่วย GenSec ตรวจพบสิ่งผิดปกติ",--Alarm tripped: GenSec called the police
hud_hint_blame_missing = "สัญญานเตือนภัยทำงานเนื่องจาก : มีคนโทรแจ้งตำรวจเนื่องจากเห็นการก่ออาชญากรรม",--Someone saw suspicious activity and called the police
hud_hint_blame_police_alerted = "สัญญานเตือนภัยทำงานเนื่องจาก : ตำรวจพบสิ่งผิดปกติ",--The police have been alerted
hud_hint_blame_csgo_gunfire = "สัญญานเตือนภัยทำงานเนื่องจาก : เพื่อนบ้านพบเห็นการก่ออาชญากรรม",--The neighbors called the police
hud_hint_alarm_civ = "สัญญานเตือนภัยทำงานเนื่องจาก : ประชาชนกดปุ่มนิรภัย",--Alarm tripped: Civilian pressed the alarm button
hud_hint_alarm_cop = "สัญญานเตือนภัยทำงานเนื่องจาก : หน่วยรักษาความปลอดภัยตรวจพบกล้องชำรุด",--Alarm tripped: Security operator detected a broken camera
hud_hint_alert_explosion = "สัญญานเตือนภัยทำงานเนื่องจาก : เกิดเสียงระเบิดดังขึ้น",--Alarm tripped: An explosion was heard
hud_hint_alarm_pager_bluff_failed = "สัญญานเตือนภัยทำงานเนื่องจาก : การตอบเพจเจอร์ไม่สำเร็จผลเนื่องจากตรวจถูกจับพิธุทได้",--Alarm tripped: Pager operator wasn't convinced by the answer
hud_hint_alarm_pager_not_answered = "สัญญานเตือนภัยทำงานเนื่องจาก : เพจเจอร์ไม่ได้รับการตอบรับ",--Alarm tripped: Pager operator didn't receive an answer
hud_hint_alarm_pager_hang_up = "สัญญานเตือนภัยทำงานเนื่องจาก : ตอบเพจเจอร์ไม่สำเร็จ",--Alarm tripped: Criminal disconnected from the call
hud_hint_cam_criminal = "สัญญานเตือนภัยทำงานเนื่องจาก : กล้องวงจรปิดตรวจเจออาชญากร",--Alarm tripped: Camera detected a criminal
hud_hint_gunfire = "สัญญานเตือนภัยทำงานเนื่องจาก : ตรวจพบการใช้งานอาวุธ",--Alarm tripped: Camera detected gunfire
hud_hint_cam_dead_body = "สัญญานเตือนภัยทำงานเนื่องจาก : กล้องจงจรปิดตรวจพบศพ",--Alarm tripped: Camera detected a dead body
hud_hint_body_bag = "สัญญานเตือนภัยทำงานเนื่องจาก : กล้องจงจรปิดตรวจพบกระเป๋าต้องสงสัย",--Alarm tripped: Camera detected a body bag
hud_hint_cam_hostage = "สัญญานเตือนภัยทำงานเนื่องจาก : กล้องจงจรปิดตรวจพบประชาชนที่ถูกจับกุม",--Alarm tripped: Camera detected a hostage
hud_hint_cam_drill = "สัญญานเตือนภัยทำงานเนื่องจาก : กล้องจงจรปิดตรวจพบสว่านกำลังทำงาน",--Alarm tripped: Camera detected a drill
hud_hint_cam_saw = "สัญญานเตือนภัยทำงานเนื่องจาก : กล้องจงจรปิดตรวจพบเลื่อยกำลังทำงาน",--Alarm tripped: Camera detected a saw
hud_hint_cam_sentry_gun = "สัญญานเตือนภัยทำงานเนื่องจาก : กล้องจงจรปิดตรวจพบป้อมปืน",--Alarm tripped: Camera detected a sentry gun
hud_hint_cam_trip_mine = "สัญญานเตือนภัยทำงานเนื่องจาก : กล้องจงจรปิดตรวจพบระเบิด",--Alarm tripped: Camera detected a trip mine
hud_hint_cam_ecm_jammer = "สัญญานเตือนภัยทำงานเนื่องจาก : กล้องจงจรปิดตรวจพบเครื่องก่อกวนสัญญาน",--Alarm tripped: Camera detected ECM feedback
hud_hint_cam_c4 = "สัญญานเตือนภัยทำงานเนื่องจาก : กล้องจงจรปิดตรวจพบการระเบิด",--Alarm tripped: Camera detected an explosion
hud_hint_cam_computer = "สัญญานเตือนภัยทำงานเนื่องจาก : กล้องจงจรปิดตรวจพบคอมพิวเตอร์ที่กำลังถูกแฮค",--Alarm tripped: Camera detected a hacked computer
hud_hint_cam_broken_cam = "สัญญานเตือนภัยทำงานเนื่องจาก : กล้องจงจรปิดตรวจพบกล้องที่ชำรุด",--Alarm tripped: Camera detected a broken camera
hud_hint_cam_vault = "สัญญานเตือนภัยทำงานเนื่องจาก : กล้องจงจรปิดตรวจพบว่าตู้นิรภัยเปิดอยู่",--Alarm tripped: Camera detected an open vault
hud_hint_cam_fire = "สัญญานเตือนภัยทำงานเนื่องจาก : กล้องจงจรปิดตรวจพบไฟไหม้",--Alarm tripped: Camera detected a fire
hud_hint_cam_voting = "สัญญานเตือนภัยทำงานเนื่องจาก : กล้องจงจรปิดตรวจพบเครื่องลงคะแนนเสียหาย",--Alarm tripped: Camera detected broken voting machines
hud_hint_cam_glass = "สัญญานเตือนภัยทำงานเนื่องจาก : กล้องจงจรปิดตรวจพบกระจกแตก",--Alarm tripped: Camera detected a broken window
hud_hint_cam_breaking_entering = "สัญญานเตือนภัยทำงานเนื่องจาก : กล้องจงจรปิดตรวจพบการบุกรุก",--Alarm tripped: Camera detected breaking and entering
hud_hint_cam_crate_open = "",--ERROR: hud_hint_cam_crate_open
hud_hint_cam_distress = "สัญญานเตือนภัยทำงานเนื่องจาก : กล้องจงจรปิดตรวจพบการก่ออาชญากรรม",--Alarm tripped: Camera detected suspicious activity
hud_hint_civ_criminal = "สัญญานเตือนภัยทำงานเนื่องจาก : ประชาชนเห็นการก่ออาชญากรรมและโทรแจ้งตำรวจ",--Alarm tripped: Civilian saw a criminal and called the police
hud_hint_civ_gunfire = "สัญญานเตือนภัยทำงานเนื่องจาก : ประชาชนได้ยินเสียงของปืนและโทรแจ้งงตำรวจ",--Alarm tripped: Civilian heard gunfire and called the police
hud_hint_civ_dead_body = "สัญญานเตือนภัยทำงานเนื่องจาก : ประชาชนพบเห็นศพ",--Alarm tripped: Civilian saw a dead body and called the police
hud_hint_civ_body_bag = "สัญญานเตือนภัยทำงานเนื่องจาก : ประชาชนพบเห็นกระเป๋าต้องสงสัย",--Alarm tripped: Civilian saw a body bag and called the police
hud_hint_civ_hostage = "สัญญานเตือนภัยทำงานเนื่องจาก : ประชาชนพบเห็นประชาชนที่ถูกจับกุมและโทรแจ้งตำรวจ",--Alarm tripped: Civilian saw a hostage and called the police
hud_hint_civ_drill = "สัญญานเตือนภัยทำงานเนื่องจาก : ประชาชนพบเห็นสว่านที่กำลังทำงานและโทรแจ้งตำรวจ",--Alarm tripped: Civilian encountered a drill and called the police
hud_hint_civ_saw = "สัญญานเตือนภัยทำงานเนื่องจาก : ประชาชนพบเห็นเลื่อยที่กำลังทำงานและโทรแจ้งตำรวจ",--Alarm tripped: Civilian encountered a saw and called the police
hud_hint_civ_sentry_gun = "สัญญานเตือนภัยทำงานเนื่องจาก :  ประชาชนพบเห็นป้อมปืนและโทรแจ้งตำรวจ",--Alarm tripped: Civilian encountered a sentry gun and called the police
hud_hint_civ_trip_mine = "สัญญานเตือนภัยทำงานเนื่องจาก : ประชาชนพบเห็นระเบิดและโทรแจ้งตำรวจ",--Alarm tripped: Civilian encountered a trip mine and called the police
hud_hint_civ_ecm_jammer = "สัญญานเตือนภัยทำงานเนื่องจาก : ประชาชนได้รับผลของเครื่องก่อกวนสัญญานและโทรแจ้งตำรวจ",--Alarm tripped: Civilian was affected by ECM feedback and called the police
hud_hint_civ_c4 = "สัญญานเตือนภัยทำงานเนื่องจาก : ประชาชนได้ยินเสียงระเบิดและโทรแจ้งตำรวจ",--Alarm tripped: Civilian heard an explosion and called the police
hud_hint_civ_computer = "สัญญานเตือนภัยทำงานเนื่องจาก : ประชาชนพบเห็นคอมพพิวเจอร์กำลังถูกแฮคและโทนแจ้งตำรวจ",--Alarm tripped: Civilian saw a hacked computer and called the police
hud_hint_civ_broken_cam = "สัญญานเตือนภัยทำงานเนื่องจาก : ประชาชนพบเห็นกล้องที่ชำรุดและโทรแจ้งตำรวจ",--Alarm tripped: Civilian saw a broken camera and called the police
hud_hint_civ_vault = "สัญญานเตือนภัยทำงานเนื่องจาก : ประชาชนพบเห็นตู้นิรภัยที่กำลังเปิดและโทรแจ้งตำรวจ",--Alarm tripped: Civilian saw an open vault and called the police
hud_hint_civ_fire = "สัญญานเตือนภัยทำงานเนื่องจาก : ประชาชนพบเห็นไฟไหม้และโทรแจ้งตำรวจ",--Alarm tripped: Civilian saw a fire and called the police
hud_hint_civ_voting = "สัญญานเตือนภัยทำงานเนื่องจาก : ประชาชนพบเห็นเครื่องลงคะแนนเสียหายและโทรแจ้งตำรวจ",--Alarm tripped: Civilian saw a broken voting machine and called the police
hud_hint_civ_glass = "สัญญานเตือนภัยทำงานเนื่องจาก : ประชาชนได้ยินเสียงกระจกแตกและโทรแจ้งตำรวจ",--Alarm tripped: Civilian heard a window break and called the police
hud_hint_civ_breaking_entering = "สัญญานเตือนภัยทำงานเนื่องจาก : ประชาชนพบเห็นการบุกรุกและโทรแจ้งตำรวจ",--Alarm tripped: Civilian saw someone breaking and entering and called the police
hud_hint_civ_distress = "สัญญานเตือนภัยทำงานเนื่องจาก : ประชาชนพบเห็นสิ่งผิดปกติและโทรแจ้งตำรวจ",--Alarm tripped: Civilian saw suspicious activity and called the police
hud_hint_civ_weapons_hot = "สัญญานเตือนภัยทำงานเนื่องจาก : ประชาชนพบเห็บอาววุธและโทรแจ้งตำรวจ",--Alarm tripped: Civilian saw a weapon and called the police
hud_hint_cop_criminal = "สัญญานเตือนภัยทำงานเนื่องจาก : หน่วยรักษาความปลอดภัยพบเห็นการก่ออาชญากรรม",--Alarm tripped: Police detected a criminal
hud_hint_cop_gunfire = "สัญญานเตือนภัยทำงานเนื่องจาก : หน่วยรักษาความปลอดภัยได้ยินเสียงปืน",--Alarm tripped: Police detected gunfire
hud_hint_cop_dead_body = "สัญญานเตือนภัยทำงานเนื่องจาก : หน่วยรักษาความปลอดภัยตรวจพบศพ",--Alarm tripped: Police detected a dead body
hud_hint_cop_body_bag = "สัญญานเตือนภัยทำงานเนื่องจาก : หน่วยรักษาความปลอดภัยตรวจพบกระเป๋าต้องสังสัย",--Alarm tripped: Police detected a body bag
hud_hint_cop_hostage = "สัญญานเตือนภัยทำงานเนื่องจาก : หน่วยรักษาความปลอดภัยตรวจพบประชาชนที่ถูกจับกุม",--Alarm tripped: Police detected a hostage
hud_hint_cop_drill = "สัญญานเตือนภัยทำงานเนื่องจาก : หน่วยรักษาความปลอดภัยตรวจพบสว่านกำลังทำงาน",--Alarm tripped: Police detected a drill
hud_hint_cop_saw = "สัญญานเตือนภัยทำงานเนื่องจาก : หน่วยรักษาความปลอดภัยตรวจพบเลื่อยกำลังทำงาน",--Alarm tripped: Police detected a saw
hud_hint_cop_sentry_gun = "สัญญานเตือนภัยทำงานเนื่องจาก : หน่วยรักษาความปลอดภัยตรวจพบป้อมปืน",--Alarm tripped: Police detected a sentry gun
hud_hint_cop_trip_mine = "สัญญานเตือนภัยทำงานเนื่องจาก : หน่วยรักษาความปลอดภัยระเบิด",--Alarm tripped: Police detected a trip mine
hud_hint_cop_ecm_jammer = "สัญญานเตือนภัยทำงานเนื่องจาก : หน่วยรักษาความปลอดภัยตรวจพบเครื่องก่อกวนสัญญาน",--Alarm tripped: Police was affected by ECM feedback
hud_hint_cop_c4 = "สัญญานเตือนภัยทำงานเนื่องจาก : หน่วยรักษาความปลอดภัยได้ยินเสียงระเบิด",--Alarm tripped: Police detected an explosion
hud_hint_cop_computer = "สัญญานเตือนภัยทำงานเนื่องจาก : หน่วยรักษาความปลอดภัยตรวจพบคอมพิวเตอร์ที่กำลังถูกแฮค",--Alarm tripped: Police detected a hacked computer
hud_hint_cop_broken_cam = "สัญญานเตือนภัยทำงานเนื่องจาก : หน่วยรักษาความปลอดภัยตรวจพบกล้องที่ชำรุด",--Alarm tripped: Police detected a broken camera
hud_hint_cop_vault = "สัญญานเตือนภัยทำงานเนื่องจาก : หน่วยรักษาความปลอดภัยตรวจพบตู้นิรภัยเปิดอยู่",--Alarm tripped: Police detected an open vault
hud_hint_cop_fire = "สัญญานเตือนภัยทำงานเนื่องจาก : หน่วยรักษาความปลอดภัยตรวจพบไฟไหม้อยู่",--Alarm tripped: Police detected a fire
hud_hint_cop_voting = "สัญญานเตือนภัยทำงานเนื่องจาก : หน่วยรักษาความปลอดภัยตรวจพบเครื่องลงคะแนนเสียหาย",--Alarm tripped: Police detected broken voting machines
hud_hint_cop_glass = "สัญญานเตือนภัยทำงานเนื่องจาก : หน่วยรักษาความปลอดภัยตรวจพบกระจกแตก",--Alarm tripped: Police detected a broken window
hud_hint_cop_breaking_entering = "สัญญานเตือนภัยทำงานเนื่องจาก : หน่วยรักษาความปลอดภัยตรวจพบการบุกรุก",--Alarm tripped: Police saw someone breaking and entering
hud_hint_cop_crate_open = "",--ERROR: hud_hint_cop_crate_open
hud_hint_cop_distress = "สัญญานเตือนภัยทำงานเนื่องจาก : หน่วยรักษาความปลอดภัยตรวจพบการก่ออาชญากรรม",--Alarm tripped: Police detected suspicious activity
hud_hint_cop_weapons_hot = "สัญญานเตือนภัยทำงานเนื่องจาก : หน่วยรักษาความปลอดภัยพบเห็นอาวุธ",--Alarm tripped: Police detected a weapon
hud_hint_clean_block_interact = "คุณอยู่ในโหมดประชาชนอยู่",--No suspicious actions allowed in civilian mode
menu_spectator_being_traded_hesitant = "เบนกำลังเจรจา !",--Bain is negotiating!
hint_teammate_helpedup = "$HELPER; ได้ช่วย $TEAMMATE; ลุกขึ้น",--$TEAMMATE; has been helped up by $HELPER;!
hint_teammate_revived = "$HELPER; ได้ช่วย $TEAMMATE; ออกมาจากคุกแล้ว",--$TEAMMATE; has been released from custody thanks to $HELPER;!
hint_trade_offered = "ตำรวจได้ยอมรับการแลกเปลี่ยนตัวประกันแล้ว",--Set this hostage free to release your teammate from custody!
hint_you_were_helpedup = "$HELPER; ได้ช่วยคุณลุกขึ้น",--You have been helped up by $HELPER;!
hud_civilians_killed = "ฆ่าประชาชนไปแล้ว: $AMOUNT; คน",--Civilians killed: $AMOUNT;
hint_sentry_set_ap_rounds = "ป้อมปืนถูกเปิดระบบ AP Rounds",--Sentry Gun: AP Rounds Enabled
hint_sentry_normal_ammo = "ป้อมปืนถูกปิดระบบ AP Rounds",--Sentry Gun: AP Rounds Disabled
hint_sentry_not_enough_ammo_to_place = "ไม่มีกระสุนเพียงพอที่จะวางป้อมปืน",--Not enough ammo to place sentry gun
hint_teammate_downed = "$TEAMMATE; ล้ม !",--$TEAMMATE; was downed!
menu_spectator_being_traded = "ตำรวจได้ยอมรับการแลกเปลี่ยนตัวประกันแล้ว",--You can now be traded!
hud_hint_mask_off_block_interact = "คุณต้องใส่หน้ากากก่อน",--No suspicious actions allowed in casing mode.
hud_vehicle_no_enter_carry = "คุณไม่สามารถขึ้นยานพาหนะโดยถือกระเป๋าได้!",--Can't enter the vehicle while carrying loot
hint_skill_messiah_get_up = "กดปุ่มกระโดดเพื่อลุกขึ้น !!",--Press Jump to get up!!
hud_days_title = "ภารกิจวันที่ $DAY; จากทั้งหมด $DAYS;",--Day $DAY; of $DAYS;
hud_day_payout = "จำนวนเงิน: $MONEY;",--PAYDAY: $MONEY;
hud_objective = "สิ่งที่ต้องทำ",--OBJECTIVE
hud_secured_loot = "",--
