menu_music_volume = "ค่าเสียงเพลง",--MUSIC VOLUME
menu_music_volume_help = "ความดังเสียงเพลงประกอบเกม",--Adjust the music volume.
menu_sfx_volume = "ค่าเสียงประกอบ",--SFX VOLUME
menu_sfx_volume_help = "ค่าเสียงประกอบเช่นยิงกระสุนปืน,เสียงแกะสลักของระเบิด,เสียงประตู",--Adjust the sound effects volume.
menu_voice_volume = "ค่าเสียงไมค์",--VOICE CHAT VOLUME
menu_voice_volume_help = "ค่าเสียงไมค์ของผู้เล่น",--Adjust the voice chat volume.
menu_voicechat_toggle = "ใช้งานระบบพูดคุยไมค์",--USE VOICE CHAT
menu_voicechat_toggle_help = "ใช้งานระบบพูดคุยไมค์ในทีม",--TURN VOICE CHAT ON OR OFF.
menu_push_to_talk_toggle = "ใช้งานระบบกดเพื่อพูด",--USE PUSH TO TALK
menu_push_to_talk_toggle_help = "ใช้งานระบบกดเพื่อพูด",--TURN PUSH TO TALK ON OR OFF.
menu_jukebox_heist_playlist = "กำหนดเพลย์ลิสต์ขณะปฏิบัติการ",--Custom heist Playlist
menu_jukebox_heist_playlist_help = "กำหนดเพลย์ลิสต์ขณะปฏิบัติการ",--Create a custom playlist with your favorite tracks.
menu_jukebox_heist_tracks = "กำหนดแทร็กขณะปฏิบัติการ",--Custom heist tracks
menu_jukebox_heist_tracks_help = "กำหนดแทร็กเพลงขณะปฎิบัติการ",--Choose a specific track for each heist.
menu_jukebox_menu_playlist = "กำหนดเพลย์ลิสต์ขณะอยู่หน้าเมนู",--Custom menu playlist
menu_jukebox_menu_playlist_help = "กำหนดเพลย์ลิสต์ขณะอยู่หน้าเมนูของเกม",--Create a custom playlist with your favorite menu tracks.
menu_jukebox_menu_tracks = "กำหนดแทร็กขณะอยู่หน้าเมนู",--Custom menu tracks
menu_jukebox_menu_tracks_help = "กำหนดแทร็กเพลงที่ควรเล่นเมื่ออยู่หน้าเมนู",--Choose what track should play in each menu screen.
menu_sound_option_default = "คืนการตั้งค่าดังเดิม",--DEFAULT SOUND OPTIONS
menu_sound_option_default_help = "เรียกคืนการตั้งค่าดังเดิมในส่วนของเสียง",--Resets sound options to their default state.