menu_controls= "การบังคับ",--CONTROLS
menu_controls_help= "ปรับเปลี่ยนการตั้งค่าปุ่มของคุณ",--Change your control preferences.
menu_video= "วิดีโอ",--VIDEO
menu_video_help= "ปรับเปลี่ยนการตั้งค่าวิดีโอของคุณ",--Change your video preferences.
menu_sound= "เสียง",--SOUND
menu_sound_help= "ปรับเปลี่ยนการตั้งค่าเสียงของคุณ",--Change your sound preferences.
menu_network= "เครือข่าย",--Network
menu_network_help= "ปรับเปลี่ยนการตั้งค่าเครือข่ายของคุณ",--Adjust network settings
menu_mods= "มอด",--Mods
menu_mods_help= "ตรวจสอบสถานะมอดที่ติดตั้ง",--Check status on installed mods
menu_option_default= "เรียกคืนการตั้งค่า",--DEFAULT OPTIONS
menu_option_default_help= "เรียกคืนการตั้งค่าดังเดิมทั้งหมด",--Resets all options to their default state.
menu_clear_progress= "ลบเซฟเกมทั้งหมด",--CLEAR PROGRESS
menu_clear_progress_help= "ลบเซฟเกมออกทั้งหมดเหมือนซื้อเกมใหม่",--This will reset your cash, reputation and upgrades.
menu_mods = "ส่วนเสริม",--Mods
menu_mods_help = "ส่วนเสริมของเกมที่ผู้เล่นสร้างขั้นเอง",--Check status on installed mods
base_options_menu_lua_mods = "ปิดหรือเปิดส่วนเสริม",--Lua Mod
base_options_menu_lua_mod_options = "ตั้งค่าของส่วนเสริม",--Mod option
base_options_menu_keybinds = "ตั้งค่าปุ่มของส่วนเสริม",--Mod Keybind
menu_ban_list = "รายชื่อผู้เล่นที่ถูกแบน",--Ban List
menu_quickplay_settings = "การตั้งค่าหาห้องรวดเร็ว",--QuickPlay Settings
menu_gameplay = "ระบบการเล่น",--
menu_gameplay_help = "ปรับแต่งระบบการเล่น",--
menu_user_interface = "ลักษณะของผู้เล่น",--
menu_user_interface_help = "ปรับแต่งลักษณะของเกมตามผู้เล่น",--
menu_loading_hints = "เทคนิคการเล่น",--
menu_loading_hints_help = "แสดงเทคนิคการเล่นขณะโหลดเกม",--
menu_throwable_contour = "เส้นขอบของอาวุธขว้าง",--
menu_ammo_contour = "เส้นขอบของกระสุน",--
menu_mute_heist_vo = "ปิดเสียงของผู้ว่าจ้าง",--
menu_throwable_contour_help = "แสดงเส้นขอบของอาวุธขว้าง",--
menu_ammo_contour_help = "แสดงเส้นขอบของกระสุน",--
menu_mute_heist_vo_help = "ปิดเสียงของผู้ว่าจ้างในงานจ้างต่างๆ",--
menu_toggle_workshop = "เปิดการใช้งาน Workshop",--
menu_toggle_workshop_help = "ปิดหรือเปิดการใช้งาน Workshop",--
