menu_choose_contract = "เลือกงานจ้างใหม่",--Choose new contract
menu_edit_game_settings = "แก้ไขการตั้งค่าของห้อง",--EDIT GAME SETTINGS
menu_permission = "สถานะของห้อง",--PERMISSION
menu_permission_help = "ตั้งค่าสถานะของห้องว่าให้ใครสามารถเข้ามาได้",--Set who will be able to join this game. Public game can be joined by anyone while Friends-Only game can only be joined by your friends. Private games are invite-only.
menu_public_game = "สาธารณะ",--PUBLIC
menu_friends_only_game = "เพื่อนเท่านั้น",--FRIENDS-ONLY
menu_private_game = "ส่วนตัว",--PRIVATE
menu_reputation_permission = "เลเวลขั้นต่ำ",--REPUTATION LIMIT
menu_reputation_permission_help = "ตั้งค่าให้เลเวลที่มากกว่าหรือเท่ากับสามารถเข้าร่วมเกมได้",--Players with reputation lower than this setting will not be able to join the game. You can not set it higher than your current reputation.
menu_toggle_drop_in = "สามารถเข้าออกห้องได้",--ALLOW DROP-IN
menu_toggle_drop_in_help = "อนุญาตให้ผู้เล่นเข้าห้องระหว่างเกมได้",--Allow or disallow people to join the game in the middle of playing.
menu_toggle_ai = "เล่นกับบอท",--PLAY WITH TEAM AI
menu_toggle_ai_help = "ตั้งค่าให้มีบอทหรือไม่มีบอท",--Set whether or not you want to play with the team AI.
menu_kicking_allowed_option = "การขับไล่ผู้เล่นในเกม",--In-game kicking
menu_kicking_allowed_option_help = "ตั้งค่าให้ระบบการขับไล่ผู้เล่น",--Set how the in-game kicking system will work.
menu_toggle_auto_kick = "ขับไล่ผู้เล่นที่ใช้งานโปรแกรมช่วยเล่นโดยอัตโนมัติ",--Auto-Kick Cheaters
menu_kick_player = "ขับไล่ผู้เล่น",--KICK PLAYER
menu_mute_players = "ปิดเสียงไมค์ของผู้เล่น",--MUTE PLAYER
menu_invite_friends = "เชิญเพื่อนเข้าร่วมเกม",--INVITE FRIENDS
menu_leave_lobby = "ออกจากล็อบบี้นี้",--LEAVE THIS LOBBY
menu_start_the_game = "ลงมือปฏิบัติการ",--START THE HEIST
menu_lobby_difficulty_title = "ระดับความยาก:",--DIFFICULTY: 
cn_menu_num_stages = "$stages; วัน",--$stages; Day job
menu_challenge_xp_drop = "ค่าประสบการณ์",--Experience
menu_experience = "ค่าประสบการณ์:",--Experience:
