menu_scopes = "กล้องส่อง",--Scopes
menu_scopes_help = "ซื้อกล้องส่อง",--Buy scopes.
menu_barrels = "ลำกล้อง",--Barrels
menu_barrels_help = "ซื้อลำกล้อง",--Buy barrels.
menu_grips = "ที่จับด้ามปืน",--Grips
menu_grips_help = "ซื้อที่จับด้ามปืน",--Buy grips.
menu_character_customization = "ปรับแต่งตัวละคร",--Character Customization
menu_character_customization_help = "ปรับแต่งตัวละครของคุณ",--Customize your character
menu_armor = "เกราะ",--Armor
menu_armor_help = "ซื้อและปรับแต่งเกราะ",--Buy and customize armor.
menu_masks = "หน้ากาก",--Masks
menu_masks_help = "ซื้อและปรับแต่งหน้ากาก",--Buy and customize masks.
menu_mouse_select = "เพื่อเลือก",--to select
menu_mouse_preview = "เพื่อดู",--to preview
menu_mouse_switch = "เพื่อเปลี่ยน",--to switch
menu_mouse_search_market = "เพื่อหาในตลาดชุมชน",--To search on community market
menu_show_all = "กด $BTN_X; เพื่อแสดงทั้งหมด",--$BTN_X; to show All
menu_hide_all = "กด $BTN_X; เพื่อซ่อนทั้งหมด",--$BTN_X; to hide All
menu_button_show = "แสดง",--Show
menu_button_hide = "ซ่อน",--Hide
menu_player_column_one_title = "ตัวละคร",--Character
menu_player_column_two_title = "อาวุธ",--Weapons
menu_player_column_three_title = "อุปกรณ์และทักษะ",--Eqpt & Skills
bm_menu_weapon_mods = "ของแต่งปืน",--Weapon Mod
bm_menu_primaries = "อาวุธหลัก",--Primary
bm_menu_secondaries = "อาวุธรอง",--Secondary
bm_menu_melee_weapons = "อาวุธระยะประชิด",--Melee
bm_menu_grenades = "อาวุธขว้าง",--Throwable
bm_menu_armors = "เกราะ",--Armor
bm_menu_deployables = "อุปกรณ์",--Equipment
bm_menu_masks = "หน้ากาก",--Mask
bm_menu_characters = "ตัวละคร",--Character
menu_specialization = "ความสามารถพิเศษ",--Perk Decks
menu_st_skilltree = "ทักษะ",--Skills
menu_preferred_character = "ตัวละคร",--Character
bm_menu_level_req = "ไอเทมชิ้นนี้จะปลดล็อคในเลเวล $level;",--Locked to reputation level $level;
bm_menu_empty_weapon_slot = "ช่องว่าง",--Empty weapon slot
bm_menu_btn_buy_weapon_slot = "ปลดล็อคช่องเก็บของ",--Unlock weapon slot
bm_menu_locked_weapon_slot_desc = "ช่อวเก็บของนี้ถูกล็อกไว้อยู่! คุณต้องปลดล็อกก่อน",--This weapon slot needs to be unlocked before you can place any weapons here!
bm_menu_btn_remove_mod = "ถอนการติดตั้งส่วนเสริมของปืน",--Remove modification
bm_menu_btn_switch_reticle = "เปลี่ยนเป้าเล็งของกล้องส่อง",--Switch reticle
bm_menu_btn_craft_mod = "ปรับแต่งอาวุธ",--Craft modification
menu_akimbo = "ปืนคู่",--Akimbo
menu_assault_rifle = "ปืนไรเฟิล",--Assault Rifle
menu_wpn_special = "อาวุธพิเศษ",--Special
menu_grenade_launcher = "อาวุธยิงลูกระเบิด",--Grenade Launcher
menu_lmg = "ปืนกลหนัก",--Light Machine Gun
menu_pistol = "ปืนพก",--Pistol
menu_saw = "เลื่อย",--Saw
menu_shotgun = "ปืนลูกซอง",--Shotgun
menu_smg = "ปืนกลเบา",--Submachine Gun
menu_snp = "สไนเปอร์",--Sniper Rifle
bm_menu_ammo = "ชนิดหัวกระสุน",--Ammunition
bm_menu_barrel = "ลำกล้องปืน",--Barrel
bm_menu_barrel_ext = "ลำกล้องปืน",--Barrel Ext
bm_menu_extra = "ส่วนเสริม",--Extra
bm_menu_custom = "ปรับแต่ง",--Custom
bm_menu_foregrip = "ด้ามจับปืน",--Foregrip
bm_menu_gadget = "อุปกรณ์เสริม",--Gadget
bm_menu_grip = "ด้ามจับปืน",--Grip
bm_menu_vertical_grip = "ด้ามจับปืน",--Vertical Grip
bm_menu_sight = "กล้องส่อง",--Sight
bm_menu_stock = "พานท้าย",--Stock
bm_menu_upper_reciever = "โครงปืนส่วนบน",--Upper Receiver
bm_menu_lower_reciever = "โครงปืนส่วนล่าง",--Lower Receiver
bm_menu_slide = "สไลด์ปืน",--Slide
menu_es_heat_bonus = "บูสท์",--Boost
bm_menu_locked_weapon_slot = "ช่องอาวุธถูกล็อคอยู่",--Locked weapon slot
bm_menu_available_mods = "ของปรับแต่งที่สามารถใช้งานได้",--Available mods
-- DLC REQEUST
menu_l_global_value_akm4_pack = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ AK/CAR Mod Pack !",--This is an AK/CAR Mod Pack item!
menu_l_global_value_alienware_alpha = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ Alienware Alpha !",--This is an Alienware Alpha item!
menu_l_global_value_alienware_alpha_promo = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ Alienware Alpha !",--This is an Alienware Alpha item!
menu_l_global_value_armored_transport = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ Armored Transport !",--This is an Armored Transport item!
menu_l_global_value_bbq = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ BBQ Weapon Pack !",--This is a BBQ Weapon Pack item!
menu_l_global_value_big_bank_snp = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ Big Bank Heist !",--This is a Big Bank Heist item!
menu_l_global_value_butch_pack_free = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ Butcher Mod Pack !",--This is a Butcher Mod Pack item!
menu_l_global_value_character_pack_clover = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ Clover Character Pack !",--This is a Clover Character Pack item!
menu_l_global_value_complete_overkill_pack = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ Completely OVERKILL PACK !",--This is a Completely OVERKILL Pack item!
menu_l_global_value_character_pack_dragan = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ Dragan Character Pack !",--This is a Dragan Character Pack item!
menu_l_global_value_exceptional = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ ",--ERROR: menu_l_global_value_exceptional
menu_l_global_value_gage_pack = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ Gage Weapon Pack #01 !",--This is a Gage Weapon Pack #01 item!
menu_l_global_value_gage_pack_assault = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ Gage Assault Pack !",--This is a Gage Assault Pack item!
menu_l_global_value_gage_pack_historical = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ Gage Historical Pack !",--This is a Gage Historical Pack item!
menu_l_global_value_gage_pack_jobs = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ Gage Mod Courier !",--This is a Gage Mod Courier item!
menu_l_global_value_gage_pack_lmg = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ Gage Weapon Pack #02 !",--This is a Gage Weapon Pack #02 item!
menu_l_global_value_gage_pack_shotgun = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ Gage Shotgun Pack !",--This is a Gage Shotgun Pack item!
menu_l_global_value_gage_pack_snp = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ Gage Sniper Pack !",--This is a Gage Sniper Pack item!
menu_l_global_value_goty_dlc_bundle_2014 = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ GOTY Edition !",--This is a GOTY Edition item!
menu_l_global_value_goty_heist_bundle_2014 = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ Heist Bundle !",--This is a Heist Bundle item!
menu_l_global_value_goty_weapon_bundle_2014 = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ Weapon Bundle !",--This is a Weapon Bundle item!
menu_l_global_value_halloween = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ Halloween !",--This is a Halloween item!
menu_l_global_value_hl_miami = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ Hotline Miami DLC !",--This is a Hotline Miami DLC item!
menu_l_global_value_hope_diamond = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ Diamond Heist !",--This is a Diamond Heist item!
menu_l_global_value_hlm2 = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ Hotline Miami 2 !",--This is a Hotline Miami 2 item!
menu_l_global_value_hlm2_deluxe = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ Hotline Miami 2 Deluxe !",--This is a Hotline Miami 2 Deluxe item!
menu_l_global_value_humble_pack2 = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ Humble Mask Pack 2 !",--This is a Humble Mask Pack 2 item!
menu_l_global_value_infamous = "อุปกรณ์นี้เป็นไอเทมของ Infamous !",--This is an infamous item!
menu_l_global_value_legendary = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ Legendary !",--This is a Legendary item!
menu_l_global_value_pd2_clan = "ไอเทมนี้เป็นไอเทมจากชุมชนหรือ Community !",--This is a community item!
menu_l_global_value_poetry_soundtrack = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ Poetry Jam !",--This is a Poetry Jam item!
menu_l_global_value_preorder = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ Loot Bag !",--This is a Loot Bag item!
menu_l_global_value_overkill_pack = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ OVERKILL Pack !",--This is a OVERKILL Pack item!
menu_l_global_value_sweettooth = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ Special !",--This is a Special item!
menu_l_global_value_speedrunners = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ Speedrunners !",--This is a Speedrunners Item!
menu_l_global_value_the_bomb = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ The Bomb Heists !",--This is a The Bomb Heists item!
menu_l_global_value_twitch_pack = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ Humble Mask Pack !",--This is a Humble Mask Pack item!
menu_l_global_value_xmas = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ Xmas !",--This is a Xmas item!
menu_l_global_value_xmas_soundtrack = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ Xmas Soundtrack !",--This is a Xmas Soundtrack item!
menu_l_global_value_arena = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ The Alesso Heist DLC !",--This is a The Alesso Heist DLC item!
menu_l_global_value_character_pack_sokol = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ Sokol Character Pack !",--This is a Sokol Character Pack item!
menu_l_global_value_e3_s15a = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ E3 2015 Secret Mask !",--This is an E3 2015 Secret Mask item!
menu_l_global_value_e3_s15b = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ E3 2015 Secret Mask !",--This is an E3 2015 Secret Mask item!
menu_l_global_value_e3_s15c = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ E3 2015 Secret Mask !",--This is an E3 2015 Secret Mask item!
menu_l_global_value_e3_s15d = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ E3 2015 Secret Mask !",--This is an E3 2015 Secret Mask item!
menu_l_global_value_humble_pack3 = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ Humble Mask Pack 3 !",--This is a Humble Mask Pack 3 item!
menu_l_global_value_humble_pack4 = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ Humble Mask Pack 4 !",--This is a Humble Mask Pack 4 item!
menu_l_global_value_kenaz = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ Golden Grin Casino !",--This is a Golden Grin Casino item!
menu_l_global_value_west = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ Western Weapon Pack !",--This is a Western Weapon Pack Item!
menu_l_global_value_bobblehead = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ Merchandise !",--This is a Merchandise item!
menu_l_global_value_dragon = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ Yakuza Character Pack !",--This is a Yakuza Character Pack item!
menu_l_global_value_pdcon_2015 = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ PAYDAYCON 2015 Secret Mask !",--This is a PAYDAYCON 2015 Secret Mask item!
menu_l_global_value_steel = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ Gage Chivalry Pack !",--This is a Gage Chivalry Pack item!
menu_l_global_value_turtles = "อุปกรณ์นี้เป็นเนื้อหาเพิ่มเติมของ Gage Ninja Pack !",--This is a Gage Ninja Pack item!
menu_infamy_lock_info = "อุปกรณ์นี้เป็นไอเทมของ Infamy ",--This is an Infamy Reward
--Akimbo
bm_menu_skill_locked_x_1911 = "ต้องการความสามารถพิเศษหรือทักษะ",--Requires the Ambidexterity perk or the Akimbo skill
bm_menu_skill_locked_x_b92fs = "ต้องการความสามารถพิเศษหรือทักษะ",--Requires the Ambidexterity perk or the Akimbo skill
bm_menu_skill_locked_x_deagle = "ต้องการความสามารถพิเศษหรือทักษะ",--Requires the Ambidexterity perk or the Akimbo skill
bm_menu_skill_locked_x_g17 = "ต้องการความสามารถพิเศษหรือทักษะ",--Requires the Ambidexterity perk or the Akimbo skill
bm_menu_skill_locked_x_g22c = "ต้องการความสามารถพิเศษหรือทักษะ",--Requires the Ambidexterity perk or the Akimbo skill
bm_menu_skill_locked_x_usp = "ต้องการความสามารถพิเศษหรือทักษะ",--Requires the Ambidexterity perk or the Akimbo skill
bm_menu_skill_locked_jowi = "ต้องการความสามารถพิเศษหรือทักษะ",--Requires the Ambidexterity perk or the Akimbo skill
--

