menu_resolution = "ขนาดของหน้าจอเกม",--RESOLUTION
menu_resolution_help = "ขนาดของหน้าจอเกม",--Adjust the level of detail of your display.
menu_video_adapter = "จำนวนของหน้าจอ",--Monitor
menu_video_adapter_help = "จำนวนของหน้าจอ",--Choose which monitor to use in fullscreen.$NL;Requires a game restart.
menu_fullscreen = "เต็มหน้าจอ",--FULLSCREEN
menu_fullscreen_help = "เปิด/ปิด โหมดเต็มหน้าจอ",--Turn fullscreen on or off. Fullscreen display optimizes performance. Windowed displays allows for multitasking.
menu_subtitle = "คำบรรยาย",--SUBTITLE
menu_subtitle_help = "คำบรรยายตอน Bain Vlad อื่นๆพูด",--Turn subtitling on or off.
menu_hit_indicator = "เครื่องหมายตอนยิงโดน",--Hit confirm indicator
menu_hit_indicator_help = "มีเครื่องหมายตอนยิงโดน",--Turns the Hit indicator on or off.
menu_objective_reminder = "เตือนสิ่งที่ต้องทำ",--Objective reminder message
menu_objective_reminder_help = "เตือนสิ่งที่ต้องทำหรือโอบเจค",--Turns Objective reminders on or off.
menu_toggle_player_huds = "สิ่งที่แสดงในหน้าจอ",--Hidden player HUD
menu_toggle_player_huds_help = "สิ่งที่แสดงในหน้าจอเช่นหลอดเลือด,ค่าดีเท็คชั่น",--Turns the HUD on or off.
menu_brightness = "ความสว่าง",--BRIGHTNESS
menu_brightness_help = "ความสว่างของเกม",--Increase or decrease the brightness of your display.
menu_effect_quality = "คุณภาพออกเอฟเฟค",--Effect quality
menu_effect_quality_help = "คุณภาพออกเอฟเฟคเกม",--Adjusts the quality of effects in the game.
menu_advanced_video = "ขั้นสูง",--ADVANCED
menu_advanced_video_help = "เข้าสู่การตั้งค่าขั้นสูง",--Change your advanced video preferences.
menu_video_option_default = "คืนการตั้งค่าดังเดิม",--DEFAULT VIDEO OPTIONS
menu_video_option_default_help = "เรียกคืนการตั้งค่าดังเดิมในส่วนของวิดีโอ",--Resets video options to their default state.
