cn_menu_num_players_online = "Crime.net/ยูสเซอร์ที่กำลังออนไลน์อยู่ทั้งหมด: $amount; ยูสเซอร์",--Crime.net/users_online: $amount;
menu_lobby_server_state_in_lobby = "อยู่ในหน้าล็อบบี้",--IN LOBBY
menu_lobby_server_state_loading = "อยู่ในหน้ากำลังโหลด",--LOADING
menu_lobby_server_state_in_game = "อยู่ในระหว่างการปฎิบัติการ",--IN GAME
menu_cn_filter = "กด $BTN_Y; เพื่อดูกระคัดกรอง",--$BTN_Y; Filters
menu_cn_friends = "กด $BTN_Y; เพื่อดูรายชื่อของเพื่อน",--$BTN_Y; Show friends
menu_cn_legend_hide = "กด $BTN_X; เพื่อซ่อนความหมายของไอคอน",--$BTN_X; Hide legend
menu_cn_legend_show = "กด $BTN_X; เพื่อดูความหมายของไอคอน",--$BTN_X; Show legend
menu_cn_legend_host = "สร้างงานจ้างใหม่",--New contracts
menu_cn_legend_join = "งานจ้างของห้องสาธารณะ",--##Public## contracts
menu_cn_legend_friends = "งานจ้างของเพื่อน",--##Friends'## contracts
menu_cn_legend_pc = "00",--Pay grade
menu_cn_legend_risk = "ระดับความยาก",--Risk level
menu_cn_legend_pro = "งานพิเศษ",--Pro job
menu_cn_legend_ghostable = "ย่องเงียบ",--Stealthable
menu_cn_kick_disabled = "ปิดระบบขับไล่",--Kick disabled
menu_cn_challenge = "งานเสริม",--Side Jobs
menu_cn_contact_info = "ฐานข้อมูลต่างๆ",--Contact Database
menu_cn_premium_buy = "สร้างงานจ้าง",--Contract Broker
menu_cn_gage_assignment = "อุปกรณ์แต่งปืนเพิ่มเติม",--Gage
menu_cn_gage_assignment_desc = "อุปกรณ์แต่งปืนเพิ่มเติม",--Courier Assignments
menu_cn_premium_buy_desc = "ยันยืนการซื้อการว่าจ้างงาน",--Buy contract
menu_cn_premium_buy_accept = "ยันยืนการซื้อการว่าจ้างงาน",--Buy contract
menu_ghost_bonus = "โบนัสจากการย่องเงียบจากงานก่อนหน้านี้: ค่าประสบการณ์  +$exp_bonus;%",--Stealth bonus from last contract: XP +$exp_bonus;%
cn_menu_georgetown_title = "จอร์จทาวน์",--Georgetown
cn_menu_downtown_title = "ดาวทาวน์วอซิงตัน",--Downtown
cn_menu_westend_title = "เวสต์เอน",--West end
cn_menu_foggy_bottom_title = "ฟ็อกกี้บอททอม",--Foggy Bottom
cn_menu_shaw_title = "ซอว์",--Shaw
menu_cn_contract_title = "งานจ้าง : $job;",--Contract: $job;
menu_pro_warning = "นี่คืองานพิเศษ! หากคุณพลาด, งานถูกถูกยกเลิกการว่าจ้าง.",--This is a pro job! If you fail, the entire contract will be terminated.
menu_potential_rewards_min = "ผลตอบแทนขั้นต่ำ $BTN_Y;",--$BTN_Y; Potential minimum rewards:
menu_potential_rewards_max = "ผลตอบแทนสูงสุด $BTN_Y;:",--$BTN_Y; Potential maximum rewards:
menu_cn_message_stopped = "หยุดข้อความเสียง",--Voice message stopped.
menu_cn_message_playing = "กำลังเล่นข้อความเสียง...",--Playing voice message...
menu_ghostable_job = "$BTN_GHOST;โบนัสจากการย่องเงียบ: +$bonus;% EXP.",--$BTN_GHOST;Potential stealth bonus: +$bonus;% EXP.
menu_risk_pd = "ไม่มีโบนัสเสริม",--Normal. No risk reward.
menu_risk_swat = "เพิ่มค่าประสบการณ์และเงิน",--Hard. Increased XP and cash.
menu_risk_fbi = "เพิ่มค่าประสบการณ์และเงินที่ดีกว่า",--Very hard. Greatly increased XP and cash.
menu_risk_special = "เพิ่มค่าประสบการณ์และเงินที่มากกว่า",--OVERKILL. Massively increased XP and cash.
menu_risk_elite = "เพิ่มค่าประสบการณ์และเงินที่เยอะสุดๆ",--Death Wish. Tremendously increased XP and cash.
menu_cn_premium_buy_fee_short = "ใช้เงินนอกระบบทั้งหมด: $contract_fee;",--Offshore cost: $contract_fee;
menu_payday = "เงินจากงานจ้าง: $MONEY;",--Payday: $MONEY;
menu_stat_job_completed = "ปล้นสำเร็จไปแล้ว: $stat; ครั้ง",--Contracts completed: $stat;.
menu_cn_game_settings = "รูปแบบของห้อง",--Game settings
menu_heat_warm = "ได้รับค่าประสบการ์ณเพิ่มขึ้นอีก $job_heat;%",--Experience increased by $job_heat;%.
menu_potential_rewards = "ค่าตอบแทนที่จะได้รับ",--Potential rewards:
menu_feature_short_heists_available = "คุณได้รับข้อความใหม่",--You Have A New Message
menu_feature_short_heists_available_desc = "ด่านปล้นสำหรับมือใหม่ได้ถูกเพิ่มลงใน Crime.net ในด้านขวามือแล้ว",--
menu_cn_short = "ด่านปล้นเบสิก",--The Basics
menu_cn_short_desc = "ด่านปล้นเบสิกสำหรับผู้เล่นใหม่",--Choose One Of The Basic Heist
menu_contact_info_short = "",--
heist_short1 = "Flash Drive - ย่องเงียบ",--Flash Drive - Stealth
heist_short2 = "Get The Coke - บู้แหลก",--Get The Coke - Loud
short_basics_cash = "เงินสด",--Cash
short_basics_experience = "ค่าประสบการณ์",--Experience
short_basics_loot = "สุ่มไอเทมหลังจบเกม",--Loot Drop
short_basics_desc = "ยินดีต้อนรับสู่ Crime.net. หลังจากนี้จะเป็นการเรียนรู้พื้นฐานครั้งใหญ่ของ Payday นะเตรียมตัวให้พร้อมแล้วไปเรียนรู้กันได้เลย",--
short_basics_rewards = "สิ่งตอบแทน",--Reward
menu_cn_chill_combat = "เซฟเฮ้าส์กำลังถูกโจมตี",--
menu_cn_story_missions = "โหมดเนื้อเรื่อง",--
menu_cn_filters_sidebar = "ทางลัด CRIME.NET",--
menu_cn_shortcuts = "การคัดกรองห้อง",--
menu_cn_legend_mutated = "ห้องที่ถูกปรับแต่ง Gameplay",--
menu_gamemode = "โหมดของเกม",--
menu_gamemode_heist = "การปล้น",--
menu_chill_combat_under_attack = "เซฟเฮ้าส์กำลังถูกโจมตี",--
menu_chill_combat_under_attack_desc = "เซฟเฮ้าส์กำลังถูกโจมตีโดยตำรวจ$NL;การอัพเกรดจะถูกปิดใช้งานจนกว่าตำรวจจะหยุดการโจมตี",--
menu_cn_chill_combat_defend = "เข้าไปป้องกันเซฟเฮ้าส์",--
menu_cs_coins = "เหรียญแลกเปลี่ยน",--
chill_combat_rewards = "รางวัล",--
chill_combat_header = "เซฟเฮ้าส์ถูกโจมตี",--
chill_combat_desc = "เซฟเฮ้าส์กำลังถูกโจมตีไปป้องกันมันซะ",--
menu_cn_chill_combat_ignore_defend = "ให้เพื่อนร่วมทีมป้องกันไปก่อน",--
