menu_lobby_menu_state_crimenet = "อยู่ในระบบ Crimenet",--Browsing Crime.net
menu_lobby_menu_state_skilltree = "อยู่ในหน้าทักษะ",--In Skills
menu_lobby_menu_state_options = "อยู่ในหน้าตั้งค่า",--In Options
menu_lobby_menu_state_lobby = "พร้อม",--READY
menu_lobby_menu_state_blackmarket = "อยู่ในหน้าช่องเก็บของ",--In Inventory
menu_lobby_menu_state_blackmarket_weapon = "อยู่ในหน้าปรับแต่งปืน",--Modifying weapon
menu_lobby_menu_state_blackmarket_mask = "อยู่ในหน้าปรับแต่งหน้ากาก",--Customizing mask
menu_lobby_messenger_title = "ล็อบบี้:",--LOBBY:
menu_lobby_message_server_is_loading = "เซิฟเวอร์กำลังโหลด",--Server is loading
cn_menu_contract_length_header = "จำนวนวันการว่าจ้าง:",--Contract length:
cn_menu_contract_jobpay_header = "จำนวนเงินที่งานจ้างจ่าย:",--Job Payout:
menu_choose_new_contract = "กรุณาเลือกงานจ้างใหม่ใน Crime.Net",--Choose new contract from Crime.Net
menu_players_list = "รายชื่อผู้เล่น",--
menu_story_missions = "โหมดเนื้อเรื่อง",--
menu_achievements = "รางวัลความสำเร็จ",--
menu_custom_safehouse = "ปรับแต่งเซฟเฮ้าส์",--
