menu_l_lootscreen = "โบนัส",--PAYDAY
menu_l_choose_card_local = "หยิบการ์ด",--Pick a card
menu_l_choose_card_peer = "กำลังเลือก...",--Choosing...
menu_l_choose_card_chosen = "ผู้เล่นได้เลือกแล้วกำลังจะเปิดการ์ดภายใน $time;.",--Chosen! Revealing in $time;...
menu_l_choose_card_waiting = "ผู้เล่นได้เลือกแล้ว! รอการตอบสนอง...",--Chosen! Waiting for response...
menu_l_choose_card_chosen_suspense = "เลือก!",--Chosen!
menu_l_quality = "คุณภาพ $quality;",--Quality: $quality;
menu_l_max_quality = "คุณภาพสูงสุด $quality;",--Max quality: $quality;
menu_l_you_got = "คุณได้รับ ;:$NL;$item;",--Got a $category;:$NL;$item;
menu_l_waiting_for_all = "รอให้ผู้เล่นทุกคนเลือกการ์ดทั้งหมด",--Waiting for everyone to pick a card!
