wp_xsub_watervalve= "เปิดวาล์วน้ำ",--Open the Valve
wp_uc_computer= "แฮ็คข้อมูลต่อ",--Continue Hack
wp_xsub_waterhose= "ดึงสายยาง",--Pull the Hose
wp_xsub_safe= "สำรวจตู้เซฟ",--Investigate the Safe
wp_xsub_door= "เปิดประตู",--Open the Door
wp_ap_escape= "หลบหนี!",--Escape!
wp_xsub_hack= "แทรกแซงระบบ",--Override the System
wp_xsub_shelter= "รีบหาที่กำบัง",--Get to the Shelter
wp_xsub_sewer= "ท่อระบายน้ำ",--Sewer
wp_uc_saw= "เลื่อยรถ LIMO",--Saw the Limo
wp_xsub_tnt= "ติดตั้งระเบิด",--Place the Charge
wp_xsub_watertap= "เปิดก๊อกน้ำ",--Open the Tap
wp_xsub_outlet= "เสียบปลั๊กเข้ากับแหล่งจ่ายไฟ",--Plug into Power Outlet
wp_xsub_bbq= "พูดคุยกับมิชเชล",--Talk to Mitchell
wp_bridge_escape= "หลบหนี!",--Escape!
wp_xsub_escape= "หลบหนี!",--Escape!
wp_bank_escape= "หลบหนี!",--Escape!
wp_xsub_power= "สับสวิตช์ไฟฟ้าขึ้น",--Turn on the Power
wp_uc_check_limo= "สำรวจรถ LIMO",--Check the Limo
wp_uc_escape= "หลบหนี!",--Escape!
wp_uc_power= "เปิดสวิตช์เพื่อจ่ายกระแสไฟ",--Get the Power Back On
wp_uc_interogate= "ค้นหารหัสคำพูด",--Get the Code Words
wp_uc_keyboard= "ใช้งานคีย์บอร์ด",--Use the Keyboard
wp_str_esc= "หลบหนี!",--Escape!
wp_slaughterhouse_escape= "หลบหนี!",--Escape!
