bm_menu_stats_total = "รวม",--Total
bm_menu_stats_base = "ปกติ",--Base
bm_menu_stats_mod = "เสริม",--Mod
bm_menu_stats_skill = "สกิล",--Skill
bm_menu_magazine = "แม็กกาซีน",--Magazine
bm_menu_totalammo = "กระสุนทั้งหมด",--Total Ammo
bm_menu_fire_rate = "ความถี่ในการยิง",--Rate of fire
bm_menu_damage = "ความรุนแรง",--Damage
bm_menu_spread = "ความแม่นยำ",--Accuracy
bm_menu_recoil = "ความนิ่ง",--Stability
bm_menu_concealment = "ค่าอำพราง",--Concealment
bm_menu_suppression = "ค่าความดัง",--Threat
bm_menu_damage_effect = "การชกให้ล้มลง",--Knockdown
bm_menu_charge_time = "เวลาชาร์จ",--Charge time
bm_menu_range = "ระยะ",--Range
bm_menu_armor = "เกราะ",--Armor
bm_menu_movement = "ความเร็ว",--Speed
bm_menu_dodge = "ค่าหลบหลีก",--Dodge
bm_menu_damage_shake = "ความมั่นคง",--Steadiness
bm_menu_stamina = "พลังในการวิ่ง",--Stamina
bm_menu_health= "เลือด",--Stamina