menu_cs_trophies = "รางวัล",--
menu_trophy_displayed = "ประดับไว้เรียบร้อยแล้ว",--
menu_trophy_display_all = "แสดงผลทั้งหมด",--
menu_trophy_hide_all = "เลิกประดับทั้งหมด",--
menu_trophy_not_displayed = "เก็บไว้อยู่ในคลัง",--
menu_unlock_condition = "เงื่อนไขในการปลดล็อค",--
menu_cn_chill = "เซฟเฮ้าส์",--
menu_cs_map = "แผนผังบ้าน",--
Menu_trophy_unlocked = "ปลดล็อคเรียบร้อยแล้ว",--
menu_cs_daily_challenge = "ภารกิจประจำวัน",--
trophy_tooth_objective = "ค้นหาแปรงสีฟันยักษ์ในด่าน Panic Room",--Find and secure the toothbrush in the Panic Room heist.
trophy_evolution_objective = "จบการปล้นไหนก็ได้ในโหมด Mutator",--Complete any heist with an active mutator.
trophy_ring = "",--The Ring
trophy_watchout_objective = "จบการปล้นด่าน Watch Dogs โดยใช้ปืนสไนเปอร์โดยมีความแม่นยำอยู่ที่ 100 เปอร์เซ็นหรือสูงกว่า",--Complete the Watchdogs heist using only sniper rifles with an accuracy of 100% or above.
menu_cs_trophy_counter = "ทำถ้วยรางวัลสำเร็จไปแล้ว $completed; จากทั้งหมด $total; ถ้วยรางวัล",--$completed; of $total; trophies completed
trophy_sandwich_desc = "บางคนชอบแซนวิชนี้มากๆเลยจนถึงเอาไปเก็บไว้ในตู้เซฟเพื่อปกป้องมัน มันต้องเป็นอะไรที่เยี่ยมยอดมากๆ",--Someone liked this sandwich so much that they locked in a safe to protect it. It must be really good.
trophy_jfk = "",--Failed Assassination
trophy_fbi = "",--I Just Had To
menu_st_req_achievement_skill_switch_PS3 = "",--The "$achievement;" trophy
trophy_planmaker_objective = "ในการปล้นด่าน Shadow Raid เราต้องทำการขโมยชุดเกราะซามูไรก่อนเป็นอย่างแรกในระดับ Overkill หรือสูงกว่านั้น",--In the Shadow Raid heist steal all the Samurai Armour before grabbing or securing any other loot playing on OVERKILL difficulty or above.
trophy_escape_van = "",--Escape Van
trophy_medic = "",--Medic
trophy_host_objective = "จบการปล้นไหนก็ได้ $max_progress; โดยให้เราเป็นหัวห้อง",--Successfully complete $max_progress; heists while playing as the host.
trophy_framing_frame_objective = "ผ่านการปล้นด่าน Framing Frame ในระดับ Overkill หรือสูงกว่านั้นโดยผ่านทั้งสามวันแบบ Stealth เท่านั้น",--Complete the Framing Frame heist on OVERKILL difficulty or above without breaking stealth for the entire 3 days of the heist.
trophy_washington_objective = "ฆ่าศัตรู $max_progress ตัว",--Kill $max_progress; enemies.
trophy_watchout = "",--Snipe It
trophy_framing_frame = "",--The Elephant in the Room
trophy_evolution = "",--Evolution
trophy_medic_progress = "ฆ่า Medics ไปแล้ว",--Medics Killed
trophy_bank_heists = "",--Old Faithful
trophy_escape_van_desc = "นี่คือรถหลบหนีของคุณ มันจะพาคุณไปทุกที่",--This is a model of your escape van. It'll take you anywhere - or rather away from it.
trophy_flawless_objective = "จบการปล้นอะไรก็ได้ในระดับ Death Wish หรือสูงกว่านั้น โดยต้องเปิด friend Fire Mutator และห้ามได้รับความเสียหายที่เกิดจากเพื่อนด้วย",--Complete any heist with the Friendly Fire mutator active without hurting another player and on the DEATH WISH difficulty or above. This trophy requires four players in the heist.
trophy_sandwich = "",--It's not even fresh...
trophy_courtesy_desc = "นี่คือตู้ปฐมพยาบาล เพราะเราสนใจเรื่องวิชาชีพการแพทย์",--A first aid locker. Because we care about the medical profession.
trophy_goat_objective = "ส่งแพะไปแล้ว $max_progress; ในการปล้น Goat Simulator วันที่สอง",--Extract $max_progress; goats in day 2 of the Goat Simulator heist.
trophy_tiara_desc = "ดูสวยดีเนี่ย ใครใส่มันเนี่ย",--It's a real beauty. Who's gonna wear it?
trophy_jfk_desc = "สไนเปอร์ ไรเฟิล บางคนประมาทความสามารถของมัน",--A sniper rifle. Some people really underestimate the possibilities of it.
trophy_dozer_helmet_progress = "ฆ่าศัตรูแบบพิเศษไปแล้ว",--Special Units Killed
trophy_jfk_objective = "จบการปล้นด่าน Undercover ในระดับ Overkill หรือสูงกว่านั้น โดยทั้งทีม 4 คน ใช้ปืน Sniper เท่านั้น ห้ามใช้งานความสามารถใดๆทั้งสิ้นและใส่สูทเท่านั้น",--Complete the Undercover heist on the OVERKILL difficulty or above with each crew member using only sniper rifles no skills and wearing the Two-Piece Suit.
trophy_tfturret_desc = "เราขโมยสิ่งนี้มาจากรถไฟ มันไม่ง่ายแต่มันอยู่ที่นี่แล้วดูดีมากเลย",--You stole this from a train. It wasn't easy but damn it looks good here.
trophy_washington_desc = "นี่คือรูปปั้นแห่งความสุดยอดและโด่งดังสำหรับนักฆ่า",--A statue of a great and infamous cop killer.
trophy_dartboard_desc = "ใช้มันเพื่อแสดงความแม่นยำในการปาอาวุธที่ไม่สามารถเทียบได้ ไม่นับลูกระเบิดนะ",--Use it to display your unmatched throwing accuracy. Grenades don't count.
trophy_dartboard = "",--Dart Board
trophy_carshop_stealth_desc = "นี่คือการนับถือพลังของ ECM Jammer แต่คุณไม่ต้องมันที่ Car Shop",--This is a homage to the discreet power of the ECM jammer. Not that you needed one that time at the Car Shop.
trophy_escape_van_progress = "จบการหลบหนีเสร็จสิ้น",--Successful Escapes
trophy_bank_heists_progress = "จบการปล้น Bank Heist",--Banks Robbed
trophy_goat = "",--Goat
trophy_discoball = "",--Disco Night
trophy_piggy_bank_desc = "หมูผู้ใจดีที่เต็มไปด้วยเงิน",--A nice fat benevolent pig full of money.
trophy_longfellow = "",--Long Fellow
trophy_planmaker_desc = "คุณอยากได้ชุดเกราะนี้แน่ ๆ หรืออะไรอย่างอื่นอีกมั้ย",--You really wanted this armor. More than anything else.
trophy_ace_objective = "ใช้ไพ่ ACE of SPADES ปาใส่ศัตรูให้ตายให้ได้ $max_progress; ตัว ในระดับ Overkill หรือสูงกว่านั้น ",--Kill $max_progress; enemies using the Ace of Spades throwable while playing on the OVERKILL difficulty or above.
trophy_diamonds_objective = "จบการปล้น Diamond Store โดยเก็บกระเป๋าให้ครบทุกใบ และยิงป้อมปืนให้พังด้วย ในระดับ Overkill หรือสูงกว่านั้น",--Finish the Diamond Store heist with all bags and destroying the SWAT Turret on OVERKILL difficulty or above.
trophy_falcogini = "",--Falcogini
trophy_dance_desc = "อ่านและเรียนรู้ จากนั้นก็ เต้นเต้นเต้น อย่าไปคิดมากเลย",--Read and learn. Then dance dance dance. Just don't trip and mind the mines.
trophy_golden_grin_desc = "นี่คือสีหน้าของคุณที่สามารถขโมยที่ดูยื่งใหญ่ด้วยทักษะที่ยอดเยี่ยม",--It's the kind of grin you flash when you've stolen the big loot with absolutely perfect skill.
trophy_hobo_knife_objective = "หามีดจากคนไร้บ้านในด่าน Aftershock Heist",--Find the hobo's knife in the Aftershock heist.
trophy_carshop_stealth_objective = "จบการปล้น Car Shop โดยที่ Detection ต้องมีที่ 70 หรือมากกว่านั้นโดยไม่ใช้ ECM เลย ",--Successfully complete the Car Shop heist with a detection level of 70 or above without using ECM jammers.
trophy_hockey_team_desc = "คนเหล่านี้คือใครเนี่ย",--Who are these people anyway?
trophy_fbi_desc = "ของที่ระลึกเล็กน้อยที่คุณหยิบขึ้นมาขณะกำลังจู่โจมสำนักงาน FBI",--A little souvenir that you picked up when raiding the FBI offices.
trophy_dartboard_objective = "Headshot ใส่ศัตรู $max_progress; หัว  ",--Perform $max_progress; headshot kills.
trophy_boxing_gloves = "",--Big Daddy
trophy_dozer_helmet = "",--Dozer
trophy_pacifier= "",--First Steps
trophy_defender_objective = "ผ่าน Safehouse Raid ในระดับ Overkill หรือสูงกว่านั้น",--Successfully defend your safe house against a police raid on the OVERKILL difficulty or above.
trophy_train_bomb = "",--Tickets please!
trophy_tiara = "",--So Pretty
trophy_boxing_gloves_objective = "ฆ่า Bulldozer ด้วยนวม Overkill Boxing Glove ให้ได้ $max_progress; ตัว   ",--Knock out $max_progress; Bulldozers using the OVERKILL boxing gloves.
trophy_ace = "",--True Ace
trophy_tfturret = "",--Turret
trophy_courtesy_objective = "ผ่านการปล้น Beneath the Mountain ในระดับ Mayhem หรือสูงกว่านั้น โดยไม่ฆ่า Medic เลย",--Complete Beneath the Mountain heist on MAYHEM difficulty or above without killing any medics.
trophy_stealth_desc = "คุณได้รับการเคลื่อนไหวที่เหมือนผี",--You earned this through your spectral moves and ghostly presence.
trophy_train_bomb_desc = "ทุกคนชอบรถไฟ และนายก็ชอบที่จะปล้นมันด้วย คุณเคยปล้นมาครั้งนึงในป่า จำได้ป่ะล่ะ ?",--Everyone likes trains. And you like robbing trains too. You cleared one out in the woods once remember?
trophy_smwish = "",--Ultimate Heister
trophy_smg_desc = "นี่คือขวดโหลที่เต็มไปด้วยหลักฐานของการทำลายล้างด้วยปืน SMG ที่โคตรเจ๋งเลย",--This jar contains evidence of the destructive work of a good SMG.
trophy_defender = "",--Get off my Lawn!
trophy_hockey_team_objective = "หารูปโปสเตอร์ทีมงาน Overkill ในด่าน Firestarter วันที่ 3 ในระดับ Overkill หรือสูงกว่านั้น",--หารูปโปสเตอร์ทีมงาน Overkill ในด่าน Firestarter วันที่ 3 ในระดับ Overkill หรือสูงกว่านั้นOn day 3 of the Firestarter job find the rare poster of the OVERKILL hockey team.
trophy_piggy_bank_objective = "ผ่านด่าน Big Bank ในระดับ Overkill หรือสูงกว่านั้น โดยทั้งทีมห้ามอัพ Skill เด็ดขาด",--Complete the Big Bank heist on the OVERKILL difficulty or above with no crew member using any skills.
trophy_flawless_desc = "นี่คือรูปภาพที่เฉลิมฉลองมิตรภาพ เพื่อนต้องไม่ยิงเพื่อนจากด้านหลัง",--A painting to celebrate friendship. Friends don't shoot friends in the back.
trophy_tfturret_objective = "ในการปล้น Train Heist ทำการ All Loot ทั้งหมดในด่าน ในระดับ Overkill หรือสูงกว่านั้น",--Finish the Armored Transport: Train heist with all bags on OVERKILL difficulty or above.
trophy_ace_desc = "มีแค่การ์ดเท่านั้นที่คุณต้องการ",--The only card you need.
menu_trophy_unlocked = "",--Unlocked
trophy_ace_progress = "ฆ่าศัตรูไปแล้ว",--Enemies Killed
trophy_bank_heists_desc = "นายได้ผ่านด้วยกันมานานแล้ว ให้เดา นี่คือความรัก และความเกลียดชังในครอบครัว",--You've been through so much together. Guess it's one of those love/hate relationships.
trophy_bank_heists_objective = "ผ่าน Bank Heist จากทั้งหมด $max_progress; ในระดับ Overkill หรือสูงกว่านั้น ",--Successfully complete $max_progress; bank heists on the OVERKILL difficulty or above.
trophy_bonfire = "ปุ่มเผาเงินนอกระบบ",--The Burn Offshore Money button
trophy_bonfire_desc = "อย่ากดปุ่มนี้นะเฮ้ย!",--Don't push the button!
trophy_bonfire_objective = "เผาเงินนอกระบบทั้งหมดใน Safe House",--Burn all of your offshore cash in the Safe House.
trophy_boxing_gloves_desc = "ถึงคุณจะไม่คิดก็เถอะนะ แต่คุณสามารถฆ่า Bulldozer ด้วยสิ่งนี้ได้",--You wouldn't think so but you can kill a dozer with these things.
trophy_boxing_gloves_progress = "ต่อย",--Knock Outs
trophy_carshop_stealth = "",--I Got This
trophy_computer = "",--Computer
trophy_computer_desc = "เครื่องคณิตกรณ์เครื่องนี้แม่งเก่าชิบหายเลยหว่ะ",--This computer is a really old slow piece of shit.
trophy_computer_objective = "จบวันแรกของ Election Day แบบบู้ และ Hack คอมสองรอบ",--Finish day 1 of the Election Day heist after breaking stealth and completing the entire intel download on the computer.
trophy_courtesy = "",--Humanitarian
trophy_dance = "",--Staying Alive
trophy_dance_objective = "จบการปล้น Nightclub โดยใช้ Tripmines ฆ่าศัตรูเท่านั้น",--Complete the Nightclub heist using only tripmines to kill enemies.
trophy_dartboard_progress = "ทำการ Headshot",--Headshot Kills
trophy_defender_desc = "คุณสามารถต่อสู้กับตำรวจได้ โดยลวดหนามนี้จะทำให้มายากขึ้นในเวลาต่อไป",--You managed to fight the cops off. This barbed wire will make it harder for them to get in next time.
trophy_diamonds = "",--Diamonds
trophy_diamonds_desc = "คุณต้องล้อเลียนหน่วย SWAT เพื่อจะได้รับความงามนี้",--You had to swat some wheels to get this beauty.
trophy_discoball_desc = "ลูกดิสโก้ที่มีรสนิยมที่มาจากคลับที่มีรสนิยม",--A very tasteful disco ball from the Tasteful Club.
trophy_discoball_objective = "ผ่าน Night Club แบบ Stealth เท่านั้น และผ่านในระดับ Death Wish เท่านั้น",--Finish the Night Club heist in stealth on DEATH WISH difficulty or above.
trophy_dozer_helmet_desc = "นี่คือหมวกนิรภัยของ Bulldozer ที่สวยงาม",--This is a nice dozer helmet. Keep 'em flying.
trophy_dozer_helmet_objective = "ฆ่าศัตรูพิเศษ $max_progress; ตัว",--Kill $max_progress; special units.
trophy_escape_van_objective = "ผ่านการหลบหนี $max_progress; ครั้ง ",--Successfully complete $max_progress; Escapes.
trophy_evolution_desc = "ประสบการณ์ กลายพันธุ์ พัฒนาการ",--Experiment. Mutate. Evolve.
trophy_falcogini_desc = "นี่คือรถ Falcogini แบบย่ออัตราส่วน ใช่แล้ว คุณขโมยมันมา",--A scale model of a Falcogini. Yes you once stole a real one. Drive in style.
trophy_falcogini_objective = "จบการปล้น Car Shop ในระดับความยากอะไรก็ได้",--Finish the Car Shop job on any difficulty.
trophy_fbi_objective = "ผ่านวันที่สองของ Firestarter แบบ Stealth",--Successfully complete day 2 of the Firestarter heist in stealth.
trophy_flawless = "",--Mercenary
trophy_framing_frame_desc = "รู้สึกว่ารูปภาพนั้นกำลังมองเราอยู่นะ.....",--It feels as though that painting is looking at you...
trophy_goat_desc = "อ่าห์.. ในวันที่มีแพะ แต่มีความคิดที่จะนำกลับมาที่นี้มั้ย มันควบคุมตัวเองได้ ",--Ah that day with the goats... but whose idea was it to bring one back here? It's not even housetrained.
trophy_goat_progress = "ส่งแพะ",--Goats Extracted
trophy_golden_grin = "",--Golden Grin
trophy_golden_grin_objective = "ผ่าน Golden Grin Casino ในระดับ Death Wish หรือสูงกว่านั้น โดยใช้ปืนพกที่ติด Silencer เท่านั้น",--Complete the Golden Grin Casino heist on DEATH WISH difficulty or above equipped with only silenced pistols.
trophy_hobo_knife = "",--Jason
trophy_hobo_knife_desc = "ใช่ คุณเก็บมันมา แต่คุณต้องการมันจริง ๆ เหรอ",--Yes you took it. But do you really really need it?
trophy_hockey_team = "",--The First Line
trophy_host = "",--Mother of Mothers
trophy_host_desc = "คุณเป็นหัวหน้าที่ดีนะเนี่ย",--You are just the perfect host.
trophy_host_progress = "เป็นโฮสห้องไปแล้ว",--Heists Played
trophy_longfellow_desc = "ยานพาหนะที่ขนส่งหัวรบได้หลายหัว",--A multiple warhead delivery vehicle.
trophy_longfellow_objective = "จบ Meltdown ภายใน 7 นาที ในระดับ Overkill หรือสูงกว่านั้น",--Finish the Meltdown job within 7 minutes on OVERKILL difficulty or above.
trophy_medic_desc = "เข็มฉีดยาสีทอง ตั้งแต่คุณได้ส่งยาไปที่โรงพยาบาล และเพียงพอในการปัญหาการขาดแคลนบุคลากรได้ดี ",--A golden syringe. Since you've sent enough medics to the hospital to solve their staff shortage problems for good.
trophy_medic_objective = "ฆ่า Medic $max_progress; ตัว ",--Kill $max_progress; medics.
trophy_meth_cookbook = "",--Meth
trophy_meth_cookbook_desc = "สำหรับบุคคลที่อยากเข้าร่วมธุรกิจปรุงยา",--For dummies and others who want to get into the meth cooking business.
trophy_meth_cookbook_objective = "จบ Cook off ด้วย Meth 25 ถุง ในระดับ Overkill หรือสูงกว่านั้น",--Finish the Cook Off heist with 25 bags of meth on OVERKILL difficulty or above.
trophy_pacifier_desc = "ครั้งนึงผู้ที่มีชื่อเสียงก็เคยมีจุดเริ่มต้นเล็ก ๆ หรือจะให้พูดอีกคำนึง เราเคยกากมาก่อน",--Even the infamous once started small. Or in other words we all suck at first.
trophy_pacifier_objective = "ผ่าน Basic ทั้งสองรูปแบบ",--Complete all the Basics heists.
trophy_piggy_bank = "",--Clueless
trophy_planmaker = "",--Bushido
trophy_ring_desc = "9 สำหรับมนุษย์ และ 10 สำหรับนักปล้นที่พร้อมจะตาย",--Nine for mortal men. And a tenth for the mad heister that dooms them to die.
trophy_ring_objective = "ในการปล้น Birth of Sky หาแหวน 9 วงในการปล้น",--In the Birth of Sky heist find all 9 rings.
trophy_sandwich_objective = "ในการปล้น Big Bank หาแซนวิชที่อยู่ในตู้เซฟห้องผู้จัดการ",--In the Big Bank job find the half eaten sandwich in the safe.
trophy_smg = "",--Dance Party
trophy_smg_objective = "ฆ่าศัตรู 25 ตัวภายใน 25 วินาทีด้วยปืน SMG เท่านั้น",--Kill 25 enemies in 25 seconds using only SMGs.
trophy_smwish_desc = "นี่คือรูปปั้นอันเป็นเกียรติยศสูงสุดของนักปล้น",--A statue to honor the ultimate heister.
trophy_smwish_objective = "จบการปล้นทุกอย่างในระดับ One Down",--Complete all contracts on the One Down difficulty.
trophy_stealth = "",--Who's There?
trophy_stealth_objective = "ผ่านการปล้นแบบ Stealth $max_progress; ด่าน ที่ต่างกันออกไปในระดับ Overkill หรือสูงกว่านั้น ",--Successfully complete $max_progress; different jobs in stealth on OVERKILL difficulty or above.
trophy_stealth_progress = "ปล้นแบบย่องเงียบไปแล้ว",--Heists Ghosted
trophy_tiara_objective = "จบการปล้น Ukrainian Job ในระดับ Death Wish หรือสูงกว่านั้น โดยไม่ใช้ ECM เลย",--Finish the Ukrainian job on Death Wish difficulty or above with no crew members equipping ECM jammers.
trophy_tooth = "",--But it's the tooth!
trophy_tooth_desc = "แปรงสีฟันนี้โคตรใหญ่เลย",--THAT'S A BIG TOOTHBRUSH!
trophy_train_bomb_objective = "จบการปล้น The Bomb : Forest ในระดับ Death Wish หรือสูงกว่านั้น โดยต้องเริ่มตั้งแต่แรกถึงจบการปล้น",--Finish the Bomb: Forest heist on Death Wish difficulty or above. To complete this challenge you have to have played the job from start to finish.
trophy_transports = "",--The Robber
trophy_transports_desc = "รถหุ้มเกราะ เหมือนเป็นของเล่นให้คุณเล่นเลย",--Armored cars. They are like toys to you.
trophy_transports_objective = "จบการปล้น Armored Transport ทุกการปล้นในระดับ Overkill หรือสูงกว่านั้น",--Finish all Armored Transport jobs on OVERKILL difficulty or above.
trophy_washington = "",--Robbedacop
trophy_washington_progress = "ฆ่าศัตรูไปแล้ว",--Enemies Killed
trophy_watchout_desc = "คุณทำมันหนิ คุณสามารถทำมันได้เป็นร้อยครั้งเลยนะ",--You did this. You could do it a hundred times in a row too.
trophy_spooky_desc = "มันคือฟักทองที่น่ากลัวที่สุดตลอดกาล",--
trophy_spooky_objective = "ทำลายฟักทองในด่าน Prison Nightmare",--Destroy the pumpkin on the Prison Nightmare job.
trophy_run_turtle_desc = "คุณไม่จำเป็นต้องวิ่งเร็วที่สุดเพื่อจะชนะการแข่งขันเสมอไป",--You don't need to be the fastest runner to win the race. Not if you're willing to shoot the other guy in the kneecaps.
trophy_run_turtle_objective = "หาเตาในด่าน Heat Street",--Find the hidden tortoise in the Heat Street heist.
trophy_fish_trophy_desc = "เงียบเหมือนเงา คุณขโมยเงินทั้งหมดในเรือนั้นซึ่งมันไม่ได้ง่ายเลย",--
trophy_fish_trophy_objective = "ผ่านการปล้นโดยที่คนในทีมมีค่าความสงสัยสูงสุด",--
trophy_flamingo_desc = "คุณแค่ไม่ชอบพวกมัน",--
trophy_flamingo_objective = "ยิงรูปปั้นนกพิลิแกน 20 ตัว",--
trophy_flamingo_progress = "ยิงรูปปั้นไปแล้วทั้งหมด",--
trophy_glace_cuffs_desc = "ตำรวจไม่ได้มัดพวกมันไว้แต่เขาเพ่งเล็งที่จะใช้เครื่องมืออื่นๆโดยตรงแทนและคุณก็ได้เก็บมันมาจาก Green Bridge",-- contraptions
trophy_glace_cuffs_objective = "หากุญแจมือสี่อันจากทั้งหมดหกอันในด่าน Green Bridge",--
trophy_coke_desc = "โลกใบนี้,ชิโค่,และตัวของมันเอง",--
trophy_coke_objective = "ขโมย Yayo ในด่าน Scarface Mansion ทั้งหมด 24 อัน",--
trophy_coke_progress = "ได้ Yayo มาแล้ว",--
trophy_friendly_car_desc = "Ernesto Sosa ไม่ค่อยชอบเท่าไหร่ที่คุณไปทำลายรถคันนี้ของเขาหรือเมื่อตอนที่คุณฆ่าเขาไปแล้ว",--
trophy_friendly_car_objective = "เล่นด่าน Scarface Mansion ในระดับ Maygem หรือสูงกว่าในโหมดเสียงดังโดยที่ผู้เล่นทั้งสี่คนใช้ Perk Maniac และไม่มีสกิล เพื่อให้จบชาเล้นจ์นี้คุณต้องเล่นตั้งแต่เริ่มต้นเกม",--